### ISSUE TITLE
current debug version has bugs

### ISSUE THREAD

**Issue by droidmjt** [droidmjt/Droidsound#144]
note that there are some bugs left in the current debug version and i'm currently fixing them, if you noticed anything unusual, just report them here, thanks.

**Comment by droidmjt** [comment]
new binary also available in usual link

**Comment by Level99OCR** [comment]
Just got back, only had some minor issues due to one phone's continued hatred of the filecache sizing, but all other devices working great.  Will grab the latest binary.

Ratings feature looks pretty cool, it'll be a nice supplement to the playlists/favorites so that one can mark whether a soundtrack is very good or total crap.

**Comment by Sir-Sabin** [comment]
i'm having some issues with the new build, idsp files crash droidsound (i tested this on two devices) and files with 5 sec in them don't play right, it only plays 1 sec of it then goes on to the next file

**Comment by droidmjt** [comment]
idsp thing is fixed now, i fix the 5 sec song bug next

**Comment by droidmjt** [comment]
I'm currently fixing the 5 second thing + other stuff, i'll close this case and open a new one once im done.

**Comment by TheRektafire** [comment]
Hey guys, I thought I would chuck in my two into this conversation by telling about the "bugs" I've found in the latest GP version of the app. Well, one of them seems like a bug, and the other one is just trivial, but oh well, I'm gonna tell about them both anyway :) 
So, in the last Play version of DSE, if you tried to load an invalid file type (be it an audio type that it doesn't support or any non audio type such as a PDF or TXT) then usually it would either A) do nothing, or B) "play it" using some random plugin (usually UADE) but only have silence. Now in the latest version, whenever you try to use one of these invalid types it will just downright FC every time. Like I said, trivial, but still kind of a bug. I mean, if there's anything to say bug-related about this, its that these non music types show up in the first place.
Now, as for the actual bug, I sometimes get stuttering when using some, but not all, USF files. For example, out of the 5 USF sets I have right now, all of the songs on Mission Impossible and some of the songs in F1 World Grand Prix stutter every one or two seconds, regardless of how many instruments are playing at the time. The other 3 are fine, although Ridge Racer 64 songs take twice as long to load as the rest, although I can easily blame that on the fact that are relatively large. I got all of my USF rips from Zophars Domain BTW.
I would upload a screenshot of a specsheet of my tablet (Trio Stealth G4 7 inch) that I created using the CPU Z app, but apparently Git doesn't want to open any filebrowsers on my tab when I hit the select image button, so I guess I'll just have to upload to Imgur or something then post the link.

**Comment by TheRektafire** [comment]
![Tablet specs](http://imgur.com/x904MCv.png)
K, here's the picture.

**Comment by droidmjt** [comment]
Some USF songs are too CPU consuming and 1.2GHz is not enough to play them. This is not a bug actually. I may change the USF library in the future. 

About the PDF/TXT thingy, I guess its .TXT file that you have tried to play since .TXT is known zxtune extension. The problem with the format is that it has no header so it's difficult to distinguish those audio txt and real non-audio files.

**Comment by TheRektafire** [comment]
Huh. Ok. Well, maybe there is a more efficient/optimized USF player you could use? (64th note comes to mind, although tbh I've never used 64th note or any other USF/miniUSF player besides the one in this app, ) Also, if you don't mind me asking, I have some soundtracks that I'm looking for that I just can't seem to find anywhere. More specifically, I'm looking for:

FIFA 99
Armorines Project SWARM
NFL Blitz 2000
NASCAR 99 and 2000

If you could point me in the direction of a place where i could go to get these that would be super awesome! Oh, and thanks for the awesome app.

**Comment by droidmjt** [comment]
The plugin is using LazyUSF library (the best in the market), later i might update it to LazyUSF2 (probably best eventually). Unfortunately I can't help you with those songs, Google for USF rips and you might find something interesting :)
