### ISSUE TITLE
s98/pmd playback noise in latest debug ver

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#147]
umm.seems playing but not good than before...

**Comment by droidmjt** [comment]
explain in details what is different, which version you are using and which files i can use to reproduce the problem?

**Comment by crimson1117** [comment]
all pmd and s98 files playback with crappy noises....using latest dropbox version...

**Comment by droidmjt** [comment]
Yeah, seems so, i'll check it. Odd thing is that I haven't touched these plugins ever since i released the 1.652 in GP.

**Comment by droidmjt** [comment]
it was about the compiler i used. With GCC 4.6 it works fine, 4.8 and 4.9 makes it odd.

**Comment by crimson1117** [comment]
thanks.but I don't know how it comes to a noise problem...?

**Comment by droidmjt** [comment]
new binary in dropbox, fixeds s98 and pmd problems

**Comment by crimson1117** [comment]
checked.my thanks
