### ISSUE TITLE
Feature Request: mo3 support

### ISSUE THREAD

**Issue by bboombotz** [droidmjt/Droidsound#148]
Hello,

I was curious if it were possible to add support for this tracker format? Here's the wiki page about it:
http://en.wikipedia.org/wiki/MO3

Thank you and I love what you've done with this player!
Rob

**Comment by droidmjt** [comment]
where can i get some example songs?

**Comment by bboombotz** [comment]
I found it:
http://gimlao.free.fr/temp/Bejeweled%202%20Deluxe/BeyondNetwork.mo3

**Comment by droidmjt** [comment]
bugger, i need some additional component first, no big deal, i'll add it

**Comment by bboombotz** [comment]
Cool, thanks!

**Comment by droidmjt** [comment]
Bad news, that missing component, UNMO3 library, won't be available for Android so I cannot add the support for MO3 files. The BASS library can open MO3 files but it doesn't support subtunes at all. When I tried to open the example song you provided, all I got was silence. I prefer using openmpt lib for tracker musics.

The UNMO3 library is maintained by Ian Luck. 
* http://www.un4seen.com/forum/?topic=9092.0

**Comment by droidmjt** [comment]
things have changed...i'm working on MO3 support now...stay tuned

**Comment by bboombotz** [comment]
Thanks, will do! Not sure if I can help test things but when you release it on Google Play I can quickly update my app and test it out :)

**Comment by droidmjt** [comment]
![unmo3thingy](https://cloud.githubusercontent.com/assets/5917820/6313411/e893808e-b9b1-11e4-95e9-619bfd9517f6.png)

**Comment by kode54** [comment]
Most of that is due to rounding errors. The one range of four bytes that are different, not sure.

**Comment by droidmjt** [comment]
done, check out the latest binary :) close this case if it works as expected

**Comment by Sir-Sabin** [comment]
whatever you did to it, droidsound crashes as soon as i start it up on both my phone and tablet

**Comment by droidmjt** [comment]
if this crash is not related to the 2sf files, send logcat log

**Comment by droidmjt** [comment]
ah i think i found out the reason for the crash, it couldn't load some library, i have fixed it now, will upload new binary now

**Comment by Sir-Sabin** [comment]
that fixed it thx again for the quick fix

**Comment by droidmjt** [comment]
@bboombotz try out the latest BETA, if the result is ok, close this case. I wouldn't like to release this featuer in Google Play if it has bugs so please do try this out. If you are concerned about it being not signed, i can sign it for you, there are no malware/spyware inside.

**Comment by bboombotz** [comment]
Hello,

Sorry for the delay, moved into a new home with my wife and got behind on things.

I just tested the BETA version of the app and it played the mo3 file perfectly! Thank you! I did test other files just as part of testing and they played just fine as well.

Thanks so much!

**Comment by droidmjt** [comment]
great, i'll close this case, do reopen this case if something unexpected comes up with the mo3
