### ISSUE TITLE
version 1.66 release

### ISSUE THREAD

**Issue by droidmjt** [droidmjt/Droidsound#150]
Pre-release of the official Google Play version. For those who care, please download the beta version and report any immediate bugs.

**Comment by Level99OCR** [comment]
Downloading now to give it a spin!  After the 1.66 official release, is the source in a state where the GIT can be updated?  I'd like to take a look into doing some skin themes for the interface to offer some variety.

**Comment by Sir-Sabin** [comment]
the next button doesn't work unless you hold it with the latest build

**Comment by droidmjt** [comment]
@Sir-Sabin , known bug and already fixed, I upload new binary right now.

**Comment by droidmjt** [comment]
@Level99OCR , use the current git version to create your skin, i can merge it to the final product from there and credit you.

**Comment by droidmjt** [comment]
i assume no major bugs, official release happens in few hours :)

**Comment by droidmjt** [comment]
Released.
