### ISSUE TITLE
s98 and MXDRV volume set?

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#152]
for s98 hope a fm/ssg/adpcm/rhythm volume control like PMD.
for MXDRV，did you used a LPF?I cannot hear some small sounds while gamdx can...

**Comment by droidmjt** [comment]
MDX plugin is using different library and doesn't support LFP. For S98, i can try adding the volume controls.

**Comment by crimson1117** [comment]
so the different library should be the reason?(gamdx's library is better)

**Comment by crimson1117** [comment]
so the different library should be the reason?(gamdx's library is better)

**Comment by droidmjt** [comment]
the gamdx library is very annoying to use, currently i have other things to do,i'll see that later

**Comment by droidmjt** [comment]
by the way, any special reason for this s98 volume thingy? some s98 plays badly or ...

**Comment by droidmjt** [comment]
i'll continue my work on this, no worries :)

**Comment by droidmjt** [comment]
about the gamdx lib, is it enough if i make it just like the gamdx player is?

**Comment by crimson1117** [comment]
s98 volume thingy:there is s98 logged for PC-88 and PC-98 and actually the volume of FM/SSG sets is not same.
the gamdx lib:really want infinite loop,and others OK.
thanks

**Comment by droidmjt** [comment]
the gamdx library has setting for a filter, i suppose it's LPF related but there is no option to change LPF frequency, sure, there will be infinite loop

i'll do the s98 volume thing at last, its very annoying because i need to modify the library itself and it is not written by me

**Comment by droidmjt** [comment]
the gamdx thing, did you compare the sound to the gamdx android player?

**Comment by droidmjt** [comment]
there is a problem with gamdx library, no matter which sample rate i set, it always sounds like 22050Hz.

**Comment by droidmjt** [comment]
you can do also comparison by yourself, download the android gamdx player and listen, the sound is bad

**Comment by crimson1117** [comment]
since it is hard to output sound with real smart phone,I'll output it using android emulation(bluestacks)

**Comment by droidmjt** [comment]
hard to output sound with real smart phone? just download the gamdx player from gorry's website, then play for example the After Burner song below, then use DS-E MDX player, you'll hear the difference.

Example song:
ftp://ftp.modland.com/pub/modules/MDX/After%20Burner/ab2-bfd.mdx (also get the .pdx file from same folder)

http://gorry.haun.org/android/gamdx/dist/old/
http://gorry.haun.org/android/gamdx/dist/old/gamdx_2013_1213_1.zip

That zip file has the latest player. 

For the emulator part, try genymotion.com, extremely fast x86 Android emulator. Use Android OS 4.3 since all the above are somehow weird.

**Comment by crimson1117** [comment]
https://www.dropbox.com/s/8aup0k2jykstpou/DSE_SGOP.wma?dl=0
https://www.dropbox.com/s/kae366l20trmvxj/gamdx_SGOP.wma?dl=0

https://www.dropbox.com/s/nf0obppsmn465c6/SGOP.mdx?dl=0

man,I still don't get it...

**Comment by droidmjt** [comment]
i'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/e456v8e44k5wchl/droidsound-debug02.apk?dl=0

there is a special build that has GAMDX player, listen the After Burner song, also i tried the SGOP mdx, couldn't hear any differences.

**Comment by droidmjt** [comment]
the difference is noticeable only when there is .pdx file included

**Comment by droidmjt** [comment]
ah, got it now, the beginning sounds different between those two with those players, but other than that, it sounds the same.

**Comment by crimson1117** [comment]
yes,and I don't get it...

**Comment by droidmjt** [comment]
you dont get what? you mean you can't understand why it happens? One thing that crossed my mind with the default player is that, it skips the F9 commands at the beginning, so the volume raising from 0 gets skipped

**Comment by crimson1117** [comment]
yes,and what is this "F9 commands"

**Comment by droidmjt** [comment]
0xf9 is volume increase

**Comment by crimson1117** [comment]
umm,thanks.it seems track 4,7,8 not making some voice in dse version

**Comment by droidmjt** [comment]
how did you check that those tracks are not making any voice?

**Comment by crimson1117** [comment]
that's the function of hoot

**Comment by droidmjt** [comment]
I have reported the MDX library problem to correct parties. It's up to them to fix it. BouKichi's library problem is probably a small bug in the MDXMML parsing, Gorry's library has a small bug in handling the sample data (frequency seems to be the same all the time making it sound bad)

**Comment by droidmjt** [comment]
this is done, i'll upload new binary soon for you to test :)

**Comment by crimson1117** [comment]
oh,thanks a lot.

**Comment by crimson1117** [comment]
well,do you know mercury unit for mdx?on markun2's page there is some are strange mdx used PCM++ thing,and they are creppy.

**Comment by droidmjt** [comment]
never heard of the mercury unit thing.

I'll disable the GAMDX player since it is incomplete. Once the PDX loading/playing works as expected, i'll put it back.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/jpbob4oy3gmwldz/droidsounde1664_34.apk?dl=0
if the volume settings work as expected, close this case. It seems darius2 needs some volume chaging, it plays very loud
