### ISSUE TITLE
droidsound skips files with long slient at the beginning of files

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#155]
droidsound skips files with long slient at the beginning of files, is this a bug or a option? if it is a option how do i turn it off?

**Comment by droidmjt** [comment]
fixed in latest beta i think, try and see

**Comment by Sir-Sabin** [comment]
that fixed it, sorry it tok soo long to reply back kept forgetting to replay back

**Comment by droidmjt** [comment]
great
