### ISSUE TITLE
ADLMIDI and BASSMIDI playback problems.

### ISSUE THREAD

**Issue by KynikossDragonn** [droidmjt/Droidsound#157]
EDIT: I forgot to mention. I'm using the playstore version you released, not any of the betas on the dropbox link.

I can't seem to play the following files from NAM no matter what I try to use:
PLT204.MID
PLT205.MID

from this archive: http://mirsoft.info/gmb/music_info.php?id_ele=MTI4NTA=

It'll stop for a second, then try to go to the next file, then stop another second then play another random file from the folder until it finally starts playing either PLT201.MID PLT208.MID or PLT211.MID

Also when I play the FMSpecific MIDI's to Descent 1, it still goes to the next file even though I have the double arrow endless looping set. Perhaps the MIDI plugin is "crashing" at the EOF?

EDIT 2: I can't get this file to play at all, but I can get it to play in XMIPLAY and Winamp: https://dl.dropboxusercontent.com/u/45822870/blackthorne_ingame1.xmi
I also can't seem to change subtunes on this despite it being detected: https://dl.dropboxusercontent.com/u/45822870/syngame.xmi

**Comment by droidmjt** [comment]
try the latest beta, GP has some bugs

**Comment by KynikossDragonn** [comment]
I get a force quit with the beta on the files I mentioned that refuse to play.

**Comment by droidmjt** [comment]
yeah the silence is problematic in GP version. In BETA version, BASSMIDI has a setting that allows you to suppress silence at the beginning. It's not mandatory option tho.

ah the favourites, the logic has changed a bit. If you add a song to favourites and press nextbutton it will play next file instead of a next subtune no matter what setting you use. I think i need to add a switch for this case in settings, there was another feature request related to this.

**Comment by KynikossDragonn** [comment]
Would there be anyway to fix the ADLMIDI issue with it having to decay for a second before looping? BASSMIDI loops without any decay but ADLMIDI keeps pausing for a brief moment before it loops what it's playing.

**Comment by droidmjt** [comment]
i'll see what i can do about it

**Comment by KynikossDragonn** [comment]
Cool, also I really like these new buttons in the beta as a side note.

**Comment by droidmjt** [comment]
i can add volume setting for soundfonts, the pausing problem is fixed

**Comment by KynikossDragonn** [comment]
Cool thanks! And yeah a gain (or volume multiplier, whatever the proper term may be) setting would be really useful to prevent clipping problems like I described.

**Comment by droidmjt** [comment]
could you send me a soundfont + mid file so i can test the clipping thingy?

**Comment by KynikossDragonn** [comment]
Sure here you go:
http://www.schristiancollins.com/soundfonts/GeneralUser_GS_1.44-SoftSynth.zip
https://dl.dropboxusercontent.com/u/45822870/walk2.mid

**Comment by droidmjt** [comment]
i couldn't hear anything odd but i added the volume setting, new binary in the usual location, report bugs please

**Comment by KynikossDragonn** [comment]
Just a quick question, with the beta you have going now, do I still need to erase droidsound directory before installing a new beta, or can I safely keep the folder around? Takes kinda forever to rebuild the directory cache and what not.

**Comment by droidmjt** [comment]
you shouldn't need to. As long as you never go back to v1.652 or older. I just use adb.exe to install a new one and thats it, only in some extreme cases i had to remove droidsound folder but in normal cases no.

**Comment by KynikossDragonn** [comment]
Success! The volume setting lets me avoid clipping issues entirely, thank you so much!

**Comment by droidmjt** [comment]
i was just about to comment something about the crash but it seems it didn't crash :)

if all works, please close this case.

**Comment by KynikossDragonn** [comment]
I still get a "Unfortunately Droidsound-e has stopped." when I try to play blackthorne_ingame1.xmi so something's really going screwy with handling that file that XMIPLAY and Winamp doesn't seem to care.

**Comment by droidmjt** [comment]
crap i forgot to check that, i'll check it

**Comment by KynikossDragonn** [comment]
It's weird that the debug crashes, but the playstore version just ignores the file and plays nothing... Are there more breakpoints or something with your debug builds that would trigger a crash when something goes wrong?

**Comment by droidmjt** [comment]
when i try to play blackthorne thingy, it just goes to next file since it fails playing

**Comment by droidmjt** [comment]
i'll do fresh install with dropbox version and see

**Comment by droidmjt** [comment]
same deal..just goes directly to next file

**Comment by KynikossDragonn** [comment]
This is a pretty weird problem... I wonder what's with this file that makes it impossible to play.

I'm currently testing the changes to ADLMIDI, so give me a moment to see if everything's working fine for this.

**Comment by droidmjt** [comment]
where did you get that blackthorne mid file?

**Comment by KynikossDragonn** [comment]
http://hoot.joshw.info/pc/blackthorne_at.zip Here's the origin. It's for HOOT but the .xmi's can be extracted out of the ZIP and played with anything from XMIPLAY to whatever supports .XMI files.

The MIDI.ADV in the archive I think means Blackthorne used a pretty old (before it was even called MSS) Miles Sound, I think AIL?

Here's where I got syndicate's XMI from:
http://hoot.joshw.info/pc/syndicate_at.zip

**Comment by droidmjt** [comment]
http://www.mirsoft.info/gmb/music_info.php?id_ele=MTMzNzA=

is that the same?

**Comment by KynikossDragonn** [comment]
Yes, it's the same songs, but these files were recorded through logging as it played via a UART, it doesn't have the loop information that the original data (what the HOOT archive contains) uses, so trying to listen to them on repeat will result in stuck notes when it jumps back to the beginning of file. This is why I'm trying to use the .XMI files instead since you added the loopstart detection feature (which even works in Duke3D!!!!!!)

**Comment by droidmjt** [comment]
ah yes, it reads there its recorded, crap.

**Comment by droidmjt** [comment]
i check the syngame

**Comment by KynikossDragonn** [comment]
Speaking of loop detection, I just now realized it only seems to work with ADLMIDI for me, BASSMIDI just goes back to the beginning of the file when it hits the end. And on a side note with this, PLT205 from NAM has a horrendously stupid loop point, it's kinda amusing seeing droidsound-e handle it just like it does ingame.

**Comment by droidmjt** [comment]
don't expect BASSMIDI subsong feature to be ready any time soon. The rest is working now.

**Comment by KynikossDragonn** [comment]
No biggie, thanks alot for your hard work.

Is the loop detection part of ADLMIDI's source code? If so I should probably dive into it to see how it can loop Duke3D just like ingame but Winamp cannot. (though it's MIDI loop detection seems to hinge on tracks named "loopStart" and "loopEnd")

**Comment by droidmjt** [comment]
check latest beta from dropbox, bassmidi subsong feature is not there yet, but its coming

**Comment by KynikossDragonn** [comment]
Works just fine, now I can listen to original combat music to Syndicate and not that dubstep crap the reboot featured. Thanks!

I might even try using this to make playlists out of SystemShock's XMI's but is it possible to add duplicate entries on the playlist?

**Comment by droidmjt** [comment]
why would you need duplicate entries?

**Comment by KynikossDragonn** [comment]
Due to the way SystemShock's XMI's are, each "subsong" is actually a piece of a whole track. So if I wanted to make a whole song I'd have to make a playlist for one with some of the subsong entries duplicated in a few parts to have it somewhat like it is in-game.

I'm not sure about TerraNova: Strike Force Centauri though.

**Comment by droidmjt** [comment]
ah that kind of stuff. By the way, do you have midi files that have subsongs using looping?

**Comment by KynikossDragonn** [comment]
Not on hand, or any I'd know of. The only MIDI's I have that feature loop points would be NAM and Duke3D. (but these are not XMI's and instead are standard MIDI files with features of the "Apogee Sound System" put into) Blackthorne's .XMI's have looppoints too, so does FF7 for the PC.

And systemshock's "subsongs" all loop by themselves as the game's music engine has the intro and main parts of the song as separate subsongs in the .XMI file. (For example, it plays subsong 8 9 10 11 then goes to playing subsongs 3 4 3 4 and 5, something weird like that. )

**Comment by droidmjt** [comment]
bassmidi subsong thing fixed, i'll upload new beta today

**Comment by droidmjt** [comment]
new binary in dropbox.com link

**Comment by KynikossDragonn** [comment]
BASSMIDI Subsong selector works just fine.

here's a debug crashlog of blackthorne_ingame1.xmi

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException
	at com.droidmjt.droidsounde.service.PlayerService.playNextSong(PlayerService.java:479)
	at com.droidmjt.droidsounde.service.PlayerService.playNextSong(PlayerService.java:495)
	at com.droidmjt.droidsounde.service.PlayerService$MyHandler.handleMessage(PlayerService.java:387)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5365)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)

============================
Droidsound-E version: 34
Time: Tue Apr 21 18:04:26 CDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: samsung/gardaltetmo/gardaltetmo:4.2.2/JDQ39/T399UVUANI2:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 2087002112
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
new version in dropbox link, should work now

**Comment by KynikossDragonn** [comment]
Holy crap it works, thank you!

All that really remains with the MIDI plugin is getting BASSMIDI to recognize loop points, but if that's too much of a issue I can just close it here. I'm quite happy with how ADLMIDI handles all the songs I'm used to hearing on OPL anyways!

**Comment by droidmjt** [comment]
looppoints, it does recognize looppoints, send me a song that fails

**Comment by KynikossDragonn** [comment]
Stand by, still testing things out.

**Comment by droidmjt** [comment]
all right i hold my breath also :)

**Comment by KynikossDragonn** [comment]
Alright here's two that ADLMIDI handles loop points in but not BASSMIDI:

https://dl.dropboxusercontent.com/u/45822870/STALKER.MID
https://dl.dropboxusercontent.com/u/45822870/PLT205.MID

**Comment by droidmjt** [comment]
i check

**Comment by droidmjt** [comment]
new binary in dropbox.com link

**Comment by KynikossDragonn** [comment]
Holy hell you even made it recognize the loop points in these converted Warcraft MIDI files, thank you!

I got this strange crash when I started this version though (it happened only once by the way):
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.sddb.droidsound.OPEN_DONE flg=0x10 } in com.droidmjt.droidsounde.PlayerActivity$5@423a1f88
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:773)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5365)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.droidmjt.droidsounde.database.SongDatabase.updateplistCount(SongDatabase.java:2482)
	at com.droidmjt.droidsounde.PlayerActivity$5.onReceive(PlayerActivity.java:1145)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:763)
	... 9 more

============================
Droidsound-E version: 34
Time: Fri Apr 24 02:20:29 CDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: samsung/gardaltetmo/gardaltetmo:4.2.2/JDQ39/T399UVUANI2:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 2183704576
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
try with the latest version from dropbox.com link, if it still happens, i'll check it.

**Comment by droidmjt** [comment]
do close this issue if there is nothing more to add

**Comment by KynikossDragonn** [comment]
I'm sorry for the delays in response I've been having phone and personal problems.

I've also been trying to collect some more samples to test against but, missing my harddrive after moving back to my family I've lost quite a bit of music to test with... still trying to scour the web for it.

I still need to update to whatever latest binary you have now or will soon but the binary I have currently, for some odd reason blackthorne's music will pause at the loop point (it continues to "play" but it acts as if I hit pause, as in, the notes that are playing will decay to silence and time playing will just infinitely accumulate)

**Comment by droidmjt** [comment]
i'll check it

**Comment by droidmjt** [comment]
I just tried blackthorne_ingame1.xmi and no problems with loop point.

**Comment by KynikossDragonn** [comment]
I suppose whatever it was probably was fixed, link says 40 hrs ago, are you pushing another debug build or is it safe to grab this one for testing on my end?

**Comment by droidmjt** [comment]
new binary uploaded, try it out

**Comment by KynikossDragonn** [comment]
Still happens. This is with BASSMIDI not ADLMIDI, should of mentioned sorry.

**Comment by droidmjt** [comment]
so you enable the forever loop (2-arrow thing) and then start the song (blackthorne_ingame.xmi) correct?

**Comment by KynikossDragonn** [comment]
Yeah, and right when it hits the loop point, all notes stop playing and fade into silence and this goes on forever until I press stop.

**Comment by droidmjt** [comment]
i try again

**Comment by KynikossDragonn** [comment]
And what's really bizzare, this does NOT happen to my Cyberbykes XMI's and those don't even have loop information, just "EOF". ADLMIDI isn't affected by this bug, so there's that.

**Comment by droidmjt** [comment]
no problems here, do you have any bassmidi settings enabled?

**Comment by KynikossDragonn** [comment]
DecaySeek DecayEnd NOCROP are all checked, since this was the only way (until you added loop detection) to make the music fade out the notes rather than hard cut them off when the loop occurs. (Though a caveat is, some MIDI's that send reset instructions at the very beginning of the file will cause all the notes to cut abruptly, this can't be avoided by design and is a good thing actually. Duke's MIDI's have reset instructions but have loop points to avoid resending the instructions again when the song repeats)

**Comment by droidmjt** [comment]
i try with those settings

**Comment by droidmjt** [comment]
you are correct, this should be easy fix, i was able to reproduce the problem now

**Comment by KynikossDragonn** [comment]
This may very well be the last thing to even fix for this. Though I wonder which option or combination of, is actually causing this?

**Comment by droidmjt** [comment]
nocrop

**Comment by KynikossDragonn** [comment]
Also just a refresher, is the reason why the voices cut out so much is due to coding differences with BASSMIDI for android?

I had a recording of this playing on FluidSynth and it sounds way different... I also could of sworn I had one of it playing through BASSMIDIDrv for Windows but, I don't have any MP3 or FLAC recordings sadly. I really need to keep better track of my things....

**Comment by droidmjt** [comment]
i have no idea, new binary uploaded

**Comment by KynikossDragonn** [comment]
Alright everything's working just fine! Case closed.
