### ISSUE TITLE
Regression: Latest Version Stops at EOF for MIDI if Additional Song Length is used

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#161]
Using MIDs from Master of Magic, once it gets to end of file, the player stops and will not go forward to the next track if additional song length is set.  This is testing on my Galaxy S3 with 5.1 CM12.1, I will be testing on the other devices later.

**Comment by droidmjt** [comment]
Easy fix :) thanks for reporting it.

**Comment by droidmjt** [comment]
what's the expected behaviour in this case, should it advance to next file or do something else?

**Comment by droidmjt** [comment]
nevermind, this is done

**Comment by droidmjt** [comment]
new binary in dropbox.com link

**Comment by Level99OCR** [comment]
Grabbing it now.

**Comment by Level99OCR** [comment]
Tested fixed on SGS3 4.4 stock.
