### ISSUE TITLE
atrac3plus audio with more than 2 channels cause FC.

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#162]
As title says.

**Comment by droidmjt** [comment]
Google Play version or BETA? possible to send me the song?

**Comment by droidmjt** [comment]
nevermind, i managed to reproduce the problem, it's not about channel amount, its something else

**Comment by VIRGINKLM** [comment]
It's Google Play version, I just ripped myself some tracks from Tekken Revolution (there's no public rip for them yet). There are stereo and 6 channe versions of the same track, the stereo versions work well (atrac3plus, 48KHz, 320kbps) but the 6 channel versions (atrac3plus, 48KHz, 512kbps) force close the app. I could provide you with the files.

**Comment by droidmjt** [comment]
sure, just send one file. how much memory in your device?

**Comment by VIRGINKLM** [comment]
(Change extension to at3)
![new world order multichannel](https://cloud.githubusercontent.com/assets/3772761/7221233/92dfca32-e6eb-11e4-8954-ed995fdaeaab.PNG)
My device is has 1GB for RAM which like 700MB are available while using the app.

**Comment by droidmjt** [comment]
got the file, problem found, it gets invalid number of samples

**Comment by VIRGINKLM** [comment]
File plays normally in FFMpeg/vgmstream on Windows though, maybe it's a bit more complicated than an incorrect value of samples.

**Comment by droidmjt** [comment]
it's just that, i'll deploy fix very soon

**Comment by droidmjt** [comment]
fixed, hopefully I can upload new beta soon

**Comment by droidmjt** [comment]
new binary in dropbox.com link

**Comment by VIRGINKLM** [comment]
Thanx, tested again but I get the same issue. Could it be a device specific issue? (DSP not allowing 6-channel audio to be downmixed to Stereo)

**Comment by droidmjt** [comment]
![screenshot_2015-04-21-12-46-26](https://cloud.githubusercontent.com/assets/5917820/7249775/841a60a8-e825-11e4-86d9-fc4c485d1ca4.png)

it works, see the songlength, this is the file you sent me :)

**Comment by droidmjt** [comment]
i'm using Samsung Galaxy S3 device

**Comment by VIRGINKLM** [comment]
Nope doesn't work. Checking issue #123 I guess it's either an HTC software issue (devices from 2011-2012) or an Android software issue (possibly ICS devices can't deal with multichannel at all). From the image you posted I guess it's a S3 Touchwiz Kitkat ROM based on Note 2's KitKat ROM which could make sense why it works on that one (they must have added support post-4.1.x versions). Possibly the stock ICS ROM of Galaxy S3 might have the same issue.

**Comment by droidmjt** [comment]
did it create droidsounde_crash*.log files in your droidsound/ folder? if yes, send the latest files here, if it didn't you need to send me logcat log

**Comment by VIRGINKLM** [comment]
Yep, here it is:

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.IllegalArgumentException: Unsupported channel configuration.
	at android.media.AudioTrack.audioParamCheck(AudioTrack.java)
	at android.media.AudioTrack.<init>(AudioTrack.java)
	at android.media.AudioTrack.<init>(AudioTrack.java)
	at com.droidmjt.droidsounde.service.AsyncAudioPlayer.init(AsyncAudioPlayer.java:227)
	at com.droidmjt.droidsounde.service.AsyncAudioPlayer.run(AsyncAudioPlayer.java:90)
	at java.lang.Thread.run(Thread.java:864)
============================
Droidsound-E version: 34
Time: Tue Apr 21 14:01:26 EEST 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: htc_asia_wwe/htc_shooteru/shooteru:4.0.3/IML74K/385730.1:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls 
Lang: Ελληνικά
Locale: el_GR
InternalSD free space: 4276420608
InternalSD path: /mnt/sdcard

**Comment by droidmjt** [comment]
Tried with vanilla android 4.0.x, same deal, i suppose its broken in 4.0.x. Odd thing is that in Android developer pages it reads 5POINT1 channel configuration is supported already in API level 5 :). I'll add notification for this kind of events so it prevents crashing.

**Comment by VIRGINKLM** [comment]
Also you can add it in Google Play as "known issues". Also I guess this issue doesn't need to be open anymore, if we need to do more tests on narrowing down exactly what happens and under the exact  conditions we can discuss that further with a closed issue.

**Comment by droidmjt** [comment]
when i have time, i can try to add resampler option for compatibility so that it resamples 5point1 to Stereo, no idea how it sounds afterwards tho.

**Comment by VIRGINKLM** [comment]
Just a downmixer would do I guess, but just for decices that can't handle it and it should give a notice that the device is unable to handle multichannel audio and it will fall back to a compatibility workaround.

**Comment by droidmjt** [comment]
get the latest beta, it has a fix :) i'll need to add it also to vgmstream

**Comment by VIRGINKLM** [comment]
Yep, it works now, even though it reports the audio as Stereo.

**Comment by droidmjt** [comment]
yes because it is Stereo now, i can add there a msg that 5.1->Stereo

**Comment by VIRGINKLM** [comment]
Yeah, I guess that's the best option for devices that have to go that way.
