### ISSUE TITLE
Crash on scan

### ISSUE THREAD

**Issue by superandroidtron** [droidmjt/Droidsound#164]
I'm currently running Android 5.0.2 on my OnePlus One, and every time I try to scan my library, the application tries scanning the ZIP version of HVSC (spending upwards of 20 minutes on the play store version of the app), then crashes with a nondescript error message. This did not occur when I was on 4.4. I've tried both the beta and release versions of the app (including the latest beta uploaded moments ago).

**Comment by droidmjt** [comment]
in droidsound folder, there should be some crash log files, post them here or send logcat log please

**Comment by superandroidtron** [comment]
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.droidmjt.droidsounde/com.droidmjt.droidsounde.PlayerActivity}:
android.database.sqlite.SQLiteDatabaseLockedException: database is locked
(code 5): , while compiling: SELECT TITLE FROM PLAYLISTS WHERE TITLE=?
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
at
android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3941)
at android.app.ActivityThread.access$1000(ActivityThread.java:147)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database
is locked (code 5): , while compiling: SELECT TITLE FROM PLAYLISTS WHERE
TITLE=?
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native
Method)
at
android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
at
android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at
android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at
android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
at
android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
at
com.droidmjt.droidsounde.database.SongDatabase.createPlaylist(SongDatabase.java:2682)
at
com.droidmjt.droidsounde.PlayerActivity.checkPlaylists(PlayerActivity.java:945)
at
com.droidmjt.droidsounde.PlayerActivity.onCreate(PlayerActivity.java:1671)
at android.app.Activity.performCreate(Activity.java:5933)
at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
... 11 more
============================
Droidsound-E version: 34
Droidsound-E Build: 2
Time: Thu Apr 30 17:56:35 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: oneplus/bacon/A0001:5.0.2/LRX22G/YNG1TAS17L:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
idivt
Lang: English
Locale: en_US
InternalSD free space: 48452751360
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
do you use AIMP?

**Comment by droidmjt** [comment]
In case you do use it, there was another person with oneplus one phone having problems with Droidsound-E and the root cause was AIMP, after he removed AIMP, DS-E started working again.

**Comment by superandroidtron** [comment]
I do not have AIMP installed.

**Comment by droidmjt** [comment]
All right, do you have any other audio related apps installed? also try the very latest beta. The log doesn't tell much, only that the DB is locked.

**Comment by droidmjt** [comment]
try the latet beta i just uploaded

**Comment by droidmjt** [comment]
try this binary
https://www.dropbox.com/s/e456v8e44k5wchl/droidsound-debug02.apk?dl=0

**Comment by droidmjt** [comment]
ignore that, try the beta from usual link.

https://www.dropbox.com/s/lr2n45tvajjpq5c/droidsound-debug.apk?dl=0

**Comment by droidmjt** [comment]
try the latest GP version instead. I'll close this case due to inactivity. feel free reopen it when you can test more
