### ISSUE TITLE
SPC Files Skip

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#167]
i'm having problems with spc files on my phone (Power Saver is not on this time) they skip when try to play them. any ideas why?

**Comment by droidmjt** [comment]
which version? latest beta?

**Comment by Sir-Sabin** [comment]
the beta, it uses alot of cpu when playing spc files, 2sf and gsf files work great on it

**Comment by droidmjt** [comment]
go to settings and see the interpolation option, set it to None

**Comment by Sir-Sabin** [comment]
yep i have the latest beta from 7 days ago and set it to none makes it only skip at the beginning of he songs

**Comment by droidmjt** [comment]
what was your phone again, model and brand?

**Comment by Sir-Sabin** [comment]
it's a Samsung Galaxy Ace II X S7560M

**Comment by droidmjt** [comment]
all right

**Comment by droidmjt** [comment]
I just tested it with 1.2GHz dual-core phone using every interpolation methods, it uses lots of CPU but no skipping. The funny thing is that before i added the interpolation setting in DS-E it always used the most CPU consuming option (Sinc).

**Comment by droidmjt** [comment]
wtf...i just tried the GP version and it uses half-less cpu...fixing time...

**Comment by droidmjt** [comment]
I compared the GP version with the latest BETA and they consume same amount of CPU. I used the same 1.2GHz dual-core phone.

**Comment by Sir-Sabin** [comment]
there is nothing that is running it stays at 3% to 10% when it's idling

**Comment by JFD62780** [comment]
Speaking of SPCs, the latest, Signed build, thinks RSNs are SonicArranger files and tries to open them via UADE.  Is this related?

**Comment by JFD62780** [comment]
...This just in: instant crash on playing a separate SPC (starfield demo in Example folder) in latest build.

Phone: Samsung Galaxy S4
OS: Android KitKat 4.4.4

**Comment by droidmjt** [comment]
crap, i'll check it

**Comment by droidmjt** [comment]
Just tested this, copied sftr.rsn to /mnt/sdcard/Music and added filebrowser to the folder, played fine, RSN files are nowadays treated as archives.

**Comment by droidmjt** [comment]
The main reason why UADE tries to play it is that none of the other plugins detect it. In your case the .RSN is detected as a normal file in your DB while the player tries to treat is as an archive. Rescanning will help you :)

**Comment by JFD62780** [comment]
...Forgive me for unnecessarily getting you to post three times in a row -- The rescan worked.  Way better than ever.  I let it scan and went to sleep, and when I woke up it WASN'T stuck rescanning in an endless loop!  IT'S A MIRACLE! XD

**Comment by droidmjt** [comment]
great :)

**Comment by droidmjt** [comment]
@Sir-Sabin, does the google play version work?

**Comment by Sir-Sabin** [comment]
yea it played but lagged a bit, sorry it took so long i kept forgetting when i was on pc,

**Comment by droidmjt** [comment]
v1.663 google play version?

**Comment by Sir-Sabin** [comment]
The One on the play store i'll test it again when i get my new sd card from amazon

**Comment by droidmjt** [comment]
so you have tested with play store version (1.663) with your old phone, correct?

**Comment by droidmjt** [comment]
something just crossed my mind about the delays...i'll make debug build soon for you to try

**Comment by droidmjt** [comment]
ah crap .. i just realized that i cannot access almost anything now...the debug build has to wait now

**Comment by droidmjt** [comment]
i got myself a VPN access, I'll make a new debug build soon and upload it for you to test

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/czqlcra25wxv1er/droidsound1663_nowidget.apk?dl=0

try that and let me know how it works

**Comment by Sir-Sabin** [comment]
No Change, it still skips

**Comment by droidmjt** [comment]
bugger, well, i still have few options left, let's see, i'll make another debug build soon.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1h137xlejy7d1uz/droidsounde1664_04.apk?dl=0

**Comment by Sir-Sabin** [comment]
That fixed it, it works on my old phone without skipping

**Comment by droidmjt** [comment]
excellent, one headache less, close this case.

**Comment by Sir-Sabin** [comment]
Roger Roger
