### ISSUE TITLE
QSF options disappear after changing (4.3)

### ISSUE THREAD

**Issue by 47iscool** [droidmjt/Droidsound#169]
After I played one qsf file changed some settings the qsf options are gone from the audio setting.

**Comment by droidmjt** [comment]
what settings you changed? DS-E has no QSF specific settings at least.

**Comment by 47iscool** [comment]
I think I disabled interpolation.

Can't remember thouh because it happened when I was using the Google Play version l.

**Comment by 47iscool** [comment]
Sorry for the typos, I hate typing on android.

**Comment by droidmjt** [comment]
which plugin interpolation?

**Comment by 47iscool** [comment]
Maybe I was mistaken, maybe I was on the gsf plugin without noticing.

Also FYI I have no more xsf memory leaks on 4.3.

**Comment by droidmjt** [comment]
Good to hear that no more memory leaks. Unfortunately i cannot reproduce that other problem of yours.

**Comment by 47iscool** [comment]
Like I said it could have just been me on options for another xsf plugin. I'm not really worried about it anyway. Also thanks for trying.

**Comment by droidmjt** [comment]
no problem, if you manage to reproduce this again, feel free to reopen this issue

**Comment by 47iscool** [comment]
Okay thanks a million.l

**Comment by 47iscool** [comment]
Yet more typos, sorry.
