### ISSUE TITLE
Slow Scanning and extracting files on LG-G3

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#171]
i've ran into a problem with my new phone a LG-G3 running Lolipop 5.0.1, it scanning and extracting big files in 7z, could this be a OS bug or droidsound bug?

**Comment by droidmjt** [comment]
first off, congrats for the new phone, i suppose the SPC playing is no more the problem (close the related ticket)  :)

secondly, note that 5.00, 5.01 and 5.02 version have this and that broken + there is this memory leak problem that is not fixed before 5.1.1. 

It is hard to say what is the problem really, I have 5.0.2 phone and it scans very fast. How did you measure the scanning speed, comparing to the old phone or?

**Comment by Sir-Sabin** [comment]
It's slow when scanning some 7z (at3 files are one of them) i know its not a sdcard issue as i just copied a 300mb file to the phone from the sdcard.

**Comment by Sir-Sabin** [comment]
Also when it reads from 7z files there is a long delay before it plays for big files in 7z files

**Comment by droidmjt** [comment]
7z files are slow if they use solid-block feature.

**Comment by Sir-Sabin** [comment]
the 7z files are not solid and droidsound is using 56 to 82 mb of ram and there's 1.4gb of ram free, it plays files no problem with files that aren't compressed

**Comment by droidmjt** [comment]
Don't worry about the file cache, its just 32mb that it needs. 
Also make sure that by any chance there is no power saving/balanced power mode running. I'll do some scan tests with my new and old phone. For how long it takes your phone to scan 300mb 7z archive (at3 files) ? where did you get the 7z files, josh site?

**Comment by droidmjt** [comment]
Don't worry about the file cache, its just 32mb that it needs. 
Also make sure that by any chance there is no power saving/balanced power mode running. I'll do some scan tests with my new and old phone. For how long it takes your phone to scan 300mb 7z archive (at3 files) ? where did you get the 7z files, joshw site?

**Comment by droidmjt** [comment]
>>Also when it reads from 7z files there is a long delay before it plays for big files in 7z files.

how big file you are trying to play and how big is the archive?

**Comment by Sir-Sabin** [comment]
it's any type from gsf, 2sf, btrsm, etc, the big the file is the longer it takes for it to load from the 7z files

**Comment by droidmjt** [comment]
what i noticed is that if i perform a full rescan and turn my phone screen off, the CPU becomes very slow meaning that there is a wakelock problem, this happens with CM12.1 ROM tho.

where did you get the 7z files?

**Comment by Sir-Sabin** [comment]
i made them myself, they are non-soild 7z files from the files from joshw's site

**Comment by droidmjt** [comment]
then i need one those files, just one 7z is enough that helps me to reproduce the problem

**Comment by droidmjt** [comment]
actually, i do the 7z myself

**Comment by droidmjt** [comment]
try this for comparison:
get these files:

http://psp.joshw.info/g/Grand%20Theft%20Auto%20-%20Liberty%20City%20Stories%20(2005-10-24)(Rockstar%20North,%20Rockstar%20Leeds)(Rockstar).7z

http://psp.joshw.info/a/Archer%20Maclean%27s%20Mercury%20%5b%5bHg%5d%20Hydrium%5d%20(2005-04-06)(Awesome%20Studios)(Ignition).7z

unpack them both and then repack them in to same archive using LZMA method and non-solid block, double check that it is indeed non-solid block. Use normal compression level, you should get around 388MB sized archive having both games inside. Upload that archive to separate folder in your phone that has no other files, then create filebrowser to the folder and take time how long it scans.

After scanning, reset filecache, and play the GTA song number 11.  (36MB) sized)

Let me know how long the scanning time was for the archive and how long it took to start playing that file.

**Comment by Sir-Sabin** [comment]
I let the file scan when i was sleeping it was the same results, it took about a min for it to play it from the test folder on my phone

**Comment by droidmjt** [comment]
it took also around 1min here with solid block using very old phone

**Comment by Sir-Sabin** [comment]
Could there be a bug in 7z unpacker causing it to be slow or is it the phone itself?

**Comment by Sir-Sabin** [comment]
I'm going to take the phone back to bestbuy as it has the wrong os installed as it should have 4.4 installed not 5.0.1

**Comment by droidmjt** [comment]
it took 1min to start playing with sgs3 phone using solid block but using nonsolid block it took only 7 seconds with same device...on my newer phone it was 27 seconds (solid block) and 3 seconds (non solid block)

**Comment by Sir-Sabin** [comment]
It even doing it with zip files i made with the phones file manager, is your phone lollipop 5.0 to?

**Comment by droidmjt** [comment]
yes it is lollipop 5.0.2 version. dont use phones file manager. i created my files on PC.

**Comment by droidmjt** [comment]
i used 7zip to create those files

**Comment by Sir-Sabin** [comment]
So it might be a phone issue then

**Comment by droidmjt** [comment]
not the phone itself but the file manager app

**Comment by Sir-Sabin** [comment]
Is that causing droidsound to scan 7z and zip files to be so slow?

**Comment by droidmjt** [comment]
It is the file manager that prolly creates not so compatible archives.

**Comment by Sir-Sabin** [comment]
I made the 7z files from my pc not my phone.

**Comment by droidmjt** [comment]
ah ok i thought you made both with your phone's file manager. anyway, it is hard to say what is wrong, i'm using the latest beta tho but it has no changes related to archive handling.

**Comment by droidmjt** [comment]
if you make zip files with your PC is it still acting odd?

**Comment by droidmjt** [comment]
what app do you use to create 7z archives on your pc?

**Comment by droidmjt** [comment]
about 388mb archive test, since it is non-solid block archive and took 1min for you to get the test file playing while my ancient 1.4ghz phone handled the same case in 7 seconds, can you see the potential problem here? 

since your phone is quad core 2.5ghz it should have handled that very fast.

after googling a bit about lg g3 and 5.0.1 problems i found ppl complaining about various things, one was a performance issue

**Comment by droidmjt** [comment]
few things comes to my mind:
1. lg really screwed the 5.0.1 update
2. your cpu is not running at max speed
3. you accidentaly created solid block archive

please post here a screenshot of the 388mb archive info

**Comment by Sir-Sabin** [comment]
my cpu doesn't run at full speed it runs at 60% and uses 2 cores of the 4 it has, here is a sceenshot of the The G File i made from the 2 folders: https://www.dropbox.com/s/ibi64rw5b64mp27/The%20G%20File.jpg?dl=0

**Comment by droidmjt** [comment]
please add the screenshot here.. i cannot access dropbox now..just drop the image the message box and it will attach it

**Comment by Sir-Sabin** [comment]
Here is 
![the g file](https://cloud.githubusercontent.com/assets/6171863/7828464/d0c1f950-0401-11e5-895b-c929386fd0d8.jpeg)

**Comment by droidmjt** [comment]
looks good...so its not the archive type then. really strange...try to create a zip file (use PC) of the same content and see what happens. let me also know which app you use to create the zip including the switches

**Comment by Sir-Sabin** [comment]
I'm going to try and zip them with ZArchiver i have installed and see if that works

**Comment by droidmjt** [comment]
wouldnt it be faster to pack on pc then adb push to phone?

**Comment by Sir-Sabin** [comment]
Driodsound isn't reading the zip file with the apps on my phone ill try on my pc later

**Comment by Sir-Sabin** [comment]
Droidsound won't read the file made from the pc to, it's just to 2 blank folders when it's done scanning

**Comment by droidmjt** [comment]
there is nothing i can do for now...once i get back home i investigate this more

**Comment by Sir-Sabin** [comment]
I took the phone back, it wasn't working the way i wanted it to do and it was throwing errors at me when copying on the phone and my pc, so it's back to my old phone for now and wait for the s5 to come down and hope it doesn't come with 5.0 preinstalled

**Comment by droidmjt** [comment]
crap :( too bad it didn't become fully clear what was the root cause for the slowdown.

Anyway, I was checking earlier sammobile website about firmware versions and learned that USA(AT&T) at least is still on 4.4.2 version, many have moved to 5.0 already. If you want to avoid all the hassle with firmwares, get Nexus 5. It will get Android M in Q3 also. Heck, even Nexus 4 got Android 5.1.1 image :(

I think Motorola Moto G and  X series are also quite solid.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/czqlcra25wxv1er/droidsound1663_nowidget.apk?dl=0 

try that and let me know it works

**Comment by Sir-Sabin** [comment]
I got a New Phone, A Samsung Galaxy S4 with 5.0.1 and it works great, no slow scanning and reading of files in 7z or zip files and the G.Folder scanned fast to, i guess it was something LG did with lollipop that caused it

**Comment by droidmjt** [comment]
that's good news, i suppose it is LG-only thing then. 

Odd case, especially now that you have 5.0.1 OS....oh well, let that remain a mystery, do close this case.

**Comment by Sir-Sabin** [comment]
Roger Roger
