### ISSUE TITLE
Donkey Kong 64 USF stuttering and slowdown

### ISSUE THREAD

**Issue by Diamondragon** [droidmjt/Droidsound#172]
I didn't see this one listed on the unsupported games list so I was curious: does anyone know if this title's music is supposed to work? I'm trying to play it from a non-solid 7z on a Nexus 5 (Snapdragon 800), but it has the aforementioned problems. Weird thing is, is isn't consistently maxing out any of my cores despite the slowdown.

**Comment by droidmjt** [comment]
7z format doesn't affect playing performance. 

Current LazyUSF1 library messed up some formats, for example quake2 used to play, after @kode54 did some changes, it stopped working, blame him :)

I can later see if the lazyusf2 would work better.

**Comment by Diamondragon** [comment]
Ah, I'm glad you knew about it. Thought I was going crazy! Thanks for the answer, too.

**Comment by kode54** [comment]
You could either be a good boy and bisect the bug, or just switch to lazyusf2, which may break some other things while fixing Quake 2.

Donkey Kong 64 is not likely to work properly on a mobile device that isn't super powerful, unless someone feels like implementing ARM dynamic recompiler, which will only ever work on Android devices, since everyone else forbids executing unsigned code.

**Comment by droidmjt** [comment]
@kode54, sorry dude, i was a bit too hasty, this dk64 problem is different than quake2. i think the dk64 problem can be fixed..after listening few songs i feel that its some small buffering issue..lets see

**Comment by kode54** [comment]
DK64 is also a PAL game, maybe you need to look into how the save state is loaded and processed for its region code? (The ROM header is included in the save state, but usually not the ROM itself.)

**Comment by droidmjt** [comment]
i tried again the dk64 songs...when i enabled the HLE option it worked fine..without it , it almost plays..nexus5 should be able to play it with HLE enabled..remember to restart the song acter enabling HLE

**Comment by droidmjt** [comment]
i close this case since HLE seems to work...i will open other issue when/if lazyusf2 has been added
