### ISSUE TITLE
Lockscreen controls. 

### ISSUE THREAD

**Issue by x-amp** [droidmjt/Droidsound#173]
I recently updated to the Google Playstore version of Droidsound and for some odd reason, no matter what format I'm playing, using the lock screen controls have a massive delay. Sometimes they don't seem to work at all. When I revert to 1.662 the issues isn't there.

**Comment by droidmjt** [comment]
what android version you use?

**Comment by droidmjt** [comment]
also that 1662 version, is it beta or official version?

**Comment by x-amp** [comment]
I believe it was beta.. I using a Samsung Galaxy S4 on android version 4.4.2

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/czqlcra25wxv1er/droidsound1663_nowidget.apk?dl=0

try, it has widget disabled + no psf reverb option, let me know how it works

**Comment by x-amp** [comment]
Seems to work better. After a restart, there is a bit of a delay on the first time I try to move to the next track. After that its fine.

**Comment by droidmjt** [comment]
all right, i'll make a new debug build soon, let's see if we can get this fixed

**Comment by x-amp** [comment]
Are you able to duplicate the issue on your end? After a couple of day of use, the lock screen  controls have a hit and miss situation. The press is registered but the action is delayed. Weird thing is, the notification controls work flawlessly even while the phone is in the lockscreen

**Comment by droidmjt** [comment]
i tried with 4.4.4 and was not able to reproduce the problem, i'll get back to this when i get back home

**Comment by droidmjt** [comment]
sigh,now that i started fixing bugs again, i'll make a new binary today and lets see if it fixes the remaining problem.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1h137xlejy7d1uz/droidsounde1664_04.apk?dl=0

**Comment by x-amp** [comment]
Looks like we have a winner. I'll play around with for most of the day and see if anything changes.

**Comment by droidmjt** [comment]
good good, i hope it works finally

**Comment by x-amp** [comment]
Seeing no problems. Think this one is solved

**Comment by droidmjt** [comment]
excellent, i'll close this case.
