### ISSUE TITLE
[Enhancement]Add Bass Wavepack library

### ISSUE THREAD

**Issue by lybxlpsv** [droidmjt/Droidsound#174]
so wavepack encoded soundfont/sf2pack can be used.
saves quite alot of space, turned down the huge CrisisGM from 1.6gb to 300mb, Roland SC-55 25mb to 5mb and Setzer SPC 1mb to 200k.

**Comment by droidmjt** [comment]
no problem but are you aware that the packed soundfont cannot be used directly, it must be unpacked first to phone memory/sdcard and then used according to BASSMIDI documentation, so you wouldn't win anything spacewise

**Comment by lybxlpsv** [comment]
yey
it's sf2pack not sfpack, according to documentation wavpack(lossy)/flac(lossless) encoded soundfont can be used directly if wavpack/flac library is present.

also tried making simple bassmidi player loading crisis packed with wavpack on pc, didn't notice any free space different after loading the soundfont

**Comment by droidmjt** [comment]
all right, i hope it is so that i don't need to unpack it to a file first. but you can imagine how slow it is for android device to unpack 300MB file to 1.6GB :( let's see how this goes

**Comment by droidmjt** [comment]
this is done, i'll upload a new beta soon

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/asaqtnesxevqmd5/droidsounde1664_02.apk?dl=0

i just tested it on emulator, let me know how it works

**Comment by lybxlpsv** [comment]
works, haven't tried crisis. thanks for implementing once again :)

**Comment by kode54** [comment]
sf2pack does not unpack the entire file, but only individual samples when loading them. I would also advise trying FLAC as well, since that may not compress as well, but it will definitely decompress a lot faster.
