### ISSUE TITLE
Midi playback problem

### ISSUE THREAD

**Issue by lybxlpsv** [droidmjt/Droidsound#175]
http://tyuson.sakura.ne.jp/midi/fffile/10/ff10ryoko/ryoko_syxg100.mid
http://tyuson.sakura.ne.jp/midi/fffile/10/ff10blitz/ff10blitz.mid
http://tyuson.sakura.ne.jp/midi/fffile/10/ff10syugeki/syugeki_syxg100.mid

also this midi sounds terrible, probably theres some poly limit?
http://tyuson.sakura.ne.jp/midi/fffile/10/ff10kessen/kessen_syxg100.mid

**Comment by droidmjt** [comment]
those first 3 songs fails because of a bug in BASS library, on x86 it works fine, but fails on armv7a. This has been reported to author. About the kessen song, which soundfont do you use? Does it sound bad from the beginning or ?

**Comment by droidmjt** [comment]
It seems on Android the midivoices setting is using value 40 by default, i'll add an option to set it between 40-1000, that should fix the problem with kessen song.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1h137xlejy7d1uz/droidsounde1664_04.apk?dl=0

**Comment by droidmjt** [comment]
i suppose it works :)
