### ISSUE TITLE
SNSF Support?

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#176]
Can you put SNSF Support in Droidsound? I dunno if Caitsith made the source code available

**Comment by droidmjt** [comment]
i have some source but not sure if it is correct. could you tell me where i can get some example songs, thanks

**Comment by Sir-Sabin** [comment]
With a Google search i found this: http://snsf.caitsith2.net/ hope they work

**Comment by droidmjt** [comment]
ah of course, i should have done it myself :) I'll see what I can do about it.

**Comment by droidmjt** [comment]
ehh, according to the modland there is around 10 games ripped using this format, do you think it makes sense to have this format supported? I'm quite sure the same games exist in almost every other format

**Comment by Sir-Sabin** [comment]
Some games can't be ripped to spc like lost viking which can't be ripped to spc, I know it has small number of games

**Comment by droidmjt** [comment]
well, i'll see that later, currently i have other tasks

**Comment by 47iscool** [comment]
I was also going to ask about this but forgot. 

It would be great if you could when you have the time.

**Comment by droidmjt** [comment]
this is done, will be available in next build :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/o8ih8dyvnjx1945/droidsounde1664_52.apk?dl=0

if it works as expected, close this case

**Comment by Sir-Sabin** [comment]
Works great on the three games have on my phone, i will close this case now
