### ISSUE TITLE
4.1 crash logs

### ISSUE THREAD

**Issue by 47iscool** [droidmjt/Droidsound#177]
As you requested some weeks back.
My brother decided to try DSE again and got the same problems. It crashes when scanning PSF,USF & GSF.

https://www.dropbox.com/s/18vvqn3wo9smj6o/DSE%20Crash%20Logs%20%28Android%204.1%29.7z?dl=0

**Comment by droidmjt** [comment]
Are you using archives of any kind or just plain files? Try to see if you can disable some applications since this is memory issue. All the libs together takes around 30MB of memory, if your memory is that tight, i recommend unloading some other apps while using DSE.

**Comment by 47iscool** [comment]
No compression used.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/l71gyhqi6de0vqu/droidsounde1664_22.apk?dl=0

Try that build.
I tested it with 30-40 GSF/PSF/USF sets using Android 4.1 OS with 384MB of memory and scanned/played perfectly.

**Comment by 47iscool** [comment]
Alright, I will ask my brother to test and will let you the results on Sunday. Also lazyusf2 is great, no more lags with any game.

**Comment by 47iscool** [comment]
Let you know, I meant.

**Comment by 47iscool** [comment]
Works great, not sure what you did but thanks a lot. My brother said to give his thanks.

**Comment by droidmjt** [comment]
great, cheers :)
