### ISSUE TITLE
.ads not detected

### ISSUE THREAD

**Issue by 47iscool** [droidmjt/Droidsound#178]
Not sure why but the vgmstream plugin isnt detecting .ads files which is basically the same as .ss2 files but has a different extension.

**Comment by droidmjt** [comment]
prolly forgot to include that extension, i'll add it, will make a new build soon

**Comment by 47iscool** [comment]
Thanks. Just wanted to let you know.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/l03gnapjfh3hhpm/droidsounde1664_23.apk?dl=0

that should fix it

**Comment by droidmjt** [comment]
reopen this case incase the problem is still there

**Comment by 47iscool** [comment]
Working great thanks.

Would have tried it but I have been under the weather for a while.

**Comment by droidmjt** [comment]
good good
