### ISSUE TITLE
Source code license needed

### ISSUE THREAD

**Issue by logomancer** [droidmjt/Droidsound#179]
There appears to be nothing in this repo saying what license this code is under. Can you clarify by adding a license file or headers in your source code? Thanks!

**Comment by droidmjt** [comment]
sure, but may i ask for what reason?

**Comment by droidmjt** [comment]
added license, all good now?

**Comment by logomancer** [comment]
Well, adding a license file lets people know under what terms they can use your source code. The license file as-is is not useful because it doesn't say anything about this. I'd suggest selecting a license. If this code is open source, there are many to choose from: http://choosealicense.com/

**Comment by droidmjt** [comment]
yes and i chose the No License thing

**Comment by logomancer** [comment]
If you're retaining all rights then you should add 'All Rights Reserved' to make that clear.

**Comment by droidmjt** [comment]
I did exactly what they told in that page about this type of license.

**Comment by logomancer** [comment]
Fair enough.
