### ISSUE TITLE
Scrobbler support added

### ISSUE THREAD

**Issue by droidmjt** [droidmjt/Droidsound#184]
http://www.last.fm/user/droidmjt/library

I'll finish the feature and upload new binary soon. Let me know if there is something related to Scrobbling that I should take care of.

The feature can be enabled/disabled.

**Comment by HumbleBeeBumbleBee** [comment]
Hi @droidmjt ! Super excited to see your work and test the apk.

**Comment by 47iscool** [comment]
What's this?

**Comment by HumbleBeeBumbleBee** [comment]
@47iscool 
From Google... 
To "scrobble" a song means that when you listen to it, the name of the song is sent to a Web site (for example, Last.fm) and added to your music profile. Here's how it works: Once you've signed up and downloaded Last.fm, you can scrobble songs you listen to on your computer or iPod automatically.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1vxvuvw03h29ybf/droidsounde1664_42.apk?dl=0
let me know how it works :) at least for me it worked quite ok
