### ISSUE TITLE
Crashed on my Oneplus 2

### ISSUE THREAD

**Issue by LGA1150** [droidmjt/Droidsound#186]
I've got a Oneplus 2, Android 5.1.1, Snapdragon 810 ARM64 CPU. The APP failed to start after I installed it.

**Comment by droidmjt** [comment]
sorry to hear that, I need logcat log, most likely DS-E created it for you and is located in droidsound folder, if not there, you need to create one with adb.exe

**Comment by droidmjt** [comment]
Which version you are using?

**Comment by LGA1150** [comment]
1.664_52

**Comment by LGA1150** [comment]
I E-mailed the log to you.

**Comment by droidmjt** [comment]
got it, i'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bn8kxqmeh8ucp2j/droidsounde1664_53.apk?dl=0

**Comment by LGA1150** [comment]
Thanks, it works!

**Comment by droidmjt** [comment]
excellent, i'll close this case

**Comment by LGA1150** [comment]
@droidmjt 
Don't forget to update the download link!
:)

**Comment by droidmjt** [comment]
done :)
