### ISSUE TITLE
Bug on PMD Play? 

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#187]
http://hoot.joshw.info/pc98/grnsd98.zip
GS_08.M2 have strange noises when the piano solo starts.
http://vgmrips.net/packs/pack/grounseed-nec-pc-9801-opna#08-i-gat-feeling-milly
The right playback is like above...

**Comment by droidmjt** [comment]
did the same song work before in any other version?

**Comment by crimson1117** [comment]
in 201501?? version there is no bug...I just used this debug version(the most new) as I re-used an Android.

**Comment by droidmjt** [comment]
What android version you use with droidsound? secondly, could you tell me the exact location of the piano solo. 201501??, so some build from 2015 January?

**Comment by droidmjt** [comment]
nevermind, found the solo part, at least on emulator both sound the same :(

**Comment by droidmjt** [comment]
what is the report songlength on your device for the song?

**Comment by droidmjt** [comment]
crap, on real device it fails, but works fine on emulator, i'll check it more

**Comment by droidmjt** [comment]
do you have a build that works with the gs_08.m2 song?

**Comment by crimson1117** [comment]
ah,I checked. in the 140613 test version I also found this bug...That's the most early version that supports PMD...

**Comment by droidmjt** [comment]
i checked codes back to 2014, it seems this never worked, on ARM, the songlengths are always incorrect, luckily there is another pmd library, if that fails, then there is nothing i can do, this is pmd library issue, actually.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/9x4c9mvg9mjb6hx/pmd.zip?dl=0
ignore this message

**Comment by droidmjt** [comment]
it seems this is related to some difference between x86 and ARM during compile/linking, it might take forever to find it :(

**Comment by crimson1117** [comment]
...umm,vgm can solve this GS_08.M2 thing,just put it to far-away future?

**Comment by droidmjt** [comment]
all right, i'll close this case and i remember this, i try to fix it later

**Comment by droidmjt** [comment]
this has been fixed, will upload new binary later today
