### ISSUE TITLE
pausing on bluetooth

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#189]
When you are playing through bluetooth music  players including xmp player will pause the track when the bluetooth speaker or car stereo is turned off. But on droidsound-e it then continues playing through the android device so then you have to manually pause it yourself. I listen to modules and SIDS in the car and I wonder please could you fix this problem. Thank you

**Comment by droidmjt** [comment]
although i don't own a single bluetooth device (except my phone), i can try to fix it

**Comment by filevans** [comment]
Thank you very much. Droidsound has given me the chance to listen to all the music formats while I'm driving in my car. That is brilliant

**Comment by lybxlpsv** [comment]
@droidmjt if you have Windows 7 PC/Laptop you can use a2dp sink mode/play music http://i.imgur.com/IIjbyws.png

**Comment by droidmjt** [comment]
news to me, i'll see if i can use that

**Comment by droidmjt** [comment]
good news, this is fixed, i'll upload new binary today, i need to finish some other things first :)

**Comment by droidmjt** [comment]
I tried to fix this metadata + bluetooth problem but it seems SGS6 is somewhat retarded, on SGS3 CyanogenMod 12.1 it sends the metadata ok, but on SGS6 it doesn't, identical code...good work samsung. No idea what is wrong.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/fiixnjfpm8a6ijw/droidsounde1664_64.apk?dl=0
let me know how it goes

**Comment by drew887** [comment]
I can confirm that it pauses upon shutting down my bt headphones or if they go out of range. It takes ~5-15 seconds for the pause to happen though. 

It also doesn't pause if I just turn off the phone's Bluetooth; it just starts playing out of the phone.

**Comment by droidmjt** [comment]
>>It also doesn't pause if I just turn off the phone's Bluetooth; it just starts playing out of the phone. 
ah, i'll fix it

**Comment by filevans** [comment]
No hang on . thats the right behaviour. Just deactivating phone's Bluetooth should not pause music. It should only pause upon turning off Bluetooth speaker or headphones.

**Comment by droidmjt** [comment]
all right, i'll see what i can do

**Comment by filevans** [comment]
What i mean to say is you've done it right already. Just the delay seems a bit long that's all. Thanks a lot. Well done!!

**Comment by droidmjt** [comment]
thanks, I noticed I was waiting for a wrong intent, thats why the delay, fix will arrive shortly, stay tuned :)

**Comment by droidmjt** [comment]
fixed, now it pauses instantly :) i'll upload new binary

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/4oqi2ht4rqies06/droidsounde1664_65.apk?dl=0

**Comment by drew887** [comment]
Works instantly

**Comment by filevans** [comment]
Works well thank you. Only problem is now play/pause and track forward/ backward buttons don't work on the Bluetooth speakers or car stereo to control the music. So when you get back in the car you still have to go to your phone to start the music again. Could you add those basic functions in too? Also when receiving a phone call through Bluetooth will it automatically pause the music And resume after call? Xmp player, Es file explorer and poweramp do all that including the basic play/pause forward/back.  Thanks a lot for your help well done

**Comment by filevans** [comment]
Sorry is working now. Wasn't the first time for some reason

**Comment by filevans** [comment]
Resume playing after a call automatically doesn't work though

**Comment by droidmjt** [comment]
fixed, new binary coming in few minutes

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/lhs8w2ebldy8pwo/droidsounde1664_66.apk?dl=0

**Comment by drew887** [comment]
Just tested the resuming and pausing during/after a phone call and it works for me, both with and without a BT device.

**Comment by droidmjt** [comment]
great news :)

**Comment by Level99OCR** [comment]
Testing with car audio and bluetooth headphones. My only apparent issue is that if the device is on and I'm looking at a different screen besides Droidsound, I can't pause, skip, or go back a song in the app. With screen off or screen focused on DSE, it's not an issue.

Bluetooth is a pain in the butt.

**Comment by drew887** [comment]
I can use my BT headphones to pause, play, and skip forward/backwards from any screen. Even from lockscreen/ screen off. O:

**Comment by Level99OCR** [comment]
Could honestly be a bug on my device, then. I'll tinker with other devices to see how they do.

**Comment by filevans** [comment]
Yes everything works fine for me too. The first time I ran it I had the problem. So I did the reset GUI and restarted phone then everything worked fine.

**Comment by droidmjt** [comment]
@Level99OCR on what devices this last bug happens? 
@drew887 what devices you tested with?

**Comment by drew887** [comment]
I used my Nexus 5, I can also test with a nexus 4 if need be.

**Comment by droidmjt** [comment]
nexus devices are rock solid, i'm not surprised it works as expected with those :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/gj7101mk8m209gm/droidsounde1664_68.apk?dl=0
not really related to bluetooth, but for x86, @Level99OCR , try this build if it would speed up things on your x86 device

**Comment by droidmjt** [comment]
it also works on my devices, no matter if its in DSE screen or in some other

**Comment by droidmjt** [comment]
any updates here?

**Comment by droidmjt** [comment]
reopen this case if need to

**Comment by Level99OCR** [comment]
It's my specific device, Asus Zenfone 2, that cause the bluetooth issues for me. Sorry for false positive.

**Comment by droidmjt** [comment]
no problem
