### ISSUE TITLE
mod volume amplification

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#190]
Please could mod volume application be added like xmp player and modo have (x2, x3). As modules can be very quiet. Or a normalize option would be even better. Thank you for listening.

**Comment by droidmjt** [comment]
if you download the latest unofficial binary, there is a volume control, normalize will come in next version (1.665).

**Comment by droidmjt** [comment]
i'll close this case since part of it is already implemented in the latest binary, the rest will follow in 1.665
