### ISSUE TITLE
set default folder location

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#191]
Would it be posible to set a default folder location so when you load the program it goes straight to there instead of the list of folders and shortcuts to network. Or remember last directory you were in would be even better

**Comment by droidmjt** [comment]
this feature is already there

**Comment by filevans** [comment]
For some reason it wasnt but is now. Thanks a lot

**Comment by filevans** [comment]
For some reason it wasnt but is now. Thanks a lot
