### ISSUE TITLE
feature request: automatically play next song

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#193]
Is it possible to have autoplay next song without adding files to playlist. From browser. As I tried to play an sc68 with sub songs and it just stops after the first song and doesn't advance to next sub song

**Comment by droidmjt** [comment]
there is a setting that allows it to advance to next subsong, also, the latest binary has manual playqueue creator that enables this for everything, i'm still busy adjusting various things

**Comment by filevans** [comment]
Yes but the setting is not working for sc68 at least. Just stops. General behaviour for playing sc68 and advancing is strange. I left them playing and it stops after a subsong. but then it suddenly started playing the next track after a very long silence. Might just be the plugin itself though

**Comment by droidmjt** [comment]
what build you are using?

**Comment by droidmjt** [comment]
i just tested couple of sndh tunes, it has 4 subsongs, and it worked as expected, im using the unofficial _55 build

**Comment by droidmjt** [comment]
the setting must be enabled BEFORE you click a song :)

**Comment by filevans** [comment]
Yes I have had it enabled constantly since I installed it as I always go straight into options and set things up how I want them.
Try to play a folder of sc68 files. Strange behaviour...

**Comment by filevans** [comment]
Build 53. I was waiting for Bluetooth pausing to be fixed before I downloaded a new build as I won't be using it until then as I mainly want to play in my car

**Comment by filevans** [comment]
Try sc68. Might be different. I haven't tested sndh much

**Comment by filevans** [comment]
Can i send you some sc68 files of mine

**Comment by droidmjt** [comment]
sure, thats the optimal way to solve problems usually. SC68 is not so popular anymore, most of the stuff is SNDH, see http://sndh.atari.org

**Comment by filevans** [comment]
Yes i already know about sndh I've got that pack. But Amiga uses the ym / sc68 module type too and that pack doesn't include any Amiga music which Is a lot. And a lot of really excellent stuff.
Where can I send you some sc68 files? Email?
Thanks

**Comment by filevans** [comment]
Emailed you a file now mate
Thanks

**Comment by droidmjt** [comment]
all right, i'll check it, cheers

**Comment by droidmjt** [comment]
no files in my email box, droidmjt@gmail.com

**Comment by droidmjt** [comment]
nevermind, its there, saw wrong :)

**Comment by droidmjt** [comment]
I tested the SC68 song you sent, unfortunately it works as expected, I can try with few other devices tho, let's see. I have no long pauses or anything, once the subsong ends, next one starts normally.

**Comment by filevans** [comment]
It must be the version I'm using then 53. Probably resolved now

**Comment by droidmjt** [comment]
I haven't changed the sc68 recently, it must be something else. I go get some small bluetooth device soon, so i can finally fix these bluetooth problems.

**Comment by droidmjt** [comment]
there is a new build now, check it out, should fix the BT problem

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/fiixnjfpm8a6ijw/droidsounde1664_64.apk?dl=0

**Comment by droidmjt** [comment]
any change with this?

**Comment by filevans** [comment]
Sorry for the delay. I found out one of the problems for the long pauses or silences is that  some sc68 don't make any sound. It us playing and the timer is going along but no sound coming out on some tracks. I'll send you some of the files for you to take a look at. Thanks a lot

**Comment by droidmjt** [comment]
http://sourceforge.net/p/sc68/bugs/11/
The guy knows this problem already, there is nothing i can do here except wait for a new build of SC68 library.

**Comment by droidmjt** [comment]
close this case, we can reopen it one day when the lib is fixed
