### ISSUE TITLE
new UI thoughts

### ISSUE THREAD

**Issue by droidmjt** [droidmjt/Droidsound#195]
please try out the latest binary and let me know your thoughts about the UI. In settings click the Restore GUI incase the old GUI is still there.

**Comment by drew887** [comment]
Love the new look, especially the shadow on the description text. Feels very sleek and modern.

**Comment by sketch242** [comment]
I think the shadow makes it a little harder to read, personally.  I preferred the black background to the grey.  Matter of taste, though.  Also, I was kinda hoping for a total material design overhaul after the back arrow appeared in the upper left in dev builds a while back.  :)

**Comment by droidmjt** [comment]
>>shadow makes it a little harder to read? 

in which view? PLAYER view?
>>complete material design overhaul? 
It is using material design where possible, if you have some examples of the material design you are looking for, paste me a link.

**Comment by droidmjt** [comment]
ah, the shadow under the texts in player view, if you mean that, i have reduced the shadow size, and changed the background a bit darker. If you wish to change it by yourself, go to droidsound/theme/ and edit the gui.css file. Line 295 is the background color and below you can see the shadow values, save it and restart the app. Of course if you set background to #000000, then shadows also disappear completely :)

**Comment by droidmjt** [comment]
once i get my bluetooth dongle, i fix the remaining BT problems and requests, then it's time for an official release. After that, we head to a new version that brings more good stuff, hopefully :)

**Comment by droidmjt** [comment]
I'll close this case, reopen this case if you have some concerns/problems with the UI

**Comment by 47iscool** [comment]
Like it, plus I see snsf support has been added.
