### ISSUE TITLE
Feature Request: Lollipop/Marshmallow Lockscreen controls?

### ISSUE THREAD

**Issue by LGA1150** [droidmjt/Droidsound#196]
DS-E does have lockscreen control, when I was on Android 4.4.4 Kitkat.
But now I'm using Android 5.1.1 Lollipop, and the feature is gone.

**Comment by droidmjt** [comment]
how does your lockscreen look like when DS-E is playing music?

**Comment by LGA1150** [comment]
It shows as a normal notification.

**Comment by droidmjt** [comment]
try to drag it down, see what happens

**Comment by LGA1150** [comment]
It unlocks the screen and directly goes to the notification bar..

**Comment by droidmjt** [comment]
in lock screen, if you touch the DS-E notification and drag it down, it will show you the controls, this is feature in Lollipop and above. This has been tested with various nexus devices, numerous samsungs devices and emulators, there is nothing i can do here.

**Comment by droidmjt** [comment]
![dse_lockscreen](https://cloud.githubusercontent.com/assets/5917820/10562789/ec4bf6c2-7575-11e5-9194-2d85cb05b2b0.png)

**Comment by droidmjt** [comment]
![dse_lockscreen2](https://cloud.githubusercontent.com/assets/5917820/10562831/a711b8f0-7578-11e5-97e9-3bed90adf446.png)

**Comment by droidmjt** [comment]
there, dragging down the notificationm :)

**Comment by droidmjt** [comment]
what happened, not working? what device do you have?

**Comment by droidmjt** [comment]
http://www.howtogeek.com/202404/how-to-tame-notifications-in-android-5.0/

**Comment by LGA1150** [comment]
It only works after I disabled the Screen Lock PIN. I don't know it is a bug or feature.

**Comment by droidmjt** [comment]
![dse_lockscreen3](https://cloud.githubusercontent.com/assets/5917820/10564919/c68cd012-75cc-11e5-8a88-077962da9c2a.png)

**Comment by droidmjt** [comment]
really ? :) 

from phone settings, after you enable PIN, it should ask you what you want to show in lock screen, make sure you didn't select the option to hide everything

**Comment by droidmjt** [comment]
I was googling about this topic earlier today and learned that there are numerous pages where people complain about this problem. I also thought the controls were gone, obviously they are just hidden :)

**Comment by droidmjt** [comment]
I'll close this case, reopen this if you think there is something i could change in DS-E
