### ISSUE TITLE
Can't Add Stuff From Ext. SD Card

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#198]
I found i can't add stuff like a file folder or soundfonts from my ext. sd card. i was able to do it before. i'm still using a Samsung S4 with 5.0.1 installed, any ieads why it's doing this?

Edit: i'm using the latest Beta version of droidsound

**Comment by droidmjt** [comment]
yeah i know this bug, i'll fix it, sorry about that

**Comment by droidmjt** [comment]
when you try to mount the filebrowser, what folders you see on the root level?

**Comment by Sir-Sabin** [comment]
It seen everything, i got a storage folder and it had the Ex. Sd Card in it, that new build fixed it for me, thx for help

**Comment by droidmjt** [comment]
great, remember to click the Restore GUI button in settings to get the latest UI. I'll close this case.
