### ISSUE TITLE
feature request: simple folder explorer instead of database

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#199]
Hello. Would it be possible to have an option to just have a simple straight forward folder explorer rather than a database. Like other music programs. As the database takes a long time to scan and personally I don't see why it has to have it. On bsplayer if you play a file it automatically adds all the songs in that folder to the playlist for example. And poweamp and xmp player just automatically play the next song and none if them use a database. Thank you for listening.

**Comment by droidmjt** [comment]
it's there already, New -> Filesystem Browser, enjoy :)

**Comment by filevans** [comment]
I do that but it still then scans the folder I add and updates database.
And another problem related to it is if you then add a new folder it doesn't only scan that folder to add to database butvrescans all the old folders again that you already had added. And takes a long time. Which I thought seems inefficient.
Is there a way to just add a folder without adding to database and waiting for it to scan everything
Thanks

**Comment by droidmjt** [comment]
you can disable rescan from settings. Also if you enter to FileSystem Browser and click New -> Folder, you can avoid the rescan

**Comment by filevans** [comment]
Oh yes got it now. Sorry about that. Great

**Comment by droidmjt** [comment]
great :)
