### ISSUE TITLE
feature request: normalize or gain option for mp3 / bass plugin

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#200]
Hello. Please could you add the normalize or gain option for mp3 / bass plugin. As I would now like to use droidsound-e for my mp3 player now all the Bluetooth features have been added and fixed as I really like the player. And some mp3s vary in volume as you know depending on album or rip. Thanks for listening

**Comment by droidmjt** [comment]
yes this is on my backlog, will arrive in version 1.665, i'll close this case and reopen when the feature is ready to be tested
