### ISSUE TITLE
feature request: connect / add local wifi network share

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#201]
OK this is my last feature request. Not sure if this is already there, as has the option to add a network, but I wanted to connect to my wifi network folders where I have all my files shared. I tried to add the IP address but wouldn't let me add it. Thanks for your help

**Comment by droidmjt** [comment]
if this is quick feature, i'll add it in this version, if it takes long time to implement, then 1.665. The network accepts HTTP/FTP servers currently.

**Comment by filevans** [comment]
Im trying to add my router usb share which is 192.168.1.1

**Comment by filevans** [comment]
Another related feature is a network cache. Not sure if it has it already, especially needed for mp3 playing across WiFi. ESFileexplorer doesn't have a network cache and you can get skipping playback. So that is something else please you could consider if not already there

**Comment by droidmjt** [comment]
there is cache already :)

**Comment by droidmjt** [comment]
im currently adding the feature, this should be quick

**Comment by filevans** [comment]
Wicked sounds!!

**Comment by filevans** [comment]
I am bordering on happy now!!

**Comment by droidmjt** [comment]
browsing works already :) this feature will be ready today, it was easier than I thought, after all this was very good idea.

**Comment by filevans** [comment]
All my ideas are good ;-)
Thanks for implementation

**Comment by droidmjt** [comment]
new binary coming in few minutes :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/0f8uj9kimregzi9/droidsounde1664_69.apk?dl=0

**Comment by droidmjt** [comment]
smb://192.168.1.1/blabla or smb://username:password@192.168.1.1/blabla should work

**Comment by droidmjt** [comment]
found a small bug about the userinfo, fixing it now

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tvyig6v99uw8qzq/droidsounde1664_70.apk?dl=0

**Comment by droidmjt** [comment]
another problem...

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/l364ejmlnn3pod1/droidsounde1664_71.apk?dl=0
finally

**Comment by droidmjt** [comment]
new version coming, SMB performance improved

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nkpoxwq6s83x2hf/droidsounde1664_72.apk?dl=0

**Comment by droidmjt** [comment]
reopen this case if need to

**Comment by filevans** [comment]
I cant work out his to add a network location. You gave an example but not mentioned which one to select to add it in the first place. I press the + then do i choose network link or file browser? I tried both and it doesn't add. I typed in my root share which is

smb://admin:password@192.168.1.1

But nothing adds. I have 3 drives on there. And wanted to add the root share so I can just browse any drive

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/3ob8lnobq2nsnpc/droidsounde16645_04.apk?dl=0

Instructions:
1. New -> Network Link
2. Choose the folder where you want the .lnk file to be placed, for example /dsroot/Network with the selector, so the fullpath should be /sdcard/dsroot/Network
3. In second box type: smb://username:password@192.168.1.1/ <- note that required slash
4. Last box type something
5. Click OK

just incase i pasted the instructions here too :)

**Comment by filevans** [comment]
Please could you put the directory listing in alphabetical order and also sort directories to top  as at the moment everything is jumbled up together and sorting doesn't work on network for some reason. As sometimes I like to sort by date to see latest added songs and its not working. Also on view options an option to sort directories to top please. Thank you for listening

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tf8ntrkziuov0h4/droidsounde16647_01.apk?dl=0

**Comment by droidmjt** [comment]
I'll close this case, if something is wrong with this, let me know.
