### ISSUE TITLE
Feature Request: Remove plugins from Plugin Settings that have been disabled

### ISSUE THREAD

**Issue by TeamFail** [droidmjt/Droidsound#202]
Basically the title. If I've disabled a particular plugin because I don't use it, shouldn't it also not be shown in the Plugin Settings menu as well since I have no need for it (And inherently no need to configure it at all in any way?)

**Comment by droidmjt** [comment]
is that a real problem actually?

**Comment by TeamFail** [comment]
It's mostly just to keep the Plugin Setting list neat if other plugins are disabled. It's not really a high-priority issue, but it'd be really nice for housekeeping. Besides, at least for me, the app runs much faster when I only have the plugins I need enabled, hence why I did it in the first place.

**Comment by droidmjt** [comment]
Makes sense, well, I'll see what I can do.

**Comment by TeamFail** [comment]
Alright, sounds good. Guess I'll close this for now then.

**Comment by droidmjt** [comment]
A small problem with this one, for the preference entries there is no chance to hide them, only add/remove, so if i remove, and then add again, the order changes and that may confuse users, if there would be hide option i could just add it now :( 
Sorry about that.
