### ISSUE TITLE
App repeatedly opens a blank white page

### ISSUE THREAD

**Issue by thebigl1** [droidmjt/Droidsound#204]
When moving between the different tabs in Droidsound it seems to randomly try to open some kind of page, but it looks like a blank white screen until I press Back to return to Droidsound itself. It seems to resemble those full screen ads some games use.

(Sorry about the duplicate under Closed, the mobile interface doesn't seem to have buttons to edit your posts)

(EDIT 2- I can't seem to reproduce this now, but I'm wondering if it had something to do with another app, or the option to restore the CSS file)

**Comment by droidmjt** [comment]
Weird case, never experienced this, if you manage to reproduce this problem, let me know how, until that, close the issue. The CSS file restoring just extracts the latest from the package and it has only few things changed compared to previous version. Maybe some other app interfered this.

**Comment by thebigl1** [comment]
I've noticed that it seems to happen when I unlock the phone while Droidsound is in the foreground. By holding the Home button to see the tasks running, this blank white page seems to be "Dual Clock", one of the built-in apps.

To be exact, if I have Droidsound in the foreground and lock the phone with the power button, then after swiping my lock screen, that's when it seems to open the blank page. It's not 100% consistent, but it's the most I've been able to reproduce this.

**Comment by droidmjt** [comment]
i upload new binary tomorrow, i think it fixes this problem

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/0dup9gn7fzhhhwd/droidsounde1664_74.apk?dl=0
try that

**Comment by thebigl1** [comment]
I haven't seen the white screen in a while, but I'll keep an eye out. Think I'll close this for now. Thanks for the new APK!
