### ISSUE TITLE
Gauntlet Legends USF stuttering and hangs

### ISSUE THREAD

**Issue by thebigl1** [droidmjt/Droidsound#206]
This isn't the first time it's happened, but for a while I was able to play this USF set just fine. In the current build though, any songs from it I try to play will stutter for about five seconds and then lock up part of the app, preventing it from playing anything. I tried toggling HLE (high level emulation), and tried the USF set on Modland's server, and it still stutters.

**Comment by droidmjt** [comment]
when this worked last time?, if you can remember the build, even better

**Comment by thebigl1** [comment]
I'm pretty sure it was a couple builds ago from the Google Play Store version. Is there a way to roll back the version, or should I just get an older APK?

**Comment by droidmjt** [comment]
couple of builds, great, then it is easier to track down what might cause it, at this moment, getting an older version is your only choice. What is your device that you use?

**Comment by thebigl1** [comment]
Still my Samsung Galaxy S4.

**Comment by droidmjt** [comment]
ah this problem, it is library related issue, nothing i can do about it, if the library gets fixed one day, i'll update it in DSE.

**Comment by droidmjt** [comment]
I'll close this, I'll reopen this when/if there is a fix in the library
