### ISSUE TITLE
plugins in alphabetical order

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#207]
Please could you put the plugins in alphabetical order in audio settings as they are all jumbled up and hard to find the right one to change the settings
Thank you

**Comment by droidmjt** [comment]
all right, I'll change it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/z1p38190qztoc59/droidsounde1664_77.apk?dl=0

**Comment by filevans** [comment]
Great thank you. Please could you check closed issue about adding samba network share please mate. It is not working for me

**Comment by droidmjt** [comment]
you forgot to add "/" at the end of the uri, thats why it didn't work, i tried it like that and didn't work here either, but after i added the "/", it worked, that is a requirement for SMB things

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/3ob8lnobq2nsnpc/droidsounde16645_04.apk?dl=0
here is the latest build

**Comment by filevans** [comment]
Ok i still can't get samba share working it will not even add the folder. I asked in the other post if I should add network link or filebrowser but you didn't answer. Well I tried both neither worked. The folder link won't add. I presumed I should press '+' then choose either network link or filebrowser. Could you give clear instructions how to add the folder as too complicated. On es filexplorer it us simple. You just choose network then add IP address. Very easy.

**Comment by droidmjt** [comment]
are you using this build:
https://www.dropbox.com/s/3ob8lnobq2nsnpc/droidsounde16645_04.apk?dl=0 

Instructions:
1. New -> Network Link
2. Choose the folder where you want the .lnk file to be placed,  for example /dsroot/Network with the selector, so the fullpath should be /sdcard/dsroot/Network
3. In second box type: smb://username:password@192.168.1.1/
4. Last box type something
click OK

**Comment by droidmjt** [comment]
I can also make this so that, the first box is gone and it will automatically put the .lnk file in correct place, under the Network.

**Comment by droidmjt** [comment]
lemme see the other post, i must have missed it

**Comment by filevans** [comment]
Yes automatic link would be better no first box
 I didn't know what I had to put in the first box.

**Comment by droidmjt** [comment]
yeah I agree it is a bit misleading and annoying, i'll change it, i suppose you got it working?

**Comment by droidmjt** [comment]
crap, can't remove that box actually, some users probably don't need the folder and/or want to keep their network related things elsewhere

**Comment by filevans** [comment]
No still cant get the network folder to show. I can see it's created the lnk there but cannot see any folder to select. I did everything you said. Not sure what is happening

**Comment by droidmjt** [comment]
![smb](https://cloud.githubusercontent.com/assets/5917820/10961248/5fd8714c-8395-11e5-9ea7-038450a3f0b3.png)

**Comment by droidmjt** [comment]
i know for a fact that it works :) That is my Windows share, can't really think what is wrong with your setup.

**Comment by droidmjt** [comment]
double check that your full smb://  line ends with "/", then make sure that the share is indeed enabled. Others could also participate in this to make sure if its just one user or all :)

**Comment by filevans** [comment]
Even if it won't connect it should still add so you can ammend it. But it just won't add. And it is annoying to fill each field every time to keep testing. I am using the build after you added this feature I'm going to try this latest build now

**Comment by filevans** [comment]
Ok it is adding now on this latest build. Good.

The alphabetical order is much better too. Just one thing please could you change and put title for SC68 as SC68 and not Atari ST and put it further down with S... titles. As it is more logical to look for it under header sc68. Plus it is used more by Amiga than ST. Atari ST songs are all on sndh now. My whole collection of sc68 are Amiga modules 100s of them. No ST. and also Amiga sc68 modules are much better quality with high quality samples rather than bleeps. Just doesn't make sense to put sc68 under A..

**Comment by droidmjt** [comment]
sure, i'll change it

**Comment by droidmjt** [comment]
changed, can we close this case?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tf8ntrkziuov0h4/droidsounde16647_01.apk?dl=0

**Comment by droidmjt** [comment]
I'll close this, reopen this case if something is wrong with this request.
