### ISSUE TITLE
pmd playback error

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#209]
those pmd files with pcm plays error now...what happened

**Comment by crimson1117** [comment]
http://hoot.joshw.info/pc98/evebe.zip 1664_59 still ok,seems from 72 that bug is there....

**Comment by droidmjt** [comment]
i'll check it later today, most likely easy fix

**Comment by droidmjt** [comment]
fixed, i upload new binary soon for you to test

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tf8ntrkziuov0h4/droidsounde16647_01.apk?dl=0

**Comment by crimson1117** [comment]
thanks
