### ISSUE TITLE
Crash when listing file with Japanese character

### ISSUE THREAD

**Issue by lybxlpsv** [droidmjt/Droidsound#210]
When I add file browser to a folder that has JP char it just crashes.
<example removed because reasons>

**Comment by droidmjt** [comment]
all right, i'll check it, thanks for reporting it.

**Comment by droidmjt** [comment]
uploading new binary now

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/wgomm75v2470nld/droidsounde16647_02.apk?dl=0

**Comment by droidmjt** [comment]
if it still crashes, better get crashlog

**Comment by lybxlpsv** [comment]
finally found a working micro USB cable :p
Works on cm12.1.
