### ISSUE TITLE
Can no longer change tracks with headphone remote button

### ISSUE THREAD

**Issue by sketch242** [droidmjt/Droidsound#211]
I used to be able to switch to the next/previous track by double-clicking or triple-clicking on the headphone remote.  However, this functionality seems to have broken recently.  Also, a single click does still stop playing the current track, but another single click will not restart it. 

Due to the timing, I'm not sure if it's due to updating to Marshmallow or if it was a change in a recent release of Droidsound-E   I am sure it's not related to the phone itself, as I first noticed it shortly after updating my Nexus 5 to Marshmallow, but it died a couple of weeks ago and I replaced it with a Nexus 5X, where I see the same behavior.

**Comment by droidmjt** [comment]
not related to hardware, prolly a bug due to recent changes, can you send me a screenshot or a link the device you are using (the headphone remote button), i need to know how it looks like, how many buttons it has etc etc

**Comment by sketch242** [comment]
Just a single-button remote (no volume control) on a set of cheap-ish Philips earbuds.  Something like this (except in a less hideous color scheme):
http://www.amazon.com/Philips-SHE2675BG-28-Discontinued-Manufacturer/dp/B004JU0E9O

**Comment by droidmjt** [comment]
All right, so how exactly it worked before with a single button? 2-clicks -> next song, 3-clicks prev song?

**Comment by sketch242** [comment]
Yep, exactly like that.  Also I'm pretty sure that one click after stopping would start playing again.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/cln0btp84i58h4d/droidsounde16647_03.apk?dl=0
this should fix the problem, works exactly like before

**Comment by droidmjt** [comment]
reopen the case if the problem is still there.

**Comment by sketch242** [comment]
Works perfectly again.  Thanks!
