### ISSUE TITLE
freezes when playing mp3s

### ISSUE THREAD

**Issue by GL1TCH04** [droidmjt/Droidsound#212]
i have this huge with music (seemingly only streamed music files like mp3s, etc) played in droidsound-e causing my phone to freeze once i lock its screen while said music is playing
after a few seconds, the music then begins to occasionally stutter
the phone doesn't react to any buttonpresses whatsoever
i've tried out different things like enabling/disabling accurate sound data and the wakelocks, but to no avail

model: gt-i9505
OS: 5.0.2 (Aurora S6 Port)

**Comment by droidmjt** [comment]
what version of the app?

**Comment by GL1TCH04** [comment]
version is 1.6646
files are local

**Comment by droidmjt** [comment]
i just tested your scenario with 1.2GHz Dual-Core device and in lockscreen / screen turned off mode it doesn't stutter. The problem is most likely the custom ROmyou are using. I will add a setting that allows you to change the buffer size, it most likely solves your problem.

**Comment by GL1TCH04** [comment]
at first i also thought it was the rom (considering it's a port of the galaxy S6 firmware for the S4) but the thing is, i'm not having any issues whatsoever with the built-in music player
also again, it's not just music stuttering, it's the entire device completely locking up, requiring me to force power it off and reboot it

i'll try with the buffer size setting though and report back

**Comment by droidmjt** [comment]
"port of the S6 firmware for the S4"...sounds like a nightmare :)
>>  i'm not having any issues whatsoever with the built-in music player

Of course, it probably have just one native library in use. I think this is most likely native library related issue, the BASS library is not compatible with the ROM. I will create you a test build within few hours then we know how it is.

**Comment by GL1TCH04** [comment]
alright, i'll be waiting and have a look once i have it

also, it's actually not that bad
ever since i started using it, things have slowly been getting fixed and it's almost good as a daily driver now, aside from the camera still being a bit buggy

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/cln0btp84i58h4d/droidsounde16647_03.apk?dl=0
let me know how it goes

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/hlgm23h8a93m081/droidsounde16647_03b_testonly.apk?dl=0

**Comment by droidmjt** [comment]
try both

**Comment by GL1TCH04** [comment]
alright, after doing a tiny rom update, installing a different kernel and setting up said kernel, i installed and used both versions
they seemed to take a bit long to load files, but i fixed that by setting the sdcard read ahead to ~4mb
the first version (the one without "testonly" in the filename) froze on screen lock
the testonly version seems to have that fixed (tried it twice)

**Comment by droidmjt** [comment]
now we know the error, the testonly uses ffmpeg to play the mp3, the other one uses BASS, compatibility issue

**Comment by droidmjt** [comment]
try netradio, see what happens

**Comment by droidmjt** [comment]
did you try netradio?

**Comment by GL1TCH04** [comment]
netradio doesn't work at all
it just doesn'T open

**Comment by droidmjt** [comment]
so it's the BASS library that is not compatible then, all right, this is clear now.
