### ISSUE TITLE
Reverb muting NES noise channel

### ISSUE THREAD

**Issue by 47iscool** [droidmjt/Droidsound#213]
Not much to explain really. I'm using the latest version on GP.

Also I'm not sure if its a problem on my end, but reverb only works for nsf/nsfe.

I was wondering it will be implemented for vgm as well.

**Comment by droidmjt** [comment]
>> Also I'm not sure if its a problem on my end, but reverb only works for nsf/nsfe.

which formats you tried? It won't work with SPC, VGM and GYM.

>> I was wondering it will be implemented for vgm as well.

When the global reverb/echo becomes available, then yes.

**Comment by droidmjt** [comment]
at least tell me a song how i can reproduce the muting problem, tried with few examples and couldn't hear the difference.

**Comment by 47iscool** [comment]
Set the reverb to something like 1.00 and try an NSF(e) file.

**Comment by 47iscool** [comment]
Almost forgot to tell  you I only use the file browser now instead of letting it scan for a playlist like what the older versions required.

**Comment by droidmjt** [comment]
Ok i try

**Comment by droidmjt** [comment]
I couldn't reproduce your scenario. I tried with echo 1.00 (stereo being 0.00), then 0.9 (stereo being 0.00), they sound the same, I tried those example nsf nsfe songs.

**Comment by droidmjt** [comment]
this is funny, I use headphones always when i listen to something, but when i tried the same without my headphones, it sounds like a channel is missing :)

**Comment by 47iscool** [comment]
Still having the same issue even with the newest version.

Also I forgot to mention that about not using headphones, I think this might be the issue.
