### ISSUE TITLE
some midi speed not right

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#216]
https://www.dropbox.com/s/f9oqgtpgmd2rroq/ebe_midi.rar?dl=0
seems foo_midi have right playback,while on android it have a quicker one.

**Comment by droidmjt** [comment]
what MIDI player, all or BASSMIDI?

**Comment by crimson1117** [comment]
bassmidi.these files are for sc-55 so blahbalhblah.

**Comment by droidmjt** [comment]
all right, but its still the same library :)

**Comment by droidmjt** [comment]
shit, BASSMIDI computes the songlength wrong in those MID files...IAN!!!!!!!!

**Comment by droidmjt** [comment]
I reopen this case when the fix is available.

**Comment by lybxlpsv** [comment]
is it the same problem like in this midi http://www.midi-karaoke.info/21179885.play.mid
https://www.youtube.com/watch?v=hHGR_J_vbN8 XG SoftSynth
https://www.youtube.com/watch?v=9OAupIcg9YM Bassmidi
something feels off on the bassmidi, not sure if it's midi speed or just pitch bend.

**Comment by droidmjt** [comment]
not related problem

**Comment by droidmjt** [comment]
the problem in this case is that the songlength is not computed correctly with BASSMIDI

**Comment by droidmjt** [comment]
@lybxlpsv could you test the EVE_01.mid with various MIDI players and see if the songlength is indeed 4:14 or 3:13. Ian claims the length is indeed 3:12, but I don't know.

**Comment by droidmjt** [comment]
jetaudio claims its 4:14, android own music player claims its 1:26:22 (lol)

**Comment by crimson1117** [comment]
umm,but BASSMIDI on foobar2000 works fine...(foo_midi)

**Comment by droidmjt** [comment]
yes i know, but there are other players where the songlength is reported differently. Nevermind, I use the other library so the problem goes away.

**Comment by lybxlpsv** [comment]
midi is 4:10 (the GM ones, not FM)
http://i.imgur.com/LlbuBrj.png

**Comment by droidmjt** [comment]
oh, tempo, i'll see if i can get this fixed then

**Comment by droidmjt** [comment]
is the tempo value stored inside a MIDI or is it defined by user always?

**Comment by droidmjt** [comment]
crap, of course it is stored there. But I have no real static values in my player

**Comment by droidmjt** [comment]
I have a library that computes the songlength correctly. I'll use it.

**Comment by droidmjt** [comment]
the tempo setting doesn't affect the songlength at least but i can hear the tempo is incorrect

**Comment by droidmjt** [comment]
I set manually the tempo value and now it sounds correct. There is no such thing as FF 51 03 in the file, instead there is FF 51 04 xx xx xx, i took those xx bytes it works.

**Comment by droidmjt** [comment]
@lybxlpsv you were right, its about the tempo, im no MIDI expert but if the songlenght computing is somehow related to correct tempo value then if the tempo value parsing gets fixed in BASSMIDI, most likely the songlength gets fixed too. I'll wait for Ian's comments about this.

**Comment by droidmjt** [comment]
good news, this tempo thing will be fixed in next BASSMIDI update :)

**Comment by droidmjt** [comment]
got new BASSMIDI, this is fixed now, will upload new binary soon.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/mxc3mjh6yq7gdlr/droidsounde16647_08.apk?dl=0

**Comment by crimson1117** [comment]
thanks,fixed now
