### ISSUE TITLE
[Enhancement]Add CRI .hca(ADX2) support

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#217]
http://www.mediafire.com/download/2o6cnhdep2dfc7a/cri_adx2le_sdk_unity_v201.zip
SDK
https://mega.co.nz/#!Fh8FwKoB!0xuFdrit3IYcEgQK7QIqFKG3HMQ6rHKxrH3r5DJlJ3M
or
http://www.mediafire.com/download/858tqikj74qinw4/HCA_decoder.zip
decoder with source

**Comment by lybxlpsv** [comment]
interesting format, do you know any encoder floating around?

**Comment by crimson1117** [comment]
not intersting,but many ps3/x360 games using this format .

**Comment by droidmjt** [comment]
I much rather wait until this has been integrated into vgmstream or ffmpeg

**Comment by crimson1117** [comment]
sourceforge.net/p/vgmstream/feature-requests/6
created in 2014:( we can wait FFMPEG

**Comment by droidmjt** [comment]
I'll close this case since there is nothing i can do for now, I have the decoder saved just in case. If there won't be updates in ffmpeg/vgmstream any time soon, then i'll work on this. I reopen this case when there is news.

**Comment by crimson1117** [comment]
3 mouths passed~

**Comment by lybxlpsv** [comment]
I think you should be bugging vgmstream or ffmpeg instead of droidmjt as putting such decoder with unknown source or leaked sdk may cause some legal issues and removal from play store.

**Comment by kode54** [comment]
Added to my fork of vgmstream, here on GitHub.

**Comment by crimson1117** [comment]
finally! thanks everyone

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/48zmjhwz2mlfyd9/droidsounde16647_79.apk?dl=0
try and see how it works

**Comment by droidmjt** [comment]
don't use that build actually, the vgmstream itself is acting weird, i need to revert to the earlier version, will upload new version soon
