### ISSUE TITLE
option to 'share' a file by email

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#219]
I like to share songs with friends and when I find ones I like I have to try and remember them all then go to esfile explorer to share them by email and  I wondered if it would be possible to add an option to send a song by email, by adding an option to share when you hold down on a song, and also then multiple select other songs too by then tapping on those.

**Comment by droidmjt** [comment]
I can put this on my backlog but I can't promise it will be ready any time soon since i have other items to work on that have been waiting for a long time.

**Comment by droidmjt** [comment]
close this case, if i ever reach this far on my backlog, i'll reopen it

**Comment by filevans** [comment]
What about just ability to multi select and copy files to a folder then. That would be helpful to have the songs in one folder ready to share and send in esfile explorer. Would be possibly an easier short term answer to it.

**Comment by droidmjt** [comment]
like i said above, i have a backlog, numerous people have asked me various features, if i put this feature on top of the list, would that be fair?

**Comment by filevans** [comment]
No. I agree it would not be a priority if other things are more important
 I just tried to think of an easier way to add something similar. As I like to share songs I find that I like and it is quite a long winded process at the moment to remember the songs and go to another program to do it. I will wait for you when ready thanks
