### ISSUE TITLE
bug: editing song length affects mp3

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#222]
When using the song length option, for SIDS or other formats that don't have song length information it also affects mp3 playing too
 Please could it be changed so mp3 and other formats are not included in this song length information editing, as mp3 does not need it
Thank you

**Comment by filevans** [comment]
As it ruins mp3 playing

**Comment by droidmjt** [comment]
unless i made a recent bug, that should not even be possible since I have never seen an MP3 that wouldnt have songlength

**Comment by filevans** [comment]
I think I realised the problem, it is when you change the default song length. Only additional song length should be set. Default song length seems to be a redundant option in this case as makes ALL songs the length you set including mp3s.

**Comment by droidmjt** [comment]
If I edit the default songlength to 1234, that songlength is ONLY applied to songs that don't have songlength available in the file, and there is no way it could affect any MP3. Please send me the MP3 that gets affected by the default songlength option.

**Comment by filevans** [comment]
Happening on loads of mp3s just abruptly ending and going to next song, but if I just edit additional song length and say put 180 and leave default song length alone on 0 then its OK. Seems fine if I do that
What is the difference between default song length and additional song length options?

**Comment by filevans** [comment]
I found out the problem, for some reason it was screwing up mp3 song lengths usually displaying too long and then when reach end of mp3 it was starting the mp3 from beginning, and also would not seek, kept jumping to beginning. So I reset preferences and everything is fixed now, song lengths are accurate on mp3s, I don't know what happened.

What is the difference between default song length and additional song length options though anyway?

**Comment by droidmjt** [comment]
ah, yes, the default songlength doesn't affect the MP3 files but additional songlength does, I'll fix it, it is not suppose to affect MP3 files. The difference between those two is, default songlength is used when no songlength is available from the song file itself, additional songlength is a bit odd in my opinion, it was requested long time ago and i can't even remember the case, but i do remember that it was for the VGM/VGZ format songs.

**Comment by droidmjt** [comment]
this is also fixed

**Comment by droidmjt** [comment]
i'll close this case, we can reopen it later.
