### ISSUE TITLE
[Enahncement/Feature Change] Modify Songlength Options for Create Ringtone

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#223]
It's been a while since anything has been brought up with this, but the current create ringtone functionality is a holdover from prior to your tackling the code for this project. It currently has a time length slider for how long the resultant song is when creating a ringtone, along with name, and binary options for set as default as well as HQ (which I don't even know what HQ does for this).

Now that the songlength options in Droidsound have been greatly enhanced (audio fade, extra length at end, etc), is it possible to draw that information in when rendering a song as opposed to manually setting a song length? This would resolve a few issues I have with the feature:

1) Lowest song length is 10 seconds. If I wanted to create a ringtone from a short sound effect file, say 4 seconds long, the resulting ringtone would still be at minimum 10 seconds long. This is played as silence and, if I'm in the middle of listening to something when I get a text, I hear a sound for four seconds and then six seconds of silence before music resumes on Android.
2) I use create ringtone to also render playable files that I send to other people for listening. Having a song be its full length, complete with additional time and fadeout, would be spectacular. Instead, right now I have to enter a separate program to trim and fade a rendered song, and even then the max time is shorter than some of the songs I am rendering so those are cut short.

I'm assuming that there should be an easy way for create ringtone to draw in a generated length based on Droidsound's current options (length, fade, extra time) and run the generate job based on that. If not, and this would require a huge rewrite, just forget about it.

**Comment by droidmjt** [comment]
simply put, you want ringtone creator to be able to use fade+songlength+extra length? that shouldn't be a problem

**Comment by Level99OCR** [comment]
Yeah, simply put, I'd rather it not use a definite length slide and instead get actual songlength from Droidsound. So if the song is 1:44 and I have 5 extra seconds plus audio fade, when I make a ringtone from it the end result is a WAV that is 1:49 and has a fadeout.

**Comment by droidmjt** [comment]
this is done, but there is no additional songlength, you should be able to work with songlength + fade. Songlength can be 00:00 -> 05:00 using 1 second steps.

**Comment by Level99OCR** [comment]
Works for me as a compromise solution! Thanks, I'll grab the latest build whenever you up it with the changes. No imminent need, though.

**Comment by filevans** [comment]
is this issue ready to close now?

**Comment by Level99OCR** [comment]
Latest build, according to readme, is 16647_09, which did not have the enhancement as far as I know? Waiting for MJT to chime in here.

**Comment by droidmjt** [comment]
reopen this case or leave a comment if the result is not ok, i'll close this

**Comment by Level99OCR** [comment]
Just got my net back. Getting this crash on my Zenfone 2 when trying to make a ringtone:

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.droidmjt.droidsounde.utils.NativeArcFile$ArcEntry.getName()' on a null object reference
	at com.droidmjt.droidsounde.file.ArcFileSource.intGetRelative(ArcFileSource.java:146)
	at com.droidmjt.droidsounde.file.FileSource.getRelative(FileSource.java:433)
	at com.droidmjt.droidsounde.plugins.GMEPlugin.load(GMEPlugin.java:405)
	at com.droidmjt.droidsounde.service.Player.startSong(Player.java:650)
	at com.droidmjt.droidsounde.service.Player.dumpWav(Player.java:224)
	at com.droidmjt.droidsounde.service.Player.run(Player.java:1208)
	at java.lang.Thread.run(Thread.java:818)
============================
Droidsound-E version: 39
Droidsound-E build: 34
Time: Sat Jan 02 11:38:34 EST 2016
CPU: x86
CPU: armeabi-v7a
CPU: armeabi
Fingerprint: asus/WW_Z00A/Z00A:5.0/LRX21V/2.19.40.22_20150627_5104_user:user/release-keys
CPU
Lang: English
Locale: en_US
InternalSD free space: 33929265152
InternalSD path: /storage/emulated/0

Let me know if you need a full logcat.

**Comment by Level99OCR** [comment]
I apparently can't reopen this since you closed it but I'm checking on other devices now to see if this is just one device running CM13. I don't really have any devices running on stock android anymore but can find one or two to see if its just the custom code.

**Comment by Level99OCR** [comment]
Disregard previous posts, I made a really stupid newbie error. This works as advertised, and I'm very grateful for the functionality!

**Comment by droidmjt** [comment]
how exactly you made it crash?

**Comment by droidmjt** [comment]
leave  a message here please

**Comment by Level99OCR** [comment]
I was trying to make a ringtone from a song that was removed from the system. Like I said, it was a stupid newbie error ;)
