### ISSUE TITLE
bug: playing HES PC-Engine music

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#225]
Hello
It is not playing PC engine music properly, playing with one channel missing, missing all of the melody. And I wondered if it could be fixed, I tried changing all the settings, no help
Thanks a lot

**Comment by droidmjt** [comment]
send here some example songs

**Comment by filevans** [comment]
Sent to your email sir

**Comment by droidmjt** [comment]
ok i listened the song, it sounds just like with other players, the only difference is that if you don't use headphones and you enable echo, it sounds a bit different like a channel would be missing.

**Comment by filevans** [comment]
Without echo on there is the whole main melody missing, could you get the game and listen to the songs on an emulator.

**Comment by droidmjt** [comment]
I believe you and there is nothing i can do since it's the library fault, is there some other player that plays these songs properly?

**Comment by filevans** [comment]
This must be a problem with the actual plugin, I'll have to try to tell the author. We can close this case then and do you happen to have any contact details of the author

**Comment by droidmjt** [comment]
https://github.com/kode54/Game_Music_Emu/issues

**Comment by filevans** [comment]
Later on I'm going to test with chip amp bundle plugins on winamp and I'll let you know

**Comment by filevans** [comment]
could this case be reopened, as i've just tried the songs with the chimpamp plugin bundle on winamp http://chipamp.org/
and the songs play with all the channels and melodies correctly

**Comment by filevans** [comment]
i have done some looking and i think that the plugin used is NEZplug, and doesn't use game music emu

well this plugin is a lot better, and also supports other formats too 
http://nezplug.sourceforge.net/

**Comment by droidmjt** [comment]
yes nezplug, i know the lib, it plays the same formats GME does

**Comment by filevans** [comment]
Well I have done further testing with nezplug and it plays HES tg16/pce music perfectly, GME plays HES music terribly

**Comment by droidmjt** [comment]
sure, i believe you, I can add this library as a backup for HES music.

**Comment by filevans** [comment]
That would be a grand job

**Comment by filevans** [comment]
would that mean i would have to disable GME to use it? thanks

**Comment by filevans** [comment]
would be better NEZplug as the default plugin and GME as the backup plugin, may not even be needed at all, as NEZplug is really good

**Comment by droidmjt** [comment]
nezplug cannot play SPC for example, now, close all your cases, once im done with your requests, i'll open them one by one

**Comment by droidmjt** [comment]
this is done

**Comment by filevans** [comment]
not working, HES is still default to GME, and i tried to disable GME and now the HES music files wont play at all

please could you set HES default to NEZPlug

related to this in disable plugins could you put the plugins in alphabetical order, as they are all jumbled up like they used to be in audio plugin settings

thank you

**Comment by droidmjt** [comment]
go to Settings -> Audio -> NEZPlug -> check the override switch

**Comment by filevans** [comment]
Yes that's working and plays the songs right now, but still there's a problem . the m3u file should contain about 10 tracks but it's coming up 256. It displays the correct amount on wimamp. And  pretty sure droidsound displays the correct amount for GME but not for nezplug

**Comment by droidmjt** [comment]
its there too in settings, same place

**Comment by droidmjt** [comment]
it reads Process M3U files

**Comment by filevans** [comment]
Might as well just be on without a setting as all PC engine music needs the m3u otherwise they don't play the tracks properly. Or at least default it to on please. Thanks trying now

**Comment by filevans** [comment]
yes works like a charm, could you set both of those options ticked as default please, as GME should be overided by default for HES files and m3u has to be on too. I think these are redundant options, should just be on without needing a selection

**Comment by droidmjt** [comment]
i'll set the on by default, close this case

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/uwebty4p3mp1wc6/droidsounde16647_11.apk?dl=0
test this please

**Comment by filevans** [comment]
Ok working nicely

But m3u file does not show up in filesystem browsers.... Only in database links ..

**Comment by droidmjt** [comment]
thats a quick fix

**Comment by filevans** [comment]
this is fixed now, good, closing issue, thank you very much

**Comment by filevans** [comment]
just one slight niggle, in audio settings - plugins, the NEZplug appears before MOD (OpenMPT) not in alphabetical order, should be after in the list

**Comment by droidmjt** [comment]
ok, i fix this, i close this since this doesn't need testing, thanks for the notice
