### ISSUE TITLE
add song location or song extension to search results

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#227]
Hello, please could you add song file location to search results, although there is not a lot of room it would be better to put it where the artist mame smaller text us, more useful, as a lot of systems have the same game title and it is very hard to differentiate between which system the result us from.

Or if too much hassle at least show the file extension in the results, this would differentiate between which system it is
Thank you

**Comment by droidmjt** [comment]
I'll rather show the extension.

**Comment by filevans** [comment]
Either is ok

**Comment by droidmjt** [comment]
thats done

**Comment by filevans** [comment]
Excellent

**Comment by filevans** [comment]
I still think that file location should be put there in search results instead of artist name, this why:

- when you find a file, you want to know where it's found it, and there's no way of knowing. I just was looking for a Tim Follin song and it found it under artist name Tim & Geoff Follin but wasn't in my Tim Follin and I had no idea where it was finding it

-most songs you will have in a folder under artist name so if the folder location is there instead of artist then you will still know the artist as it will display the folder where it is which will be the artists name

- this will work better than reading just artist name as some formats don't show any artist name and this way would give more comprehensive information, instead of being blank for those formats

**Comment by droidmjt** [comment]
if i decide to do this, this will happen ONLY under search tab.

**Comment by droidmjt** [comment]
would be nice if you could give me a brief instructions how to reproduce this so i can get better picture about request

**Comment by droidmjt** [comment]
btw, use this: .ctim follin

**Comment by droidmjt** [comment]
will find only tim follin stuff

**Comment by filevans** [comment]
yes 'only' under search tab, yes just needed for there, i agree 100%

**Comment by droidmjt** [comment]
this is done

**Comment by filevans** [comment]
extensions are still not displaying when searching for songs

**Comment by droidmjt** [comment]
oh yeah, search, i fix

**Comment by droidmjt** [comment]
now its fixed, stupid logic error :)

**Comment by filevans** [comment]
Rescan database is not working at all now to test this sorry

**Comment by droidmjt** [comment]
huh? how? explain more, how to reproduce?

**Comment by droidmjt** [comment]
what searching has to do with rescan?

**Comment by filevans** [comment]
Search doesn't work when no db....

I've reslved the scan problem now, I had to add a filebrowser then it let's me scan. 

Search is showing extensions now, that's good, thank you

**Comment by droidmjt** [comment]
if there is no songs.db then there is nothing you can search locally

**Comment by droidmjt** [comment]
can we close this?

**Comment by filevans** [comment]
That's what I said, and scan wouldn't work until I added a file browser ,(database)

Related to this, file browser should be renamed database browser, when adding new shortcut / database

As firstly it is not really a 'file' browser it is database, and also too confusing file browser / filesystem browser the names

**Comment by droidmjt** [comment]
so what do you want me to do with this?

**Comment by filevans** [comment]
I'll have to think about that. But just for now rename file browser as database browser, when adding new shortcut / database. Much better, clear

**Comment by droidmjt** [comment]
it is now Database Browser.

**Comment by filevans** [comment]
this is all fixed, closing now, thank you very much
