### ISSUE TITLE
moving song bar can accidentally swipe screen 

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#229]
When moving the song playing position knob or especially if you want to drag the knob back to the beginning of a song to start again it can  accidentally swipe the screen left or right, to browser or the other way. It would be better if swiping left and right only registered movement in the main middle section of the screen, and not below the line where the stars and song length / song knob position are. This would allow freedom to play with the song position knob without any annoyance. 
Thank you for listening

**Comment by droidmjt** [comment]
what is "main middle section of the screen", if possible, send a screenshot and highlight the area

**Comment by filevans** [comment]
Well everything above the bottom line where the song length, bar and stars are. What program is good for taking a screen shot and highlighting

**Comment by droidmjt** [comment]
![dse_player_view](https://cloud.githubusercontent.com/assets/5917820/11768615/63348542-a1db-11e5-931b-d65cea7a0d88.png)

highlight the area where the seekbar should be

**Comment by droidmjt** [comment]
you want me to move the seekbar above the blue line where the metadata is located? even if i would move it upper, i dont think it would make any difference. it would still be the same seekbar, same height and width and same sensitivity.

**Comment by filevans** [comment]
No im not asking you to move seek bar. I am talking about which part of the screen allows you to swipe to next screen (browser/search) swiping should not be allowed in the bottom part of the screen where the seek bar is as it inferferes with the moving of the seek bar, it swipes the screen when you don't want it to. You just want to seek and move seek bar knob... It swipes sometimes when you're doing it

 I will highlight what i mean but i asked what program is the best for that

**Comment by droidmjt** [comment]
microsoft paint, you can use that

**Comment by filevans** [comment]
I mean an app for android to draw/ highlight

**Comment by droidmjt** [comment]
nevermind, i got it now what you want....i'll see if i can change the sensor area

**Comment by filevans** [comment]
I'm on android you see. I know paint on windows does it

**Comment by filevans** [comment]
Yes sensor area for swiping. Only in middle section of playing window

**Comment by droidmjt** [comment]
its not that easy because i need to avoid the stars sensor also

**Comment by filevans** [comment]
Out of interest what app do you use for taking screenshots

**Comment by filevans** [comment]
It is everything below the line not. Swiping to next screen not allowed. Stars and seek bar still function as normal. But swiping not allowed between 'screens' in this area.

**Comment by filevans** [comment]
It is just disable ability to swipe between browser/player/search in this lower area

**Comment by droidmjt** [comment]
in the player view, the blue line just above the stars, how about if i disable swipe below that blue line?

**Comment by droidmjt** [comment]
i took the screenshot by holding HOME + POWER buttons for few secs

**Comment by filevans** [comment]
That was the line I was talking about yes. Disable swipe completely below blue line, exactly right.
Then seek bar is controlable comfortably without accidentally swiping to another screen

**Comment by droidmjt** [comment]
that shouldn't be a problem

**Comment by filevans** [comment]
please could you reopen issue #225 pc-engine HES music, as ive found the problem, and have posted some info on the issue there

**Comment by droidmjt** [comment]
i can't do this, takes too much time to change all of the stuff, sorry, not gonna happen. close this case

**Comment by filevans** [comment]
OK but when you move the scroll bar for music at the moment it swipes, and it is quite annoying, maybe when you have more time then

**Comment by droidmjt** [comment]
all right, sounds reasonable, but don't expect it any time soon.
