### ISSUE TITLE
changing sorting by holding down rather than tap

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#230]
Hello, this is my last request for now, one I meant to mention some the ago.
Please could it be altered so that to change sorting on the top green bar - you have to press and hold for 1 second rather than just tap, as at the moment its too easy to accidentally change sorting by a quick tap when other controls are close by, like parent folder or music file select. Thank you for listening.

**Comment by droidmjt** [comment]
this is easy fix

**Comment by droidmjt** [comment]
fixed

**Comment by droidmjt** [comment]
i'll close this case, once the new binary is up, if this doesn't work as expected, reopen this case.

**Comment by filevans** [comment]
this is working fine now, good, case done
