### ISSUE TITLE
some converted at3 have 06:39 song length?

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#231]
https://www.dropbox.com/s/pmp4ehphdbowarc/bgm02_v02.at3?dl=0
https://www.dropbox.com/s/j6m3zcj1v5wq5 ... 2.msf?dl=0
the famous YO-KAI Disco

converted by AlphaTwentyThree‘s msf2at3 plugin...and song length is 06:39...

**Comment by droidmjt** [comment]
what should the songlength be then?

**Comment by crimson1117** [comment]
what should the songlength be then? 1min 26 s 376ms
vgmstream cannot play MSF.
also,converted at3 cannot be played.(FFMPEG can play them then)

**Comment by droidmjt** [comment]
from ffprobe:

Input #0, wav, from 'bgm02_v02.at3':
  Duration: 00:06:39.37, bitrate: 31 kb/s
    Stream #0:0: Audio: atrac3 (p[2][0][0] / 0x0270), 48000 Hz, 2 channels, fltp, 132 kb/s

**Comment by droidmjt** [comment]
ffprobe is a tool from ffmpeg package

**Comment by crimson1117** [comment]
crimson1117：droidsound-e(FFMPEG) claims it's 06:39...and GOLDWAVE said File contains inconsistent length information.Calculate the length based on the file's size?
AlphaTwentyThree：Yes, that's done in the script. Opening the file with Adobe Audition works for me, I haven't checked the other programs. Winamp and foobar also play the file correctly (rename to wav first). I suggest you decode the file with any of the two players and edit the files afterwards.

So maybe the script thing.It seems not to be the plugin's problem,so I'll close this.Thanks.

**Comment by droidmjt** [comment]
i do one more check, just to be sure

**Comment by crimson1117** [comment]
http://forum.xentax.com/viewtopic.php?f=13&p=43570#p43570 the msf to at3 script is here,if somewhere time is set there(?)

**Comment by droidmjt** [comment]
i checked the header and stuffs, the only way to get the songlength is to use bitrate and filesize

**Comment by droidmjt** [comment]
its 1:34 then

**Comment by droidmjt** [comment]
i can't get 1:26 no matter what

**Comment by droidmjt** [comment]
i also checked the script, it doesn't set sample count in the header or anything that could be used to get the 1:26 length

**Comment by crimson1117** [comment]
http://ww4.sinaimg.cn/large/636891efjw1ez50d22tgnj20sh0emn1a.jpg
I used GOLDWAVE...

**Comment by droidmjt** [comment]
all right, what do you suggest I should do with this?

**Comment by droidmjt** [comment]
the only thing i can do for now is make it stop properly when the sounddata ends, there is nothing i can do to get the correct songlength (1:26:xx)

**Comment by crimson1117** [comment]
oh that sounds really good

**Comment by droidmjt** [comment]
It's fixed now. The header in that at3 file looks like its missing lots of stuff, at least the files i've seen before do have more stuff like loop point offsets etc etc

**Comment by crimson1117** [comment]
it is said to be old atrac file,since fixed,I'll close this.Thanks.
