### ISSUE TITLE
SNES RSN files not showing up in filesystem

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#232]
sorry i've found another bug, SNES RSN files won't show up if you explore files in filesystem ...

they only show up in shortcuts to folders where media scan has been done

related to this, RSN files contain lots of tracks, they work a bit like a zipfile does, so because of this to diferentiate between files like this and normal folders, please could the extension be visible, or an option to display the extension?
thank you

**Comment by droidmjt** [comment]
RSN is RAR archive and filesystem is not currently supporting archives, close this case, this support is not coming any time soon. I have it on my backlog tho.

**Comment by filevans** [comment]
sorry didnt know, thanks for that

**Comment by droidmjt** [comment]
i'll close this case, once the feature is there, we can reopen this
