### ISSUE TITLE
turn off interpolation by default

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#233]
Please would it be possible to turn off interpolation by default for all of the plugins, because it does not sound authentic like the original hardware with it on, and the sound is crisper and sharper without it

I have to go through turning it all off everytime I install a new version. People can put interpolation on if they really want it. I think it sounds dulled and muffled.

**Comment by droidmjt** [comment]
didn't you say earlier "this is my last request..." :)

**Comment by droidmjt** [comment]
i'll switch off interpolations except from SPC

**Comment by droidmjt** [comment]
done

**Comment by filevans** [comment]
I know sorry, I don't like interpolation on spc either, I can't stand interpolation on SNES or amiga modules, it muffles the sound, does original snes hardware interpolate the sound? Amiga didn't unless you put it in yourself, 'sound filter' was called.

**Comment by droidmjt** [comment]
interpolation on Amiga? you mean the filter option?

**Comment by droidmjt** [comment]
disabled

**Comment by filevans** [comment]
Yes, in amiga case, that was an option to put on. but I don't like interpolation on anything, unless it is supposed to there. I'm pretty sure it is a modern add on with some plugins, not a default feature on original hardware

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2z2z6jii20ne2vu/droidsounde16647_12.apk?dl=0

**Comment by filevans** [comment]
interpolation filter is still on 'internal default' for openMPT mod plugin, this was the main one i was hoping to have off by default, as it is not authentic, the amiga didnt sound like that with interpolation

ive just noticed there seems to be 2 amiga mod players, openMPT is the one that is default, when i turn interpolation off it affects the sound of .mod files, but there is also another plugin UADE that i think plays the deliplayer / exotic trackers formats, it is the openMPT one that is default anyway for mods and the interpolation is still on

**Comment by droidmjt** [comment]
fixed

**Comment by filevans** [comment]
Fixed thanks
