### ISSUE TITLE
disable / enable plugins  + new shortcut / link in alphabetical order

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#235]
please could you put the disable / enable plugins in alphabetical order, and also the menu adding new folder / filebrowser would be good in alphabetical order too please, if not too much hassle

**Comment by droidmjt** [comment]
i'll put the New items in alphabet order, cant do that with plugins

**Comment by filevans** [comment]
you did it on audio settings - plugins, but not able to in the enable / disable settings?

dont you think that these two menus could be combined, and just put a tick next to each plugin to enable/ disable it in audio settings (plugins)

**Comment by droidmjt** [comment]
im sorry, what two menus?

**Comment by filevans** [comment]
Audio - Plugin settings
+
Enable/Disable plugins (177)

they are basically all the same plugins, on the 'Audio - Plugin settings' menu, it has a space there for each plug in that can have a tick box just the same as the 'Enable/Disable plugins (177)'

so these 2 menus could be combined

**Comment by droidmjt** [comment]
nevermind, both are now in alphabet order, but combining I cannot do, it gets too annoying, sorry

**Comment by filevans** [comment]
no its ok, just was an idea for efficiency

**Comment by filevans** [comment]
i just wondered what DSEMusic database link is, as there's nothing inside it

thanks

**Comment by droidmjt** [comment]
DSEMusic is just a placeholder to get easy start, so all user have to do is copy music to /sdcard/DSEMusic and rescan, thats it.

**Comment by filevans** [comment]
thanks

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/75vd5sgmaswi8rg/droidsounde16647_15.apk?dl=0
this fixes sorting in the later models, forgot that i need to change things from two places

**Comment by droidmjt** [comment]
oh hell, dont use that version, there is some shit...i'll fix it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ke05e6yj2xqeylc/droidsounde16647_16.apk?dl=0

**Comment by droidmjt** [comment]
ignore the earlier versions, sorry about this

**Comment by filevans** [comment]
Good nice now
