### ISSUE TITLE
SC68 Soundfx

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#237]
a while ago I reported certain SC68 files not playing, these were 'soundfx' and as we knew there is a problem with soundfx format with the SC68 player

but now ive found 2 other players that play soundfx format, and i wonder if you might be able to incorporate one of them to play this format properly

these players both play soundfx 1.3 - 2.0:
http://www.exotica.org.uk/wiki/DeliPlayer
http://www.exotica.org.uk/wiki/Oldsk00l

thanks a lot

**Comment by filevans** [comment]
ive also just realised, a plugin already included in droidsound-e plays soundfx format already:
UADE
http://www.exotica.org.uk/wiki/UADE

would it be possible to proritise UADE plugin to overide SC68 for the soundfx modules

**Comment by filevans** [comment]
list of all players that play soundfx:
http://www.exotica.org.uk/wiki/SoundFX

**Comment by droidmjt** [comment]
there is no need to prioritize since those soundfx module UADE plays are not using SC68 extension.

**Comment by filevans** [comment]
There are lots of soundfx modules in the sc68 collection with sc68 extension, and sc68 plugin has an issue playing them, and UADE is not recognising them to play them when it can. So what can I do about it? Rename all the soundfx sc68 modules to .SFX extension?

**Comment by filevans** [comment]
I'll try it

**Comment by filevans** [comment]
I renamed one to .SFX and that triggered UADE to play it, but still plays it silently, exactly the same problem. So I don't understand it

**Comment by droidmjt** [comment]
its because they are different formats
