### ISSUE TITLE
in browser change hold down Menu to say 'full rescan' not just scan

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#239]
when pressing hold down menu could you please change this to say "full rescan" not just scan as otherwise it is not clear which type of scan this is

and would it also be possible to add here just light rescan here, this could be just called "rescan"

thank you

**Comment by droidmjt** [comment]
this doesn't need fixing, the rescan in context menu is always full scan, non-full scan is useless because the non-full scan should be done during startup, i'll keep it like this.

**Comment by filevans** [comment]
Can you just label it full scan then, as in settings menu it is not full scan unless you tick it. So non full scan is default
 So on the hold down menu you wouldn't know which type of scan is, I had to ask you as didn't know. Don't you think?

**Comment by droidmjt** [comment]
yes i have renamed it to Rescan (Full)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8kq1rzhqe21aqje/droidsounde16647_20.apk?dl=0

**Comment by filevans** [comment]
this is better now, thanks
