### ISSUE TITLE
when sorting, sort archives too

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#240]
ok this is my last request now,

when sorting, please could you allow zip / rar archives to be sorted too
at the moment when sorting by filename they are at the top, archives should be bellow folders really, as they are a file, folders should be at top

or if they could be sorted in alphabetical order like this:

AMIGA
C64
SNES (zip)
ST

this method would also be good, rather than zip files at top, isnt right

thank you

**Comment by droidmjt** [comment]
this is fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8kq1rzhqe21aqje/droidsounde16647_20.apk?dl=0

**Comment by filevans** [comment]
ok archives are at the bottom now, this is better than at the top, but there 'could' be an option to have them mixed in the folders, in alphatical order, but that's up to you. the reason that might be good is that if some big folders are compressed into an archive then they would be displayed alphabetically with the folders
