### ISSUE TITLE
bug: when deleting a folder doesnt delete

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#241]
when holding down on a folder in browser and selecting 'delete' it then says "really delete folder? and you choose yes, but it doesnt delete it

this is in normal filesystem browser

**Comment by droidmjt** [comment]
yes i noticed the same and it's fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8kq1rzhqe21aqje/droidsounde16647_20.apk?dl=0
i also did some other changes, the sorting bar is switchable now, check if from settings -> misc -> sorting something. This should fix the rest of the bugs too except the USB thing

**Comment by filevans** [comment]
delete folder still not deleting

**Comment by filevans** [comment]
correction, it is working to delete when browsing database folders, but not working to delete when browsing filesystem browser

**Comment by droidmjt** [comment]
this is fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ufwgs5bwsp4jmqt/droidsounde16647_21.apk?dl=0

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ourgnj97msgaxm9/droidsounde16647_22.apk?dl=0

**Comment by filevans** [comment]
have you also set as default long press to change sorting? and use parent folder as author, these are better set as default, then they can be disabled by people if they really dont want it, as im testing versions constantly and have to enable these settings every single time now

you could also make the duration of press slightly shorter, so it suits more people, not a tap, but a slight press, slightly less than a long press....

**Comment by droidmjt** [comment]
look, most users don't like new things to be set by default, they prefer old stuff, i have learned this by the hard way, secondly, you requested long clicking, you got it, others didnt request short click to have a delay, so if i change it, ppl come to nag me this and that

**Comment by droidmjt** [comment]
close this case if the bug is fixed

**Comment by filevans** [comment]
ok, but i am dedicated to testing, and because of problems i have to reset my settings every time, most users arent testing every single version like me, and can easily untick or tick an option if they prefer it that way, whereas i have to go through changing those options every time, the use parent folder as author doesnt affect anything as only overrides a blank space or 'unknown' it doesnt interfere with known authors in any way, so doesnt affect anyone. and the hold down long press to change sorting is needed, because it is too easy to change accidentally before as its just right by the first song entry.  

i havent tested this version yet as i was trying to avoid having to change all the options again if i have to reset my settings, but am going to test it now

**Comment by droidmjt** [comment]
yes i can see you are testing but i can't understand how the sorting-click setting can affect your testing so badly, i can enable them for now by default but official build will have them disabled

**Comment by droidmjt** [comment]
if the bug is fixed, close this case

**Comment by filevans** [comment]
I said I'm about to test it now

Yes interim builds set the options I want as default and official build not,  I'm happy with that

**Comment by filevans** [comment]
fixed but in testing ive encountered another problem related to this now which ill post now
