### ISSUE TITLE
creating new folder in filesystem browser triggers rescan

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#242]
when you create a new folder in filesystem browser it triggers a database rescan, could this be disabled? it would be reasonable if you were browsing in database and you created a folder, but should not do it for filesystem browser, as the whole point of using filesystem browser is for speed and not to have to deal with the database

**Comment by droidmjt** [comment]
i try

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/teemqfclsp7wz3h/droidsounde16647_23.apk?dl=0

**Comment by filevans** [comment]
this is fixed, thank you

but one thing is, when you press add new folder you are then asked to choose where you want to add the new folder. well if you are already in the location in filesystem browser where you want to create it, wouldnt it be possible to just create the folder there, as you are already browsing the location already where you want the folder? it is long winded

**Comment by droidmjt** [comment]
I know what you mean but user might be inside an archive or a place where folders cannot be created and then it leads to confusion and troubles not to mention the hassle in the code, sorry. Close this case.

**Comment by filevans** [comment]
Not if you can only do it in filesystem browser, and not database. Would that not be possible just in filesystem browser only
