### ISSUE TITLE
sc68 files not showing up on filesystem browser

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#243]
![screenshot_2016-01-01-12-29-58](https://cloud.githubusercontent.com/assets/14978933/12071450/facfab82-b083-11e5-871a-17b31c2e259f.png)

i added a new folder to my music folder of the new sc68 files, and for some reason none of them are displaying at all in filesystem browser, but they display in database (as i did a full rescan)

**Comment by filevans** [comment]
i wondered if it might be because i added the folder after i added the filesystem browser shortcut? but doubt that's it

it's weird as the other sc68 files showed up before my old files, and they have the same extension. i think the only difference is these have lower case extension .sc68 and my old files were upper case .SC68

or could it be the folder they are in, droidsound doesnt like the characters? either length, or the brackets or the use of _

otherwise i cant think of any other reason

**Comment by filevans** [comment]
ive tried renaming the folders and a file to uppercase but still doesnt display the file, so dont understand it

**Comment by droidmjt** [comment]
i don't even understand the problem here....tell me the fullpath where you have your files, i try to reproduce the scenario

**Comment by filevans** [comment]
/sdcard/Music/-Computer & Console/AMIGA/SC68n/Jochen Hippel_Mad Max/5th Gear.SC68

Maybe I need to completely uninstall and reset everything

**Comment by filevans** [comment]
i fixed this problem by deleting the short cut and readding it
it is a bug but it might be hard to find the cause, so i suppose close this for now
