### ISSUE TITLE
external sd card check

### ISSUE THREAD

**Issue by droidmjt** [droidmjt/Droidsound#244]
@Level99OCR, this time task for you :)

For those devices of yours that has external SD card slot, could you check one thing for me?

Open Filesystem browser, go to '/mnt' folder and note down all the paths you see, then go to '/storage'
folder and note down all the paths you see and post them here please.

**Comment by droidmjt** [comment]
i'll close this case, post your findings here if you time

**Comment by Level99OCR** [comment]
You got it, I'm going to go through every single one of my devices tonight. Do you also want me to note if there's any root-level symlinks along with the /mnt/ and /storage/ directories? There's definitely a few instances of just /external_sd or /extSd

**Comment by Level99OCR** [comment]
Got through about 60% of the devices, here's the list so far:

/storage/extSdCard
/storage/sdcard
/storage/sdcard0
/storage/sdcard1
/storage/emulated/0
/storage/emulated/legacy
/storage/usbdisk
/storage/self/primary
/storage/****-****
/storage/external_SD
/sdcard
/mnt/extSdCard
/mnt/sdcard
/mnt/expand
/mnt/sdcard0
/mnt/sdcard1
/mnt/user/0
/mnt/runtime/default/ <--- these are another path to get to ****-****, 0, and legacy
/mnt/

Will run through the much older devices tomorrow to see if I missed any. Also, tablet needs to charge so I know there's at least one more.

**Comment by Level99OCR** [comment]
There, I have now gone through every single device I have, a few with multiple rom versions (stock and CM), and grabbed all the possible paths for SD storage. I have listed some typical internal storage paths because some devices allow native usage of external SD as internal. All 6.0 roms moving forward will support using external SD as internal, too.

**Comment by droidmjt** [comment]
excellent, thanks for the list :)
