### ISSUE TITLE
bug: backing out of database folder goes back to empty folder

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#246]

**Comment by filevans** [comment]
![screenshot_2016-01-03-19-08-55](https://cloud.githubusercontent.com/assets/14978933/12091697/f0d9db64-b2ce-11e5-94a0-017ebd21c89a.png)

**Comment by filevans** [comment]
i created a database link to my chip and mod music folder which is inside sdcard/music/

when you go into the folder say to level 2, and press back to go back, it should back from my database shortcut to the root filebrowser lists, but instead it goes to the parent folder "music" which is not part of the shortcut, the shortcut is a direct link to sdcard/music/mods/

but on going back it actually goes to sdcard/music/ when it shouldnt

ive tried completely deleting database and doing full rescan but same thing happens

i tried the same shortcut on normal filesystem browser and this doesnt happen, it works as it should and backs to the root menu where the links are properly

**Comment by droidmjt** [comment]
i have a folder /sdcard/Music/chiptunes/mods/test123, i created a DB Browser to folder /sdcard/Music, when i use it to enter any folders and then keep pressing Back, it works as expected.

**Comment by droidmjt** [comment]
ehhh

**Comment by droidmjt** [comment]
got it, i try to fix it

**Comment by filevans** [comment]
as i said you have to go into the database directory structure more than one level in, for example, create this directory structure:

sdcard/music/mods/amiga/artist

but only do a shortcut to sdcard/music/mods/

then go into the database to a deeper level to ..../amiga/artist....

then press back, and before going to root shortcuts list it goes to your "music" folder which should not be part of the shortcut structure, see?

**Comment by droidmjt** [comment]
yeah i was able to reproduce the problem

**Comment by filevans** [comment]
only happens on database, not filesystem browser

**Comment by droidmjt** [comment]
i hope it works with this build
https://www.dropbox.com/s/x2z9p31ifgnlvjp/droidsounde16647_26.apk?dl=0

**Comment by filevans** [comment]
fixed, brilliant, great, fantastic
