### ISSUE TITLE
info window on player has a couple of access pixels

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#247]
there are a couple of extra pixels than should be on the info window which causes it to be "loose", and means you can drag it up and down a couple of pixels, this doesnt feel solid, it is slightly bigger than neccesary. the part where you have the info window below title/author:
________________
Plugin:
Format:
Channels:
etc.....
________________
try to drag it up and down, it moves a couple of pixels and it shouldnt need to, especially when standard info is there and not extended information, as it all fits in there with a lot of room to spare so doesnt need to be scrolled 

please could you edit the size of the information so it fits perfectly rather than loosely there
thank you

**Comment by droidmjt** [comment]
yeah im aware of it but I never found it bothering me

**Comment by filevans** [comment]
just doesnt feel solid, and would be better if fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/x2z9p31ifgnlvjp/droidsounde16647_26.apk?dl=0
should be fixed now

**Comment by filevans** [comment]
fixed, brilliant, great
