### ISSUE TITLE
+ new shortcut / folder menu format suggestion

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#248]
i have a better way to present the menu of shortcuts and folders, as i still think it is confusing having 'shortcut links' and actually 'create new files' mixed up all together, and for new users it is hard to diferentiate between creating a new folder and instead just a shortcut to filebrowser etc. (as nothing is labelled shortcut or actual new file/folder, so i think something like this, would be better, 2 headers like this:

instead of saying new at the top, chage this to smaller font size and put like this:

shortcuts:
__________
DB Browser
Filesystem Browser
Local Mediastore
Network Link 
etc.
__________
create new file:
__________
folder
playlist

organise them like that, to easily diferentiate between 'shortcut' and 'create a new file'
something like that much better

**Comment by droidmjt** [comment]
thanks but won't be happening any time soon, i'll add this to my backlog

**Comment by filevans** [comment]
what about just in the mean time put the create new file options right at the bottom and just put a line to seperate them then, nothing more for now

**Comment by filevans** [comment]
also what is mega folder please?
is that a short cut to something?

**Comment by droidmjt** [comment]
I can add the line separators to the New window fragment. Mega Folder is the https://mega.nz folder mount thing.

**Comment by filevans** [comment]
the menu hasnt been changed to put the 2 'create' items at the bottom with a seperator on the new version

**Comment by droidmjt** [comment]
i'll pass this for now, i need to do something else

**Comment by filevans** [comment]
could just move the 2 create items to the bottom, dont bother with separator, thats easy isnt it
