### ISSUE TITLE
centralise sub song in display

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#249]
![62b6b104-b1fc-11e5-998a-f68dda77be86 copy](https://cloud.githubusercontent.com/assets/14978933/12118509/4924e902-b39d-11e5-80a7-c6774ccb68bd.gif)

hello would it be possible to centralise the sub song like this, and also move the + add to favourites along a bit, not only looks better like this, centralised, but also '+' is too close to the sub song track numbers i think.

**Comment by droidmjt** [comment]
fixed

**Comment by filevans** [comment]
looks nice and pretty, thanks a lot
