### ISSUE TITLE
Filesystem Broswer Folder Title

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#250]
when browsing the root of any Filesystem Broswer, the folder title at the top always reads:
_______
Filesystem
_______

could this be changed so it reads the name of the folder/shortcut name instead?

**Comment by droidmjt** [comment]
i can try

**Comment by filevans** [comment]
you could just have it display the path

so for a filesystem browser that links to: sdcard/music/mods

then display mods/ as the root, then every subsequent level will include mods/ in the path, as at the moment the root path is ignored, and the path only displays from depth level 2 of the path

so in this case the path is only displayed after entering depth level 2, for example 'amiga' subfolder inside mods shortcut..

**Comment by droidmjt** [comment]
fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/kvvj55ps1jhyikx/droidsounde16647_27.apk?dl=0

**Comment by filevans** [comment]
great work man
