### ISSUE TITLE
Glitchy page scroller (ViewPageindicator) 

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#251]
galaxy nexus cm11 nightly.

when i tap the top of the screen to scroll left, it scrolls left two pages, whenever there are two pages to the left.

EDIT: Cannot advance beyond the second page by tapping the tab bar. (portrait only, not on landscape)

When dragging tab left, then using second finger to move tab over to left, then let go, it shows the wrong description (next, or blank if last tab).

**Comment by droidmjt** [comment]
good find, i was able to reproduce, i'll get it fixed ASAP

**Comment by jimbo1qaz** [comment]
see edit,  may or may not be relevant.

**Comment by droidmjt** [comment]
i'll check it and fix it

**Comment by droidmjt** [comment]
fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1lg2g6k7ffoegs0/droidsounde16647_29.apk?dl=0
