### ISSUE TITLE
excessive toasts when changing playlist sort (combine them?)

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#252]
when changing sorting order,  dse produces one toast per switch.  they last over a second each and pile up quickly.

can you make each toast replace the previous? for example by reusing the same toast object,  changing the message, and redisplaying?

**Comment by droidmjt** [comment]
I can only shorten the display time, not replace

**Comment by droidmjt** [comment]
its already using the shortest time (2 secs), don't know how to combine them.

**Comment by droidmjt** [comment]
nevermind, fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1lg2g6k7ffoegs0/droidsounde16647_29.apk?dl=0

**Comment by jimbo1qaz** [comment]
Same bug occurs in repeat selection and shuffle. Can you find all instances of toasts and fix this?

(I wonder why Android didn't implement it this way by default.)

**Comment by droidmjt** [comment]
what instances? in every view it works the same way and the way it works is, if there is existing toast, it cancels it and shows a new one. There is no other way to do this, all you can do is cancel the existing and immediately so a new one, this definitely reduces the time toast is being shown + this prevents user to suffer simultaneous toasts that each has to timeout.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/rh2ltpix52h7nsm/droidsounde16647_30.apk?dl=0

**Comment by droidmjt** [comment]
test the above binary, if it works, close this case
