### ISSUE TITLE
sorry by entry by default? 

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#253]
sorting defaults allows choosing between title, date, composer, and filename. it's missing the option for short by entry. 

is "entry" by cd index number?

**Comment by droidmjt** [comment]
entry is DB _id

**Comment by droidmjt** [comment]
i'll add it to settings

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1lg2g6k7ffoegs0/droidsounde16647_29.apk?dl=0
