### ISSUE TITLE
Cannot seek SPC and MIDI files

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#254]
Tested on SPC and MIDI files.  Tapping the seek bar does nothing. Sliding the seek bar instead switches pages.

**Comment by lybxlpsv** [comment]
yeah, most of the format arent seekable.
ffmpeg also isnt seekable.
bassmidi seeking support should be easy and no need to check for instrument change/tempo/other midi change during mid-playback stuff, dunno about others though

**Comment by droidmjt** [comment]
for MIDI files i can probably add seeking, but any emulated formats seeking would be just silly, especially if the library itself doesn't support seeking, the only way to seek in that case would be just render n amount of samples until we are in correct place, for slow devices that would mean playback would stop at some point, also, now to mention what would happen when doing backwards seeking

**Comment by droidmjt** [comment]
MIDI and ffmpeg plugin seeking added

**Comment by lybxlpsv** [comment]
Nice, how about vgmstream?
seems to be seekable too

**Comment by droidmjt** [comment]
there is no seek function in vgmstream lib

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ladjir3tkyj9eok/droidsounde16647_28.apk?dl=0

**Comment by droidmjt** [comment]
vgmstream is same deal, there is no seek function, the seek function is written outside the lib, it just renders x amount of samples until the correct position

**Comment by droidmjt** [comment]
close this case, nothing i can do anymore here

**Comment by droidmjt** [comment]
i'll try to create the vgmstream seeking, hope for the best

**Comment by jimbo1qaz** [comment]
If you want, close this.

**Comment by droidmjt** [comment]
i try to add the vgmstream seeking, let's see how it goes, i hope its lightweight

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/qmjrh8xnhqwuzdr/droidsounde16647_31.apk?dl=0
added vgmstream seeking, i hope it works as expected

**Comment by droidmjt** [comment]
all is done here, i'll close this

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/k4aqzwyw7jzdb5d/droidsounde16647_35.apk?dl=0
