### ISSUE TITLE
Enhancement Request: Enable filepath display on info page in player

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#256]
Simply because not all games have metadata that has the game name in it, most notably vgmstream files. This way, when on random in a big playlist, the game name can still be found via the filepath of the file being played. It doesn't necessarily need to be the entire length of the filepath, including the root and mountpoints, but just the general directory and filename/zipname would be enough to compensate for the lack of metadata of some files.

**Comment by droidmjt** [comment]
sure,  no problem

**Comment by droidmjt** [comment]
i need 3-5 scenarios and output in player view how it should look like

**Comment by droidmjt** [comment]
nevermind, this is fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/qmjrh8xnhqwuzdr/droidsounde16647_31.apk?dl=0
