### ISSUE TITLE
can't browse External SD Card on CM13/6.0.1

### ISSUE THREAD

**Issue by lybxlpsv** [droidmjt/Droidsound#259]
ppsspp had a button that requests user permission to access storage stuff and external sdcard is now readable on that program, maybe something like that? or new permission stuff?

edit : I tried opening music with xplore, droidsound-e is able to play it that way.
also tried manually adding the /storage/5006-6946 and it works.

**Comment by droidmjt** [comment]
if there is CM13 for SGS3 i9305 then i might be able to help, otherwise, nothing i can do

**Comment by droidmjt** [comment]
currently DSE grants access to external storage

**Comment by droidmjt** [comment]
>>...also tried manually adding the /storage/5006-6946 and it works.

so you added filebrowser/db browser to that folder?

**Comment by lybxlpsv** [comment]
yeah, adding filebrowser to /storage/5006-6946 works.
that folder doesn't appear if I click it though, have to type it manually.

**Comment by droidmjt** [comment]
ah this hex-path thingy, i'll get it fixed

**Comment by droidmjt** [comment]
could you check if /mnt folder has similar path with those numbers (/storage/5006-6946), for example /mnt/5006-6946

**Comment by droidmjt** [comment]
nevermind, i think i managed to fix this

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/qmjrh8xnhqwuzdr/droidsounde16647_31.apk?dl=0
let me know how it works

**Comment by droidmjt** [comment]
leave a comment if it fails still
