### ISSUE TITLE
Bug/Issue: Unresponsive after adding files and cold-starting Droidsound (from reboot/full program exit)

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#262]
Installed latest build v34, installed my normal VGM directory. Scan finished, played a bunch of songs to test, added to favorites, etc etc. Rebooted phone, and Droidsound starts but immediately is unresponsive and FCs. Here is crashlog:

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131624003, class com.droidmjt.droidsounde.playlistview.PlayListView) with Adapter(class com.droidmjt.droidsounde.playlistview.PlayListAdapter)]
	at android.widget.ListView.layoutChildren(ListView.java:1562)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:3842)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3641)
	at android.view.View.dispatchTouchEvent(View.java:8547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2372)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1722)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2333)
	at android.view.View.dispatchPointerEvent(View.java:8742)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4136)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4002)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3576)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3693)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3584)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3750)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3576)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3584)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5823)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5797)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5768)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5913)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:195)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
============================
Droidsound-E version: 39
Droidsound-E build: 30
Time: Thu Jan 28 11:33:11 EST 2016
CPU: armeabi-v7a
CPU: armeabi
Fingerprint: Sony/D6503/D6503:5.1.1/23.4.A.1.264/2418263178:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 9669713920
InternalSD path: /storage/emulated/0

Going to go back to some previous builds, like v31, to see if this happens then too in the meantime.

**Comment by droidmjt** [comment]
the error line is missing, impossible to know in what line the error happens. I tried to reproduce the error and failed.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/k4aqzwyw7jzdb5d/droidsounde16647_35.apk?dl=0

**Comment by droidmjt** [comment]
i tried with emulator tho, i'll put vgz files in to my phone check it there

**Comment by droidmjt** [comment]
also, if possible, test the _35 build with your other devices

**Comment by droidmjt** [comment]
nevermind, this problem happens when user tries to switch screen too fast before the data is available

**Comment by Level99OCR** [comment]
Still not working, even with a clean install. It worked after some FileBrowser adds, but not some others. I am getting a logcat now.

**Comment by Level99OCR** [comment]
The crash still happens at the opening of the app even if I touch absolutely nothing.  Here is the LogCat of the crash, did not LogCat pre-crash because the app works fine after adding and still in the app.

---- Jan 29, 2016 07:10:57 ----

01-29 07:10:57.947   761  1236 W art     : Long monitor contention event with owner method=void com.android.server.pm.Settings$RuntimePermissionPersistence.writePermissionsSync(int) from Settings.java:4899 waiters=0 for 271ms

01-29 07:10:58.040   228   228 W SurfaceFlinger: couldn't log to binary event log: overflow.

01-29 07:10:59.734   761  1101 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.cyanogenmod.trebuchet/com.android.launcher3.Launcher (has extras)} from uid 1000 on display 0

01-29 07:11:01.112  7328  7370 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

01-29 07:11:01.112  7328  7370 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

01-29 07:11:01.557   237  1009 W msm8974_platform: Codec backend bitwidth 16, samplerate 48000

01-29 07:11:01.557   237  1009 I msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(14)

01-29 07:11:02.043  1203  1228 I art     : Background partial concurrent mark sweep GC freed 5884(336KB) AllocSpace objects, 3(640KB) LOS objects, 31% free, 8MB/12MB, paused 2.505ms total 587.021ms

01-29 07:11:02.224   761   771 I art     : Background partial concurrent mark sweep GC freed 22355(1250KB) AllocSpace objects, 3(64KB) LOS objects, 22% free, 13MB/17MB, paused 6.467ms total 2.409s

01-29 07:11:02.672 14625 14625 I Choreographer: Skipped 126 frames!  The application may be doing too much work on its main thread.

01-29 07:11:03.207   761  1702 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.droidmjt.droidsounde/.PlayerActivity (has extras)} from uid 10022 on display 0

01-29 07:11:03.323   761   792 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=7328, uid=10022) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver

01-29 07:11:03.324   761   792 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=7328, uid=10022) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.googlequicksearchbox/com.google.android.apps.gsa.search.core.icingsync.ApplicationLaunchReceiver

01-29 07:11:03.538 14084 14084 I WebViewFactory: Loading com.android.webview version 44.0.2403.119 (code 246011900)

01-29 07:11:03.587 14084 14084 W System  : ClassLoader referenced unknown path: /system/app/webview/lib/arm

01-29 07:11:03.605 14084 14084 I LibraryLoader: Time to load native libraries: 5 ms (timestamps 1391-1396)

01-29 07:11:03.605 14084 14084 I LibraryLoader: Expected native library version number "",actual native library version number ""

01-29 07:11:03.630 14084 14084 I LibraryLoader: Expected native library version number "",actual native library version number ""

01-29 07:11:03.630 14084 14084 I chromium: [INFO:library_loader_hooks.cc(120)] Chromium logging enabled: level = 0, default verbosity = 0

01-29 07:11:03.638 14084 14084 I BrowserStartupController: Initializing chromium process, singleProcess=true

01-29 07:11:03.640 14084 14084 E SysUtils: ApplicationContext is null in ApplicationStatus

01-29 07:11:03.657 14084 14084 W chromium: [WARNING:resource_bundle.cc(285)] locale_file_path.empty()

01-29 07:11:03.664 14084 14084 E libEGL  : validate_display:255 error 3008 (EGL_BAD_DISPLAY)

01-29 07:11:03.664 14084 14084 E libEGL  : validate_display:255 error 3008 (EGL_BAD_DISPLAY)

01-29 07:11:03.665 14084 14084 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I389a668de0)

01-29 07:11:03.665 14084 14084 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.28.00.04

01-29 07:11:03.665 14084 14084 I Adreno-EGL: Build Date: 10/24/15 Sat

01-29 07:11:03.665 14084 14084 I Adreno-EGL: Local Branch: mybranch15621148

01-29 07:11:03.665 14084 14084 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.3

01-29 07:11:03.665 14084 14084 I Adreno-EGL: Local Patches: NONE

01-29 07:11:03.665 14084 14084 I Adreno-EGL: Reconstruct Branch: NOTHING

01-29 07:11:03.742 14084 14084 E DataReductionProxySettingListener: No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp

01-29 07:11:03.790 14084 14084 W AwContents: onDetachedFromWindow called when already detached. Ignoring

01-29 07:11:04.148 14084 14084 E SQLiteLog: (1) no such table: MODLAND

01-29 07:11:04.171   761  1248 I ActivityManager: START u0 {act=android.speech.tts.engine.CHECK_TTS_DATA cmp=com.google.android.tts/.settings.CheckVoiceData} from uid 10095 on display 0

01-29 07:11:04.265 14084 14736 W chromium: [WARNING:data_reduction_proxy_config.cc(423)] SPDY proxy OFF at startup

01-29 07:11:04.291 14084 14757 I OpenGLRenderer: Initialized EGL, version 1.4

01-29 07:11:04.660 14084 14084 W linker  : /data/app/com.droidmjt.droidsounde-1/lib/arm/libbasszxtune.so: is missing DT_SONAME will use basename as a replacement: "libbasszxtune.so"

01-29 07:11:04.854   761  1671 E AudioService: Adding Player: com.droidmjt.droidsounde to available player list

01-29 07:11:04.856  2212  2767 I Avrcp   : State change for music app

01-29 07:11:04.856  2212  2767 I Avrcp   : updatePlayStatusForDevice: device: null

01-29 07:11:04.871 14084 14084 I Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.

01-29 07:11:05.010 14084 14084 W BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 14084

01-29 07:11:10.100 14084 14084 W System.err: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.droidmjt.droidsounde.SCAN_DONE flg=0x10 } in com.droidmjt.droidsounde.PlayerActivity$8@6b631b1

01-29 07:11:10.100 14084 14084 W System.err: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:892)

01-29 07:11:10.100 14084 14084 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)

01-29 07:11:10.100 14084 14084 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)

01-29 07:11:10.100 14084 14084 W System.err: 	at android.os.Looper.loop(Looper.java:148)

01-29 07:11:10.100 14084 14084 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5466)

01-29 07:11:10.100 14084 14084 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)

01-29 07:11:10.100 14084 14084 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

01-29 07:11:10.100 14084 14084 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

01-29 07:11:10.100 14084 14084 W System.err: Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)

01-29 07:11:10.101 14084 14084 W System.err: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)

01-29 07:11:10.101 14084 14084 W System.err: 	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)

01-29 07:11:10.101 14084 14084 W System.err: 	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)

01-29 07:11:10.101 14084 14084 W System.err: 	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)

01-29 07:11:10.101 14084 14084 W System.err: 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)

01-29 07:11:10.101 14084 14084 W System.err: 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)

01-29 07:11:10.101 14084 14084 W System.err: 	at com.droidmjt.droidsounde.database.SongDatabase.setRescan(SongDatabase.java:306)

01-29 07:11:10.101 14084 14084 W System.err: 	at com.droidmjt.droidsounde.PlayerActivity$8.onReceive(PlayerActivity.java:1824)

01-29 07:11:10.101 14084 14084 W System.err: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:882)

01-29 07:11:10.101 14084 14084 W System.err: 	... 7 more

01-29 07:11:10.116 14084 14084 E AndroidRuntime: FATAL EXCEPTION: main

01-29 07:11:10.116 14084 14084 E AndroidRuntime: Process: com.droidmjt.droidsounde, PID: 14084

01-29 07:11:10.116 14084 14084 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.droidmjt.droidsounde.SCAN_DONE flg=0x10 } in com.droidmjt.droidsounde.PlayerActivity$8@6b631b1

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:892)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5466)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase.setRescan(SongDatabase.java:306)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at com.droidmjt.droidsounde.PlayerActivity$8.onReceive(PlayerActivity.java:1824)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:882)

01-29 07:11:10.116 14084 14084 E AndroidRuntime: 	... 7 more

01-29 07:11:10.118   761  3191 W ActivityManager:   Force finishing activity com.droidmjt.droidsounde/.PlayerActivity

01-29 07:11:10.219   761  3675 I OpenGLRenderer: Initialized EGL, version 1.4

01-29 07:11:10.278   761   771 I art     : Background partial concurrent mark sweep GC freed 12741(918KB) AllocSpace objects, 3(60KB) LOS objects, 22% free, 13MB/17MB, paused 2.791ms total 125.056ms

01-29 07:11:10.316   761   792 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{b946a67 u0 com.droidmjt.droidsounde.SCAN_UPDATE} to ReceiverList{8a3e16d 14084 com.droidmjt.droidsounde/10095/u0 remote:2d3a584}: process crashing

01-29 07:11:10.415   761   792 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{946e014 u0 com.droidmjt.droidsounde.SCAN_DONE} to ReceiverList{8a3e16d 14084 com.droidmjt.droidsounde/10095/u0 remote:2d3a584}: process crashing

01-29 07:11:10.649   761   792 W ActivityManager: Activity pause timeout for ActivityRecord{8ab188d u0 com.droidmjt.droidsounde/.PlayerActivity t87 f}

01-29 07:11:11.937   237  1009 W msm8974_platform: Codec backend bitwidth 16, samplerate 48000

01-29 07:11:11.937   237  1009 I msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(14)

01-29 07:11:11.958 14084 14084 I Process : Sending signal. PID: 14084 SIG: 9

01-29 07:11:12.011   761  1671 I WindowState: WIN DEATH: Window{c065aa1 u0 com.droidmjt.droidsounde/com.droidmjt.droidsounde.PlayerActivity}

01-29 07:11:12.014   761  1687 E AudioService: Removing Player: com.droidmjt.droidsounde from index0

01-29 07:11:12.118   761  1725 I ActivityManager: Process com.droidmjt.droidsounde (pid 14084) has died

01-29 07:11:12.118   761  1725 W ActivityManager: Scheduling restart of crashed service com.droidmjt.droidsounde/.service.PlayerService in 14206ms

01-29 07:11:12.152   761   807 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0

01-29 07:11:12.876   761  1725 I ActivityManager: START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10019 on display 0

---- Jan 29, 2016 07:11:17 ----


This was done at info level. If you need verbose, I have also captured that and can attach but its way more lines.

**Comment by Level99OCR** [comment]
It looks like Build 31 does it too, so its some change between Build 28 and 31 since 27 works fine.

**Comment by Level99OCR** [comment]
Would a screen recording help if you need the verbose logcat?

**Comment by droidmjt** [comment]
if possible, provide as accurate as possible logcat log from the very beginning when the app starts

**Comment by droidmjt** [comment]
i have a feeling what causes this, I will upload new test build soon

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/r7c9vi413sceqbm/droidsounde16647_37.apk?dl=0
try this, if it's still there, i need that verbose log

**Comment by droidmjt** [comment]
forgot one thing, i'll upload a second binary soon

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/k53q1zyxjanuh2z/droidsounde16647_38.apk?dl=0

**Comment by Level99OCR** [comment]
Build 38 still having the same issue. I have attached the logcat zip'd up because its huge. It shows it opening successfully once, for absolutely no reason. Then, after exiting and loading again (doing nothing else), the second time it crashes.
[Log_2016-01-30_12-47-22.zip](https://github.com/droidmjt/Droidsound/files/110915/Log_2016-01-30_12-47-22.zip)

**Comment by Level99OCR** [comment]
[droidsounde_crash_20160130_124744.txt](https://github.com/droidmjt/Droidsound/files/110916/droidsounde_crash_20160130_124744.txt)
[droidsounde_crash_20160130_124709.txt](https://github.com/droidmjt/Droidsound/files/110917/droidsounde_crash_20160130_124709.txt)

The two associated droidsound crashlogs, for what its worth.

**Comment by droidmjt** [comment]
ok i can see the problem now, my gut feeling was wrong...i'll get this fixed

**Comment by Level99OCR** [comment]
No worries, thanks for looking into it!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ozausu2wg17bgav/droidsounde16647_39.apk?dl=0

**Comment by Level99OCR** [comment]
Fixed, thanks very much!
