### ISSUE TITLE
Lock screen shows UNKNOWN track after audio interrupted

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#263]
After the audio is interrupted by another app with exclusive audio, the lock screen widget shows "UNKNOWN" track and cannot unpause. The notification widget still thinks the song's playing, while the app interface shows no song loaded but can press play to restart.

Cm11 4.4.4, galaxy nexus, latest beta apk.

**Comment by droidmjt** [comment]
i'll check it.

**Comment by droidmjt** [comment]
could you tell me what is expected behaviour in this case?

**Comment by jimbo1qaz** [comment]
I think it should act like playback is paused through normal means. Unless a paused stream will be destroyed by other exclusive apps. 

* The lock screen widget should either disappear or act paused, NOT display "UNKNOWN".
* The notification panel should not require pause/unpause to merely unpause.
* The lock screen, notification, and app UI should be consistent.

**Comment by droidmjt** [comment]
actually, i just noticed that when another app starts playing, DS-E gets a signal to stop playing, so what I did is I made the widget also act like music has been stopped. Check out the _38 build from another issue.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/k53q1zyxjanuh2z/droidsounde16647_38.apk?dl=0

**Comment by droidmjt** [comment]
ah, need to fix some small things yet

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/evxgl1eh7ts7uxc/droidsounde16647_41.apk?dl=0

**Comment by droidmjt** [comment]
DSE will be set to pause state when another app starts playing and home-screen widget, notification and playscreen are set to pause state also, tested with CM12 and official roms
