### ISSUE TITLE
Lock screen widget disappears if paused from app/notification

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#264]
The lock screen widget defaults to showing up when playing. It remains enabled when pausing from widget, but not when pausing from app. I think it should show up whenever paused, regardless of where it came from. But not when stopped.

If you want, you can always hide when paused. But I myself think that's not ideal.

**Comment by droidmjt** [comment]
I just tried the latest version. I started a song from examples, let it play a bit, then pause it, then turned off the screen to get into the lock screen, in lock screen i saw the widget in paused state, i typed my PIN and entered back to the APP, clicked resume playing, all worked as it should. This is with official ROM tho. I don't have CM now, not sure if this is CM-only bug.

**Comment by droidmjt** [comment]
I hope my latest fixes have corrected this already, I haven't uploaded the current version yet.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/evxgl1eh7ts7uxc/droidsounde16647_41.apk?dl=0

**Comment by droidmjt** [comment]
this works normally with CM12 and official ROMS with latest build
