### ISSUE TITLE
PPZ Issues with PMD

### ISSUE THREAD

**Issue by Jazz392** [droidmjt/Droidsound#266]
I'm having a similar issue to https://github.com/droidmjt/Droidsound/issues/209. It doesn't result in an error, but PMD files that use PPZ aren't playing correctly when the used to.

**Comment by droidmjt** [comment]
interesting, at least share the file so i can check it :)

**Comment by droidmjt** [comment]
or does this happen with the same song what is mentioned in the #209 case? What version you are using?

**Comment by droidmjt** [comment]
i can't hear any problems with those songs, the problem got fixed long time ago, download the _40 build from the main page and try again

**Comment by crimson1117** [comment]
I think that's a rhythm thing again.https://web.archive.org/web/20110804230736/http://www.ylw.mmtr.or.jp/~hosino/ma-net/bins/archive/game_sample/m88/ym2608rl_fmpmd.zip
Today I played some touhou PMD and it comes strangely then I knew it.

**Comment by droidmjt** [comment]
these .wav files are completely different sized than the ones currently included in the app. Which one i should include?

**Comment by droidmjt** [comment]
the samples in the above mentioned zip files are using 44100Hz while the ones currently included in the app uses 48000Hz. Also the samples above seem to have a little extra, i wonder what are the correct samples to use.

**Comment by crimson1117** [comment]
ym2608rl_fmpmd.zip is made by markun2,for FMPMD2000(WinFMP&PMDWin).since you used a Portable PMDWin,I think that's better

**Comment by droidmjt** [comment]
all right, will use those files instead then

**Comment by crimson1117** [comment]
ah,since most of s98 is pc88 type,I recommand use ym2608rl_fmpmd.zip for pmd,and the former .wav files for those s98 play

**Comment by droidmjt** [comment]
will do

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/evxgl1eh7ts7uxc/droidsounde16647_41.apk?dl=0
you probably have to click Settings -> Misc -> Extract System files and restart to get the rhythm files to correct place. After restart verify that that droidsound/ folder has 's98' and 'pmd' folders

**Comment by crimson1117** [comment]
thanks!It worked.

**Comment by droidmjt** [comment]
i'll close this case, leave a comment if needed
