### ISSUE TITLE
an song plays strangely

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#267]
http://vgmrips.net/packs/pack/xenon-mugen-no-shitai-nec-pc-9801 
in the pack 16 xenon.vgz,and http://hoot.joshw.info/pc98/xenon.zip 
what ever kind of this song,if the volume is lower than half,the beginning cannot play correctly(some silence)

**Comment by droidmjt** [comment]
i'll check it

**Comment by droidmjt** [comment]
and by "play correctly" do you mean it will skip it and go to next song?

**Comment by droidmjt** [comment]
what volume did you change? there are 3 of them.

**Comment by droidmjt** [comment]
If the volume is more than half, its completely silent, but why do you have to set the value so high?

**Comment by crimson1117** [comment]
the beginning of the song plays abnormal.I mean the volume of the smartphone.I didn't thange volume in DSE-set

**Comment by droidmjt** [comment]
do you mean that if you change volume using hardware buttons (physical volume setting), it corrupts the sound? If yes, I can already say that is not related to the application anyhow, hardware volume setting cannot affect the sample data anyhow.

**Comment by crimson1117** [comment]
but actually is,When I change volume using hardware buttons (physical volume setting), its corrupted sound fixed!

**Comment by droidmjt** [comment]
Maybe your phone is old or getting broken :) 

There is not a single line of code what would affect sample data by using hardware volume setting, there is some logging but its just logging and it can be seen in logcat and thats it.

For the sake of paranoia I can double check it today but 99,9% sure I can say there is nothing.

**Comment by droidmjt** [comment]
Checked the code, there is just one line that enables hardware buttons to change the volume in the app but that is not affecting the sample data anyhow. When you next time encounter the same problem, let me know how to reproduce it.

**Comment by crimson1117** [comment]
thx,just close this.

**Comment by crimson1117** [comment]
I just found that if I set FM volume up(0 to 20) and It plays normal with a lower volume,so if there is some relationship with that?

**Comment by droidmjt** [comment]
Those volume settings in the Settings -> PMD have no relations to anything, i tried playing those songs while changing the FM volume between 0-20 and also higher values, the only thing that happened was that the FM sounds lowered down. If you put them too high then naturally those songs sounds different since whole channel (FM in this case) is nearly muted. There is no any kind of sound corruption.

Check the Volume Setting in the actionbar that the plugin and song volumes are both zeros.

**Comment by crimson1117** [comment]
I checked it,so the sound goes normally with android speaker...maybe that's the earphone thing.thanks a lot.
