### ISSUE TITLE
Play/pause state desyncs frequently (eg. when headphones are unplugged)

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#268]
CM11 Galaxy Nexus

Whenever I unplug my headphones, DSE pauses, but the lock screen widget and notification icon still think it's playing.

With so many play-state desync bugs, it may be a good idea to redesign the event/communication/widget system.

**Comment by droidmjt** [comment]
i'll fix it.

**Comment by droidmjt** [comment]
on build _40 only home screen widget keeps showing it is playing, playscreen and notification goes to paused

**Comment by droidmjt** [comment]
this is fixed, will upload new binary later

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/evxgl1eh7ts7uxc/droidsounde16647_41.apk?dl=0

**Comment by droidmjt** [comment]
tested this also with CM12 and it works with build _41, i'll close this case.
