### ISSUE TITLE
[Bug] After a certain amount of time, no longer able to delete files from within Droidsound E

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#270]
Haven't been able to metric it yet, will try to grab a logcat today, but when I first open the app and start listening to things, I'm able to delete archives and files that have been scanned by Droidsound. After a bit of time, if I try to delete it, it will no longer remove it. No error is reported, things keep working otherwise, but no files can be deleted. Currently on build 40, I believe.

**Comment by droidmjt** [comment]
I really need instructions how to reproduce this :)

**Comment by Level99OCR** [comment]
I'll get them to you as soon as I can narrow down the scenario that causes this. Hopefully getting it this afternoon.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/evxgl1eh7ts7uxc/droidsounde16647_41.apk?dl=0
thats the latest version, i wonder if it happens with _41 version also

**Comment by Level99OCR** [comment]
Seems to have been some anomalous issue on my end, or 41 fixed it. Will reopen if I'm able to recreate.
