### ISSUE TITLE
Feature Request:FM-TOWNS eup file

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#271]
source and player:
http://www.purose.net/befis/download/lib/mplay/mplaysrc.lzh
http://www.purose.net/befis/download/lib/mplay/mplay201.lzh

**Comment by droidmjt** [comment]
This source is missing the library itself that produces the sound, besides, i could find only 5 audio files of this format. Not very good idea to include plugins like this.

**Comment by crimson1117** [comment]
I have plenty of them(audio files)...you need some?well,since the library is missing,I'll close this one
