### ISSUE TITLE
error while playing some gbs file due to gmp

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#275]
http://gbs.joshw.info/m/Magical%20Chase%20GB%20-%20Minarai%20Mahou%20Tsukai%20Kenja%20no%20Tani%20he%20(GBC)(2000-08-04)(Quest)(Microcabin).7z

**Comment by droidmjt** [comment]
what is gmp?

**Comment by droidmjt** [comment]
whats wrong with that music?

**Comment by droidmjt** [comment]
by gmp if you mean the GME library, then there is nothing i can do here. The updated library won't fix this either.

**Comment by droidmjt** [comment]
nevermind, i got an idea

**Comment by droidmjt** [comment]
fixed, now it plays fine :) will upload new binary later, im too busy :(

**Comment by crimson1117** [comment]
ah thanks:) 
http://gbs.joshw.info/m/Metal%20Masters%20(1994-12)(Bit%20Managers)(Electro%20Brain).7z
http://gbs.joshw.info/s/Shantae%20(GBC)(2002-06-02)(WayForward)(Capcom).7z
these music is awesome!recommanded!
