### ISSUE TITLE
SPC interpolation defaults to None (should be Gaussian)

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#276]
GEP: SPC interpolation defaults to None, causing massive degradation of sound quality. The most authentic setting to hardware is Gaussian interpolation. Other interpolation increases high-frequency content, producing less muffled output (but more sample compression noise/artifacts).

**Comment by droidmjt** [comment]
i can change it, I was told earlier that it should be set to None

**Comment by droidmjt** [comment]
i'll close this case since it's just a preferences value change

**Comment by jimbo1qaz** [comment]
Also "disable spc surround" should be unchecked for authenticity, but checked for people with mono speakers.

**Comment by droidmjt** [comment]
If its possible to check by code whether user has mono speakers or not, then its no problem

**Comment by jimbo1qaz** [comment]
I don't know of any such functionality, not sure if it would be accurate, and nobody else has done anything similar (admittedly I'm talking about Windows).

**Comment by jimbo1qaz** [comment]
I think this should be kept up to user preference?

**Comment by droidmjt** [comment]
most likely, I'll check couple of things if its possible to know if a user has stereo/mono speakers, otherwise its user's own preference
