### ISSUE TITLE
Full rescan needed to view new archives and DSEMusic subfolders

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#280]
CM11 Galaxy Nexus, DSE v53 (probably)

Every time I add new archives/folders, or rename/delete them, I must perform a time-consuming full rescan before they are visible.

Is this the fault of my file manager program?

**Comment by droidmjt** [comment]
DSE uses SQL to store filepath infos. If you rename/delete indexed filepath, then of course you need to rescan it.

**Comment by jimbo1qaz** [comment]
standard rescan does not update any of my files, only full. is that normal? (Android Gallery also needs a manual rescan)

**Comment by droidmjt** [comment]
Unfortunately full scan is needed if you change the paths since the SQL DB must be updated.
