### ISSUE TITLE
xma1 problems

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#281]
i don't know if you know this but xma 1 files just repeat the first sec of the files and Final Fantasy XIII xma's crash the app, just wanted to tell you if you weren't aware of those problems

**Comment by droidmjt** [comment]
where can i get these XMA1 files?

**Comment by Sir-Sabin** [comment]
You can get them from http://x360.joshw.info/ the ones that do it are Gears of War, Lost Odyssey and Lego Batman 3

**Comment by droidmjt** [comment]
at least with build _53 those FF13 songs won't crash, it just skips them. Xbox360 version of FF13 songs works just fine (the .scd files). 

I don't think those FF13 XMA files ever worked since ffmpeg doesn't recognize the format.

**Comment by droidmjt** [comment]
the rest of the files GoW etc etc, i'll get it fixed.

**Comment by Sir-Sabin** [comment]
Ok, you might mean the ps3 version that you are talking about as that's scd

**Comment by droidmjt** [comment]
yes correct, PS3 version :)

**Comment by Sir-Sabin** [comment]
I would also Fable III xma crashes when i scan them

**Comment by droidmjt** [comment]
do you have build _53?

**Comment by Sir-Sabin** [comment]
Yep, i'm using build _53

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tfcuug0zv12p9ia/droidsounde16647_54.apk?dl=0
but some of those files are not even recognized by ffmpeg so they cannot be played

**Comment by droidmjt** [comment]
leave a message if there is something that can be done, i'll close this case

**Comment by Sir-Sabin** [comment]
It works, but castle crashers plays to fast (will test it out later to see if i can fix it with a rename of the file type)

**Comment by droidmjt** [comment]
I just tested those songs with latest ffplay and latest droidsound-e and to me it sounded the same, what is the filename of the song that plays too fast?

**Comment by Sir-Sabin** [comment]
all of them, they sound fast and this is with the latest build of droidsound, do they play at 44khz for you?

**Comment by droidmjt** [comment]
yes they do play at 44khz, take ffplay and play those songs
https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-20160517-git-af3e944-win32-static.7z

**Comment by Sir-Sabin** [comment]
what's the command line to get them to work? i just get errors when i try to play them with it

**Comment by droidmjt** [comment]
ffplay.exe blablabla.xma for example
ffprobe.exe blabalblabla.xma shows infos

**Comment by Sir-Sabin** [comment]
i got it to work, was in the wrong dir, it also makes a noise when playing and was showing this error when playing over and over again, could be a bug in it

[xma1 @ 0586b620] Packet loss detected! seq 2 vs 2sq=    0B f=0/0

**Comment by droidmjt** [comment]
yeah, i get those errors also but the music plays fine, because of the errors i think the code is not fully working, lets wait and see :)
