### ISSUE TITLE
Playlist files not getting updated

### ISSUE THREAD

**Issue by sketch242** [droidmjt/Droidsound#282]
I back up my .plist files from sdcard/droidsound/playlists/ semi-regularly, but I just noticed that some of them are much older (as far back as November of last year), and don't contain all of the entries that are in the actual playlists.

I stopped Droidsound and refreshed my file browser and found that one of the playlists (not Favorites.plist) had been updated to the current date/time, but the others are still older, including one smaller one where I can count that the number of songs in the actual playlist in droidsound is higher than the number of files in the .plist file.

Is this a bug?  The fact that they get updated sometimes makes it seem that way  Should I be doing something else to back up my playlists?

I'm on DSE 1.6647 (not sure if this was from the store or an older dev release at this point).

**Comment by droidmjt** [comment]
Yeah, its a bug and I'll fix it. Would it be OK so that there would be a switch for update .plist files before exit? I'll also update the other functionality from Settings related to playlists.

**Comment by sketch242** [comment]
Sure, that'd be fine  But why not just make it the default?

**Comment by droidmjt** [comment]
Actually, after second thought, no need to have that since playlist files and DB gets updated every time you add something to a specific playlist. I have added an option to flush DB entries to files now. Will upload new binary later.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tfcuug0zv12p9ia/droidsounde16647_54.apk?dl=0

**Comment by droidmjt** [comment]
if you perform any kind of rescans, playlists are not affected. When ever you add a new entry to playlist, both the DB and .plist do get updated. Incase you want to flush present DB entries to files, now there is a button for that :) 

You can find it in here Settings -> Playlists

**Comment by droidmjt** [comment]
actually, there is still a small problem with playlists, i'll try to fix it :(

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/uassbqnglh1auyr/droidsound16647_56.apk?dl=0, now it can flush playlist stuff automatically, just enable it from settings

**Comment by droidmjt** [comment]
also there was marshmallow related scanning bug that made scanning extremely slow, it has been fixed too

**Comment by droidmjt** [comment]
another bug with playlists appeared

**Comment by droidmjt** [comment]
don't use the binary yet :(

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/igvgs5sj6zxz45p/droidsounde16647_57.apk?dl=0

**Comment by droidmjt** [comment]
I'll close this due to inactivity, leave a message if there are problems related to this.

**Comment by sketch242** [comment]
This version rescanned my music on first launch, but crashed partway through, The second launch left me with an empty browser (except for Network and an empty DSEMusic), but I tried the export playlist to files function and it worked...so that part seems to work fine.  :)   However, successive launches try to rescan every time, and it crashes again every time.

I haven't added any new music in ages, so this seems likely to be a bug, since it never crashed while scanning before.

**Comment by sketch242** [comment]
Via process of elimination I have figured out which archive is causing it to crash.  This time it hung after scanning, but after a restart it showed all of the scanned music successfully.  Unfortunately the one that causes the crash is a 370MB archive of songs for UADE, curated from modland's many formats so that it only includes formats that UADE on droidsound can actually play.

**Comment by sketch242** [comment]
If you want to take a look at the file, it's at https://dl.dropboxusercontent.com/u/108158470/Amiga.zip

**Comment by droidmjt** [comment]
all right, i'll check the file

**Comment by droidmjt** [comment]
i got crash here too with the amiga.zip, prolly small fix, i'll try to fix it later today

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bt234eovht1gfj8/droidsounde16647_60.apk?dl=0
fixed the amiga thing

**Comment by sketch242** [comment]
Yep, works now.  Thanks!

**Comment by droidmjt** [comment]
I'll close this case, leave a message if something is wrong about the feature
