### ISSUE TITLE
Outdated libopenmpt plugin

### ISSUE THREAD

**Issue by random12343** [droidmjt/Droidsound#283]
The included libopenmpt plugin is quite outdated. Last version has fixes for various module formats (.mt2 comes to mind) so it sounds like a good idea to update it.

**Comment by random12343** [comment]
The recent source code snapshots have even more major fixes.

**Comment by droidmjt** [comment]
sure, will update it, will upload new binary in this weekend

**Comment by random12343** [comment]
Awesome!

Latest snapshots are here: https://buildbot.openmpt.org/builds/auto/src/

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tfcuug0zv12p9ia/droidsounde16647_54.apk?dl=0

**Comment by random12343** [comment]
Good news are that some issues on 16647_53 are now fixed.

Bad news are that there is still work to be done on openmpt.

Appreciated the update though, keep it up!

**Comment by droidmjt** [comment]
is there something i can do here or is it libopenmpt issue?

**Comment by random12343** [comment]
It seems to be the lib unfortunately.

I cannot verify though. No access to OSes other than Android right now.

If you feel like comparing to baseline openMPT yourself, here's a module to try:

ftp://ftp.modland.com/pub/modules/Mad%20Tracker%202/Sonic/dream%20alone.mt2

You will either need madtracker 2 on a winXP system or lower, or winamp with the madtracker plugin to check how it sounds on the de-facto engine.

**Comment by droidmjt** [comment]
report that here: http://bugs.openmpt.org/my_view_page.php

and they will fix it most likely :)

**Comment by random12343** [comment]
I doubt. The mt2 engine some has some quite unique feats, even by today's standards. One can hope thought.

There's a reason I posted that particular module, there's an xm version of it which happens to sound seemingly OK on openmpt:
http://modarchive.org/index.php?request=view_by_moduleid&query=168740

Oh well..

**Comment by droidmjt** [comment]
I constantly checkout their SVN and the Load_MT2.cpp is being updated quite often, you won't lose anything if you try.

**Comment by random12343** [comment]
Will get to it eventually. It'll be quite a demotivational submission.

**Comment by droidmjt** [comment]
All right, I suppose we could close this case for now since the fix is not in openmpt yet.

**Comment by random12343** [comment]
Just let it be for now. Let's see what the ompt people say.

The report:
https://bugs.openmpt.org/view.php?id=793

**Comment by droidmjt** [comment]
Great, one last thing, add also the modland link there for reference :)
ftp://ftp.modland.com/pub/modules/Mad%20Tracker%202/Sonic/dream%20alone.mt2

**Comment by random12343** [comment]
There are other modules too in the archive...

**Comment by droidmjt** [comment]
I'll close this case for now since there the fix is not there yet, leave a message when the fix is there and I will update the lib.

**Comment by droidmjt** [comment]
Revision 6372, [Fix] MT2: Tentative fix for missing sample assignments for some instruments (fixes Destiny - Dream Alone.mt2)

There you go :)

**Comment by random12343** [comment]
Yeah, it was the bug report of mine's. Still long way to go, you can update droidsound with the dream alone fix until then...

**Comment by random12343** [comment]
Even more updates committed :-)

**Comment by droidmjt** [comment]
excellent :) I'll update it in this weekend

**Comment by random12343** [comment]
Weird. I tried v16647_57 and it doesn't seem to have any of the changes. Are you sure that you update from the latest snapshots?

**Comment by droidmjt** [comment]
yeah because its not there yet, i've been busy with other things, will upload new binary later today

**Comment by random12343** [comment]
Oh, ok :-)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/p1ufr6q6qd24n3m/droidsounde16647_58.apk?dl=0
check this out

**Comment by random12343** [comment]
Yeah it seems to have been updated. The update broke some stuff though...

**Comment by random12343** [comment]
It also fixed some other stuff... :-)

**Comment by droidmjt** [comment]
what did it break?

**Comment by random12343** [comment]
r6407 is meant to fix it. Feel free to update when it's uploaded here: https://buildbot.openmpt.org/builds/auto/src/

**Comment by random12343** [comment]
r6407 is up :-)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/823h0neuuj9lhbt/droidsounde16647_59.apk?dl=0
try that :)

**Comment by random12343** [comment]
Did, still has issues on the openmpt side. Gets better though.

It's ok, you already do more than enough by updating droidsound so often.

**Comment by random12343** [comment]
New version out again :-)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xf2a8il52wodpwi/droidsounde16647_63.apk?dl=0
has latest libopenmpt changes

**Comment by random12343** [comment]
Yeah, much better now. :-D

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ukn0xr3c6etpjbf/droidsounde16647_65.apk?dl=0
check out the noise sharpening feature in volume settings
