### ISSUE TITLE
Feature Request:SGT support

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#284]
http://www.vgmpf.com/Wiki/index.php?title=SGT
some direct music called sgt,ff8 and la-mulana(original)and Gothic II used that...
http://chokuto.ifdef.jp/urawaza/com/dmusic.html
page about this format?

**Comment by droidmjt** [comment]
First i need some example songs, second, the .jp link is no use since it looks like windows-only thing. Before I have any example songs I cannot say if its possible to include this format or not.

**Comment by crimson1117** [comment]
https://www.dropbox.com/s/7vhjmzvgw1xhk5c/dmusic_FF8.rar?dl=0

**Comment by droidmjt** [comment]
no go, there is no library that would support this format anymore :(

**Comment by crimson1117** [comment]
https://www.dropbox.com/s/n6cnanzazp8peaw/ldm.lzh?dl=0
found a DirectMusic library but don't know if it can work?
on japanese site http://search.vector.co.jp/vsearch/vsearch.php?key=Direct+music&kanji=euc

**Comment by droidmjt** [comment]
its Windows-only stuff

**Comment by crimson1117** [comment]
I know.since nothing can we do I close this one.
