### ISSUE TITLE
[Internal Function Change Request] Shuffle method

### ISSUE THREAD

**Issue by truskj** [droidmjt/Droidsound#285]
I have suggestion for how the shuffle button could work, to stop tracks repeating.
I'm not sure how much work this would be, but perhaps go about it more like the iPod does.
eg.
when I press "shuffle" on my iPod, it takes the current playlist, and completely randomizes the sequence of tracks, and then will play this new sequence, in order.
like this, I'm able to skip forward and backwards through tracks, and you will never hear the same track repeat, (until the entire sequence loops).
again, not sure how much work this would be, but just a suggestion,
thanks!

**Comment by droidmjt** [comment]
I know what you mean, I'll try couple of options and see what works the best. This is a good idea :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/18054enlgc9wfi1/droidsounde16647_61.apk?dl=0
fixed, see how it works

**Comment by truskj** [comment]
Implemented in less than 24hrs, very impressive ;)
it works well! however, now when adding directories / archives by touching and holding and selecting "add to new playqueue" or "new playqueue". the app seems to crash, I'm using a stock Xperia Z1 if that helps.
also, is there anyway to view the current playqueue?
Thanks!

**Comment by truskj** [comment]
Also, another suggestion, if I may..
There was an older SPC player app I used on iOS, it had a function which could be toggled, where it would automatically skip any songs less than 5 or 10 seconds in length, it was convenient as many music sets contain those win chimes or fanfares which just break up the flow.

**Comment by droidmjt** [comment]
ah crap, forgot to test that 'new playqueue' thing, i get it fixed later today. For now there is no way to see the current playqueue. 

About the SPC feature, I can try to add a feature where user defines minimum songlength, if songlength is less than that, it skips it.

**Comment by truskj** [comment]
No worries about the playqueue, it's not really important.
I'll do more testing for ya, and see if I can suggest more, I use the app daily while working or riding.
Brilliant app. ;)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/i9cj3sy1sodslot/droidsounde16647_62.apk?dl=0
now the shuffle is fixed, hopefully :)

**Comment by truskj** [comment]
Seems pretty good so far! thanks!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ukn0xr3c6etpjbf/droidsounde16647_65.apk?dl=0
added the minimum songlength thing, also, if you encounter new bugs, please report ASAP

**Comment by droidmjt** [comment]
i'll close this case, leave a comment
