### ISSUE TITLE
Add support for "LOOPSTART" and "LOOPLENGH" metatags

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#286]
Some games that don't use sequenced music formats (such as ogg, mp3, wav ect.) use metatags in order to loop their music ingame. These tags work like this:

LOOPLENGH: <samples> (This determinates how long the loop is in samples)
LOOPSTART: <sample> (This determinates the loop starting sample)

I'd appreciate it if this feature is going to be added.

Here is an example of these tags:
![example](https://cloud.githubusercontent.com/assets/15172856/16285420/4e85470c-38d6-11e6-818c-321ebca39171.png)

**Comment by droidmjt** [comment]
Sure, just send me example songs of each format, then I can add it.

**Comment by theGIZOID** [comment]
Alright, I have mailed you some example files.

**Comment by droidmjt** [comment]
got it, I will check them.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/y1245ax1gnbsaxd/droidsounde16647_73.apk?dl=0

try that, remember to enable endless looping first

**Comment by droidmjt** [comment]
crap, found related bug, i'll fix it now

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/fpo5e5dd23bfkyj/droidsounde16647_74.apk?dl=0

**Comment by theGIZOID** [comment]
I got home and immediately tried it. It works as intended, thanks a lot.
