### ISSUE TITLE
"Play song endlessly" breaks on SPC files

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#287]
DSE version 74. Tested on Galaxy Nexus 4.4 and Nexus 5X 6.0.

When I enable "play song endlessly" (repeat setting), SPC files fail to open. The app goes down the list, trying (and failing) to open each song until you change the repeat mode, where the app begins playing a song below the one you selected.

**Comment by droidmjt** [comment]
are the SPC files inside RSN or another kind of archive?

**Comment by droidmjt** [comment]
Does this happen only with SPC files?

**Comment by jimbo1qaz** [comment]
I tested with bare spc files outside of an archive, the bug still occurs.

This bug is not limited to SPC files. I tested with some bare opus files I
had. The app glitched up pretty badly (cycles through songs without
playing, even after switching out of "endless repeat").

(Note: Testing through DB browser on /sdcard/Music)

**Comment by droidmjt** [comment]
reset preferences and try again, if that doesnt work, try fresh install

**Comment by droidmjt** [comment]
check if you have set the 'minimum songlength' to something else than 0. If i set to endless repeat and minimum songlength is > 0 is just hangs, i

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8a3waysemto28ye/droidsounde16647_76.apk?dl=0

**Comment by jimbo1qaz** [comment]
oh... that's why.

The new APK seems to fix things. Did you disable "minimum song length" on
infinite loop?

**Comment by droidmjt** [comment]
I fixed it, now the minimum songlength doesn't mess up the endless repeat. If all works, close this case.
