### ISSUE TITLE
SPC file "sort by entry" broken

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#288]
DSE version 74. Tested on Galaxy Nexus 4.4 and Nexus 5X 6.0.

When I enable "sort by entry", SPC file sort alphabetically instead.

#287 appeared recently as well. Did you update/change the SPC library, or somehow break API calls?

**Comment by droidmjt** [comment]
i cannot reproduce this problem

**Comment by jimbo1qaz** [comment]
I recall it worked in the past?

**Comment by droidmjt** [comment]
it has always worked like it works now

**Comment by jimbo1qaz** [comment]
so close?
