### ISSUE TITLE
[Feature] Open current plugin settings?

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#289]
Can you add a button in the player, that opens the settings for the currently playing plugin? Many game formats have settings that dramatically alter the sound, which are a bit inconvenient to access now.

**Comment by droidmjt** [comment]
I'm not sure if this is possible at all. I can check if it is possible to directly open specific area from preferences.

**Comment by droidmjt** [comment]
this will take some time, won't be ready any time soon

**Comment by droidmjt** [comment]
solved this one, wohoo

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/dqgf1yd8c9yrnb6/droidsounde16647_82.apk?dl=0
