### ISSUE TITLE
Revert to default fonts?

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#290]
You added a font selector recently. Right now, it doesn't have an option to pick "empty" font, or return to default settings. Can you add a [default] choice in the font selector?

**Comment by droidmjt** [comment]
ah yes, reset to defaults button, I'll add it.

**Comment by droidmjt** [comment]
ah yes, reset to defaults button, I'll add it.

**Comment by jimbo1qaz** [comment]
Not "reset all fonts to default", but rather "default" in the font selector.

**Comment by droidmjt** [comment]
reset button would make it use  empty aka default font, the same font it uses when you run it for the first time.

**Comment by droidmjt** [comment]
but if there is a problem with that, i can add a new entry to the list.

**Comment by jimbo1qaz** [comment]
reset button is ok. but each font should be resettable individually (I
think). and the fonts menu is already rather long, so it may fit better in
the font selector.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/wofugue4x25u405/droidsounde16647_77.apk?dl=0

**Comment by jimbo1qaz** [comment]
Well, the font selector is actually much longer than the font menu. Adding
"default" as a selector entry may not necessarily be the good idea (scroll
up a lot). Do you think that font menu clutter is worse, or font selector?

**Comment by droidmjt** [comment]
I got confused, what exactly do you mean by font selector?

**Comment by jimbo1qaz** [comment]
! edited the previous comment.

**Comment by droidmjt** [comment]
ok I'll add two buttons in the font menu to reset both fonts to defaults
