### ISSUE TITLE
[Feature] Automatically add extra time when fadeout?

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#291]
Right now, I don't want to add extra time or fadeout to any of my non-looped songs. However, for looped songs, I want to play them for tagged time, plus N seconds of extra time + fadeout. Can you add an option to "automatically add extra time when fading out"?

**Comment by droidmjt** [comment]
If the extra time info is stored somehow in tags using the same tagname, it shouldn't be a problem.

**Comment by jimbo1qaz** [comment]
Yes, some songs are tagged with fadeout time. But I originally meant that the global fadeout setting is added as extra time (for files not excluded from fadeout). For example, GameCube AST files do not have tags (native game format).

**Comment by droidmjt** [comment]
ah ok, I get it fixed.

**Comment by droidmjt** [comment]
ok I added a setting that allows fadeout time to be added to song length, is this what you wanted?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/wofugue4x25u405/droidsounde16647_77.apk?dl=0

**Comment by jimbo1qaz** [comment]
Works.
