### ISSUE TITLE
Android 5/6: DSE notification marked as private

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#292]
Right now, the DSE notification is marked as private. So if you turn on:

* "Sound & Notification -> (Notification) When device is locked: Hide sensitive notification content"

in Android, you can't see the playing song, switch songs, or pause/unpause.

Is this intentional?

**Comment by droidmjt** [comment]
Not intentional

**Comment by droidmjt** [comment]
you can close this case, nothing can be done here

**Comment by jimbo1qaz** [comment]
You could mark the notification as non-sensitive, is that possible?

Even then, I'm not sure if the control is expandable. You could check <https://developer.android.com/guide/topics/ui/notifiers/notifications.html#lockscreenNotification>. They have documentation about private notifications and the new lock screen music API.

**Comment by droidmjt** [comment]
holy shit, thanks for the link, news to me, i try it at once

**Comment by droidmjt** [comment]
now play controls are visible even if you select 'hide contents' from lock screen security settings :)

**Comment by droidmjt** [comment]
Luckily I was mistaken in this case, I never set the notifications to private myself tho, I guess it is set private by default, good thing is that this was one line fix.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/wofugue4x25u405/droidsounde16647_77.apk?dl=0

**Comment by jimbo1qaz** [comment]
Nexus 5X, PureNexus Marshmallow 6.0.1:

As soon as I drag down to reveal controls, my password prompt appears. If I
exit the password prompt, the notification un-expands and controls
disappear.

Would the MediaSession
<https://developer.android.com/reference/android/media/session/MediaSession.html>
API help?

**Comment by droidmjt** [comment]
what option you have selected from System settings for lock screen notification?
There should be 3, show content, hide content or do not show notifications?

**Comment by jimbo1qaz** [comment]
hide sensitive notification content

**Comment by droidmjt** [comment]
it works fine here with 'show content' and 'hide content'.

**Comment by droidmjt** [comment]
i'll upload a new binary soon, i made a test with and without the one line fix, maybe i accidentally uploaded the wrong binary

**Comment by droidmjt** [comment]
crap, it seems the mediasession is the only way for API 21 and above, odd thing is that it works on my samsung just fine

**Comment by jimbo1qaz** [comment]
The notification shows a new "stop" Burton when expanded. Is this intentional?
