### ISSUE TITLE
Adding extra time to AST files plays from beginning (not loop point)

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#293]
When I add extra time to a Gamecube AST file (Mario Kart Double Dash), for example with the fadeout extra time, the extra time plays back from the beginning of the file, instead of looping properly.

Fixing this bug would make "add fadeout as extra time" work even better.

**Comment by droidmjt** [comment]
disable the option i added and go to Settings -> Audio -> VGMStreamPlugin. There is a separate fadeout stuff for the plugin, can that solve your problem?

**Comment by droidmjt** [comment]
dont use that yet, there is a bug

**Comment by droidmjt** [comment]
ah, no bug there, i saw it wrong, some other unrelated crash thingy
