### ISSUE TITLE
[Issue] No NSF playback

### ISSUE THREAD

**Issue by David8989** [droidmjt/Droidsound#294]
I m trying to play some nsf music but the player just skip any of them. I tried another app and tge files are working

**Comment by Sir-Sabin** [comment]
I'm having the same problem, it's just frozen

**Comment by droidmjt** [comment]
what build number?

**Comment by Sir-Sabin** [comment]
76 the latest one on the site it just freezes it does it on my tablet and phone

**Comment by droidmjt** [comment]
weird, I check it now

**Comment by theGIZOID** [comment]
I use 77 and the same thing happens to me too.

**Comment by David8989** [comment]
I downloaded it today, it is V 1.6647

**Comment by droidmjt** [comment]
@David8989 i wanted to know the _xx build number :)

**Comment by David8989** [comment]
Yeah, sorry. i havent found it in the about section at first ^^' But i checked the apk i downloaded, and it was 76

**Comment by droidmjt** [comment]
is minimum songlength option enabled?

**Comment by David8989** [comment]
Not here.

**Comment by droidmjt** [comment]
i just did fresh install with the latest version(not in dropbox yet), tried with minimim songlength etc etc and worked, i'll upload new version now, lets see

**Comment by droidmjt** [comment]
go to Examples/Console/ and try to play any NSF song, what happens, does it go to next song?

**Comment by theGIZOID** [comment]
NSFE files seem to work but not NSF files.

**Comment by droidmjt** [comment]
@theGIZOID yeah, same bug, good

**Comment by Sir-Sabin** [comment]
Same for me to

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/kc0uo3hi2k08ih1/droidsounde16647_80.apk?dl=0

**Comment by theGIZOID** [comment]
It works again for me.

**Comment by droidmjt** [comment]
good good

**Comment by theGIZOID** [comment]
Also: Nice new notification bar :)

**Comment by droidmjt** [comment]
thanks :)

**Comment by David8989** [comment]
Yeah, its working again here. Thanks ^^

**Comment by droidmjt** [comment]
great, i'll close this case

**Comment by jimbo1qaz** [comment]
Why are the notification bar icons smaller horizontally (than 78)?

**Comment by droidmjt** [comment]
Post the screenshots of the smaller icons.

**Comment by Sir-Sabin** [comment]
Found another problem, when you turn the fade options it freezes and crashes on gbs files

**Comment by droidmjt** [comment]
thanks for reporting, I'll check it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/cx065jzl6ickoy3/droidsounde16647_83.apk?dl=0
let me know if the new change brought some new bugs

**Comment by Sir-Sabin** [comment]
That fixed it, the only bug i see is it doesn't add the fade when change tracks in a nsf file

**Comment by droidmjt** [comment]
crap, i'll check it.

**Comment by droidmjt** [comment]
i did fresh install of build _83, enabled fadeout, started megaman 2 subtune 2, and fadeout worked just normally
