### ISSUE TITLE
Blue bar at the bottom of the PLAYER-screen in Landscape-Mode

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#295]
Like the title already says there is a blue bar at the bottom of the screen blocking off some of the free screen space. It's not super annoying (I actually don't mind it at all) as you can still read everything but I don't remember it being there before.
![screenshot_20160706-041447](https://cloud.githubusercontent.com/assets/15172856/16605582/8f25630a-4330-11e6-88d8-9355f2d14169.png)
I don't mind it, like I said, but I think it's worth mentioning anyways.

**Comment by droidmjt** [comment]
yeah i know, fixed already, get build 81 from frontpage :)

**Comment by theGIZOID** [comment]
Alright, I close this issue then.
