### ISSUE TITLE
[Best-Implementation Discussion] Volume Normalization in Overall Application

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#296]
So this has been on my mind for a while now, simply because even with the current features available within the application for plugin/song specific volume changes, there's probably a better way to achieve the effect of normalized volumes between songs.

I'm not requesting any specific implementation with this, rather I'm interested in discussing the best way this could be achieved theoretically given the constraints of Android and Droidsound.

From my understanding, Droidsound bypasses the OSes detectable audio stream, meaning that anything like Viper audio or CM's EQ would not apply. Which is fine, since those are flawed by nature anyway. Please correct me if I'm wrong on this specific, though. 

Because of that, any feature for adaptive volume levels needs to come within Droidsound itself. I've experimented with replaygain on desktop programs, but it doesn't seem to work for any chiptunes formats I've tried. So any kind of database storing a listing of volume changes per track after scanning wouldn't work as well. Even if it did, Droidsound would have to spend cycles actually playing the song, analyzing the volume levels, and then writing back the information per track. Depending on the device and library size, that could take a very, very, very long time.

The individual volume sliders per plugin and per song are useful but not optimal. Even within plugins, some songs are much louder than others. SSF, for example. About half the games that have tracks in SSF are anywhere from 5-8db lower in relative volume from the other half of the games. So cranking the plugin volume would either result in distortion for the louder tracks, or still have the volume disparity for the softer tracks. Per song is a good bandaid solution but doing it for every single track requires lots and lots of patience, as well as listening throughout a song to make sure the volumes don't get loud at any point. A per-directory slider might work except you have plenty of soundtracks with different file types that have different loudness points. Again, SSF as example. For a soundtrack with quiet SSF but normal volume MP3/WAV/ADX in the same directory, a per-directory volume implementation would not apply either. 

All of those factors narrow down to something that is implemented in realtime. Something like the R128 Normalizer for foobar where it seeks ahead and does volume changing/gating would be best since the changes are completely on autopilot. I'm not sure what kind of CPU overhead a feature like that would require, though. 

I'd be happy to hear of any other methods I haven't considered since this would be something extremely nice to have, and remove a lot of manual work to make a playlist "perfect" for listening. Nothing breaks up a nice coding/scripting session for me more jarringly than having to turn the volume down because my ear drums suddenly got blasted, or I can't even hear the music on the song its so quiet.

**Comment by jimbo1qaz** [comment]
RG was added recently. Can you try installing the latest DSE (readme.md)? It works on PSF files, probably not AST/BRSTM/etc (internal game stream formats are not supported in fb2k) probably SPC and the like.

**Comment by Level99OCR** [comment]
I have v81 installed, I'll check it out once my database rescans.

**Comment by jimbo1qaz** [comment]
You have to turn on RG in the settings. (The settings panel is a bit messy by now?)

**Comment by Level99OCR** [comment]
Yeah, I found that. I'm not really hearing an audible difference in the majority of the formats I'm playing, though. I remember tinkering with replaygain in foobar, scanning tracks and trying to apply the gain to SPC and VGM, just to have it not take and not work. Maybe I'm doing something wrong? I was under the impression replaygain really did only apply to streaming formats like MP3 and OGG, like, you can't even apply replaygain to WAV files if I remember correctly.

**Comment by droidmjt** [comment]
if you have a file that contains replaygain info but you cannot hear any difference, please send me the file, i'll check it

**Comment by Level99OCR** [comment]
I have confirmed that replaygain does in-fact work for files that contain that info. The problem I was more referring to is for files that, based on their type, do not support replaygain and go through some other method of volume normalization. For example, SPC doesn't do replaygain from my knowledge, but it has in its tags an "amplification" value that can be tweaked. Some files, like NSF, don't support any kind of gain playback information. This is why I was bringing up the idea of volume normalization outside of gain tags to provide a more seamless and "dummy-friendly" way to keep volume levels in check and relative to a central loudness.

**Comment by droidmjt** [comment]
try adding RG info at the end of the NSF file and see what happens :)

**Comment by Level99OCR** [comment]
Welp, closing this until I have a better reason to bring up normalization then!

**Comment by Level99OCR** [comment]
https://github.com/jiixyj/libebur128 Just putting this here in case you're curious, this is the whole easymode loudness thing I was talking about. I'm fine going through the manual process of unzipping all of my files, adding replaygain to everything, zipping them up and putting them back in order to make it work, but eventually if something like this could be enabled in the audio pipe, it would reduce the hassle. Just my two cents!

**Comment by droidmjt** [comment]
yeah I was aware of that stuff, but doing RG loudness scanning on phone, I guess it is fast for modern formats, but for example c64 sids, oh hell

**Comment by Level99OCR** [comment]
lol fair point. I mean, I won't pretend I know the depths of how the readahead algorithm works for loudness scanning or how it would interfere with particular formats, but yeah, that would have been the ideal solution. Maybe one day, when every other bug is fixed and you've added all the higher priority features!

**Comment by droidmjt** [comment]
It's difficult to say what would be the ultimate solution for this. Personally I would never scan a single song with a phone just to get a RG info, i just manually set it in volume setting and thats it.

**Comment by Level99OCR** [comment]
Right, I get that. Under ideal conditions, I would do the same. I have four caveats to that though:

1) I don't trust my own ears sometimes. And while it can be set on a per song level, sometimes its very finicky to get it just right and having to do that for every song if you have a massive collection is nearly impossible. RG is unbiased so its a nonissue there.
2) It can't be done in certain situations. The most glaring example I have would be listening to the MDScene VGM Arcade library while driving. Loaded that into a playqueue yesterday for my drive home, and I swear song to song could be as big as 15db difference. Since its on shuffle, I wouldn't be able to set it for every song in that game easily on hand. Not that it would be possible anyway because I definitely shouldn't be tinkering with those settings while driving a moving car. Having to constantly turn up and down the volume there is an additional distraction. Again, here, RG would/will be a help.
3) It doesn't stick through a clean install. RG would stick through a clean install, though.
4) This is the one that RG doesn't do: within-song loudness compensation. There are some video game songs, mostly orchestral but I think there are examples in most genres, where sections of the song are much, much quieter than the rest. Some developers did this manually during dialog scenes for voices to be heard without changing the volume in-engine, or implementing any kind of sidechain compression. R128 style loudness dynamically compensates for that.

As it stands, I'll spend the next couple of days tinkering with RG once I get the library stuff extracted. I'm curious mostly about the older chip formats, specifically ones that have subsongs that may have different loudness for each. 

Regardless, thank you for actually engaging in this dialog. It is very helpful from both a user and a developer perspective.
