### ISSUE TITLE
[Issue] Delete functionality not deleting file from device

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#297]
This function was implemented a while ago, but the new permission system either in Lollipop or in Marshmallow has partially broken it. If the songs are on the external SD card, deleting a file/archive only removes the entry from within the Droidsound database. The file still exists on the external, and doing a rescan of the directory within Droidsound readds the entry.

I know other applications I've used required a new step in 5.0/6.0 Android to have access to R/W for external storage using a method called DocumentProvider storage (titanium backup mentions that function by name, not sure if its called anything else). The user is prompted to a screen that shows recent files but can enable an option to display onboard/external storage, and select the external storage in order to give the requesting app full access to it. Here's Google's info on it: https://developer.android.com/guide/topics/providers/document-provider.html

As always, thanks for your time and efforts.

**Comment by droidmjt** [comment]
bugger, I'll investigate this more

**Comment by theGIZOID** [comment]
If you do so please add an option too where you can remove the entry in the DB-Browser only.

**Comment by droidmjt** [comment]
@theGIZOID i need more info about your request

**Comment by theGIZOID** [comment]
I actually thought it was intentional that the delete function only removed the file from the DB-Browser but I also forgot how different 5.0/6.0 handles sd-card permissions compared to older Android versions.

What I mean is a feature that removes selected files from the DB-Browser without deleting them from the device itself so that you can get the file back into the DB-Browser when re-scanning the directory.

**Comment by Level99OCR** [comment]
What would probably be more efficient and less sloppy codewise would be to split up those functions, then. One function, called "delete", removes the file/folder/whatever from the storage permanently. Another function, called "hide", can hide an already scanned entry from the viewable db browser or whatever. This would require no rewrites to the scanning and you won't burn cycles if the rescan is accidentally run.

**Comment by droidmjt** [comment]
once i get my rooted phone back, i'll get this fixed. I will add a switch for a delete function so that it can delete from DB-only or from both location

**Comment by droidmjt** [comment]
i cannot get this fixed until next month so close this case for now, I have this on my todo list anyway.

**Comment by Level99OCR** [comment]
Closed for now
