### ISSUE TITLE
[UI Change Request] Different color for song seek/length bar when unable to seek

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#298]
Some file formats in Droidsound are seekable, and some aren't. There's no real way to distinguish this from looking at the Player tab, except by trying to slide the dot on the seeker bar and seeing what happens. If it can't seek, it will begin to slide between screens. This is a tiny bit annoying in how to figure out if you can go to a later portion of a track, so I would request the seeker bar be a different color than blue if the song is not seekable. Red, or white with a black outline; basically something to indicate that "no, you can't get to a later part of the song".

Also, tiny request to increase the touch detection area for seeking a song anyway. I have fat fingers and more than half the time my finger misses the precise dot area when I want to see. Not a huge increase, but an increase would be appreciated provided it doesn't overlap the other controls.

Thanks!

**Comment by droidmjt** [comment]
this should be easy fix, I just disable the seekbar when seeking is not possible. I'll increase the seekbar area, no problem.

**Comment by droidmjt** [comment]
this is fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/dqgf1yd8c9yrnb6/droidsounde16647_82.apk?dl=0

**Comment by droidmjt** [comment]
I also increased the sensitivity area of the seekbar, let me know if it needs more adjusting.

**Comment by Level99OCR** [comment]
Beautiful, works exactly as I imagined. Closing, thanks!
