### ISSUE TITLE
[Issue] Doing "new playque" from playlist that contains subfolders of zips renders device unusable

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#299]
Haven't done a lot of permutation testing on this one yet, but basically, if I add a directory that contains multiple compressed files in it, and then try to make a playque from that playlist, Droidsound becomes a CPU hog and basically makes my phone unusable until I reboot it.

Tested on latest build 81. Initially tried to make a playque from playlist of all of my Playstation musics, and then tried to make a playque from playlist containing just the A folder of my Playstation musics. Same result each time: the notification bar freezes, then a minute later the phone locks screen because the launcher crashed, then the lock screen is so sluggish I can't actually get back into my phone. I let the device sit for 5 minutes to see if it was just taking a long time to queue up the music, but nothing ever played and it never resolved itself.

PS Sorry for the flood of tickets on GitHub. When it rains, it pours :p

**Comment by droidmjt** [comment]
so for example /sdcard/Music containing music1.zip, music2.zip and music3.zip and you want to create a playqueue of those, correct?

**Comment by Level99OCR** [comment]
Yes, but as far as I can tell, this is only if the playqueue is being created from a playlist file, and not from a filebrowser or other such source.

**Comment by Level99OCR** [comment]
Tested further by adding one level up parent directory when adding my music to the application. Normally I add them on a per-system basis and then add each Alphabetical subfolder to its own playlist for the system. This time I did one above so that I could directly try doing a playqueue from an entire system's directory. Doing a playqueue from the directory itself works exactly as intended, and loads a playqueue in 10-15 seconds even for a directory containing a ton of subfolders. I think it is just the "New Playqueue" action being done from any kind of playlist that isn't just files (that it has subfolders) that is causing the issue.

**Comment by droidmjt** [comment]
how many files do you usually queue when you listen something?

**Comment by droidmjt** [comment]
Im not able to reproduce this no matter what. I have 3 zips, PSF.zip, 2SF.zip and USF.zip, they are all in /sdcard/droidsound/dsroot/MyMusic folder, after rescanning, I added that folder to my playlist (favorites.plist) and started creating new playqueues from various folders, no crash, I wish I could make it crash so I could fix your problem.

**Comment by droidmjt** [comment]
my PSF.zip has folders 0-9, A, B and so on.

**Comment by droidmjt** [comment]
>>  I think it is just the "New Playqueue" action being done from any kind of playlist that isn't just files (that it has subfolders) that is causing the issue.
I'll try that, I missed that completely.

**Comment by droidmjt** [comment]
Here is my setup, favorites.plist has the following tree inside:

[DIR]  MyMusic/
[ARC]  MyMusic/2SF1
[ARC]  MyMusic/PSF
[ARC]  MyMusic/USF

each of those archives contains folders like 0-9, a, b and under those folders there are the real music folders with game names/blabalbla.psf for example.

I created new playqueues of the favorites.plist (root), MyMusic and each of those archives separately and also separately of the alphabet folders, no problems. If I missed something, let me know.

**Comment by droidmjt** [comment]
I try your instructions

**Comment by droidmjt** [comment]
excellent, it crashes, fixing time

**Comment by Level99OCR** [comment]
Only developers get so excited about having an application crash, lol. Good luck!

**Comment by droidmjt** [comment]
do you think it makes sense to add a limit to the queue size? for example 1000 or 2000

**Comment by Level99OCR** [comment]
Personally, I'd prefer not, or setting it to some massive limit to reasonably keep the application from being stupid and grabbing tons and tons of memory just as a safety measure. As it stands, there isn't a limit on the playqueue, right? Unless it is part of a requirement to fix the playlist-to-playqueue issue, I'd really like to avoid putting a cap on how many songs can be queued up. 

Just to give you an idea, my personal use case for the playqueue feature is for long drives, coding marathons, and exercise sessions. Right now, I will queue up an entire system's library of songs and put it on shuffle, and for some systems that file count can be very, very large. Being able to get all the Sega Genesis music in a shuffle mode and skipping tracks that don't fit the current mood is incredibly valuable to me. I wouldn't want to place a limit on that, obviously.

**Comment by droidmjt** [comment]
There is no limit at the moment, I was just concerned about the memory usage.

**Comment by Level99OCR** [comment]
I'll do some testing with a low-ram device to see if massive playqueues gunk up the works. 1gb is standard these days, will also see if I can get my hands on a 512mb as the lowest possible consideration for a Droidsound-viable device.

**Comment by theGIZOID** [comment]
I could test this on my old Sony Ericsson Xperia Pro. It has 512 MB of RAM so I could do that if I am able to find it.

**Comment by Level99OCR** [comment]
That could definitely work. I would recommend a large library of small sized songs either in their own directories or in a single zip, without subsongs. Something like Genesis or Arcade VGMs, since they compress extremely well but uncompressed are large and would comprise numerous amounts of files. The larger the amount of files in the playqueue for testing, the better.

**Comment by theGIZOID** [comment]
So after finding and preparing my phone I finally got to test things.
NOTE: Unfortunately, I don't have many Genesis VGMs and no Arcade VGMs at all. All songs are compresed in zip files (except for SPC, they are in their RSN archives). Also, my Genesis VGMs are saved as VGZ files using OptVGM to decrease filesize drastically.

I've tried adding as many files as possible, ranging from VGMs, SPCs, GSFs, 2SFs and so on. I've eded up with over 3000 files on my playlist. It took some seconds to set it as a new playqueue but everything was fine after that. I had no memory issues.

**Comment by Level99OCR** [comment]
If that's the case, then no, should not put a limit on playqueue size.

**Comment by Level99OCR** [comment]
I also have tested on my 1st gen Moto G with the entire DS music library, which is gargantuan, and had no issues making a new playqueue from that on a device with 1gb of ram. It took about 10-15 seconds to load a playqueue and it ran very smoothly.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bmpbuded4nlafdq/droidsounde16647_84.apk?dl=0
hopefully fixed now

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/dierlwxaq8o1dnp/droidsounde16647_85.apk?dl=0
small bug fixed

**Comment by Level99OCR** [comment]
Seems to work great so far, thanks!
