### ISSUE TITLE
Notification control buttons are too small to press easily

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#300]
In v78, you added new buttons to the DSE notification, to allow lock screen playback control. In v81, you shrunk the new buttons significantly. As a result, they are too small and closely spaced to press easily. Can you revert the changes?

v78 expanded: https://cloud.githubusercontent.com/assets/913957/16666722/cf2378da-443d-11e6-9d3f-0f6588091941.png
v78 collapsed: https://cloud.githubusercontent.com/assets/913957/16666723/cf286e80-443d-11e6-88b6-bb2dfdc59e74.png
v81 expanded: https://cloud.githubusercontent.com/assets/913957/16666724/cf2acb80-443d-11e6-95ca-784f0ea3d570.png
v81 collapsed: https://cloud.githubusercontent.com/assets/913957/16666725/cf2b97c2-443d-11e6-9849-bd69dec54881.png

Changing the expanded notification has no benefits, as far as I know.

Changing the collapsed notification *could* increase the space for the song name, but the space is minimal and probably isn't worth the decreased usability.

**Comment by droidmjt** [comment]
ah, they are same sized icons but they are just not using all the space of the area, I'll make it like they were before

**Comment by droidmjt** [comment]
this is fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/dqgf1yd8c9yrnb6/droidsounde16647_82.apk?dl=0

**Comment by jimbo1qaz** [comment]
The "collapsed" buttons are still too small. Did you not change them?

**Comment by droidmjt** [comment]
oh crap, forgot that one, I'll change those later today

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/cx065jzl6ickoy3/droidsounde16647_83.apk?dl=0
see if its any better now

**Comment by jimbo1qaz** [comment]
Still broken I think.

**Comment by Level99OCR** [comment]
Hmm, the collapsed buttons look fine size-wise to me. I can upload pictures later of my lock screen to show but maybe your device is doing some weird DPI scaling that is making the buttons appear too close together?

**Comment by droidmjt** [comment]
I have adjusted those but i havent uploaded the build yet, just finished with the playqueue thing earlier

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bmpbuded4nlafdq/droidsounde16647_84.apk?dl=0

**Comment by droidmjt** [comment]
shit, still something wrong, i fix it now

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7x9lk6ktdfg3j1j/droidsounde16647_86.apk?dl=0
fixed

**Comment by jimbo1qaz** [comment]
Seems to be fixed. What did you change for expanded/collapsed?
