### ISSUE TITLE
Music cutoffs in non-stop mixes separated in multiple tracks

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#301]
So I have ripped music from a music CD that plays music non-stop, all tracks blend into each other, like non-stops do. However, if I seperate the songs in tracks the end of the current song cuts off and the next one starts with a little delay. So I re-ripped the music CD but this time as an image + cuesheet. It worked a little better, but it still cuts of the music at the end of each track but does not delay the next song. So I removed the cuesheet and played the image alone. It worked, but now I have a single, gigantic file with a total length of 48:07 and it's painful to jump to a specific track using the search bar.

So I suggest something like a feature letting the next track prebuffer so that songs can blend properly into each other. Listening to a non-stop mix with hiccups is no fun and so is searching for a speciffic song in one single gigantic file.

**Comment by Level99OCR** [comment]
I believe the term you're looking for is "gapless playback".

**Comment by theGIZOID** [comment]
Ah, gapless playback, yes, thank you, that was indeed the term i was looking for :*)

**Comment by droidmjt** [comment]
is it enough if i make gapless when using CUE files?

**Comment by theGIZOID** [comment]
Yes, this should be enough, but I'd appreciate it if you could do both.

**Comment by droidmjt** [comment]
don't expect this to be ready any time soon, I don't even know how to implement this :(

**Comment by theGIZOID** [comment]
It's okay, take your time :)

**Comment by droidmjt** [comment]
Whats the easiest way to create .cue sheet for multiple mp3 files? If you have some easy tools to create cue sheet for audio files, let me know. This feature is nearly finished.

**Comment by theGIZOID** [comment]
I usually rip my music from audio CDs using cuetools. It creates them automatically after finishing the rip, but I think that you can also create cuesheets manually using the very same programm, but I am not sure though.

**Comment by droidmjt** [comment]
yeah I tried cuetools and found the option but all I get is an error about file not being part of an album

**Comment by theGIZOID** [comment]
Try cueripper, this should be within the cuetools package.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nhnzo5saydyfke7/droidsounde167_09.apk?dl=1
I hope the gapless feature is like you wanted. You need to enable it from settings first tho. 
See Settings -> Audio -> BASS

**Comment by theGIZOID** [comment]
Thanks a lot, gapless playback works properly, however, it gets a bit messy when trying to change the track number. Whenever a track is finished it does properly play the next song gapless, however, it does not change the track name and the number. Also the counter just keeps on going and doesn't stop for anything.

Furthermore, when trying to skip to the next track it just skips a few seconds and continues on playing.
This, however, might be because I am playing back a whole a whole image file (one music file and one cue sheet) instead of seperate tracks. I need to confirm this first though.

**Comment by theGIZOID** [comment]
Yep, using one image file and a cue sheet results into glitchyness as described above. Using cue sheets with seperate tracks results into glitched ID3-tag displays only (it always shows the name of the first song in the list). Playback single files without cue sheets works perfectly. I can live with that. Again, thanks a lot 👍

**Comment by droidmjt** [comment]
cue + one image file used to work, i get it fixed :)

**Comment by theGIZOID** [comment]
Also, it looks like the notification bar broke as well. It doesn't update the current track when gapless playback is enabled.

**Comment by droidmjt** [comment]
fixed the one image + cue thingy, the notification is not broken actually, I just forgot to send updates to it :)

I'll upload new binary later today.

**Comment by droidmjt** [comment]
email me one of those songs that freeze, I'm not able to reproduce it after all

**Comment by theGIZOID** [comment]
Hmm... might be an error on my end. It happens at every single song without looppoints, no exception. I am going to re-install DSE completely and try again.

**Comment by droidmjt** [comment]
wait for the new binary

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/kzia04wc3jnfvvf/droidsounde168_10.apk?dl=1
let me know how it works

**Comment by theGIZOID** [comment]
Re-installed and tested, everything works as expected, image + cue files are fixed, the notification bar updates the songs and endless loop does no longer freeze on songs without loop points. Everything is right again. Thanks a lot.
