### ISSUE TITLE
[Issue] Playing .TXT file crashes Droidsound

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#302]
For some reason, Droidsound lists .txt files whenever it does a filescan for its database. Trying to play a .txt file crashes the app, so they either shouldn't be listed or should be automatically skipped before attempting to identify the file for the appropriate plugin to play it with.

**Comment by theGIZOID** [comment]
Thats funny. I remember that DSE skipped .txt files and just played the next song after a .txt.

**Comment by Level99OCR** [comment]
Not sure if its because of explicitly playing but I made a playqueue that included some and it crashed because apparently they were all queued up.

**Comment by theGIZOID** [comment]
It will also crash when selected from the file browser. And I swear that this did not happen in older builds. It just skipped the .txt and played the next file in the directory/playlist.

**Comment by droidmjt** [comment]
i need to get the same .TXT file you have that causes the error. TXT is a valid format extension and cannot be skipped.

**Comment by droidmjt** [comment]
this is fixed, small bug eventually, thanks to my recent changes :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/dqgf1yd8c9yrnb6/droidsounde16647_82.apk?dl=0

**Comment by Level99OCR** [comment]
I grabbed 82 and 83, since additional updates in 83. Testing this with 83. The good news is that indeed it does not crash anymore. The bad news is that it is now affecting playqueue/playback. 

Trying to add a playqueue or start playback of a folder/zip that contains an "invalid" txt (I'll explain further down) stops playback entirely. Nothing will play, nothing will move, you can even quit the app and reopen it and it'll be as if the instance never closed (does not check for orphans even after Force Stopping the app, probably isn't also force stopping the player service). Only after selecting a song in a folder that does NOT contain a txt file does any music start to play.

The reason I'm quoting "invalid" is that I'm not sure what constitutes a valid TXT file for playback. TXT typically is just a plaintext document, some of which are bundled with various gamerips supplying information on the rip or credits or whatever. These mainly affect playback of stuff from MDScene's Arcade Rips, since nearly all of those games have a TXT file next to the actual music files. So, for example, if I open up the MDScene rip of the arcade game G.I. Joe - A Real American hero, who's file contents are a bunch of VGM files and a single TXT file, and try to play back any VGM file, nothing will play because the TXT file is in there.

So improvement: TXT file doesn't crash the app now. But now a whole bunch of files aren't able to be played.

**Comment by droidmjt** [comment]
i have a folder named SPC that contains several folders and those folders contain .txt file and I am able to create playqueues just fine.

**Comment by droidmjt** [comment]
i download the same file and see how it goes

**Comment by Level99OCR** [comment]
Okay, I'll see if I have anything else that does it as well. Very strange.

**Comment by droidmjt** [comment]
couldn't find the file but i used another from Arcade folder, no go, I used R-Type instead, even if i click the .txt file nothing happens, it just goes to next file and plays. I copied the archive to /sdcard/droidsound/dsroot/VGM, used DB browser, scanned, no probs.

This is the worst part in development, failure to reproduce :(

**Comment by Level99OCR** [comment]
No worries, appreciate you checking it out. I'll do a clean install to see if that changes anything as well, keep you posted.

**Comment by Level99OCR** [comment]
Okay, clean install on x86 seems to work as intended. I have to give my G4 away for a couple days so I will test again with that when I can and will reopen this if needed. Thank you very much, as usual.
