### ISSUE TITLE
[Issue-SongCrash] * song crashes Droidsound

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#303]
Creating an issue that can be closed and opened as needed for reports of songs crashing DroidSound for various revisions. 

Version: Droidsound E 1.6647 Build 83
Game: Skies of Arcadia
System/Filetype: Dreamcast (DSF)
Source: joshw.info
Song(s) that crash: All
Additional Info: Playing any song crashes the app outright. Other dreamcast games work.

Please use the above as a template for reporting additional files that crash.

**Comment by droidmjt** [comment]
in cases like this, always include the source of the music, it helps :)

**Comment by droidmjt** [comment]
luckily i have skies of arcadia, lets see

**Comment by droidmjt** [comment]
lol, so this wasnt a real problem was it?

**Comment by droidmjt** [comment]
ok, got crash here, but it works if you don't archive the files, i'll check it

**Comment by droidmjt** [comment]
fixed

**Comment by Level99OCR** [comment]
If you wouldn't mind, whenever a game is fixed for playback, can you include build/version number so that we have a record of which version things should be working in? It will help track regressions down the line.

**Comment by droidmjt** [comment]
yeah sure, v1.6647 build 84 will fix this one.

**Comment by Level99OCR** [comment]
Awesome. Two new ones to report, I'm going through all my PSF files since adding the directory to playqueue and putting it on random a lot of FCs, so there will likely be more as the day goes on.

Version: Droidsound E 1.6647 Build 83
Game: Ape Escape
System/Filetype: Playstation 1 (PSF)
Source: joshw.info
Song(s) that crash: All
Additional Info: Playing any song crashes the app. Many other PSF and MINIPSF work.

Version: Droidsound E 1.6647 Build 83
Game: Aqua Paradise - Boku no Suizokukan
System/Filetype: Playstation 1 (PSF)
Source: joshw.info
Song(s) that crash: All
Additional Info: Playing any song crashes the app. Many other PSF and MINIPSF work.

Version: Droidsound E 1.6647 Build 83
Game: Atelier Elie - Salberg no Renkinjutsushi 2
System/Filetype: Playstation 1 (PSF)
Source: joshw.info
Song(s) that crash: All
Additional Info: Playing any song crashes the app.  Atelier Elie - Salberg no Renkinjutsushi 1 works.

Version: Droidsound E 1.6647 Build 83
Game: Azito 3
System/Filetype: Playstation 1 (PSF)
Source: joshw.info
Song(s) that crash: All
Additional Info: Playing any song crashes the app.  Azito 1 and 2 work.

Will continue building a list of specific games but maybe this is just a big PSF bug? I vaguely recall kode54 saying the plugin had been updated a bit ago to be more accurate and wouldn't play specific rips that didn't conform to standards or something, though that could have been specific to the PSF2 playback since the game in question then was FFX.

**Comment by droidmjt** [comment]
I believe the fix i made will help with these also, do these use additional library file or files ?

**Comment by Level99OCR** [comment]
They do include a number of PSFLIB files, yes. In fact, all the ones I listed have two or more PSFLIB files.

**Comment by droidmjt** [comment]
clear case, i think the fix i made will fix these, i'll test these later today

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bmpbuded4nlafdq/droidsounde16647_84.apk?dl=0
try and see how it works

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/dierlwxaq8o1dnp/droidsounde16647_85.apk?dl=0
here is newer build, found some small bug in PLAYLISTS view, no big thing

**Comment by Level99OCR** [comment]
testing today, should I do a clean install or dirty upgrade?

**Comment by Level99OCR** [comment]
Did a dirty upgrade, Skies and Azito 3 work just great on v89. Thanks!
