### ISSUE TITLE
Midi stuff

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#304]
They are playing very fast!ALL of them...

**Comment by droidmjt** [comment]
what MIDI player?

**Comment by crimson1117** [comment]
Bass

**Comment by droidmjt** [comment]
and what build number? also send me few midi files that fails, I just tried with some standard midi files using BASSMIDI + common soundfont and no problems. I haven't changed the MIDI plugin for a long time. If the problem would be elsewhere it would affect other formats also.

**Comment by crimson1117** [comment]
ok I know...maybe my feeling is wrong,sorry.
