### ISSUE TITLE
[Plugin Updates] vgmstream, highlytheoretical, gameemuplayer plugin updates

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#306]
In July, a number of plugins got some major updates that should be pushed to Droidsound. VGMStream, Highly Theoretical, and GEP all got stuff fixed in them, especially HT in regards to Dreamcast playback. If not already done so, requesting their updates be pushed into the next version of the app.

**Comment by droidmjt** [comment]
vgmstream done already, i can update the rest

**Comment by Level99OCR** [comment]
Fantastic!

**Comment by Level99OCR** [comment]
Just FYI the updated plugins seem to be working a charm. Shenmue music inparticular is not ear-grinding nightmares half the time anymore.

**Comment by droidmjt** [comment]
great, good to hear
