### ISSUE TITLE
ReplayGain not supported in archives (7z)

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#308]
Nexus 5x, CM13 6.0.1, DSE v87:

It seems that files stored in archives do not have ReplayGain applied.

I tested 7z archives with SPC and PSF files. Neither had the RG bubble filled.
Bare SPC and PSF files have working RG.

**Comment by droidmjt** [comment]
good find, I was storing wrong filepath :( Now it's fixed.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/kwdnrmub2bdjum7/droidsounde16647_88.apk?dl=0
it should work now
