### ISSUE TITLE
Compressed file formats missing in filebrowser

### ISSUE THREAD

**Issue by TeamFail** [droidmjt/Droidsound#310]
First off, THANK YOU SO MUCH for adding a proper file browser to DSE. It's so much more convenient than having to build up a database every time I add new audio files, which is actually super CPU-intensive, so this will perform much better on my old phone whenever I need to use it.

However, it seems that file formats that are compressed (.7z, RAR, RSN, ZIP, etc...) are missing from the file browser, which is annoying because then I either have to maintain a database still to find them or extract them using a file browser on my device, which wastes space since I have two copies of the audio files on my device at that point. I know I'm not the only person to have this issue ([See here](https://twitter.com/VinsCool022/status/755134929185476608)), so perhaps is this just a bug, or is this intentional?

Edit: Should mention this is the version on the Google Play Store currently. I haven't used any of the newer builds, and if this was fixed in the newer builds, feel free to disregard this.

**Comment by droidmjt** [comment]
When I first time implemented the file browser, the plan was to support archives to, I even started coding it, but for some reason there were troubles with it. I can try again to implement it. You better start using the dropbox version, GP won't get any updates :)

**Comment by TeamFail** [comment]
Kinda bummed to hear that the GP version will be not updated, but I guess I've missed out on a lot by not getting the latest versions here. Anyways, I have gone and updated, and I do hope to see you sometime finish support for that.

**Comment by droidmjt** [comment]
this is done, the only problem left is the initial scan for archives that contain +20000 entries, will upload new binary after I have fixed some other problems. Supported archives: 7z, rar, zip, rsn, lha.

**Comment by droidmjt** [comment]
oh hell, found problems with 7z archives, zip and the rest seems to work fine

**Comment by droidmjt** [comment]
7z bug found and fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/3zrq5i5ycwv72hh/droidsounde16647_93.apk?dl=0
check it out and report bugs

**Comment by droidmjt** [comment]
#314 and #313 should be fixed in that build also

**Comment by TeamFail** [comment]
This one seems to be working nicely now. Thanks!

**Comment by droidmjt** [comment]
test carefully :)

**Comment by jimbo1qaz** [comment]
I can't open 7z archives in the file browser

I have a bunch of 7z files created using Linux command-line. When I try opening them, File Browser skips through all archives, and ends up playing a mod file I have in the same folder.

**Comment by droidmjt** [comment]
post one here and i check it

**Comment by jimbo1qaz** [comment]
I'll post some archives later. I'm away from my main PC.
____
Also, filebrowser shows all file extensions. They're a bit distracting? Foobar2000 puts them in a separate column. But that's not exactly practical on a mobile UI.

Also, foobar2000 has a media library feature, that recognizes filesystem changes almost instantly, I assume with some sort of filesystem watch that doesn't work under Linux Wine.

DSE need a full rescan to recognize any changes whatsoever.

**Comment by droidmjt** [comment]
filesystem observer would help in that case

**Comment by jimbo1qaz** [comment]
Media Library requires full rescan, filesystem is instant.

Is it practical to scrape metadata using the filesystem explorer, or is that only possible in Media Library?

Does Media Library use SQL path database, and filesystem use Android list directory without caching?

**Comment by droidmjt** [comment]
Media Library uses SQL and list directory uses Android list directory without caching. A little caching is done when browsing archives with filesystem browser. MediaStore uses also SQL and it doesn't require rescans, only a re-enter to a folder and its updated. The only problem with MediaStore is that it recognizes only certain formats. The only way to achieve nearly instant updates is to use plain files and filepath observers.

**Comment by jimbo1qaz** [comment]
Sample archive of SPC: https://dl.dropboxusercontent.com/u/34131225/zelda-lttp.7z

yes this is the same as https://github.com/droidmjt/Droidsound/issues/315#issuecomment-237130639

**Comment by droidmjt** [comment]
can't reproduce, the archive works fine here, tested with emulators and real device

**Comment by jimbo1qaz** [comment]
I just reset settings, still get the same bug.

**Comment by droidmjt** [comment]
The only thing I can do here is wait my CM13 phone back and test the feature with it.

**Comment by jimbo1qaz** [comment]
foobar2000 prints an error log whenever a file can't be read (and is
skipped). Do you want to implement something similar? Logcat? Replace
white/blue metadata text with error log (and disable autoskip unplayable)?

**Comment by droidmjt** [comment]
send me logcat log of this problem, I'll see if the clears anything

**Comment by droidmjt** [comment]
found the problem, oh hell

**Comment by jimbo1qaz** [comment]
Do you have a download with the fix?

**Comment by droidmjt** [comment]
not yet

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2b0r49hzjklwjjd/droidsounde16647_96.apk?dl=1

**Comment by jimbo1qaz** [comment]
Still doesn't open archives. Also, maybe you should rename new "local folder" to "new folder". This was rather confusing for me, even though the dialog title says "new".

**Comment by droidmjt** [comment]
I found the problem now, it seems to happen with filesystem browsers created manually.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/0jlr5qie1p4ltve/droidsounde16647_97.apk?dl=1
try this

**Comment by jimbo1qaz** [comment]
yeah works
