### ISSUE TITLE
BASSMIDI crashes

### ISSUE THREAD

**Issue by hoodlum47** [droidmjt/Droidsound#311]
Hi, just wanted to let you know that on the latest build (90) whenever I try to play a midi through BASSMIDI it immediately crashes the app. I have tested several midis and the other midi plugins and BASSMIDI is the only one that crashes the player.

**Comment by droidmjt** [comment]
its fixed now, one line logic error i forgot to fix earlier, i'll upload new binary very soon

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/304efs4acz0y13p/droidsounde16647_91-release.apk?dl=0
there

**Comment by hoodlum47** [comment]
Thanks, this build fixed the issue.

**Comment by droidmjt** [comment]
use this instead: https://www.dropbox.com/s/mqki8fszsvslcvj/droidsounde16647_92.apk?dl=0

**Comment by hoodlum47** [comment]
Oh ok, did you happen to break something else in the process?

**Comment by droidmjt** [comment]
had to fix something else also and left a typo behind, should have been "/system..." instead of "/1system..."

**Comment by hoodlum47** [comment]
Ah gotcha, I'm not a coder, but it is my understanding these little slip-ups happen often.
