### ISSUE TITLE
[Issue] App does not scan when adding new DB Browser

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#312]
Build 92. When I try to create a new DB Browser entry in dsroot it does not properly scan (or does not scan at all?) and cannot find my .zip files.

**Comment by droidmjt** [comment]
what is the target path?

**Comment by theGIZOID** [comment]
Bummer. I tried a clean install and it does work again x)
Sorry, case closed.

**Comment by droidmjt** [comment]
if the target path is /sdcard/droidsound/dsroot, you should use another path

**Comment by droidmjt** [comment]
I will prevent that in future builds, it may bring unwanted behaviour

**Comment by theGIZOID** [comment]
It did not mater where the path was. It just was too stubborn to read anything for some reason.
