### ISSUE TITLE
[Issue] Audio fade: "Append fadeout length" affects excluded file extensions

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#313]
Pretty much what the title says. The music does not fade but the fade out length is still being added as long as audio fade is enabled.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/3zrq5i5ycwv72hh/droidsounde16647_93.apk?dl=0
check it out and report bugs

**Comment by theGIZOID** [comment]
Does work like intended, thank you very much :)

**Comment by droidmjt** [comment]
no problem :)
