### ISSUE TITLE
"Reset preferences" confirmation?

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#314]
I discovered I lost all my settings in DSE. My guess is because I accidentally hit the "reset preferences" button at some point. Can you add a confirmation dialog?

Also, the "reset preferences" toast uses a different font from other toasts.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/3zrq5i5ycwv72hh/droidsounde16647_93.apk?dl=0
check it out and report bugs

**Comment by jimbo1qaz** [comment]
Also can you link to ?dl=1 ? That produces a direct link, and requires less clicks on desktop and mobile.

Do you think putting files in a Dropbox/Public folder is a good idea? That allows people to take their existing URL, then just change the number at the end.

Why do you have two version numbers in a row anyway?

**Comment by droidmjt** [comment]
first is the version number second is the build number. I can add the dl=1 link.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/3zrq5i5ycwv72hh/droidsounde16647_93.apk?dl=1

**Comment by jimbo1qaz** [comment]
why are there so many builds with the same version number? did you stop incrementing the version? is that incremented only for Google Play?

**Comment by droidmjt** [comment]
I will change it to next one soon

**Comment by jimbo1qaz** [comment]
Preferences are reset properly, but app crashes when I hit OK.

**Comment by droidmjt** [comment]
send crashlog

**Comment by theGIZOID** [comment]
It also crashes when resetting RG-settings.
I have sent the crashlog via E-Mail.

**Comment by jimbo1qaz** [comment]
possibly related: I lost RG status in non-archived files. Or is it an unrelated bug in PSF files?

**Comment by droidmjt** [comment]
ah a bug in a toast thing, but it doesn't crash here, no matter what I reset, i check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/rme1f44w6n6wwoc/droidsounde16647_94.apk?dl=0
changed something about the toast thing try this

**Comment by theGIZOID** [comment]
Tested, it does no longer crash on my side and properly displays the toast message.

**Comment by droidmjt** [comment]
great
