### ISSUE TITLE
ReplayGain not supported outside of archives

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#315]
DSE v93, CM13, Nexus 5x.

*The first autocomplete when I typed ReplayGain in the "title" box... "ReplayGain not supported in archives (7z)"*

This time... however, ReplayGain information isn't loaded properly in bare files.

I normally store SPC files in 7z archives, because they share lots of data. When I extracted them, RG stopped working (the indicator becomes empty).

I normally store PSF files in folders, because they don't compress well. When I archived them in 7z, RG started working.

**Comment by jimbo1qaz** [comment]
Sample archive of SPC: https://dl.dropboxusercontent.com/u/34131225/zelda-lttp.7z

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/eecmwjfcm37serg/droidsounde16647_95.apk?dl=1
should have tested this better earlier, now I tested it and works with and without archiving

**Comment by jimbo1qaz** [comment]
Fixed.
