### ISSUE TITLE
[UI Change Request] Allow Any Numeric Field to be Modified Via On-Screen Keyboard

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#316]
Allow me to explain.

There are particular settings in Droidsound E that are controlled via slider (plugin/song volume settings, length of song/fadeout for creating ringtone). I would also like the ability to press on the number itself and manually key in the data, since the slider can be a bit finicky. Being able to easily zero-out a plugin or song volume as opposed to spending a few minutes trying to get the slider exactly to 0.0, or being able to easily get to 3 or 5 or 15 or 30 seconds ringtone length would be much more of an enjoyable experience.

Hopefully not too difficult of a change.

**Comment by droidmjt** [comment]
I'll add buttons to fine-tune the values.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2b0r49hzjklwjjd/droidsounde16647_96.apk?dl=1

**Comment by droidmjt** [comment]
leave a message, i think this works fine

**Comment by Level99OCR** [comment]
Works fine, sorry for lack of updates. Appreciate the implementation and work!
