### ISSUE TITLE
[Playqueue Behavior Change Request] Allow Parent DB Broswer source to be turned into a playqueue/added to playlist

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#317]
Right now, anything underneath a parent DB Browser source has all the options for adding to playqueue, making into new playqueue, adding to playlist, etc. However, the DB Browser itself can't do that. The only options are Delete or Rescan (Full). Since I have added all my systems by folder as DB Browsers themselves (I have one just for DS, for example, it helps cut down on add/rescan time should something change in them, and I shuffle files around a lot), being able to add those DB Browsers as a playqueue, making a new playqueue from them, or adding to current playlist would be most helpful.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2b0r49hzjklwjjd/droidsounde16647_96.apk?dl=1
see if it works

**Comment by Level99OCR** [comment]
Will grab this evening and give it a run in the downtime, thank you.

**Comment by Level99OCR** [comment]
Works like a charm! Thank you!
