### ISSUE TITLE
VGMPlugin needs to be updated

### ISSUE THREAD

**Issue by danylopez123** [droidmjt/Droidsound#318]
Your current version is 0.40.6
The newer is 0.40.7

I dont know many changes about it, but the only thing i noticed is that the sound chip C352 is fixed, fixes the swapped left and right channels

**Comment by droidmjt** [comment]
done

**Comment by danylopez123** [comment]
Thanks, but when you are goin to release the new version? I still didint saw the link for the updated one

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2b0r49hzjklwjjd/droidsounde16647_96.apk?dl=1
I'm still testing stuffs but if you can't wait, use the link above.

**Comment by danylopez123** [comment]
Oh, sorry for bothering you

**Comment by droidmjt** [comment]
if it works, close this case

**Comment by danylopez123** [comment]
It does, closed
