### ISSUE TITLE
Library doesn't get scanned on sdcard

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#319]
I had no library scanning problems with any device/android version so far but recently I got a new Galaxy S7 (Marshmallow) and it simply refuses to scan anything outside internal storage even though I can navigate manually to the files/folders themselfs. I noted that the sdcard gets mounted with a weird name by the OS which I bet it's the reason it doesn't get recognized.
system/storage/6362-6536

6362-6536 is the sdcard root

**Comment by droidmjt** [comment]
What is the version you are using? Try the latest version below.
https://www.dropbox.com/s/2b0r49hzjklwjjd/droidsounde16647_96.apk?dl=1

**Comment by VIRGINKLM** [comment]
Yep, latest, I wouldn't dare to make an issue while not being on latest version. :)

**Comment by droidmjt** [comment]
Well, I just tried the latest version with CM13, the phone has an external SDcard on path /storage/9016-4ef8/ and under that I have a folder full of various music. I created DB Browser to that location and it works fine.

**Comment by VIRGINKLM** [comment]
I guess it's a Samsung/Touchwiz thing(?)
Maybe I could provide a log?

**Comment by droidmjt** [comment]
I have that CM13 on Samsung Galaxy S3. Are you sure you are using DB Browser instead of Filesystem Browser?

**Comment by VIRGINKLM** [comment]
Yep it simply refuses to check folders that contain files that can be played back with the app.

**Comment by VIRGINKLM** [comment]
It was a sdcard that was on my previous phone and it worked. I didn't move anything, but now it doesn't work. Hmmm

**Comment by droidmjt** [comment]
you can send me logcat log but I'm out of ideas. Try another sdcard maybe. I don't have SGS7 so I cannot help you.

**Comment by theGIZOID** [comment]
Was it a clean instalation or an update? I had a similar problem on my CM13 S4 after updating and I got it to work after uninstalling DSE and deleting all DSE related folders and reinstalling the app. #312

**Comment by VIRGINKLM** [comment]
My god indeed. I even had to delete the /data folder for it to work. What did they change in the OS for it to act like this? With the same SD card I was swapping it between devices and it was fine. Closing issue.
