### ISSUE TITLE
s98 files don't loop,play one loop and silence

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#320]
ummm...

**Comment by droidmjt** [comment]
send me example songs so i can reproduce this problem

**Comment by crimson1117** [comment]
ftp://ftp.modland.com/pub/modules/S98/Shinobu%20Ogawa/XZR%20SB2/
ftp://ftp.modland.com/pub/modules/S98/Shinobu%20Ogawa/XZR%20SB2/07-danceofdirts.s98

**Comment by droidmjt** [comment]
what was the earlier build where this worked or has it been like this always?

**Comment by droidmjt** [comment]
ah, I guess this never worked, I'll see if I can get this fixed.

**Comment by crimson1117** [comment]
thanks.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/lybfpkeblqi8p6t/droidsounde16647_98.apk?dl=1

**Comment by crimson1117** [comment]
Thanks.I found those converted ps3 at3 files won't jump to next songs until 06:40(which their real time is?,but will auto jump in old version as a feature of an old issue here),also those nsf subtunes just play default times you set whatever they are music or sound effects.sound effects got long silence.also psp and some other kinds of music only got 1loop only in default mode.

**Comment by crimson1117** [comment]
nsf got long silence now...

**Comment by droidmjt** [comment]
send me the problematic songs

**Comment by crimson1117** [comment]
https://www.dropbox.com/s/9fn81vrsyutjv9y/15%20SOUND%20EFFECT%20%28Nobuyuki%20Shioda%29.nsf?dl=0
https://www.dropbox.com/s/jzfxgu66egj7gx8/bgm01a_v01.at3?dl=0

**Comment by droidmjt** [comment]
the at3 file works as usual and what exactly is wrong with the NSF file? it works just like with build _92 for example, there are no long silences in that song

**Comment by droidmjt** [comment]
tested with build _99 using default settings

**Comment by crimson1117** [comment]
at3 things are converted from msf(old things)
https://www.dropbox.com/s/dah6hdpj4yoekic/bgm02_v02a.at3?dl=0

**Comment by crimson1117** [comment]
ah I know.I seted some thing called addtional song length and urrrrrhhhh bad things happen.

**Comment by droidmjt** [comment]
there, now I was able to reproduce the problem, you see, more infos == easier to fix :)

**Comment by crimson1117** [comment]
can s98/mdx/pmd have more loops?a switch to make those things got 3 loops or more?

**Comment by droidmjt** [comment]
I'll check if the libs support loopcount directly, otherwise no.

**Comment by crimson1117** [comment]
thanks

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/r6aqj5wqnxr2596/droidsounde167_01.apk?dl=1

**Comment by crimson1117** [comment]
http://blog.livedoor.jp/ym2608/archives/52470819.html YM2608 not 55555 but actually 55466,the reason is here...

**Comment by crimson1117** [comment]
Loop worked,thanks a lot!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/a7sk8bsbsrlrull/droidsounde167_02.apk?dl=1
now it uses 55466, close this case

**Comment by crimson1117** [comment]
thanks.
