### ISSUE TITLE
[Feature Request] Customize Scrolling Bar

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#321]
The thing about the scrolling bar is that it is a lot thicker in folders with many files and this was a burden to me for a long time. I tend to tap very far to the right of my screen. Due to that I often hit the scrolling bar in these kinds of folders by accident and go off somewhere else in the folder where I don't want to be.

So I ask for a feature to add customization for the scrolling bar like adjust thickness, side, etc. or to just disable it because I barely even use the scrolling bar in any filebrowser.

**Comment by droidmjt** [comment]
if it can be disabled then i can add a switch to disable it but thats it

**Comment by theGIZOID** [comment]
Yeah, that would be enough for my case

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/lybfpkeblqi8p6t/droidsounde16647_98.apk?dl=1

**Comment by theGIZOID** [comment]
While small scrolling bars disapper, bigger ones in folders with a lot of flies still have those thick scrolling bars as shown in this [video](https://youtu.be/fZeu_zKF1Ek).

**Comment by droidmjt** [comment]
did you restart the app after disabling the scrollbars?

**Comment by droidmjt** [comment]
what the hell, on emulator it works but not on real hw, crap

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ydjghw2m85u6o4x/droidsounde16647_99.apk?dl=1

**Comment by theGIZOID** [comment]
Now it's working, thanks a lot.
