### ISSUE TITLE
MP3 streaming broken at nonstandard rates (22KHz, etc.)

### ISSUE THREAD

**Issue by JFD62780** [droidmjt/Droidsound#322]
Okay... On a recent beta, I tried playing a radio show that broadcasts at half the rate of CD's.

First attempt at being the first click.... crash.

Second attempt, at first click.... crash.

Third attempt, after playing a working track...  PLAYS AT DOUBLESPEED!

Methinks we need a resampler for streams...

Sure, it DISPLAYS the proper rate.  it just don't PLAY the proper rate...

**Comment by droidmjt** [comment]
Ah, I knew something broke, I was recently changing things for streaming. Send me the radio link.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/lybfpkeblqi8p6t/droidsounde16647_98.apk?dl=1
check out this build

**Comment by JFD62780** [comment]
Thanks for the new build.  Problem is we'll need to play the waiting game for the results, since the radio stream I mentioned is strictly open for ONLY two hours a week, namely Sunday nights at 11PM-1AM EST US.

You're welcome to be a listener by following these steps:

1:  Visit this URL, to unlock the stream to media players (like Droidsound-E).

2:  Add this URL ( http://s24.myradiostream.com:3322 ) as a Station, and name it Wolf Den Radio.

3:  Play the radio stream from a WiFi connection with the same IP address that opened the URL in step 1.

Yes, you have to jump through hoops, but the stream works...

**Comment by droidmjt** [comment]
all right, so is the problem fixed?

**Comment by droidmjt** [comment]
tested with a radio using 22050hz, works

**Comment by JFD62780** [comment]
I tested on the road, but other problems popped up, namely with streams that use lead-ins, and/or that came up as errors but still played.

This time they crashed before it could play the actual radio portion...

**Comment by droidmjt** [comment]
I need to be able to reproduce the problems, otherwise I cannot fix them. So, I need those radio stations you tried.

**Comment by droidmjt** [comment]
I'll reopen this case after you provide those stations that you tried.

**Comment by JFD62780** [comment]
Okay, not to reopen but the results are in:  The 22KHz stream actually works!

Not sure why the thing crashed at the time

But I have a few suggestions for ratio stations to add to the default list:

Radio Nintendo (http://radionintendo.com)
NoLife Radio (http://nolife-radio.com)
Radio Sega (https://www.radiosega.net)

The former two were actually in the original Droidsound when the Swimsuit Boys were in charge of making the thing; the latter, I discovered when the at-the-time most recent Radio Nintendo was shut down...

At least it'd be cool if we kept the radio links current so it won't waste SEVERAL seconds when the stream 404's...

**Comment by droidmjt** [comment]
all right, I'll include those stations.
