### ISSUE TITLE
[Feature Request] Cycle between subtunes with notification bar buttons

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#323]
Right now, if you are listening to something like NSF files you always skip to the next file instead to the next subtune in the NSF file when using the notification bar buttons, forcing me to go into the app and use these buttons instead.

**Comment by droidmjt** [comment]
you need to enable cycle subtunes from settings, close this case

**Comment by theGIZOID** [comment]
Ops, nevermind :*)

**Comment by theGIZOID** [comment]
But it would be nice if the notification bar is mentioned in the description so some people, such as me, would understand the use of this function because it already switches between subtunes in the app itself. On another thought, for what could it be used anyways?

**Comment by droidmjt** [comment]
yeah I'll add description
