### ISSUE TITLE
Vio2sf settings

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#324]
Not an issue but more of a feature request -ish.
Would it be possible to add vio2sf plugin settings together with the rest plugin settings so it is possible to change the interpolation method?

**Comment by droidmjt** [comment]
the rest plugin settings, what do you mean?

**Comment by droidmjt** [comment]
nevermind, had old lib

**Comment by VIRGINKLM** [comment]
I was trying to check the version used before writing this but It's not mentioned on the app so I assumed it must be the latest.

**Comment by VIRGINKLM** [comment]
Just noticed that the new lib even has some dev settings like voice/channel selection. Intresting!

**Comment by droidmjt** [comment]
where do you see this new lib?

**Comment by droidmjt** [comment]
If you refer to the source code in sourceforge repo, there is no interface anymore.

**Comment by VIRGINKLM** [comment]
:/ are the options still accessible? I only care for the interpolation method tbh, I dont like anything else but linear. Those fake harmonics generated by any other method (like cubic or nearest neighbor) just irritates me, it gives that typical metalic-artificial-cheap-electronics feeling that makes me cringe.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tqk8zqyjew1c0gr/droidsounde167_03.apk?dl=1
try this, if you have some 2sf songs where interpolation makes a big difference in output, let me know,

**Comment by VIRGINKLM** [comment]
WOW, works and sounds great! I find that in both NDS and GBA sample-based audio tracks sounded terrible because of no interpolation. The samples used on both of those consoles have already a really low sample rate, if you don't interpolate them you are going to generate some nasty metalic sounding artifacts. So to my ear all tracks sound amazing with linear interpolation, they just got a generation higher upgrade with this adition. Compare for example Kingdom Hearts tracks with their PS2 counterparts, they sound almost identical (since they are based one the same ADPCM samples). The ones that sudder the most are the ones that contain samples that have silent samples or samples that don't have alot of high frequencies resulting in mirroring/aliasing of the low frequencies across all spectrum again and again.

Here's an example of "Welcome To Wonderland" track:
First goes the a 15 second clip without interpolation, then one with linear and then the difference of the two slightly amplified so you can hear what bad things non-linear interpolation does to your audio.

![spectral](https://cloud.githubusercontent.com/assets/3772761/18330627/58db73fc-7562-11e6-8b82-7d4cddb81a8c.jpg)

[Sample.txt](https://github.com/droidmjt/Droidsound/files/460462/Sample.txt)
(Rename Sample.txt to Sample.m4a)

I wish GBA audio could do proper linear interpolation. It may give an option for interpolation but what it actually does is applying a High Cut filter which is not how interplation works and artifacts are not being removed properly that way, they are still there audible.

**Comment by droidmjt** [comment]
All right :) Great that it works.
