### ISSUE TITLE
[bugs fix plz]Length and adpcm problem

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#327]
Thanks for the loop...but seems new bugs there.First,when a song is short than default length,a long silence is there.it happens in some s98 and bad files,maybe gbs,hes or more?(maybe stuff not tested)Second,s98 and PMD's adpcm or rhythm seems broken...I am using mobile to type,sorry about last spam like article.

**Comment by droidmjt** [comment]
send me songs how to reproduce the length problem, the adpcm thingy i know

**Comment by crimson1117** [comment]
https://www.dropbox.com/s/feduob7qqlgnxcu/valiant7.s98?dl=0 this s98 also plays strange but seems no adpcm 
https://www.dropbox.com/s/t9yh5upap41uw8d/01%20BLACK%20CARTRIDGE%20%28Hally%29.nsf?dl=0
Using nsfplug ,default is 300 seconds.

**Comment by droidmjt** [comment]
NSFPlug problem I was able to reproduce. Valiant7.s98 doesn't sound any strange to me, what exactly is the strange part there?

**Comment by droidmjt** [comment]
I tested the valiant song with 2 months old build, works fine, make sure you have the droidsound/s98 folder with those .wav files, otherwise it sounds odd

**Comment by droidmjt** [comment]
the only problem with the NSFPlug is the silence detector

**Comment by crimson1117** [comment]
thanks,now s98 and PMD works fine.seems the files are 2016/07/04 ver...

s98 's silence detecter also strange.
https://www.dropbox.com/s/6p6nwczozloc9p4/%E4%B9%99%E5%A5%B3%E6%88%A6%E8%A8%98.rar?dl=0 Otome Senki Song 01
also I don't know if other plugin's silence detector have problems...
MSXPlug/NEZPlug also there.got some examples.

**Comment by droidmjt** [comment]
Do test if those other plugins (MSXPlug/NEZPlug) have the problems, if yes, then send me songs to reproduce the problem.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2ri2tjwptvos3s9/droidsounde167_05.apk?dl=1

**Comment by droidmjt** [comment]
I'll close this, leave a message

**Comment by crimson1117** [comment]
https://www.dropbox.com/s/rec9f1evf4zitqk/D68START.MGS?dl=0 MSXplug file
https://www.dropbox.com/s/byl743uezayrpf6/Magical%20Chase.hes?dl=0 PCE hes,using nez and track 1 will silence since no loop

**Comment by droidmjt** [comment]
i'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xu198pulaxntlw3/droidsounde16647_06.apk?dl=1
should be better now

**Comment by crimson1117** [comment]
Thanks a lot!
