### ISSUE TITLE
TFM Music Maker file playback

### ISSUE THREAD

**Issue by kyusawamura** [droidmjt/Droidsound#328]
Hello, Droidmjt! I noticed two small issues playing these files:

1- There's nothing to configure about the BASSZXTUNE. Lest there's very little to configure in the player. If you intend to leave it that way, then it's okay.
2- IMPORTANT: the modules don't loop. They only play once and there's no option to configure this.

Thank you very much for keeping this in development. Keep up the good work!

Regards
-Kyu

**Comment by droidmjt** [comment]
I'll check it.

**Comment by kyusawamura** [comment]
Thank you very much! I'm not sure if the TFE files I tested have title and author tags in them. But in case Droidsound-E isn't showing them in TFE files, it'd be nice to have them too! ;) If it's possible, that is. ^^

**Comment by droidmjt** [comment]
looping fixed, title and composer name feature will be added when the library itself has been fixed

**Comment by kyusawamura** [comment]
Thank you very much! I'll update accordingly. :D

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/v10zpq0baxxc1hb/droidsounde167_04.apk?dl=1
Try this. I tested few TFE files and worked.

**Comment by kyusawamura** [comment]
I updated, and now I tried with both a TFE and a TFD file. I noticed these things:
-Droidsound-E ignores the real loop points. It loops from the start.
-It only loops once and instantly fades out, and there's no option to change the loop count.

In addition to fixing the loop bug, could it be possible that we can have the option to change the loop count? :) Moreover, would it also be possible that we have that option for OpenMPT and/or UADE modules? :)

Thanks in advance!
Regards
-Kyu

**Comment by droidmjt** [comment]
Please send me the TFE/TFD files you tested.

**Comment by kyusawamura** [comment]
Sent. Check your GMail, my e-mail should appear with the name "Jun :v".

**Comment by droidmjt** [comment]
Haven't got any mail from you, but anyway, basszxtune cannot control loop points for the formats you mentioned, I need to roll back my changes and wait until the looping support is included in the library. Unfortunately I cannot add loopcounts for openmpt and uade since those libraries don't support looplength counting.

**Comment by kyusawamura** [comment]
I did send you an email... I suppose you should be able to see it somehow, maybe it's under junk mail?
If it depends on the plugin itself, then we'll have to be patient. In any case I'm already really happy to see TFE/TFD formats already being supported!

Thank you for the feedback!
Regards
-Kyu

**Comment by droidmjt** [comment]
I checked junk mail, nothing there. Anyway, I can add the Title/Composer thingy. Let's hope in the future BASSZXTUNE library supports loop points.

**Comment by kyusawamura** [comment]
Thanks again! I'll wait patiently for the next update. :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2ri2tjwptvos3s9/droidsounde167_05.apk?dl=1
only the looping is not there yet, let's wait patiently for the next basszxtune version :)

**Comment by droidmjt** [comment]
Now the looping works, I will upload a new binary shortly :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/pe8fj8473qvmbjz/droidsounde167_12.apk?dl=1
try this one
