### ISSUE TITLE
Vio2sf won't play Phoenix Wright NDS 1-3 now. 

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#330]
http://2sf.joshw.info/zzz_old/p/ 
File is here.

**Comment by droidmjt** [comment]
If you can find totally 10+ sets that fails to play, I'll roll back to earlier version.

**Comment by Level99OCR** [comment]
Custom Battler: Bomberman - 0010 SEQ_MU09
Akagawa Jiro Mystery: Tsuki no Hikari - NTR-CJ6J-JPN-001c
Mezase! 100 Giri Golf DS - NTR-YL5J-JPN-0002
Chibi Maruko-chan DS: Maru-chan no Machi - NTR-YO5J-JPN-0027
Hirameki Action: Chibikko Wagyan no Daiki na Bouken - NTR-CWNJ-JPN_00-0011
National Geographic: Panda - 003b SEQ_BGM081
Coraline - NTR-CRLE-USA-0011
Madagascar 2: Escape Africa - SEQ_BGM_LEVEL1_CRASH-SITE-MAR... 000A (got cut off in the screenshot I took)
Magician's Quest: Mysterious Times - BGM_ITEM58
Phantasy Star Zero - 0063 SEQ_BGM_STAGE6_RARE04
Shining Force Feather - NTR-CS4J-JPN-002a

This is in addition to a few crashes that happened while shuffling the DS collection, but none of those crashes produced a crashlog. I'll see if I can find the culprit songs later by looking at the filecache itself for when the crashes occurred.

**Comment by VIRGINKLM** [comment]
Intresting, they play on PC with the same version of vio2sf.

**Comment by droidmjt** [comment]
the version currently in DSE is not the same as before, it is a newer build of vio2sf that has built-in resampler, i can roll back and install additional resampler

**Comment by theGIZOID** [comment]
Funnily enough it did not crash on any song of "Phoenix Wright: Ace Attorney" for me using DSEs latest build. But I don't know about the other games though.

**Comment by droidmjt** [comment]
It doesn't crash here either, it's just silent.

**Comment by theGIZOID** [comment]
I do get music, I have absolutely no problem with that game.
But speaking of crashes, there is a selfmade 2sf pack I did with a friend of mine. It works fine on the PC using the Vio2sf plugin on Winamp but constantly crashes when trying to play on DSE. I am talking about Rhythm Paradise aka Rhythm Heaven in the US or Rhythm Tengoku Gold in Japan.

It's [here](https://drive.google.com/open?id=0B7CwhIj0oUmGdHg3d0lXM3kwWDA).
This pack contains all versions of the game with all languages so it is pretty big (almost 200 MB).

**Comment by Level99OCR** [comment]
The crashing games for me are not the silent ones. I have yet to figure out which ones crash yet simply because its not loading the file into the filecache and when it crashes there is no crashlog. I'll have to logcat it later tonight.

But yes, even Yoshi's Island DS has some silent songs on it. Good to know that the issue seems to be localized to that super-new version of vio2sf.

**Comment by VIRGINKLM** [comment]
I find it weird that an interpollation method would break compatibility with some tracks resulting into simple silence. In theory it means that the interpollation process resamples all samples to 0db only for specific tracks which is a bizzare behavior to begin with.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xu198pulaxntlw3/droidsounde16647_06.apk?dl=1
it better work :)

**Comment by VIRGINKLM** [comment]
Tracks fixed but now interpolation options do nothing. You need to interpolate each individual ADPCM sample pre-mixing not post mixing.

**Comment by droidmjt** [comment]
ah i see, well, in that case, I will remove the interpolation completely.

**Comment by VIRGINKLM** [comment]
This is technically a full revert then(?) :(
I don't get what is wrong. With the latest version of vio2sf on foobar2000 all these tracks play without a problem. What could possibly go wrong here?

**Comment by droidmjt** [comment]
until i get a lib that works, you need to stick with the old version

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/jzo9rd5xhvb3isn/droidsounde167_07.apk?dl=1
try this

**Comment by VIRGINKLM** [comment]
This one works and also has 2 extra interpolation options. What did you do?

**Comment by VIRGINKLM** [comment]
This one works perfectly (proper linear interpolation with no artifacts) and also has 2 extra interpolation options. What did you exactly do? Let me do some more testing before you go prime time with it.

**Comment by droidmjt** [comment]
the build at the frontpage is even better, the _08 one :)

**Comment by VIRGINKLM** [comment]
changelog?

**Comment by VIRGINKLM** [comment]
Ah I think I know why it didnt work with the 03 test. All these tracks mentioned make use of some of the obscure functions of DS's SPU. Like one of them is taking advantage of the legacy (GB/GBA) chip that produces pulse/noise type audio.

**Comment by Level99OCR** [comment]
Can also confirm the regression games all work now and oh man does that interpolation sound gorgeous, thanks so much!

**Comment by VIRGINKLM** [comment]
Exactly. I wish GSF audio plugin(s) had those interpolation methods. I don't know who implemented the interpolation option on the GSF plugin but all it does is applying a high cut filter which is not what interpolation does in practice at all. GBA with proper linear interpolation would sound sooo much better, it would push the quality to the standars of more powerfull consoles.
