### ISSUE TITLE
Bassmidi and mt32 got errors 

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#332]
Just silence then...

**Comment by droidmjt** [comment]
closing this due to lack of information

**Comment by droidmjt** [comment]
BASSMIDI is fixed, the error was caused due to renamed classes. MT32 might be silent because no .roms included anymore.

**Comment by kyusawamura** [comment]
Actually, I think there's something much worse going on...
I have my MIDI playback device set to BASSMIDI by default, and attempting to play a MIDI makes the app freeze, and it eventually makes the Android explorer/shell crash too.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xu198pulaxntlw3/droidsounde16647_06.apk?dl=1
check it out

**Comment by crimson1117** [comment]
Thanks, fixed.

**Comment by kyusawamura** [comment]
Works perfectly. Thanks!
