### ISSUE TITLE
Too.  Much.  Scanning.

### ISSUE THREAD

**Issue by JFD62780** [droidmjt/Droidsound#333]
Okay, here's a 'new' one.

I manually deleted the two apparent database files, only cause the database wouldn't update AT ALL.  EVEN IF I try to rescan a single directory (namely a personally set Playlist directory).

So, now, I TRY to start all over again, and I ask you:

MUST the Initial Scan go through all the required entries 3, 4, 5, SIX TIMES? before it's finally ready?

I SWEAR, it spent SO much time scanning that it CRASHES from overdoing its job! x.x

(Samsung Galaxy S4; release 167_08)

P.S.  Is the default directory dsroot or Droidsound/dsroot ?  This could be extremely important cause I tried updating the former, when I didn't think of, yet might've had to, update the latter...

**Comment by droidmjt** [comment]
The root is /scdard/Droidsound/dsroot, remove the folder /sdcard/dsroot, it is not being used anymore.
I have never experienced the 3,4,5,6 times scanning scenario and I would like to know how to reproduce the scenario. How does your directory structure look inside your playlist directory, you have mixed content there?

**Comment by droidmjt** [comment]
also, what is your phone's Android version and is your Droidsound folder located in internal or external memory card?

**Comment by JFD62780** [comment]
Okay.  The main directory is on the phone's Internal Storage.  BUT...  I also had two 'browsers' set for the roots of both Internal and External storage, so it wouldn't quite matter where I store my ROMS.

This was BEFORE filesystem browsing was added.

And I've learned since then that the 'browsers' outperformed the actual browser as in it detected ALL playable files.  The actual browser omitted a few files, weirdly.

The phone is still on 4.4.4.  and all you need to do to do the 'endless scan' is simply open the app.

And that was AFTER I stubbornly decided to manually delete the database and start anew.

And all that after adding updated playlists to the OLD directly BEFORE I learn of the new directory. x.x

No wonder the playlist directory hasn't changed.  It's nothing but textfile-based playlists, BTW.

**Comment by droidmjt** [comment]
Don't mount any filebrowsers to paths under /droidsound/dsroot/ folder and /droidsound/, for example like /droidsound/dsroot/jfdtunes/ or /droidsound/jfdtunes/. It seems using filebrowsers on paths that point to /dsroot/ or /droidsound/ seems to cause some troubles.  That would explain the endless scanning.

**Comment by JFD62780** [comment]
Okay, then I have a new request...

What if in addition to manually entering the directory to mount, you also include a method to navigate and choose, like the Windows crowd is used to.

I mounted the root directories so I wouldn't have to manually enter such directories more than once. :/

**Comment by droidmjt** [comment]
All righty :) I should have added those droidsound related paths in to exclusion list. Will add that next.

**Comment by droidmjt** [comment]
I suppose this can be closed or is there anything else about this?
