### ISSUE TITLE
[Feature request] Equalizer

### ISSUE THREAD

**Issue by David8989** [droidmjt/Droidsound#334]
Yeah, i miss an equalizer in the app. The only thing that makes me use other apps for playing high quality files to have the best experience.
Thanks for your awesome work!

**Comment by droidmjt** [comment]
One day after the gapless feature is done, I'll close this for now and reopen once i have time again.

**Comment by theGIZOID** [comment]
Alternatively, if you have rooted your phone you can try out ViPER4Android, it's really powerful if you know how to use it. It's worth a try at least. Just be sure to set the UI Setting to Expert to get all settings.

**Comment by David8989** [comment]
Thanks for the tip, I'll be using it. but still, an equalizer in DS would be awesome ;)
