### ISSUE TITLE
[Issue] Some MIDI Songs have incorrect play length (1sec, causing crash, or length of fadeout)

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#335]
Here's an example rip: I.M. Meen for DOS http://www.mirsoft.info/gmb/music_info.php?id_ele=MTMzNTU=

Tested using 167_08, but the issue has been around for a while and I've been trying to narrow down if it was something on my end doing it or if it was a particular feature that was causing the problem.

Track 1 Test Results:

Emu de MIDI: crash
BASSMIDI (without Audio Fade Enabled): 1 second displayed then crash
BASSMIDI (with Audio Fade Enabled for 5 seconds): 6 seconds of music, immediate fadeout, then next song
ADLMIDI: crash

This isn't the only game but its the one I have on hand right now for testing. Not sure what this could be related to, but if the crash logs would be helpful I can provide them. Hopefully this is something easy to replicate.

**Comment by droidmjt** [comment]
all right, i'll check it

**Comment by droidmjt** [comment]
this is fixed, tested the I.M. Meen song and some others, i'll upload new binary soon

**Comment by Level99OCR** [comment]
Thank you very much!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nhnzo5saydyfke7/droidsounde167_09.apk?dl=1
Try this one, I hope it's ok now. Report any odd behaviour.

**Comment by Level99OCR** [comment]
Will give it a thorough run through over the weekend.

**Comment by droidmjt** [comment]
excellent, leave a message how it worked

**Comment by Level99OCR** [comment]
Seems to be working just fine, closing. I'm going to put all my .MID on a random playlist just to be sure. Appreciate the fix!

**Comment by droidmjt** [comment]
good to hear
