### ISSUE TITLE
Please update BASSZXTUNE to latest v2.4.4

### ISSUE THREAD

**Issue by edger78** [droidmjt/Droidsound#336]
Hi droidmjt,
Some ay files which containing multiple tunes are not playing. I believe this issue solved in latest plugin build. Could you please update it in your Droidsound-E?

**Comment by droidmjt** [comment]
Please send me some example tunes so I can test it.

**Comment by droidmjt** [comment]
nevermind, problem solved, will upload new binary soon

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/fd31y53jcejcci8/droidsounde167_11.apk?dl=1
Try this, there are few problems remaining in this one but they will be fixed when they can be fixed.

**Comment by droidmjt** [comment]
leave a msg

**Comment by edger78** [comment]
Dear droidmjt,
My bad, sorry for the delay with the response, I temporarily have no phone nearby to check and provide you with samples, but if you have updated the library, it should be solved. Thank you for your prompt reaction and fix.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/pe8fj8473qvmbjz/droidsounde167_12.apk?dl=1
Try this one.
