### ISSUE TITLE
Modland search tag (,n) not working anymore

### ISSUE THREAD

**Issue by raidcookie** [droidmjt/Droidsound#338]
Hi droidmjt.

First of all I want to thank you so much for this fork, as I loved the original app and was pretty bummed when it stopped working on android 5+.

But now to my current issue, since the last update the modland search no longer seems to work. If I search for something (i.e. ',nTetris') I get no results and "Search" also doesn't get replaced with what I just entered like it usually does. It still works fine in the build I had before, which is a few months old.

I'm on Android 6.0 if that matters.

**Comment by droidmjt** [comment]
get the latest build from frontpage and do the search without quotes :)

**Comment by raidcookie** [comment]
I am on the newest build and searching without quotes. 

Still; https://puu.sh/sdraA/c349c7e4e6.mp4

**Comment by droidmjt** [comment]
go to New -> Modland DB and click OK, you need to have Modland DB indexed before you can use modland search.

**Comment by raidcookie** [comment]
Ah, big mistake on my end then. Sorry!
