### ISSUE TITLE
2nd row of title text cut off

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#339]
hello!

I'm using droidsounde167_13.apk from the main page, and the title text is cut off on the 2nd row, screenshots attached:

![screenshot_2016-12-07-08-40-27](https://cloud.githubusercontent.com/assets/14978933/20972052/44024292-bc59-11e6-9733-20c56a590b03.png)
![screenshot_2016-12-07-08-40-33](https://cloud.githubusercontent.com/assets/14978933/20972053/44065c24-bc59-11e6-9e72-9b8c677a23ea.png)
![screenshot_2016-12-07-08-40-19](https://cloud.githubusercontent.com/assets/14978933/20972054/440c1dbc-bc59-11e6-8c16-69f724ff418a.png)

**Comment by droidmjt** [comment]
change the font size

**Comment by droidmjt** [comment]
and close the case

**Comment by filevans** [comment]
ok did that on android, but what about an option in droidsound to overide system font size, as i like large text on my smart phone, but obviously it interferes with droidsound

**Comment by filevans** [comment]
or if using large text it automatically resizes the bar a couple of pixels to fit the text in?

**Comment by droidmjt** [comment]
I'll see if it's possible to do the override thing.

**Comment by droidmjt** [comment]
This is fixed, now the system font size won't affect the app anymore, I'll upload a new binary during this weekend

**Comment by filevans** [comment]
Great work

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/osld5o4cug4sl7b/droidsounde167_14.apk?dl=0

**Comment by droidmjt** [comment]
use this instead:
https://www.dropbox.com/s/cq3iutwbmyfx866/droidsounde167_15.apk?dl=1

**Comment by droidmjt** [comment]
leave a msg
