### ISSUE TITLE
Crashing on folder selector dialog on Pixel

### ISSUE THREAD

**Issue by TomMorgan** [droidmjt/Droidsound#340]
Hi, DroidSound E doesn't work on my Pixel. Whenever it tries to access the broader local filesystem it crashes; it can access the example mods fine, but if I try to mount my Download directory it crashes before the directory selector dialog appears.

I've used Android 7.1 and 7.1.1 with it and I know that more recent versions of Android require apps to request permission to access the filesystem, not sure if that's the problem though.

The behavior is the same in the original DroidSound that's on the Play Store.

DSE is my favorite player. No other player for Android uses OpenMPT, treats folders like playlists, and supports Bluetooth so well. I'd really like to be able to use it.

**Comment by droidmjt** [comment]
have you tried to enable permissions manually from device settings -> applications -> ? I think storage is disabled by default at least

**Comment by TomMorgan** [comment]
I checked that, and permission to access storage is enabled.

**Comment by droidmjt** [comment]
I'll investigate this. I have only the Android emulator with 7.1.1.

**Comment by droidmjt** [comment]
partially fixed for 7.1.1, filesystem browser works fine now, need to adjust the DB browser next

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/uwonmbc3zkp0ea7/droidsounde167_17.apk?dl=1
see how that works

**Comment by TomMorgan** [comment]
Everything works! Thank you so much!

**Comment by droidmjt** [comment]
good to hear :) please close this case
