### ISSUE TITLE
tak files won't play

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#341]
Tak files won't play in newer versions of driodsound-e, they work in older version

**Comment by droidmjt** [comment]
yeah ffmpeg got changed some time ago and I forgot to test TAK files, i'll get it fixed

**Comment by droidmjt** [comment]
try this: 
https://www.dropbox.com/s/bsi23s67645p5ue/droidsounde167_18.apk?dl=1

**Comment by droidmjt** [comment]
leave a msg

**Comment by Sir-Sabin** [comment]
Yea they play now, thx for the fast fix
