### ISSUE TITLE
OpenMPT is wrong

### ISSUE THREAD

**Issue by danylopez123** [droidmjt/Droidsound#344]
Compared to the PC one, OpenMPT for Droidsound is kinda wrong, i tested it with some modules.
Here, try to compare these ones with Droidsound and OpenMPT for PC.

[Modules.zip](https://github.com/droidmjt/Droidsound/files/787871/Modules.zip)

**Comment by droidmjt** [comment]
what version of Droidsound-E you used?

**Comment by droidmjt** [comment]
I'll close this case since it looks like there is no problem with the current openmpt version, leave a message with more details.

**Comment by danylopez123** [comment]
I forgot to say i used the latest version

**Comment by droidmjt** [comment]
All right, tell me how and where (position of the song in seconds) the error happens. I listened these songs with the latest version of openmpt for PC and couldn't hear any difference.

**Comment by droidmjt** [comment]
One thing you could do is check if you have same interpolation setting.

**Comment by ItsT3K** [comment]
I agree with Droidmjt. Check the settings. I havent had a problem with
OpenMPT. Also off topic. 2SF playback locks the app when the file is
clicked. Depacking?

**Comment by droidmjt** [comment]
@ItsT3K yeah some 2sf songs have a very big .lib file that needs unpacking and it stops the playback.

**Comment by ItsT3K** [comment]
Ah. My old Galaxy S3 Mini falls behind too. So that adds up
