### ISSUE TITLE
Update vgmstream to latest version

### ISSUE THREAD

**Issue by crimson1117** [droidmjt/Droidsound#345]
Seems the MSF stuff of PS3 have been solved in recent version.
Thanksful as ever for the soft.
btw,the atrac3 can read msf actually but cannot read its header(loop info,etc)so the loop is not good now.

**Comment by droidmjt** [comment]
as usual, post the files here that do not work, otherwise close case.

**Comment by crimson1117** [comment]
ah sorry,something wrong during the copy.

**Comment by crimson1117** [comment]
https://www.dropbox.com/s/3pxguapbr4tyajz/bgm02_v02a.msf?dl=0 
loop info got problem,seems i am not wrong.

**Comment by droidmjt** [comment]
Will update ffmpeg instead at some point.

**Comment by droidmjt** [comment]
try this: https://www.dropbox.com/s/tg0u37den33pg8a/droidsounde167_21.apk?dl=1

**Comment by crimson1117** [comment]
http://psf3.joshw.info/w/Wizardry%20Perfect%20Pack%20(2011-12-08)(-)(Acquire).7z
bgm 03/04/08 got problemed now...

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/lkz8hl6ksif10n8/droidsounde167_22.apk?dl=1
hopefully fixes the problem and won't bring any new

**Comment by droidmjt** [comment]
leave a msg

**Comment by crimson1117** [comment]
thanks,seems good for now.
