### ISSUE TITLE
SID stuff

### ISSUE THREAD

**Issue by DavisOlivier** [droidmjt/Droidsound#346]
Seems like the filter bias option isnt working.
Tried both builders, forcing sid options and some sids but seems like it just doesnt works.
Also, it'd be awesome if stereo playback were added

**Comment by droidmjt** [comment]
What do you mean by stereo playback? I'll check the bias thing at some point.

**Comment by droidmjt** [comment]
bias problem solved, fix will be available in next build

**Comment by DavisOlivier** [comment]
Well, in some plugins there's the SID stereo playback function. if i recall well, the plugin i used on linux that had this function was libsidplayfp, the same used in DS-E. Im not an android expert so forgive me if im talking shit.

**Comment by droidmjt** [comment]
If the library supports some force-stereo flag, I can add it.

**Comment by droidmjt** [comment]
I went through the library and couldn't find anything related to force-stereo.

**Comment by DavisOlivier** [comment]
Seems like it is there, but maybe not in the version ported to android?
You can see the stereo playback being mentioned in the main page: https://sourceforge.net/p/sidplay-residfp/wiki/Home/

**Comment by droidmjt** [comment]
It's a stereo tune, 2SID, 3SID and those mus+str are stereo tunes and currently they are played as stereo, has nothing to do with any stereo switch :)

**Comment by DavisOlivier** [comment]
Sorry, i mistook it. It's actually the SID plugin for XMplay that forces the stereo playback. In libsidplayfp there's the -s option when playing from terminal, but it did nothing in the sids i tested.

**Comment by droidmjt** [comment]
try this: https://www.dropbox.com/s/tg0u37den33pg8a/droidsounde167_21.apk?dl=1

**Comment by DavisOlivier** [comment]
Tested some sids and filter bias is fully working now. Thanks~
