### ISSUE TITLE
midi's soundfont

### ISSUE THREAD

**Issue by DavisOlivier** [droidmjt/Droidsound#347]
I think it would be nice if the sf2 in the same folder as the mid files were loaded automatically if it is present. Thats a common function in most midi players/plugins out there

**Comment by droidmjt** [comment]
Currently it works so that if it cannot find the SF2 user has selected from the preferences, then it searches the local folder.

**Comment by droidmjt** [comment]
Correction, you need to enable it from the settings.

**Comment by droidmjt** [comment]
Ah there is a bug, it fails to use sf2 file from the music folder if there is no sf2 available from the usual soundfont folder, I fix it.

**Comment by DavisOlivier** [comment]
I think it would be better if it used the soundfont in the midi folder even if the user selected some other in the preferences. Maybe a switch to turn that on and off would prevent any other problem too

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/0yht564wufyi2v1/droidsounde167_24.apk?dl=1
see how this works, remember to enable it from the settings first

**Comment by DavisOlivier** [comment]
Still not working
I swlected another default soundfont, tried playing midis in a folder with its own sf2 inside and it played with the default. Tried switching on and ofd the feature but it didnt change.
Also, i noticed if you press the gear button to enter the current plugin settings from the player screen, some of the options inside there wont work properly

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/quxk1e8ive2zrj3/droidsounde167_25.apk?dl=1
try this build. I tested it so that I copied SF2 file to /sdcard/Music and enabled the the SF2 override switch in settings and worked fine, when I disabled it, it used the soundfont from the settings

**Comment by DavisOlivier** [comment]
Now it worked, thanks!
I tested several folders to make sure, and it worked fine.
