### ISSUE TITLE
MT-32 Not Working

### ISSUE THREAD

**Issue by Jazz392** [droidmjt/Droidsound#349]
Whenever I try to use MT-32, Droidsound uses Emu de MIDI instead. I downloaded the roms and it still doesn't work.

**Comment by droidmjt** [comment]
what folder did you use for the roms?

**Comment by droidmjt** [comment]
I just tried it and it works, copy the roms to /droidsound/mt32/ folder and try again.

**Comment by sneakernets** [comment]
Are these ROMs included with MUNT or are we expected to have them already?

**Comment by droidmjt** [comment]
user is extected to have them
