### ISSUE TITLE
[Issue] DB Browser Add for Android 6.0 (Marshmallow) Not Scanning from SD Card

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#351]
I just had to revert my LG G4 back from Nougat to Marshmallow for performance reasons. I reinstalled clean 167_28 and the install went fine, but whenever I try to add a DB Browser from my external storage, it will add the new link but it will not scan or populate it. I am trying various permutations today to see if I can narrow down what is going on, also will be going back through previous versions to see if I can find a regression. Just giving you a heads up.

I'll try to get a logcat this morning, this isn't causing a crash or anything, it's just not scanning anything I'm trying to add.

**Comment by Level99OCR** [comment]
16647_37 add works. 167_18 does not. I'm trying to find where I put all the other versions I had in between then but that's about as narrow as I can get it this morning.

**Comment by Level99OCR** [comment]
Narrowed it down to between 16647_62 and 16647_68. Logcat shortly.

**Comment by droidmjt** [comment]
What is your music path in your external SD card? I just tried with SGS3 using CM14.1. My musicpath is /storage/1234-1234/mus and worked just fine.

**Comment by Level99OCR** [comment]
Mine is very similar. /storage/####-####/VGM

Under 16647_62 and prior, adding the path works fine and items within the path are scanned/added.
Under 16647_68 and newer, adding the path happens but nothing is scanned or added, and rescanning adds nothing as well. I've tried numerous versions from 16647_68 up through 167_28, can't seem to find one that works.

I believe it works for me under LineageOS 14.1 and derivatives on this device but not the stock Marshmallow rom. I'm going to try a few variations of the rom today to see how DS reacts.

**Comment by droidmjt** [comment]
I can try also with CM13 later.

**Comment by Level99OCR** [comment]
So it's a quirk of the stock ROM then. I'm curious as to what changed between 16647_62 and 16647_68 that made it incompatible with the LG G4 Stock MM Rom. In this case, it'll probably be difficult to replicate, though unfortunately on my end the Stock Rom is now mandated for a work-required application. I'd likely have to buy a new device if I wanted to keep any current Droidsound-E along side my daily drive if a fix can't be dug up.

I'll try to continue digging into the stock rom but I'm not hopefully. The only listed issue here I can see that had any of those builds in the comments was https://github.com/droidmjt/Droidsound/issues/279 .

**Comment by droidmjt** [comment]
when you made a clean install, did you move the app to external sdcard ?

**Comment by Level99OCR** [comment]
Nope, it's still on internal storage. It was a clean wipe throughout, cleared all data/cache/dalvik and removed the droidsound/DSEmusic/dsroot directories as applicable.

**Comment by droidmjt** [comment]
I'll try to find sources of those builds and see if I can find any differences.

**Comment by Level99OCR** [comment]
Much appreciated. I'd send the logcat but it's completely bare, almost looks normal. It says its doing the scan then immediately finishes. Very strange.

**Comment by Level99OCR** [comment]
Also if you want to send over any of the builds 63-67 I can download them and tell you the exact one that breaks it.

**Comment by droidmjt** [comment]
I don't have those builds anymore. Try to scan another folder instead of /VGM so that you put there only one zip with few files in it.

**Comment by droidmjt** [comment]
Also please open the 16647_68 apk with Total Commander for example and tell the classes.dex filedate, that might help a bit.

**Comment by Level99OCR** [comment]
The problem is a bit narrower now. 167_28 installed and if I copy the folder I'm trying to scan to the internal storage, the scan works fine. If it's on the external card, it does not scan. So it may be something with how this particular rom accesses the external storage.

So it looks like this specifically has to do with external storage handling.

**Comment by Level99OCR** [comment]
classes.dex March 27, 2017 for 16647_68

**Comment by droidmjt** [comment]
sure, also make sure that you have granted access for the APP to access external sdcard.

**Comment by Speedvicio** [comment]
in the past i had a similar problem.
Control in internal and external memory any reference folder to droidsound and delete it, after make a clean install of apk.

**Comment by Level99OCR** [comment]
16647_62 classes.dex = May 26, 2016
16647_68 classes.dex = June 7, 2016

**Comment by Level99OCR** [comment]
App permissions - Phone and Storage. It never prompted me for anything more post-installation.

**Comment by droidmjt** [comment]
all right, thanks for the infos, I'll see if I can find something.

**Comment by droidmjt** [comment]
did you also try to scan another folder from external SDCard?

**Comment by Level99OCR** [comment]
Last update for a bit: even just browsing under Filesystem, if I open a file within a zip, it'll actually play it. So that even narrows it down further: it's just the scanning/adding routines for anything for DB Browser. 

Granted, this will not do any kind of playlist, playqueue, searching, favorites, ratings, etc, but I'll be able to still use it at a base level for the time being.

**Comment by Level99OCR** [comment]
Heh, you uncannily hit it on the nose somehow. Specifically, the DB Filebrowser doesn't add/scan properly for anything on the external SD that is in any kind of subdirectory beyond one parent layer. So, here's what works:

Adding DB Filebrowser for /storage/####-####/New/ <---- anything under this subdirectory seems to add fine.

Here's what DOESN'T work:

Adding DB Filebrowser for /storage/####-####/New/Newer/ <---- adding this insta-adds the link and it is unpopulated.

So all I need to do now is move all my subfolders out from the VGM parent dir to just be resident on the external sd root. At least there's a workaround until/if/when you discover what might be causing the behavior for nested directories.

**Comment by droidmjt** [comment]
excellent, let's see if I can reproduce it and if I can, get it fixed

**Comment by Level99OCR** [comment]
Nevermind, the above doesn't work in all cases. Tried to add /storage/####-####/DS/ and the only contents were zips and it insta-added with no population. This sucks.

**Comment by droidmjt** [comment]
But you managed to get it working from external SDcard once, so its not external sdcard reading problem, its something else.

**Comment by Level99OCR** [comment]
Correct, I'm seeing if I can finagle the functionality specifics out of it now. Maybe it has to do with some kind of naming convention, I'm throwing my hands up in the air at this point and just hoping some kind of revelation happens lol.

**Comment by droidmjt** [comment]
a dirlist of /sdcard/####-####/VGM might help

**Comment by Level99OCR** [comment]
Okay, this is getting mighty bizarre. It looks as though the successful external scanning was a false positive, because it was looking for a folder on the external and actually scanning a folder on the internal.

I copied /storage/####-####/New/ over to my internal card for testing. It had the following contents on copy:
/B/ <-- Genesis B titles here in zips
/Zero Divide/ <--- .xa PS1 files here extracted
/Zero Divide 2 - The Secret Wish/ <-- mp3s extracted
/Zero Divide - The Final Conflict/ <-- mp3s extracted

When I added the directory from the external path, it worked because it was scanning the internal path for some reason. I tried to modify the contents of /New/ on the external but the changes never reflected at all. This was also why trying to add any other folders on the external would fail to populate, because the app was still looking at the internal path and there was no directory equivalents there.

To prove it, I just copied over /New/ again and modified the contents on the external. Not only did these changes not reflect, but when adding it said the following:

Updating database... /storage/emulated/0/New/

I am thoroughly exhausted with this now, but it seems that the root cause has somewhat been located.

**Comment by droidmjt** [comment]
can you tell me the external sdcard path of your phone again

**Comment by droidmjt** [comment]
also tell what folders you have under /storage

**Comment by Level99OCR** [comment]
Will do when I get back to the office this evening.

**Comment by Level99OCR** [comment]
external path is: /storage/1234-1234/ 
My numbers are different but it follows the same style where there's four alphanumeric characters, then a dash, then four more alphanumeric characters.

Under /storage I have /storage/emulated, /storage/self and /storage/1234-1234/

I looked but I couldn't find any other place for the external card to be mounted. under /mnt/ there is only /mnt/sdcard

**Comment by droidmjt** [comment]
crap I forgot that the external path is always hexnumber, anyway, this info is enough for now. I try to cook some test build soon.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/44gt44upnbu4ip4/droidsounde167_29.apk?dl=1
try this, if it doesn't work, get me logcat log when you are adding dbbrowser

**Comment by Level99OCR** [comment]
Looking good so far, gonna test throughout the weekend and closing case for now. Thanks so much! Will try to break out a few different devices on stock and custom roms to give it a thorough run.
