### ISSUE TITLE
minipsf is broken

### ISSUE THREAD

**Issue by DavisOlivier** [droidmjt/Droidsound#352]
I cant play any minipsf file here. Tried on a compressed file(7z), all of them extracted in a folder, but when i click on them nothing happens. Sometimes the SystemUI restarts, the phone hangs, and if i try playing another type of file(ex: flac) it goes back to normal. I also tried cleaning the app's data and cache, with no change in its behavior.

**Comment by droidmjt** [comment]
does this happen with EVERY minipsf file? Where did you get these minipsf files?

**Comment by droidmjt** [comment]
I just tried a minipsf file and it works. Make sure the .psflib filename is correct in those minipsf files. Send me the minipsf file you are trying to play.

**Comment by DavisOlivier** [comment]
It's not Droindsound actually.
I downloaded Final Fantasy 7 files from zophar, i double checked the files and seems like the psflib is missing. I should note the site about that.
