### ISSUE TITLE
PSF not playing

### ISSUE THREAD

**Issue by DavisOlivier** [droidmjt/Droidsound#353]
I've been having trouble playing PSF files later. Sometimes the app tries to play them using UADE plugin, then it plays nothing. This doesnt happen with all PSFs though.
![screenshot_20170406-211154](https://cloud.githubusercontent.com/assets/10873838/24780508/3912846e-1b0e-11e7-96e9-abc26d77a05f.png)

**Comment by droidmjt** [comment]
Yes and that's because the zip is missing ff6.psflib.

**Comment by droidmjt** [comment]
Close this case.
