### ISSUE TITLE
xwb and xma problems

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#354]
I'm having problems playing xma and xwb

1. Xma files don't loop and crash the player, some marvel vs capcom fies don't play (they work in 28, but not in 30)

2. Xwb files don't play and crash the player they worked in version 28 but broke in 29

**Comment by droidmjt** [comment]
example files please

**Comment by Sir-Sabin** [comment]
https://mega.nz/#!a4lklAaD!Jkbek1Bvfbk2XqcCKGwxZV2XmBSW5N-H18NDCgiRbk0

Also can you get these fsb files playing they are from ducktales remastered

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xy8m4jydmgbgbur/droidsounde167_31.apk?dl=1
try this

**Comment by Sir-Sabin** [comment]
The xma still freeze the player when they try to loop, can you give us the option to use vgmstream instead of ffmpeg?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/g3p8vxtmtn1520y/droidsounde167_32.apk?dl=1
try this

**Comment by Sir-Sabin** [comment]
Works now thx and to note the xma files that don't work might have to reripped, if you run into a set that doesn't work goto hcs64.com forums to report it

**Comment by droidmjt** [comment]
all right, will do, I'll close this case.
