### ISSUE TITLE
Bcstm not working

### ISSUE THREAD

**Issue by tleej** [droidmjt/Droidsound#355]
Versions 29 and 30 no longer play bcstm files. Version 17 did not have this problem. If attempted after around 10 seconds, the phone becomes stuck on the lock screen. I've tried using Samsung J7 and Lg stylo 2 plus and both have the same problem.

**Comment by Sir-Sabin** [comment]
I can confim it's not working for me to on my Samsung Tab A, maybe something broke somewhere

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xy8m4jydmgbgbur/droidsounde167_31.apk?dl=1

**Comment by Sir-Sabin** [comment]
They work for me now, thx

**Comment by droidmjt** [comment]
yeah it works
