### ISSUE TITLE
Improvement: Widget visual overhaul

### ISSUE THREAD

**Issue by wolfensg** [droidmjt/Droidsound#359]
Remove "blue" Droid-sound mark on the widget or recolor it to grayscale.
Also possible to make customizeable coloring for widget (stored in CSS ideally).
CSS could also handle custom PNG's for widget (single CSS config for all widgets to make it simple)

**Comment by droidmjt** [comment]
what blue Droid-sound mark?

**Comment by wolfensg** [comment]
![screenshot_20170414-222544](https://cloud.githubusercontent.com/assets/27346831/25055158/7aa0362a-2161-11e7-8793-210a01dec2cd.png)

DROIDSOUND-E in upper-left corner.
and "Now Playing".

**Comment by droidmjt** [comment]
ah that, I'll see if I can make all this configurable

**Comment by droidmjt** [comment]
It's annoying to make it configurable, and if all is using gray color it looks dull, sorry.
