### ISSUE TITLE
BASSMIDI with "invalid" soundfont hangs the player

### ISSUE THREAD

**Issue by sneakernets** [droidmjt/Droidsound#361]
BASSMIDI seems to be finicky on ARM. invalid soundfonts make the player window unresponsive. Often I cannot select any other files and I have to force close the whole program.

PS: BASSMIDI still doesn't support custom velocity ramps? Jeez.

**Comment by droidmjt** [comment]
>>PS: BASSMIDI still doesn't support custom velocity ramps? Jeez.
Did anyone ever ask for this feature? At least I cannot remember. What exactly is custom velocity ramp?

Send me and invalid soundfont, otherwise I cannot fix it.

**Comment by sneakernets** [comment]
Alright, I'll upload and send a link after work.

Custom Velocity Ramps are a "feature" of the high-end soundfonts that are built with FluidSynth in mind. A shame that FluidSynth has been an absolute nightmare to integrate. I tried it myself on Windows 10 x64 and failed miserably.

**Comment by droidmjt** [comment]
Do those invalid soundfonts fail only with BASSMIDI or with everything else?

**Comment by sneakernets** [comment]
Seems to fail only with BASSMIDI on ARM. They work on my X86 computer. 

To be specific, on my computer I use XMPlay, the example media player program by the BASS devs that shows off BASS and the many plugins it can use. DroidSound-E is the closest Android approximation to XMPlay I could find (and I love the program so far).

**Comment by droidmjt** [comment]
all right, I'll wait for the invalid soundfont

**Comment by sneakernets** [comment]
https://forums.duke4.net/topic/6973-sc-55-soundfont-huge-update/page__view__findpost__p__242988 Here is a link to the sfpack file and the sf2. The sfpack version is now locking up my phone - it's still going silly as I type this. Truly bizarre behaviour.

**Comment by droidmjt** [comment]
copied the sf2 to sdcard/droidsound/soundfont/, selected it from the settings, selected default MIDI player to BASSMIDI, tried to play FF7 songs, all works fine. Using the latest build. Tested with x86 and ARM.

**Comment by droidmjt** [comment]
ah my bad, earlier I thought you meant DS-E BASSMIDI doesn't support the custom velocity thing, maybe you can ask Ian if he is willing to implement it.

**Comment by droidmjt** [comment]
I made the earlier test so that the soundfont folder had only one file (the sc55 sf2).

**Comment by sneakernets** [comment]
that would be awesome if he could. BASSMIDI is the best midi player I've used on every OS I've used from Win95 to 10 (and even OS X through Wine)

**Comment by droidmjt** [comment]
I don't see any reason why he wouldn't implement it. Anyway, the sc55 soundfont seems to work fine, I'll close this case, leave a msg. For your problem I need detailed steps how to reproduce the problem.

**Comment by sneakernets** [comment]
Alright, I'll provide that when possible. Lot on my plate right now unfortunately.
