### ISSUE TITLE
Remote Collection

### ISSUE THREAD

**Issue by DawgY411** [droidmjt/Droidsound#362]
Can someone please tell me how to access a collection on a home computer from outside of the local area network?  I assume I have to use a network link with the FTP protocol.  However, I have tried to do this numerous times, and I can never get the link to generate.  I am using v1.67.33.

**Comment by droidmjt** [comment]
For FTP you need to have an FTP server running at your home machine and your IP address publicly visible (no NAT). Another thing is SMB, works similar way.

**Comment by DawgY411** [comment]
Thanks for the reply.  I have an FTP properly configured.  I am using a DNS as well.  Isn't SMB for local shares?

**Comment by droidmjt** [comment]
ah yes, SMB is for local thingy, forgot that. FTP it is then. Just add the uri like ftp://user:password@1.2.3.4:port

**Comment by DawgY411** [comment]
I've tried multiple times with no success.

**Comment by DawgY411** [comment]
It's as if I have not submitted anything, because there is no link generated.  One will generate for the ModDB.

**Comment by droidmjt** [comment]
for the first line in the network link dialog put this:
/sdcard/droidsound/dsroot/Network
then the rest:
ftp://user:pass@1.2.3.4:80
myftp

**Comment by DawgY411** [comment]
No luck.  I'm out of options.

**Comment by DawgY411** [comment]
SMB does not generate a link either.  I used smb://username:password@LAN_IP/ where username = Windows username, Password = Windows password, LAN_IP = local static IP of computer, and I remembered to include the "/" at the end.

**Comment by droidmjt** [comment]
try these:
/sdcard/droidsound/dsroot
ftp://ftp.modland.com
modlandtest

**Comment by droidmjt** [comment]
also do you mind telling what kind of device you have, phone or tablet, what android OS?

**Comment by droidmjt** [comment]
if it still doesn't work, then it must be some external thing what prevents those .lnk files to be created

**Comment by DawgY411** [comment]
I have a Samsung Galaxy S8+ with Nougat.

**Comment by DawgY411** [comment]
I will have time later today or tomorrow to test this.

**Comment by DawgY411** [comment]
That information did not work, so perhaps it is something with my newer setup.  I appreciate the improvements you have made to the app, droidmjt.  Hopefully, this will work for me in the future.  Thanks for your help.

**Comment by droidmjt** [comment]
Ah new samsung, makes sense, must be some new shitty permission policy, at this moment there is nothing i can do.

**Comment by droidmjt** [comment]
now I'm able to reproduce the problem

**Comment by DawgY411** [comment]
Glad to hear it.  If you need help with testing, please let me know.  Always willing to help.  Much respect for your efforts droidmjt! =)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8jkk8ztceyvg6xn/droidsounde167_34.apk?dl=1
try this, it should work :)

**Comment by DawgY411** [comment]
I just tested it.  SMB works, but I am having difficulties with folders showing for FTP.  I assume this is an issue with something external to this app.  Thanks, droidmjt!

**Comment by DawgY411** [comment]
FTP is working now too.  Thanks again, droidmjt!

**Comment by DawgY411** [comment]
droidmjt, I have one questions I hope you can answer.  Can I use SFTP with Droidsound-E?

**Comment by droidmjt** [comment]
It should work, try and see. Something like sftp://user:pass@1.2.3.4:port

**Comment by DawgY411** [comment]
I tried and it wouldn't connect.

**Comment by DawgY411** [comment]
It worked, droidmjt.  I'm not sure what the problem was before.  Thanks again.

**Comment by droidmjt** [comment]
great, close this case :)
