### ISSUE TITLE
FC on start with build 35 and 37

### ISSUE THREAD

**Issue by Altomb** [droidmjt/Droidsound#364]
Tried erasing data, cache and droidsound folder, removed and installed, still get crash.

[tmp_311-droidsounde_crash_20170428_224052.log-1133638700.txt](https://github.com/droidmjt/Droidsound/files/965857/tmp_311-droidsounde_crash_20170428_224052.log-1133638700.txt)

**Comment by droidmjt** [comment]
Yeah I can see the problem, I'll get it fixed ASAP.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/y2mckefm34jbd1q/droidsounde167_38.apk?dl=1
try this, would you mind telling in what kind of device you use this app?

**Comment by Altomb** [comment]
Samsung SM-T670 (Galaxy View Wifi). New build works fine. Thanks
