### ISSUE TITLE
Stereo down mix issue while not using headphones.

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#365]
I don't know if it's a device/software specific thing but when you playback stereo audio on Galaxy S7's speaker, only one of the channels gets sent for output without any Stereo to Mono downmixing which might leave instruments out and sound weird. It happens only in the app so the device itself does Stereo to Mono downmixing everywhere else so I doubt they messed up something with their channel paths.

**Comment by droidmjt** [comment]
You are correct, Droidsound-E is not doing downmixing.

**Comment by VIRGINKLM** [comment]
Well that renders any phone with non stereo speakers output only one of the channels, which in case of tracks with hard panning sound absolutelly incorrect (Especially early Nintendo/Sega consoles).

**Comment by droidmjt** [comment]
There should be a setting in your phone called "Mono audio", if you enable that, it should fix your problem.

**Comment by VIRGINKLM** [comment]
This setting is only for headphones.

**Comment by droidmjt** [comment]
ah crap, thats true, well, I have no time to implement any downmixing feature now.

**Comment by VIRGINKLM** [comment]
Well, fair enough, when you have time could you put that on a list that can wait for later? I issued this mostly as I hoped it wasn't an oversight or something that slipped away because of software/hardware combination reasons (like the really weird 5.1 issue I had previously reported). I mean who would have guessed?

**Comment by VIRGINKLM** [comment]
@droidmjt I was listening the other day to some tracks which sounded unrecognisable because of this problem and reminded me of this issue. I hope you haven't forgotten about it. A good way to test this issue if and how it affects your device is if you playback an NES or Gameboy track and on the Stereo Separation setting you put 1.0 then you will always hear half of the channels and the track will sound wrong/like half of it is there. In my case (Samsung Galaxy S7) only the audio for the Right channel is playing back. (intresting considering that the speaker is placed on the right side and the device prefers landscape orientation with the speaker being on the right side, so makes me guess the software choses depending on somekind of OEM specific setting if that helps)

**Comment by droidmjt** [comment]
I have implement the force-mono option now but there is a problem in GME, if you enable echo or stereo mode the sound gets odd. The force-mono works for any other plugin.

**Comment by droidmjt** [comment]
solved it, I'll add a small bonus feature and upload a new binary

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/10833w0mm1r114n/droidsounde167_56.apk?dl=1
try and let me know how it works, you can access the switch from actionbar -> effects

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1oh6myocompuj7a/droidsounde167_57.apk?dl=1
use that instead, there was a small bug in the effects fragment

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1bphloh5gd0jz8h/droidsounde167_58.apk?dl=1
effects dialog wasn't ok but now it is corrected

**Comment by VIRGINKLM** [comment]
It might be my imagination but even with Mono disabled, when headphones are unplugged this results in mono sound too? (This is how it should work on devices with only one speaker but I'm not sure if it's a result of a bug or the intended behavior)

**Comment by droidmjt** [comment]
huh? let me check it

**Comment by droidmjt** [comment]
I'm confused, what exactly is wrong? This dowmin feature doesn't check if a user has stereo speaker or not. I was not able to find a way how to detect stereo speakers.

**Comment by VIRGINKLM** [comment]
Yeah, it seems like it's always Mono when headphones are unplugged and you can choose either to be Mono or Stereo when headphone are unplugged. This is acceptable to do only if it will be Stereo on devices with stereo speakers with headphones unplugged otherwise if it's Mono on these too then it's incorrect.

The actual current behavior in C:
if headophonesplugged=false
 Audio=Mono
else if headphonesplugged=true and MonoOption=false
 Audio=Stereo
else if headphonesplugged=true and MonoOption=true
 Audio=Mono

**Comment by droidmjt** [comment]
There is no any kind of logic in my code related to Mono feature, if you enable Mono from effects dialog then its Mono whether you have headphones plugged in or not.

**Comment by VIRGINKLM** [comment]
True but before that update there was no downmixing from Stereo to Mono either and now there is even with the option disabled. I'm honestly puzzled.

**Comment by droidmjt** [comment]
is it mono if you use headphones?

**Comment by droidmjt** [comment]
I mean that even if you don't enable Mono while use headphones, is it still mono?

**Comment by VIRGINKLM** [comment]
No it's Stereo, but what I'm thinking is, on a device with Stereo speakers, when headphones are unplugged and the Mono option is unchecked does it play in Stereo or in Mono? I need to test it on my Tab 3 10.1 since it's the only device I have with stereo speakers.

**Comment by droidmjt** [comment]
The downmix feature doesn't check and CANNOT check whether a user has a device with stereo speakers or not.
