### ISSUE TITLE
Loopstart and Looplength tags no longer working

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#366]
When enabling loop forever it just ignores the tags and plays the songs like normal loop.

**Comment by droidmjt** [comment]
what plugin and kindly send me an example song

**Comment by droidmjt** [comment]
I'll reopen this once you provide that requested info.

**Comment by droidmjt** [comment]
found those files and the plugin

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/adt73oym7klz9vy/droidsounde167_39.apk?dl=1
try this, this bug was a good find

**Comment by theGIZOID** [comment]
I was about to send you an e-mail containing the files before I forget it yet again (sorry for that).
Anyways, the plugin works again as intended. Thank you :)

**Comment by droidmjt** [comment]
no probs
