### ISSUE TITLE
XM/MOD/S3M/IT, etc. subsong cycling

### ISSUE THREAD

**Issue by wolfensg** [droidmjt/Droidsound#367]
The subsong cycling does not seem to work with modules (it works fine with SID or SAP files).

Example attached.
[02-world00.zip](https://github.com/droidmjt/Droidsound/files/1011610/02-world00.zip)

**Comment by droidmjt** [comment]
Where did you download that song? Secondly, contact openmpt developers incase you are 100% sure the song is not corrupted. I cannot fix those problems, they are library related.

**Comment by wolfensg** [comment]
There are quite many of them - mostly the game soundtracks where this "trick" is used to have couple of songs using the same sample set to have different tunes for different levels. The same trick is used in Bejeweled game where one single modules contain all the subsongs. 

In other words - the file is NOT corrupted (plays fine on XMPlay, WinAMP (Windows) and MoDo on android)

If this is library related - I guess nothing can be done here.

**Comment by droidmjt** [comment]
beyond the network works just fine.

**Comment by wolfensg** [comment]
I guess the following may be the case, i.e. it depends on the patterns used in the sequence in the module.

I mean the sequence of patterns in Beyond The Network may be like (example - not related to the real thing):
Pattern No. | Real Note Data of Song No.
1 | 1
2 | 1
3 | 1
4 | 2
5 | 2
etc.

While 02-world00 may have something like:
Pattern No. | Real Note Data of Song No.
1 | 1
2 | 1
3 | - no song data - empty pattern
4 | 2
5 | 2

Some players/libraries may interpret this empty pattern as end of song.
This is just a theory (which fits here quite nicely) - I cannot check it right now but can check later with Schism Tracker or Impulse Tracker.

**Comment by droidmjt** [comment]
Go to http://bugs.openmpt.org and report this issue. Once they have fixed it, I'll update the library.

**Comment by droidmjt** [comment]
I'll close this case, leave a msg.

**Comment by droidmjt** [comment]
Did you report this bug in openmpt bugs page?

**Comment by wolfensg** [comment]
I have tried but it seems that their issue tracker does not allow creating new accounts and I cannot submit new issue with the anonymous one.

**Comment by droidmjt** [comment]
login to system using user/pass as modplug/modplug, then create your account

**Comment by wolfensg** [comment]
Tried now - it said "account is turned off".

**Comment by droidmjt** [comment]
http://bugs.openmpt.org/signup_page.php
it should popup a dialog asking useraccount, there you need to put modplug/modplug as user/pass
then you can register a new account, i just tested it and it works.

**Comment by droidmjt** [comment]
after entering the modplug/modplug thing you should face this screen
![account](https://cloud.githubusercontent.com/assets/5917820/26362845/eb8c2c6e-3fe7-11e7-8163-5fa98dcd9e09.png)

**Comment by wolfensg** [comment]
Thanks - it seems that this default account works only with the signup page and not with login page, anyway, I've raised the issue:

http://bugs.openmpt.org/view.php?id=957

**Comment by wolfensg** [comment]
They have proposed a solution.

**Comment by droidmjt** [comment]
i think i'm gonna skip that "solution"

**Comment by droidmjt** [comment]
since there is nothing wrong with the library, you might just close the issue there and move on
