### ISSUE TITLE
Mtaf format

### ISSUE THREAD

**Issue by x-amp** [droidmjt/Droidsound#368]
I don't which update did it, but .mtaf files seem to have this loud static sound playing over them.  The game music I have in that format is from Metal Gear Solid 3.

**Comment by droidmjt** [comment]
please give me direct link to the song or email it to me

**Comment by x-amp** [comment]
Sending you an email

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/jmq36d1dakhyszs/droidsounde167_41.apk?dl=1
try this

**Comment by x-amp** [comment]
That did it. Wonder what was the matter

**Comment by droidmjt** [comment]
old vgmstream build :)

**Comment by x-amp** [comment]
Looks like this issue is back again.

**Comment by droidmjt** [comment]
I tried the sample song you sent with build _81 and I couldn't hear any problems.

**Comment by droidmjt** [comment]
if the problem is still there, send me a song or a link how I can reproduce the problem.

**Comment by x-amp** [comment]
I tried uninstalling and reinstalling it and it didn't work. I'm using a note 4 with Marshmallow.

**Comment by droidmjt** [comment]
could you send me one mtaf song so i can start investigating this? i cannot reproduce the problem

**Comment by x-amp** [comment]
Sent you an email

**Comment by droidmjt** [comment]
got the file, it seems to have 5.1 channel configuration, in the mean time try enabling the compatibility mode and see if it works

**Comment by x-amp** [comment]
Even in compatibility mode there's harsh static. I can barely make out the music. I'll have to see about completely wiping droidsound

**Comment by x-amp** [comment]
Did a complete wipe and that didn't work. Compatible on or off, it still has static.

**Comment by droidmjt** [comment]
silly question but are you using headphones when this static happens?

**Comment by x-amp** [comment]
Happened with every mtaf I've tried from that game. Does it with and without headphones. Device is a Galaxy Note 4

**Comment by droidmjt** [comment]
try another mtaf with different channel configuration

**Comment by x-amp** [comment]
Ok, been trying to find other mtaf files but they seem specific to that game. It only effects my note 4 though. I tried on my Tab e with nugat and it works find. Hope you can fix it. Much appreciated

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8h8y8u0wgkpvw6v/droidsounde167_82.apk?dl=1
try this

**Comment by x-amp** [comment]
Success. Thank you. It works as intended.

**Comment by droidmjt** [comment]
great
