### ISSUE TITLE
sound tempo on spc

### ISSUE THREAD

**Issue by Speedvicio** [droidmjt/Droidsound#369]
I noticed speed changes in the playback of the SPC files via the GME module.
The strange thing is that this problem only occurs when I transmit the stream via Bluetooth connection.

This is the file in question in particular "Minor Circuit BGM"
http://snesmusic.org/v2/profile.php?profile=set&selected=2809

**Comment by droidmjt** [comment]
I tested with and without BT, no problems. It's either your hardware or the bluetooth connection that is causing it. There is no code in DS-E related to tempo or audio when audiodata is being transfered from mobile device to BT device. If it would happen in GME plugin, it would happen in any other plugin and this would have been reported ages ago.
