### ISSUE TITLE
Bug while playing Lord of the rings minigsf

### ISSUE THREAD

**Issue by zen253231** [droidmjt/Droidsound#370]
Everytime I try to play the Lord of the rings return of the king minigsf files found on zophar.net Droidsound crashes.
I'd really like to play this awesome music on m'y phone !

**Comment by droidmjt** [comment]
post here the zip file with the music

**Comment by droidmjt** [comment]
I downloaded the music pack from the zophar site, works fine on the latest build. You can get it from the front page.

**Comment by droidmjt** [comment]
Luckily i checked more, there is a bug.

**Comment by droidmjt** [comment]
nevermind, no bug, just forgot something, get the latest version, it works perfectly.
