### ISSUE TITLE
M4A

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#372]
Playback of M4A music seems to cause issues when the song finishes, mostly freezing the app, or not allowing playback of other songs. Skipping an M4A before it finishes seems to resolve this with no noticed adverse effects.

**Comment by droidmjt** [comment]
kindly send here or email me one of those songs, so i can reproduce the problem

**Comment by droidmjt** [comment]
nevermind, I was able to find m4a files, tested with both plugins, BASS and FFmpeg, I can't reproduce any problems. Below is latest build:
https://www.dropbox.com/s/28v2iyqejr2hkas/droidsounde167_45.apk?dl=1

**Comment by froggestspirit** [comment]
Ill test the latest build later, although ive been using android 4.4 if it
makes a difference. If I still get the errors, ill try sending a sample
file, although im also not sure if it matters if the song that plays after
is an mp3, since the playlist i had has a mix of mp3 and m4a

**Comment by droidmjt** [comment]
and tell me what plugin was it, BASS or FFmpeg?

**Comment by droidmjt** [comment]
tested both plugins with same example song using Android 4.4, I also added MP3 files, no problems.

**Comment by froggestspirit** [comment]
It was FFMpeg, ill try with BASS later

**Comment by froggestspirit** [comment]
I just disabled ffmpeg and it doesnt play the m4a files. When selecting
them on a playlist, it went to the next mp3 song

**Comment by droidmjt** [comment]
FFmpeg plays those .m4a files what BASS cannot play. Have you tried by resetting preferences and then try again? If the problem persists, send me those files, otherwise there is nothing I can do.
