### ISSUE TITLE
Cannot change sorting preference

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#373]
Phone: Le Max 2
OS: lineage 13, 6.0.1
App: 167_45

When I try to change the sorting preference, setting does not change. When I click on the button again it still says title, and all folders are sorted by song title.

**Comment by jimbo1qaz** [comment]
Interesting, I renamed sdcard/droidsound to something else, backed up app data (titanium backup) and wiped, and bug was not fixed.

Then I restored droidsound folder and app data, and bug was fixed.

?????

**Comment by droidmjt** [comment]
I cannot reproduce this problem in any environment.

**Comment by droidmjt** [comment]
lineage 13, do you know if that is available for Samsung Galaxy S3 or S6 ?

**Comment by jimbo1qaz** [comment]
ugh
The problem started after I renamed /sdcard/droidsound to droidsound_, started DSE (to recreate examples.zip), then deleted droidsound and returned droidsound_ to droidsound. Then the settings completely reset and this bug appeared.

Is that a bug, or is what I did unsupported? Are there any residual issues in my configuration?

**Comment by jimbo1qaz** [comment]
ugh
The problem started after I renamed /sdcard/droidsound to droidsound_, started DSE (to recreate examples.zip), then deleted droidsound and returned droidsound_ to droidsound. Then the settings completely reset and this bug appeared.

Is that a bug, or is what I did unsupported? Are there any residual issues in my configuration?
