### ISSUE TITLE
cannot enable Bassmidi module

### ISSUE THREAD

**Issue by Speedvicio** [droidmjt/Droidsound#374]
On v165.45 is impossible to enable bassmidi module.

**Comment by droidmjt** [comment]
yeah I noticed, I'll check it ASAP

**Comment by droidmjt** [comment]
ah, I didn't select soundfont, after selecting soundfont and BASSMIDI it works as usual. I suppose you are using 167.45 instead of 165..45

**Comment by Speedvicio** [comment]
I have already selected the soundfont, but i found the bug.
"Override default soundfount" interferes with the selection of the soundfont selection and don't enable bass plugin.

**Comment by droidmjt** [comment]
ah right, if the soundfont cannot be found from the same folder where the music is, it won't use the default soundfont, I can fix it.

**Comment by Speedvicio** [comment]
I have the soundfont inside the compressed archive.
Can you add the detection of It from compressed archive?

Il 19 giu 2017 5:48 PM, "droidmjt" <notifications@github.com> ha scritto:

**Comment by droidmjt** [comment]
unfortunately I cannot add support for zip-compressed soundfont, sorry

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/o1ez46zuz30v1op/droidsounde167_46.apk?dl=1
try this

**Comment by Speedvicio** [comment]
Same problem

Il 23 giu 2017 8:30 PM, "droidmjt" <notifications@github.com> ha scritto:

**Comment by droidmjt** [comment]
This is what I did, I copied .sf2 and .mid file to /sdcard/Music and enabled the "Override default soundfount" and selected BASSMIDI as default MIDI player, I also have default soundfont file selected for BASSMIDI in preferences, once I selected the .mid file from the folder it started playing it using BASSMIDI, then I deleted the .sf2 file from the /sdcard/Music folder and after I restarted the song it started using the soundfont from the default location "/droidsound/soundfont". 

Double check that you have a soundfont selected for BASSMIDI in settings, otherwise it will use EMIDI. Also make sure you are not using archived soundfonts, It's not supported.

**Comment by Speedvicio** [comment]
I have midi file with sf2 in a zip, and soundfont inside a soundfont
folder, respective soundfont is selected, but when I enable override...
Droidsound swap to emidi, in addiction this version freeze the app when I
select the next file.
With previous versions this problem don't appear

Il 23 giu 2017 11:08 PM, "droidmjt" <notifications@github.com> ha scritto:

This is what I did, I copied .sf2 and .mid file to /sdcard/Music and
enabled the "Override default soundfount" and selected BASSMIDI as default
MIDI player, I also have default soundfont file selected for BASSMIDI in
preferences, once I selected the .mid file from the folder it started
playing it using BASSMIDI, then I deleted the .sf2 file from the
/sdcard/Music folder and after I restarted the song it started using the
soundfont from the default location "/droidsound/soundfont".

Double check that you have a soundfont selected for BASSMIDI in settings,
otherwise it will use EMIDI. Also make sure you are not using archived
soundfonts, It's not supported.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/droidmjt/Droidsound/issues/374#issuecomment-310773448>,
or mute the thread

**Comment by droidmjt** [comment]
if you would have told this information in the first place...

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/pd0c730wgwyw7cj/droidsounde167_47.apk?dl=1

**Comment by Speedvicio** [comment]
Ok now work.
I don't know if it is a problem, but during a mid play, on soundfont
selection don't appear available soundfont in the list.

Il 24 giu 2017 3:37 PM, "droidmjt" <notifications@github.com> ha scritto:

**Comment by droidmjt** [comment]
in which list soundfont doesn't appear during playing?

**Comment by Speedvicio** [comment]
when a midi is started or stopped i go into bassmidi options (by rapid module menu option) , under "Select soundfont", but the  list is empty.
To change a soundfont , i must to go in all options > audio, find midi section , open bassmidi and then change soundfont.
I can explain it better.

**Comment by droidmjt** [comment]
I understood what you mean, I'll see if I can get it fixed.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/t573c7fa9fbvbnx/droidsounde167_48.apk?dl=1

**Comment by Speedvicio** [comment]
If you don't select any soundfont, Droidsound swap to emidi, but now when
you select one, it work.
Thx for your patience and for great work.

Il 25 giu 2017 1:56 PM, "droidmjt" <notifications@github.com> ha scritto:

**Comment by droidmjt** [comment]
yeah that is intended behaviour.
