### ISSUE TITLE
M4A Crash with fadeout

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#375]
I seemed to pinpoint the previous error I had. I use the settings to append fadeout to the end of tracks (I add 5 seconds for the fadeout). I noticed the M4A files would crash the program around 5 seconds before ending (when the fadeout should happen). I added M4A to the excluded file types for fadeout, rebooted, and I no longer have this issue. So fadeout seems to mess with M4A files. Tested on build 167_45

**Comment by droidmjt** [comment]
Ah, all right, I'll check it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/o1ez46zuz30v1op/droidsounde167_46.apk?dl=1
try this

**Comment by froggestspirit** [comment]
Seems to be working, I removed both MP3 and M4A from excluded files extensions, rebooted, and it played a few songs (both Mp3 and m4a) all the way through without a freeze
