### ISSUE TITLE
libADLMIDI update

### ISSUE THREAD

**Issue by sneakernets** [droidmjt/Droidsound#377]
I'm not sure which version of ADLMIDI Droidsound-E, but [the version of libADLMIDI](https://github.com/Wohlstand/libADLMIDI) I use has some new patches in it (one by me) and it'd be awesome if said patches could be included in Droidsound-E.

**Comment by droidmjt** [comment]
I can update adlmidi to the latest if that is what you meant.

**Comment by sneakernets** [comment]
Yes, that'd be great.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/aappymhlk9cwotb/droidsounde167_52.apk?dl=1
this has updated adlmidi

**Comment by sneakernets** [comment]
thanks, will download it now

**Comment by sneakernets** [comment]
Works so far, woo! Thanks so much!

**Comment by sneakernets** [comment]
*knocks* yeah there is another update. That's my fault. Can we update?

**Comment by droidmjt** [comment]
where do you see this update?

**Comment by droidmjt** [comment]
ah nevermind, i'll check it

**Comment by droidmjt** [comment]
cannot update

**Comment by sneakernets** [comment]
hmmmm. :\

**Comment by droidmjt** [comment]
Actually, if I would know a way how to add that new bank to my adldata.cpp, then no problems.

**Comment by sneakernets** [comment]
Yeah, there's a binary in the bin folder after compiling on any platform that will take the fm Banks and compile them into a cop.

**Comment by sneakernets** [comment]
Double post... He mentions how to update it manually there.

**Comment by droidmjt** [comment]
ah shit, this update requires kode54 to change some stuffs

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2smalrn309wg760/droidsounde167_63.apk?dl=1
try

**Comment by sneakernets** [comment]
Will do

**Comment by sneakernets** [comment]
BY THE GODS IT WORKS! woohoo thanks!
