### ISSUE TITLE
ffmpeg looping issues

### ISSUE THREAD

**Issue by aocodes** [droidmjt/Droidsound#381]
I'm having problems looping anything that uses the ffmpeg plugin 
Using the loop endlessly option (which I use a lot and often forget to turn it off on m4a albums) kinda crashes? the app after the song finishes it won't let me play anything which requires restarting the app. also at3 files don't loop seamlessly.

**Comment by droidmjt** [comment]
ok, send me few of those songs what fail to play, otherwise close this case

**Comment by droidmjt** [comment]
nevermind, i found m4a and I was able to reproduce the problem, i'll check it

**Comment by aocodes** [comment]
should I post a link to a sample at3 file?

**Comment by droidmjt** [comment]
yeah post a link please

**Comment by aocodes** [comment]
At3: https://drive.google.com/open?id=0B-6jQUegOoPcZm51b0U2Vm1OaWc

**Comment by droidmjt** [comment]
yeah I know, I tried with some other AT3+ file and it worked but didn't work with your file. I'll check it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/whjjsx93kaey85w/droidsounde167_53.apk?dl=1
try this, I hope it's ok now.

**Comment by aocodes** [comment]
Well, the m4a problem is fixed and many of my at3+ files work great, but it's also very problematic on some other ones

This particular file just blanks out after the loop point and it affects other certain at3's
https://drive.google.com/open?id=0B-6jQUegOoPcOFFXcWpJNGI3NnM

I'll be testing this on other devices to see if the problem persists.
