### ISSUE TITLE
Vio2SF is "crashing" on too big zip archives

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#382]
Whenever I try to listen to the PMD Explorers of Sky Soundtrack DSE just spazzes out and slows down my entire device to a level where I have to force restart it. This soundtrack has a lot of files so it can take a few seconds to start playing, depending on how powerful the device is. However, it won't play at all and seems to be non-stop skipping songs so fast that the entire System UI can get irresponsive and even crash. Note that this only happens with Vio2SF, other plugins such as GSFPlugin, GME or VGMStream are not affected by this problem. I am running on Android 7.1.2 on my Sony Xperia Z2 with DSE version 167_53

I have sent you the file in question via E-Mail.

**Comment by theGIZOID** [comment]
P.S.: This Soundtrack used to work with an older build of DSE, I just don't know which one because I haven't listened to any of my 2SF soundtracks in a long time :(

**Comment by droidmjt** [comment]
does it happen if you have those files extracted in /sdcard/Music/ and play from there?

**Comment by theGIZOID** [comment]
Haven't checked yet, I'll try now.

**Comment by theGIZOID** [comment]
Yes, this still happens when I try to play it extracted both from my SD Card and my internal storage at that said location.

**Comment by droidmjt** [comment]
What ROM you are using?

**Comment by theGIZOID** [comment]
Resurrection Remix N for Xperia Z2 (Sirius)
https://forum.xda-developers.com/xperia-z2/development/rom-resurrection-remix-n-t3592250

**Comment by droidmjt** [comment]
Odd thing is that, I have 2SF with 6MB sized 2sflib and it works faster than the song you sent. It takes surprisingly long time to start playing but I don't get any crashes. I'll test with RR ROM.

**Comment by droidmjt** [comment]
It works but it's very slow. I can investigate what causes the slowness tho.
Try this 2SF: Ace Attorney Investigations - Miles Edgeworth [Gyakuten Kenji] (2009-05-28)(Capcom)
It works faster while the 2sflib is 6MB+

**Comment by theGIZOID** [comment]
Ace Attorney Investigations works just fine, however, PMD Sky doesn't even after deleting some files out of the directory. I can remember though that it used to play just fine. And thats weird because I also have PMD Time & Darkness and it plays just fine as well and is, with the exception of a few different instrumentations and less songs, the same game.

**Comment by droidmjt** [comment]
when it used to play, were you using the same Android version?

**Comment by theGIZOID** [comment]
I was using an entirely different device with a different ROM and an older build of DSE (I haven't updated it since I got my "new" phone).

Device: Samsung Galaxy S4
ROM: crDroid (https://forum.xda-developers.com/galaxy-s4/i9505-develop/rom-crdroid-t3480917)
Android version: 7.1.2
DSE version: most likely 167_39 or newer (See my issue #366)

**Comment by droidmjt** [comment]
I just tried a build from 2016 September (167_01) and it has identical behaviour. There hasn't been any changes in 2SF plugin recently.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/oa0ogavcgekalu7/droidsounde167_54.apk?dl=1
this is the latest build, small fix for Android 4.2

**Comment by theGIZOID** [comment]
Thats strange. But I am certain that it used to work. It used to work on many old builds ever since I discovered DSE through a friend with various stock and custom roms ranging from Android 4.2 to Android 7.1.2. I'm really suprised that it doesn't work anymore. What could the problem be?

**Comment by droidmjt** [comment]
Have you checked all the performance settings of Resurrection ROM? Make sure you have maximum performance enabled. 

I have tested the PMD songs with various Android OS versions including Resurrection ROM (for Samsung Galaxy S3, Android v7.1.2), the only thing is that it's slow, but it plays without problems.

**Comment by theGIZOID** [comment]
I have checked everywhere but I cannot find any settings for performance in my rom. Yes, it is a bit slow (usually takes 1 to 2 seconds) but even after a Minute it still isn't playing and my System UI crashes and I have to restart my device.

**Comment by theGIZOID** [comment]
Or in this case, DSE itself crashed.

**Comment by droidmjt** [comment]
I was testing the latest build on SGS3 (Resurrection ROM, 7.1.2), it takes around 5-7 seconds to start playing. I can test earlier builds but I doubt there is any difference.

**Comment by theGIZOID** [comment]
I could provide you a catlog if this can help.

**Comment by droidmjt** [comment]
Thanks but I don't think logcat helps in this case. I decompressed those two 2sflibs, the Ace Attorney is around 10MB but PMD is 134MB!!!, that's the reason why it takes long time to decompress. It could also be memory related why your device with the RR ROM gets stuck.

**Comment by theGIZOID** [comment]
134 MB? Thats amazing concidering that the original rom is only 128 MB big. That certainly explains why it takes longer than usual but that does not explain why PMD Time & Darkness work, they can't be that smaller than PMD Sky. I did a catlog anyways for my own interest and I found this:

`--------- beginning of crash
[ 07-08 18:33:54.803  1702: 1702 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.droidmjt.droidsounde, PID: 1702
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 525940 bytes
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:326)
	at android.app.NotificationManager.notify(NotificationManager.java:291)
	at android.app.NotificationManager.notify(NotificationManager.java:275)
	at com.droidmjt.droidsounde.service.PlayerService.updateNotification(PlayerService.java:181)
	at com.droidmjt.droidsounde.service.PlayerService.playNextFile(PlayerService.java:897)
	at com.droidmjt.droidsounde.service.PlayerService.playNextSong(PlayerService.java:715)
	at com.droidmjt.droidsounde.service.PlayerService.playNextSong(PlayerService.java:723)
	at com.droidmjt.droidsounde.service.PlayerService$MyHandler.handleMessage(PlayerService.java:601)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: android.os.TransactionTooLargeException: data parcel size 525940 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:877)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
	... 13 more`

This might be RR ROM causing the issue but I think that may be of an interest for you.
Anyways, may I ask how you've decompressed the 2sflib file and whether or not the decompressed file could work better than the compressed one as a workaround?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8mnuguimdj44ekc/2SF_PACK.zip?dl=1
get that, and let me know which songs worked for you, there are 5 songs.

**Comment by theGIZOID** [comment]
The results are a bit weird:
001 SEQ_BGM_TITLE (03eb) - doesn't work
0010 JINGLE_SPORTS - doesn't work
102 The Sure Bet Chocobo - from FINAL FANTASY VII - works but doesn't work after playing one of the songs that don't work
117 A Snowstorm of Cherry Blossoms - works
48 Doubtful Mokito's Mansion - works but has the same problem as The Sure Bet Chocobo

As a sidenote, I also have the soundtrack of Chocobo Tales and it always works when I play it from there even after playing one of the songs that don't work.

**Comment by droidmjt** [comment]
what happened when you tried to play for example this '001 SEQ_BGM_TITLE (03eb)' ?

**Comment by theGIZOID** [comment]
It directly jumped to '117 A Snowstorm of Cherry Blossoms'
Same thing happened when playing 0010 JINGLE_SPORTS
after doing so the other two files won't work and will also skip to '117 A Snowstorm of Cherry Blossoms'

**Comment by droidmjt** [comment]
Below is 2sflib decompressed sizes in bytes next to status:
111498372 [NOT WORK]
90236356  [NOT WORK]
84098852  [WORKS IF FIRST SONG]
73353924  [WORKS IF FIRST SONG]
62984868  [WORKS]

So this is a memory related issue.

**Comment by theGIZOID** [comment]
Huh, what a bummer. Then I'm only left with contacting the developers of the rom. Well, thanks for helping me narrowing down on what the issue is. I think I can close this issue now

**Comment by droidmjt** [comment]
what is the RR ROM version you use?

**Comment by droidmjt** [comment]
build date i mean

**Comment by droidmjt** [comment]
I'm gonna install this now: RR-N-v5.8.3-20170706-i9305-Official.zip and see how it works.

**Comment by theGIZOID** [comment]
Just when I wanted to check the date of the last build I realized that they have released an update for the rom today, lol. The curent build I am runing is 'RR-N-v5.8.3-20170617-sirius-Official' and the one I am downloading and going to flash and test is 'RR-N-v5.8.3-20170708-sirius-Official'.

**Comment by droidmjt** [comment]
I'm currently using this: RR-N-v5.8.3-20170414-i9305-Official.zip. Will flash the updated now.

**Comment by theGIZOID** [comment]
Nope, it still doesn't want to work even after the update :(
Though, they said they are going to release yet [another version later on](https://forum.xda-developers.com/showpost.php?p=72954841&postcount=955)

**Comment by droidmjt** [comment]
To be correct, this is not RAM related problem, the OS is not using that much RAM but more like VM heap related.

**Comment by droidmjt** [comment]
If possible, go to /system and open file named build.prop, then search for 'dalvik.vm.heapsize' or anything related to heap values and post those values here.

**Comment by froggestspirit** [comment]
For what it's worth, the 3 PMD2 games use a different format from SDAT and SSEQ, so chances are the rip has most of the ROM, and is probably not optimized. I'm not sure if it's related, but I've had a few N64 soundtracks stutter, or freeze like animal forest (plays fine for a while, then crashes after a few minutes), and DK 64/Yoshi Story (both stutter IIRC).

**Comment by droidmjt** [comment]
About the N64 songs, the library is known to be CPU consuming. For the other problem, if the VM heap value is low (32MB or less), try increasing it somehow.

**Comment by theGIZOID** [comment]
I opened that file and it reads:
'dalvii.vm.heapsize=768m'

**Comment by droidmjt** [comment]
It can't be that then. I'm out of ideas :(

**Comment by droidmjt** [comment]
Are you able to test other custom ROM with your Xperia Z2, for example Cyanogenmod?

**Comment by droidmjt** [comment]
https://forum.xda-developers.com/galaxy-s4/i9505-develop/rom-resurrection-remix-v5-8-0-t3507378

**Comment by theGIZOID** [comment]
I no longer have my Samsung Galaxy S4 :/

**Comment by droidmjt** [comment]
bugger

**Comment by theGIZOID** [comment]
I could try installing LineageOS (the new name for CyanogenMod). Though, the ROM I am running right now is already LOS-based.

**Comment by droidmjt** [comment]
If it's not too big trouble, please try.

**Comment by theGIZOID** [comment]
I'll download it, make a backup of my curent instalation, install it and try DSE so it'll take some time, but I will

**Comment by theGIZOID** [comment]
The same problem also happens after installing lineageOS itself
The build I've testet this on is the latest one: 'lineage-14.1-20170611-unofficial-sirius'

**Comment by droidmjt** [comment]
pity, I also tried lineageos for SGS3, works as usual

**Comment by theGIZOID** [comment]
So it seems to be an problem with lineageOS on sirius devices then?

**Comment by droidmjt** [comment]
It's difficult to say. I wish I had xperia z2 device.

**Comment by theGIZOID** [comment]
Is there anything I could do to further investigate this problem?

**Comment by droidmjt** [comment]
Would you be able to try with stock ROM (Android 6.0) ?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/3nvg61w8ysxk0om/droidsounde167_55.apk?dl=1
here is latest build, changed some small thing, try it if it makes any difference.

**Comment by theGIZOID** [comment]
sadly it doesn't :(

**Comment by droidmjt** [comment]
I can't think of anything else except test with stock ROM if you can, otherwise, close this case. Too bad I couldn't help here.

**Comment by theGIZOID** [comment]
I will definetly try this but for now I just let it be and do some other stuff,
I'll tell you the results next weekend.

**Comment by droidmjt** [comment]
sure, i'll close this case and reopen once you have news about the stock ROM

**Comment by droidmjt** [comment]
leave a msg

**Comment by theGIZOID** [comment]
You know what? I changed my mind. The reason on why I said next weekend is because flashtool just froze at checking the device info and I was like, I have no nerves for this. Later I realized that my bootloader was still unlocked and that I can't install stock firmwares with an unlocked bootloader, silly.

Well... I'm on stock Android 6.0.1 and lo and behold! It does work! It loads it in no time and plays it like it should. So it is most likely a problem with the sirius builds of LOS.

**Comment by droidmjt** [comment]
Excellent news :) It's definitely the custom ROM what causes the trouble. Now, can you go to /system, open the build.prop and tell what heap values it has?

**Comment by froggestspirit** [comment]
If its any help, my stock rom on LGStylo 2 plus played PMD sky fine,
although ive yet to test on my main music player

**Comment by droidmjt** [comment]
thanks, good to know

**Comment by droidmjt** [comment]
leave a msg, i'll close this since the mystery is solved :)

**Comment by theGIZOID** [comment]
It took me a while to root stock Android 6.0.1 but here it is:
'dalvik.vm.heapsize=512m'

**Comment by droidmjt** [comment]
I have the same value, maybe 768m is too much, who knows :(

**Comment by theGIZOID** [comment]
So it is less than in the custom rom. Does any of this mean something?

**Comment by theGIZOID** [comment]
huh, So I should try lowering the value?

**Comment by droidmjt** [comment]
since we don't know what causes this problem, its just guessing, if there is a solid way how to change the heap size then why not, you have nothing to lose :)

**Comment by theGIZOID** [comment]
I think so too. And if something breaks I still have my backup :)

**Comment by theGIZOID** [comment]
OH MY GOD THAT WAS THE SOLUTION!
So I've adjusted heapstartsize, heapgrothlimit, heapsize, heaptargetutilization and heapmaxfree to the same values as they were in the stock rock and it does freakn' work. Thank you so much <3

**Comment by droidmjt** [comment]
hey hey :) good to hear :)
