### ISSUE TITLE
Feature Request: Rescan Specific Folders

### ISSUE THREAD

**Issue by Galindorf** [droidmjt/Droidsound#383]
So, it would be nice to be able to just have Droidsound refresh the folder I'm currently *in* instead of needing to rescan the entire database to have changes show up. Or maybe a refresh 'button' that would make it show changes only in the folder you're currently viewing?

**Comment by droidmjt** [comment]
from the context menu you can select rescan and it will scan the selected folder only

**Comment by droidmjt** [comment]
you can enter in to context menu by holding your finger over db-browser item

**Comment by droidmjt** [comment]
I'll close this issue since the feature is already there.

**Comment by droidmjt** [comment]
leave a msg
