### ISSUE TITLE
Feature Request: Org player loop settings

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#384]
I'm not sure if it would be easy to add, or if it's more on the plugin's end, but the ORG files for CaveStory default to playing once, then fading out. It would be nice if there was an option for the plugin to change the default number of loops before fading. A small feature, but would be nice.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/zj4pm6nzq7mu6zl/droidsounde167_59.apk?dl=1
try

**Comment by froggestspirit** [comment]
This seems to have the song play for the defined number of loops, but after
that, the song stops, no fadeout, and doesnt start the next song

**Comment by ViLXDRYAD** [comment]
you wont believe how amazed i am as this morning spontaneously wanted to listen to some cave story music pretty hard, and came across this just little after you posted that fix; btw infinite loops works like a charm for me; thanks a lot, droidmjt!

**Comment by froggestspirit** [comment]
Infinite loop has always worked for them iirc

**Comment by droidmjt** [comment]
The plugin itself never had fade option and what do you mean by 'doesn't start next song' ? I just compared builds _55 and _59, the organya plugin works just like before except that now user can add loops. I have those .org (not archived) files in /sdcard/Music and they work as expected.

**Comment by droidmjt** [comment]
If there is a .org song what does't work as expected, post it here.

**Comment by froggestspirit** [comment]
I meant the append fade to end in the general settings. I'll have to try it
again, though it would not go to the next song after completing one, and i
would have to manually select a new one (bluetooth play controls wouldnt
let me change it then)

**Comment by froggestspirit** [comment]
I tested a bit more, it only freezes if append fade length is used, and it
freezes when the fadeout should start (for me 5 seconds). The loop count
also affects the lengths of non looped songs, like the fanfares, although
they only play once, then have silence for the extra time

**Comment by droidmjt** [comment]
send me one of those songs what don't loop

**Comment by froggestspirit** [comment]
Heres a sample, and the page with the rest of the music
http://www.cavestory.org/download/music.php

**Comment by droidmjt** [comment]
I know but I don't want to go through each song to find one what doesn't loop, provide one or close this issue.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/16oj8twxc3y10pj/droidsounde167_60.apk?dl=1
this works with fadeout, I can't help you with the non-looping songs

**Comment by froggestspirit** [comment]
I tried attaching one through email, it must not have sent. Some non
looping ones are "got item" and "heart tank"

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/4s6desujx2cpj7n/droidsounde167_61.apk?dl=1
try this

**Comment by froggestspirit** [comment]
This one works except for songs like "quiet" and "pulse" end early due to
detected silence. I noticed length is still calculated for fanfares as it
would be for looped songs. I'll try and look into the org format, and see
if I can find an easy way to tell if the song loops or not from the format

**Comment by froggestspirit** [comment]
So I looked into the format,
Bad news is that all songs have loop points, "non-looped" ones just loop after the last note.
Good news is I looked in all of the soundtracks files, and came up with a simple check:
-Loop start begins at 0xA in the file, and is 4 bytes long
-Loop End begins at 0xE in the file, and is 4 bytes long.
-If loop start is 0, then the song is a looping song.
-If (loop end - loop start) is equal to or less than 0x30, the song does not loop. Anything with a greater gap is a looping song.

**Comment by droidmjt** [comment]
02 - gestation.org, it loops but the loop_start is not 0

**Comment by froggestspirit** [comment]
The difference between the loop start and loop end is greater than 0x30

**Comment by droidmjt** [comment]
So there is just one thing we can use, the loop length size.

**Comment by droidmjt** [comment]
42 - xxxx.org song seems to have loop_start 0 but loop length size greater than 0x30

**Comment by froggestspirit** [comment]
Right, though in all cases, loop start being 0 means Its looped

**Comment by droidmjt** [comment]
and what if loop_start is not 0 ?

**Comment by droidmjt** [comment]
Nevermind, I'm confused here, I'll ignore completely the loop_start info.

**Comment by droidmjt** [comment]
How about '43 - unknown track.org', loop_start is 0, loop_size is > 0x30, there is about 22 seconds of sound and then silence, for over 5minutes. How to handle those cases?

**Comment by froggestspirit** [comment]
The loop start being 0 was more of an optional check, the main one is the
length. I'll take a look at the unknown track when I get home.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nkwz09pk6egzie5/droidsounde167_64.apk?dl=1
try if the logic works

**Comment by froggestspirit** [comment]
So as far as the fading, it seems to be working perfectly now. As far as
cavestory, I guess unknown song wasnt in the soundtrack I had, but after
checking, it does not follow my rules, and would technically loop if played
long enough (maybe its a veta song before the non-loop method was
finalized). The non-looped songs still play once, but the time is still
calculating the number of plays and fadout, leaving silence at the end of
them

**Comment by droidmjt** [comment]
give me one non-looping song what plays only once but time is calculated as numbers of plays

**Comment by froggestspirit** [comment]
I think they were all the non looping songs, like get item, get heart tank,
game over, and i almost forgot tokoros theme doesnt loop (fits the original
rules though)

**Comment by froggestspirit** [comment]
That being said, the time calculated for the extra is the looped part, plus
fadeout if its added to the end, so with a 5 second fadeout, it can add
around 7-9 seconds or so of silence

**Comment by droidmjt** [comment]
I just tried with 'Get Heart Tank.org', no matter how many loops I add it's still 8 seconds as it should. Same for 'Got Item.org'.

**Comment by droidmjt** [comment]
I'm using build _64.

**Comment by froggestspirit** [comment]
Youre right, i just tried again, it only adds the fadeout (if its appended
to the end), though also when turning off the append fadeout, i get 8
seconds like you, though it fades out the fanfares (most noticeable in got
item).

**Comment by droidmjt** [comment]
so non-looping songs shouldn't fade?

**Comment by froggestspirit** [comment]
No, i dont believe the non looping songs fade in the other plugins

On Jul 21, 2017 10:41 AM, "droidmjt" <notifications@github.com> wrote:

so non-looping songs shouldn't fade?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/droidmjt/Droidsound/issues/384#issuecomment-317019331>,
or mute the thread

**Comment by droidmjt** [comment]
what other plugins?

**Comment by droidmjt** [comment]
well, you just have to live with it.

**Comment by froggestspirit** [comment]
Like NDS, and GBA. I think thats also how we had the VGStream setup, since
it makes sense for a fanfare/jingle to not fade out
