### ISSUE TITLE
Sounds warble subtly with ADLMidi

### ISSUE THREAD

**Issue by sneakernets** [droidmjt/Droidsound#385]
This is a hard one to explain, but the best way I can explain it is that the pitch of the output gently rises up and down a few Hz in a ping-pong pattern. About 1 second between changes. It happens regardless if full panning is on or off.

I didn't notice it in my phone speaker, but in my car stereo it's very apparent. I tried turning on cycle accurate sound but that didn't fix it.

Any ideas?

**Comment by droidmjt** [comment]
I will rollback to earlier adlmidi thing since i have no idea about the problem.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nkwz09pk6egzie5/droidsounde167_64.apk?dl=1
rolled back the changes

**Comment by sneakernets** [comment]
Yeah it still happens. I think there might be an issue with more than ADLMidi because the nuclear option and oplmidi also do it. I'll make recordings of it.

**Comment by sneakernets** [comment]
BASSMidi seems unaffected.

**Comment by Wohlstand** [comment]
Warble output sound is impossible in libADLMIDI or in any other audio codec as it is generating an audio chunks of same sample rate (that was requested on a first initialization) of requested length. Maybe you requesting chunks of different length and playing them with same second time (different sample rate per each chunk) or an unstable pushing to audio output device as I think, or even weird way to resample the chunk. For a debug you can dump the pure output of libADLMIDI into a RAW file and then play it locally (for example, open it through an Audacity).

**Comment by sneakernets** [comment]
I think this has been resolved somehow? Turns out it was my Bluetooth implementation in my car causing a lot of this. False alarm!
