### ISSUE TITLE
Fadeout cut-off

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#386]
I noticed in one of the newer releases, the fadeout kind of cuts off a bit, as opposed to the smooth fadeout in the older versions. I did a line in recording of a square wave loop (converted to .brstm to use VGStream), and recorded in both release 62 (latest at time) and 13 (was probably the only old version I had laying around). This is with the same phone, and same settings
http://i.imgur.com/DYw75Ma.png
I noticed the old fadeout has more of a curve, while the newer version doesn't. It don't have a preference of what shape the fadeout is, although as seen in the picture, the fadeout appears to go silent at the same time, resulting in a cut-off. (I aligned the waveforms to the start of the second wave after the fade)

I don't know if this affects only VGStream, I thought I heard it in other plugins, but I'm not 100% sure.

**Comment by droidmjt** [comment]
I think this is because of the adjusted fadeout.

**Comment by froggestspirit** [comment]
Ive been listening to Diamond/pearl today with the ds plugin, i didnt
notice it there. It might only be vgstream

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nkwz09pk6egzie5/droidsounde167_64.apk?dl=1
try, also try the non-looped songs you posted some time ago with vgmstream
