### ISSUE TITLE
Gapless Playback and Play Song Endlessly don't go along with each other

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#387]
Like issue #366 the Loopstart and Looplength don't work but only when Gapless Playback is enabled. It's minor but still annoying to disable and re-enable the feature everytime when I need/don't need it (I usually just keep it activated). Gapless Playback should be automatically disabled as soon as Play Song Endlessly gets enabled and re-enabled if Play Song Endlessly gets disabled.

DSE Build: 167_64

**Comment by droidmjt** [comment]
I'll get it fixed soon.

**Comment by droidmjt** [comment]
try this:
https://www.dropbox.com/s/kinft9xlzlqdstm/droidsounde167_65.apk?dl=1

**Comment by theGIZOID** [comment]
This did the trick. Thank you :)
