### ISSUE TITLE
GENH files/AAC

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#388]
I recently looped X/Y's soundtrack, as it is natively in .AAC format. I had to do this by appending GENH headers to the files. The GENH files show up in Droidsound-e, although they barely play, and then crash. I left the non-looped songs as .aac, which don't show up. I believe this would be related to the FFMpeg portion of vgmstream. Would it be possible to fix?
[XYAAC.zip](https://github.com/droidmjt/Droidsound/files/1405199/XYAAC.zip)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/v5wbhigq9806u2a/droidsounde167_66.apk?dl=1
try this

**Comment by froggestspirit** [comment]
The genh appears to play perfectly now, although the aac stutters loudly.
If needed i can do genh headers for the non-looped ones

**Comment by froggestspirit** [comment]
Sorry, scratch that. After testing again, the aac files are working too!
Thanks!

**Comment by droidmjt** [comment]
great
