### ISSUE TITLE
Show subversion number on About screen.

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#390]
I hope it's not really troublesome to add the ability of showing subversions (nightly/test/snapshot specific version numbers), for example "v1.67.**66**" would be the latest.
Without it you have to memorize on what version you last updated manually, which is not ideal when you try to spot a regression or generally if you don't remember having the latest version.

**Comment by droidmjt** [comment]
Done, will be available in next release build, close this case.

**Comment by VIRGINKLM** [comment]
Thanx!
