### ISSUE TITLE
Sound Equalizer

### ISSUE THREAD

**Issue by miker84** [droidmjt/Droidsound#391]
I was wondering if it is possible to add a sound equalizer to the app.  I would like to increase/decrease other aspects of the audio like bass, treble, etc.  I have installed the latest one from here.  If you cannot, I understand.  I just thought I'd ask.   Still a great app though.

**Comment by droidmjt** [comment]
It is possible, but I have no time to add it. Close this case, this item is on my personal backlog, I will add it once I have more time.

**Comment by miker84** [comment]
Okay, thank you for responding.
