### ISSUE TITLE
Noise sharpening enabled (3.00) for every file format

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#393]
Just installed 167_68 on Moto G5 Plus, Android 7.0.
Noise sharpening is enabled for every file format(?), I need to disable individually for each extension (?). This should not be on by default.

**Comment by droidmjt** [comment]
Its per plugin. Do you think it sounds better if its 0.00 ?

**Comment by jimbo1qaz** [comment]
Noise sharpening is effectively a DSP which boosts treble, and should not be on by default (no other music player I know of).

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/zbe72hr9c8f3v73/droidsounde167_69.apk?dl=1

**Comment by JFD62780** [comment]
Pity.  I personally thought 1.00 was perfect.  Oh well... :p
