### ISSUE TITLE
Switch to vgmstream for AT3 playback instead of FFmpeg

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#394]
FFMpeg's implementation is a reference decoder and is not suitable for such application as it doesn't handle certain ATRAC metadata such as loop points so any track with looping will have random issues. Later vgmstream implementations actually handle these metadata properly.

PS: Could you also add the "Ignore loop points" option from vgmstream? It's also required for certain tracks.

**Comment by droidmjt** [comment]
All right, I can switch ATRAC to use vgmstream instead. 

Send me one of those songs what actually requires ignoring loop points.

**Comment by VIRGINKLM** [comment]
http://www.mediafire.com/file/6z16jf9b6yapk49/Nittoku_Inoue_-_Uknown_Title_%28XMB_Short_Edit%29.AT3

This one and virtually all SND0.AT3 files from PSP and PS3.

**Comment by droidmjt** [comment]
Actually, since it is only for a certain tracks then it sounds like a feature for vgmstream library itself.

**Comment by droidmjt** [comment]
I have changed the AT3 for vgmstream, will be availbable in next build, please close this case.

**Comment by VIRGINKLM** [comment]
"Actually, since it is only for a certain tracks then it sounds like a feature for vgmstream library itself."
It is, all those stuff are handled properly already by the latest version of vgmstream by kode54.
Closing.
