### ISSUE TITLE
Any app crashing on attempt to render icon of APK file (Android 6.0.1)

### ISSUE THREAD

**Issue by Wohlstand** [droidmjt/Droidsound#395]
This is an Android SDK 26.0.x bug that was fixed since SDK 26.0.2.
http://www.androidpolice.com/2017/11/09/adaptive-icon-bug-swipe-facebook-causes-random-reboots-oreo-devices-thankfully-latest-update-fixes/

It's very hard bug that causes any other application (ApkPure causes be frozen on attempt to run app installation, ANY (absolutely ANY) file managers are crashing on attempt to show icon of your APK file). When this app is getting be installed without crashes of file managers, the phone is going into infinite loop of reboots: Trebuched gets crashing too because of that freaking icon!

The "medicane" from this shit is manual nuking of installed app through recovery mode, mounting system partition, entering into ADB shell, mounting of everything by `mount -a` and removing of /data/app/com.droidmjt.droidsound-1 and /data/data/app/com.droidmjt.droidsound, and reboot phone. After this phone will work fine again.

I had same shit on lot of other apps are built through those damned buggy SDK.

**Comment by droidmjt** [comment]
I compiled it now with SDK 27.0.x, I hope it fixes the problem.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/yhehiyjr63a124t/droidsounde167_70.apk?dl=1
let me know if it works

**Comment by Wohlstand** [comment]
Yeah, the trouble is gone!
droidsounde167_69.apk is broken
droidsounde167_70.apk is fine!

**Comment by droidmjt** [comment]
great :)
