### ISSUE TITLE
request: NSF playlist browser

### ISSUE THREAD

**Issue by N0Lif3** [droidmjt/Droidsound#396]
NSF's, the format for NES game music where an entire soundtrack for a given NES game is all on a single NSF file, plays perfectly in Droidsound-E and I can skip forward through an NSF to play each of the tracks. However, it would be nice to have a playlist browser for these NSF files so I could skip immediately to a specific song that I want to listen to without having to skip through 30 songs to get to it.

Thank you! Droidsound-E is my favorite music app for Android. It has been a godsend for me!

**Comment by droidmjt** [comment]
You can add those subtunes to a playlist and play them from there. The feature you are asking is not feasible.
