### ISSUE TITLE
Another libADLMIDI update

### ISSUE THREAD

**Issue by Wohlstand** [droidmjt/Droidsound#397]
I see you are still use legacy libADLMIDI...

The new features of a recent libADLMIDI:
https://github.com/Wohlstand/libADLMIDI

- Built-in seek-ability with tell and song length when using a built-in MIDI player
- Built-in MIDI player is able to fix "too short drums" which are causing various sounding issues with FM instruments. That trouble was existed an entire age.
- Fixed a lot of on-initialization troubles, so, you no more need to setup every parameter to begin playing: just init, load file and play it with default settings if you don't want use library's extras!
- Added real-time MIDI events passing support: Instead of using a built-in MIDI player you can use your own just by passing of MIDI events through a set of special functions and use adl_generate() to take an output. Be sure the samples length is fits into the MIDI delay to next row of MIDI events.
- Partial support for XG standard such as multi-banks and ability to set any channel as percussion (by XG way. For GS way I'll must to implement a support for SysEx to be able to catch those events).
- Support for external bank files in WOPL format (are can be loaded as from file, and also from the memory)

One note:
The adl_generate and adl_play functions are accepting an absolute count of samples (I.e. there are count of "short" items in given array and there are not meaning "samples per channel") and returning the same "count of 'shorts'" that was generated in fact. So, to take a count of stereo samples you must divide returned value into 2. If you giving the count of samples to take, you must multiple it into 2.

I have even added the VLC plugin into `utils/vlc_codec` that an example of real-time API usage and a super-simple SDL-Audio based example added into `examples/sd2_audio` folder

Note number two:
I have replaced adl_errorString with adl_errorInfo to don't set an error of one file globally. So, the old adl_errorString is used for initialization errors while adl_errorInfo is used for library runtime errors such as incorrectly given parameter, bad format of the bank file or a bad format of the MIDI file, etc.

Note number three:
Library is NOT thread-safe when you are using same instance (a pointer given by adl_init() call creates an instance)! You can't safely call libADLMIDI's functions on the same instance, so, use mutexes. However, you can process two or more libADLMIDI's instances in different threads. Just don't use same instance in multiple threads.

**Comment by droidmjt** [comment]
Thanks for the infos. I'll take this information to correct person since I don't deal with external library updates.

**Comment by sneakernets** [comment]
I was wondering if this was resolved. My newest DMXOPL is in the latest libADLMIDI and it would be really nice to be able to use it.

**Comment by droidmjt** [comment]
nope, I forgot this one, sorry about that. Actually, the only thing to be done here is to ask kode54 to update the MIDISynth library with the new ADLMIDI :)

**Comment by Wohlstand** [comment]
Kode54 made own fork of ADLMIDI, and after works, he wasn't touched it anymore except of minor fixes. My libADLMIDI has appeared a bit later, and it's totally different thing. However, don't scary, the API of it is friendly ;3
Just, try to review it and try few experiments with it before to take it.
Unlike Kode54's implementation, libADLMIDI has better support as Me and my friend are progressing it with new festures and quality improvements (you can read what was done in the changelog you will find in the readme).

**Comment by Wohlstand** [comment]
Oh, do you mean you are using the library which is combined set of codecs and where Kode54's ADLMIDI is included? Then, I gonna to check it out and update it by myself... @kode54 seems not so active as I see...

**Comment by droidmjt** [comment]
>>Oh, do you mean you are using the library which is combined set of codecs and where Kode54's ADLMIDI is included?

that's what I meant, the MIDISynth library.

**Comment by Wohlstand** [comment]
Okay, can you give me the link to repo with actual and most fresh MIDISynth source? Is that here on GitHub, or on GitLab? (some code of kode54 I also saw on GitLab place).

**Comment by Wohlstand** [comment]
P.S. Re-open this and assign me, as I'll do the work on MIDISynth upgrading until you will be able to puck up it with all most fresh updates and apply to the Droidsound.

**Comment by droidmjt** [comment]
no, I think this one is newer: https://gitlab.kode54.net/kode54/foo_midi

**Comment by Wohlstand** [comment]
The second is not the MIDISynth, but plugin for the FooBar player. It will have altered codebase than original MIDISynth library. So, I'll try to compare both of them, and if most of things will be same, I'll try to patch some of them with my libADLMIDI.

**Comment by kode54** [comment]
The MIDISynth library is also on GitLab, and it's kind of nasty. It really needs some love. The AdLib mode is not really that good.

**Comment by droidmjt** [comment]
Both repos have adldata.cpp but the foo_midi has also adlplayer.cpp, I believe the foo_midi repo has the latest ADLMIDI stuff.

**Comment by droidmjt** [comment]
leave a msg, when its finished

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8bkrw23marpf7kq/droidsounde167_117.apk?dl=1
@sneakernets try this one, it has also option to load custom wopl files, let me know how it works

**Comment by Wohlstand** [comment]
As my personal request: can you add next options:
- Run in PCM rate, I using it to reduce CPU eating on slow devices
- Option to choose emulation core: Nuked OPL3 or DosBox.
- Add '4' chips count
The thing works, but plays music choppy even with two cores and no way to configure for performance. Even my shitty demo player works much better in a case of sound stability...

**Comment by droidmjt** [comment]
get the build 119 from the open issue, added 4OP count + emulation core options

**Comment by Wohlstand** [comment]
Okay, thanks!

Anyway, about of 4OPs count: please set them be default `-1` which means "Auto", and the description that `-1` is "auto" by bank. In dependence on count of 4op instruments in the current bank, the count of channels is allocating by the formula. It's bad idea to have fixed count of 4ops, otherwise, you will overuse 4op channels where there are unneeded as bank contains 2op only, or missing when bank is 4op.
