### ISSUE TITLE
VGMPlay Update (Nuked-OPN2)

### ISSUE THREAD

**Issue by Ozaleto** [droidmjt/Droidsound#398]
Hey there, in a recent VGMPlay (https://github.com/vgmrips/vgmplay) update, they have added a new OPN2 core called Nuked-OPN2. It is by far the most accurate core out there. I would really appreciate it if you are able to update VGMPlay in order to support this new OPN2 core as it would really improve the quality of playback. 

Also, with this update. It allows us to switch between YM2612 (OPN2) and YM3438 (OPN2C), which, I believe is this commit right here: https://github.com/vgmrips/vgmplay/commit/a1dd05673b4c980cce4cea0b899ec7990c09b612

It would be great if an option to be able to switch between them was added as well.

Thank you for this awesome app!

**Comment by droidmjt** [comment]
I add the switch. I close this case and reopen once the feature is implemented.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/9rbgrabhu37baid/droidsounde167_71.apk?dl=1
test this please

**Comment by Ozaleto** [comment]
I tested the 167_72 one that was posted since that was more up to date, and it seems to be working perfectly. Thanks!
