### ISSUE TITLE
Customizable VGMPlay.ini

### ISSUE THREAD

**Issue by Ozaleto** [droidmjt/Droidsound#401]
Hello there, as I was stumbling through VGMPlay.ini:(https://github.com/vgmrips/vgmplay/blob/master/VGMPlay/VGMPlay.ini) 

I noticed that there's a lot of features here that would be very useful, such as being able to change the:
- Playback Rate (Allows us to switch between 50Hz and 60Hz)
- Sample Rate (Able to force native sample rate for some soundchips)
- Fade Time 
- Resampling Mode (Low end devices)
- Chip Sample Mode and Rate (For low end devices)
- Audio Buffer (For low end devices)
- Muting channels (great for those who want to study the music)

and more!

I feel like this would help make this app much more useful for people who are using it as a VGM Player, making it more customizable than what it is already.

**Comment by droidmjt** [comment]
I'll add the Playback Rate setting. What comes to 'low end devices', any Android 4.0 device is able to playback any VGMPlay music.

**Comment by Ozaleto** [comment]
A couple of users on a FM server have stated that it runs rather poorly on their old phone, and that an option like that would be really helpful for them to at least run it without any stuttering issues.

**Comment by droidmjt** [comment]
I would like to know the specs of those phones.

**Comment by Ozaleto** [comment]
Only was able to get information from one user. This user has a Lenovo A1000 running Android 5.0. 

- The chipset is Spreadtrum SC7731.
- CPU is a Quad-core 1.3GHz Cortex-A7
- GPU is a Mali-400MP2
- Has 1GB of RAM

It's just any song whenever using Nuked-OPN2.

**Comment by droidmjt** [comment]
The stuttering happens only in YM2612 songs where Nuked-OPN2 is effective. According to stats, there are just 10 sets (games) using that chip. Secondly, what's the meaning of adding Nuked-OPN2 mode if a user eventually needs to use resampler or other method to degrade the quality? Bottom line, if your phone cannot handle NukedOPN2, then don't use it or buy a new phone.

**Comment by Ozaleto** [comment]
I don't understand what you mean by 10 sets, unless it you mean only 10 people are using it, because it is a YM2612/YM3438 core that will work with *all* .vgm(s) that use those chips, which in my case personally, over 600 games that were published back then officially. On top of other machines such as FM Towns (that uses the YM2612 but at a higher clock rate) and Sega System 18 (that uses two YM3438s). 

The point here isn't force resampling mode at all, it's that it should be there along with other VGMPlay.ini customizable features so it would help those who would benefit from it, and can left unused from those who don't need it at all. 

It's a matter of options given to the user to suit their needs, after all, that is what VGMPlay.ini is for in the first place, and I feel like not being able to edit that in some sort of way is limiting to the user, when it would be very beneficial as it can easily solve all sorts of problems such the Nuked-OPN2 stuttering issue, which would not require spending money on a new phone or not using it in the first place. 

The appeal of Nuked-OPN2 is how it is the only core that has successfully emulated hardware bugs, which some composers have arranged music around these hardware bugs in mind.

**Comment by droidmjt** [comment]
According to vgmrips.net, there are only 10 sets which use YM2612 chip and 34 sets which use YM3438 chip, so 44 sets/games in total. Previously I didn't notice the YM3438 thing.  Nuked setting affects only those, no other chips.

**Comment by Ozaleto** [comment]
That is vgmrips.net, it doesn't include Sega Genesis games because it has its own site:
http://project2612.org/

This puts it over 600 now.

**Comment by droidmjt** [comment]
I'll check it.

**Comment by Ozaleto** [comment]
Alrighty.

**Comment by droidmjt** [comment]
try this: https://www.dropbox.com/s/bmojesu7fnbvx4l/droidsounde167_75.apk?dl=1
added some of those options mentioned above,

**Comment by Ozaleto** [comment]
Seems to be working great, thanks for this!
