### ISSUE TITLE
Overamplified BASSMIDI Volume by default

### ISSUE THREAD

**Issue by spaztron64** [droidmjt/Droidsound#402]
Hi, I've been using an older version of Droidsound-e for about a year now, and regarding BASSMIDI, i didn't really have any issues.
A few days ago I upgraded to the latest version listed in the links at the bottom of the main page here, and I noticed that the default volume of BASSMIDI is way too loud.
I tried messing with the Soundfont volume setting, it didn't do a thing. I changed the Plugin Volume in the dialog box that displays when playing a song, and that solution is only temporary, lasting only while the song is playing. As soon as I stop playing the song and try playing again, the default loud volume returns.

Mind checking this out?

**Comment by droidmjt** [comment]
send me the song and soundfont for testing please

**Comment by spaztron64** [comment]
http://www.mediafire.com/file/mz98kb1c1q44iuh/CrescentDream.mid
http://www.mediafire.com/file/tngbgqsqu45lzde/CHAOS8M.SF2

Just to clarify, Had the same issue with different midis and different soundfonts.

**Comment by droidmjt** [comment]
All right, I'll investigate this.

**Comment by droidmjt** [comment]
Try this: https://www.dropbox.com/s/ipbudg5ioz8wdqu/droidsounde167_76.apk?dl=1

If the problem is still there, reset preferences and try again. I was not able to reproduce your problem but I noticed another BASSMIDI related problem. It could be that those two bugs are related, not sure.

**Comment by spaztron64** [comment]
Nice work dude, it's all normal now.

**Comment by droidmjt** [comment]
great
