### ISSUE TITLE
About playing YMF278B (OPL4)

### ISSUE THREAD

**Issue by OGJunerenP** [droidmjt/Droidsound#403]
Yo! I got a problem for playing YMF278B thru either VGMPlay or GME, I've put yrw801.rom in any Droidsound directories but it didnt work. Homie, can you fix this lil' problem, please. Thanks, bro.

BTW, here's the yrw801.rom here: http://www.msxarchive.nl/pub/msx/games/roms/system/Extensions/Moonsound/yrw801.rom.zip
Here the Sonyc for MSX2+ that uses YMF278B, here's the link: http://vgmrips.net/files/Sonyc_MS.zip

I gon' be check here everyday but you can reply here anytime, homie.

**Comment by OGJunerenP** [comment]
I gon' be check here everyday but you can reply here anytime, homie.

**Comment by droidmjt** [comment]
YO!, have you tried to copy it to sdcard/droidsound/vgmplay ?

**Comment by OGJunerenP** [comment]
Yup, but didn't work.

**Comment by OGJunerenP** [comment]
When I play any of Sonyc tracks, it plays blank. That's the problem.

**Comment by droidmjt** [comment]
Problem found and fixed, will upload new binary in this weekend.

**Comment by droidmjt** [comment]
try this: https://www.dropbox.com/s/z90tdus5wcnwu5i/droidsounde167_77.apk?dl=1

**Comment by OGJunerenP** [comment]
A'ight, I'll go check. I'm using Samsung Galaxy A5 Duos running Android 6.0.1 (Marshmallow).

**Comment by OGJunerenP** [comment]
Damn, man. It worked! I've moved the yrw801.rom into vgmplay folder then I played All the tracks of Sonyc then it played perfectly! Thanks, homie!

**Comment by droidmjt** [comment]
Good to hear, enjoy :)
