### ISSUE TITLE
Incorrect behavior/logic in Loop count option.

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#404]
Currently setting in VGMstream Loop count to 0 has as a result when the song is about to hit the first loop point it simply abruptly ends the track. The correct behavior should be to ignore all loop points in any given time in the track and play the entirety of the audio file. I guess it's a simple oversight/logic mistake.

**Comment by droidmjt** [comment]
I was not aware of this, I'll see if i can get it changed.

**Comment by droidmjt** [comment]
Could you give me a song what I can use to demonstrate this?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nktc8yyog79cvjp/droidsounde167_78.apk?dl=1
see if this works as expected

**Comment by droidmjt** [comment]
bugs found from build 78, don't use

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/zn6wqf8mp5f7lwq/droidsounde167_79.apk?dl=1
try this

**Comment by droidmjt** [comment]
leave a msg if this doesn't work as intended

**Comment by VIRGINKLM** [comment]
Link is dead and 1.67.89 seems to haven't changed anything (?)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7bml1fh7tese6s6/droidsounde167_83.apk?dl=1

**Comment by droidmjt** [comment]
crap, not completely fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/98b4v4kppi54x6k/droidsounde167_84.apk?dl=1
try this, added a new switch to vgmstream settings

**Comment by VIRGINKLM** [comment]
It's halfway done. It seems to ignore the starting point loop but not the ending point loop so playback will skip loop point A but will not skip beyond loop point B. I like the idea of a separate option more though so that's definitely the right direction.

**Comment by droidmjt** [comment]
post a song/link you are using to test this feature please

**Comment by VIRGINKLM** [comment]
Sure.
http://www.mediafire.com/file/6z16jf9b6yapk49/Nittoku_Inoue_-_Uknown_Title_%28XMB_Short_Edit%29.AT3

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7fbqhqjs5wi3ggm/droidsounde167_85.apk?dl=1
try this, i hope it works better

**Comment by VIRGINKLM** [comment]
Yep, this seems to have done the job. Thanx! Closing.
