### ISSUE TITLE
SID 8580 digi's

### ISSUE THREAD

**Issue by mbwum73** [droidmjt/Droidsound#405]
Not realy a bug, but a feature request.
When I choose the SID 8580 model to play sid files in droidsound, files with digitized sounds in it doesn't sound correct. Digi's play on a very low volume.
For instance skate or die intro by Rob Hubbard, or gameover by Martin Galway. You can hardly hear the sampled sounds.
This is caused by the SID 8580 model. On a real C64 the SID 6581 can play samples, the 8580 can't (at least nog in a decent volume). So in fact the emulation of droidsound is good.
However it's not very practical. Many emulators, like Vice or Hoxs64 have added a digi boost option, to correct the low volume of sampled sounds on the SID 8580.
Off course I can play my sids on the 6581, but the 8580 has a better filter.
Can you please add a tick box to the 8SID 580 emulation to boost the digi's. Just like in Vice and Hoxs64?

**Comment by droidmjt** [comment]
I'll first contact the author of the library, I need to know if the feature is supported at all.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nktc8yyog79cvjp/droidsounde167_78.apk?dl=1
See if the digi boost works, it's only for ReSID. There is one thing about this feature, when the next version of sidplay2fp library is released, you can say goodbye to this feature, unless the author of the library is able to get it working on 2.x.x version.

**Comment by mbwum73** [comment]
Yes! It works great. Thanks!
Maybe one smal textual change. Call it Digi boost 8580. That's because this only has effect on the 8580.
But I'm very happy this works! Thank you so much.

**Comment by droidmjt** [comment]
it will be changed in next build, good that it works as expected, I'll close this case

**Comment by droidmjt** [comment]
bugs found from build 78, don't use

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/zn6wqf8mp5f7lwq/droidsounde167_79.apk?dl=1
better than build 78
