### ISSUE TITLE
Droidsound crashes if Modland no longer has files in Modland DB

### ISSUE THREAD

**Issue by kyz** [droidmjt/Droidsound#406]
If Modland DB is installed, one can browse Modland without any network connections.

However, if the underlying Modland has changed, and has removed files/dirs, then navigating to those files and trying to play them crashes Droidsound.

Example: I have Modland DB from about November 2017. On 24th December 2017, Modland removed author dirs in directories beginning "Hippel" except for "Jochen Hippel" (ftp://ftp.modland.com/readme_updates.txt),  so for example ftp://ftp.modland.com/pub/modules/Hippel/Wally%20Beben/ no longer exists. Navigating to MLDB -> Hippel -> Wally Beben and playing any module there causes Droidsound to crash complete, instead of giving some error like "this file no longer exists in Modland"

**Comment by droidmjt** [comment]
Good idea, I'll add a toast telling 'file not found'.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nktc8yyog79cvjp/droidsounde167_78.apk?dl=1
added Toast to inform about a missing file.

**Comment by droidmjt** [comment]
bugs found from build 78, don't use

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/zn6wqf8mp5f7lwq/droidsounde167_79.apk?dl=1
this should be better

**Comment by droidmjt** [comment]
leave a msg if this doesn't work as intended
