### ISSUE TITLE
Support for subsongs in VGMStream

### ISSUE THREAD

**Issue by bnnm** [droidmjt/Droidsound#408]
Some music formats supported by vgmstream (.fsb, .xwb, etc) can contain multiple subsongs in the same file. It would be an useful feature to add I think, but the player (Droidsound) needs to do some work.

Example file: [frpg2_smain.zip](https://github.com/droidmjt/Droidsound/files/1835456/frpg2_smain.zip)

In case it helps, here is example of how vgmstream needs to be called:
```
open_song(filename) {

    // first open the file normally. By default the initial subsong number is 0.
    STREAMFILE * vgmFile = open_stdio_streamfile(filename);
    vgmFile->stream_index = 0; //default, opens the first subsong
    VGMSTREAM * vgmStream = init_vgmstream_from_STREAMFILE(vgmFile);

    // now we can check if the file has subsongs:
    if (vgmStream->num_streams > 1) {
        for (int i = 0; i < vgmStream->num_streams; i++) {

            // set to change the subsong: 1=first, 2=second, etc
            vgmFile->stream_index = (i+1);

            // the VGMSTREAM *must* be recreated with the new stream_index to take effect
            VGMSTREAM * sub_vgmStream = init_vgmstream_from_STREAMFILE(vgmFile);

            // queue to play, add to playlist, etc
           ...
       } 
    }
    else {
       // play song normally, etc
       ...
    }
}

```

(vgmstream contributor, reporting this on behalf of another user)

**Comment by droidmjt** [comment]
yeah I'll add it, thanks for reminding.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/kahsg8gusuh47yw/droidsounde167_81.apk?dl=1
try this, at least the example file worked as expected

**Comment by droidmjt** [comment]
I'll close this issue, if it doesn't work, leave a msg
