### ISSUE TITLE
To Many Errors, Stopping on spc, vgm and some gsf files

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#409]
I'm getting To Many Errors, Stopping on spc, vgm and some gsf files when trying to play with 80, if you know about the and trying to fix this just close this

**Comment by droidmjt** [comment]
I really don't, send me logcat logs, otherwise close this case.

**Comment by droidmjt** [comment]
And please be more specific, what kind of errors? how to reproduce the errors?

**Comment by droidmjt** [comment]
Try this, take one song of each format (spc, vgm, gsf) which made the system crash/reboot/etc etc, put them in to /sdcard/TestMusic/ and play them from there, do not use archives, just plain files. If possible, uninstall the apps you previously mentioned in the other ticket. Play these files in sequence and see if it crashes.

**Comment by Sir-Sabin** [comment]
That's the error droidsound is giving me when i play them via 7z files, work fine extracted,
Here's the log https://www.dropbox.com/s/utol7rwd99ere98/logcat_03-22-2018_03-09-17.txt?dl=0

**Comment by droidmjt** [comment]
Ah 7z, makes sense, i recently updated archiving stuff, will fix it soon.

**Comment by droidmjt** [comment]
no errors in that log, briefly explain what happens?

**Comment by Sir-Sabin** [comment]
When i try to play them that are in 7z droidsound just says failure to many errors stopping and just not plays them, it doesn't crash it, it just refuses to play them

**Comment by droidmjt** [comment]
all right, I get this fixed as soon as possible.

**Comment by droidmjt** [comment]
could you send one of those 7z archives where this failure happens?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/kahsg8gusuh47yw/droidsounde167_81.apk?dl=1
try this, i tested a few different kind of 7z archives and worked better now

**Comment by Sir-Sabin** [comment]
It seems to be working now I'm going to close this ty for the fix
