### ISSUE TITLE
Crash Loop on Android 8 Oreo

### ISSUE THREAD

**Issue by Famic0m** [droidmjt/Droidsound#410]
I have tried every apk on the repo and it just will not run on Android 8 at all have tried uninstalling and reinstalling and nothing

**Comment by droidmjt** [comment]
works for me on Android 8

**Comment by Famic0m** [comment]
I recently updated to android 8 on my galaxy S8 and ot allows me to open the app and select a song but as soon as it attempts to load the song it crashes so I restart the app try again and it tells me too many failures stopping and won't play anything @droidmjt

**Comment by droidmjt** [comment]
and how exactly you are trying to play your songs, from archives? plain files? over network? what music formats?

**Comment by Famic0m** [comment]
@droidmjt its VGM files and its plain and compressed files

**Comment by droidmjt** [comment]
if you put any .VGM file to /sdcard/Music/, go there with filesystem browser and try to play it, you get the error message?

**Comment by Famic0m** [comment]
problem was I moved my door folder to a backup location so I wouldnt lose it and for some odd reason it wasn't refreshing automatically but I moved it back and rescanned the database and  it seems to be working now @droidmjt

**Comment by droidmjt** [comment]
yeah, if you move around already scanned folders and they use DB, you need to rescan database

**Comment by Famic0m** [comment]
and it took me FOREVER to figure that out oh well we live and let learn xD @droidmjt

**Comment by droidmjt** [comment]
better late than never :)
