### ISSUE TITLE
GSF Player

### ISSUE THREAD

**Issue by DavisOlivier** [droidmjt/Droidsound#411]
I've been using the app for a while without updating it, so i recently updated and noticed Highly Advanced isn't being used anymore and mGBA took its place. But mGBA doesn't sound so good imo, and doesn't have the interpolation option either. Could you please add some option to switch between the two players? Thanks in advance.

**Comment by droidmjt** [comment]
that switch would be useless because the whole library is gone, what I could do is to add filter effects what could be used in any plugin

**Comment by DavisOlivier** [comment]
That would be a great add, but mGBA still isn't that great as i noticed some channels overlapping others in loudness

**Comment by droidmjt** [comment]
>>That would be a great add, but mGBA still isn't that great as i noticed some channels overlapping others in loudness

please send me a song where I can hear that happening

**Comment by DavisOlivier** [comment]
The most noticeable case i noticed is the Wild Pokemon Battle, at 00:04 where the bass overlaps the main instruments/square waves.

Listen this for a comparison:
https://youtu.be/XaEb7FAupXs

[Pokemon LeafGreen.zip](https://github.com/droidmjt/Droidsound/files/1857993/Pokemon.LeafGreen.zip)

**Comment by droidmjt** [comment]
wild pokemon battle, which song from the zip?

**Comment by droidmjt** [comment]
Ok, I listened the youtube song, for crying out loud, this case is closed

**Comment by DavisOlivier** [comment]
Its sad to see how you close issues unsolved. You could at least explain why you're closing it instead of giving a vague comment like this last one

**Comment by droidmjt** [comment]
Yeah, it's about the comparison between those two plugins, the mGBA and the youtube thing, personally I couldn't hear any difference around 00:04 in that video compared the mGBA. Another thing is that the previous GSF plugin is no longer developed while the mGBA is.

**Comment by DavisOlivier** [comment]
https://github.com/mgba-emu/mgba/issues/1016

**Comment by droidmjt** [comment]
we are now talking about GSF files, those games in the issue you mentioned are not in GSF format.

**Comment by DavisOlivier** [comment]
But as mentioned before, its the GB part of the songs that sounds incorrect. The song i mentioned uses both GB and GBA soundchips. I found the same issue in Mother 3 soundtrack too, it uses the GB sound chip in a lot of songs and the volume of GB channels are low too. But since this issue is also being checked at the mgba github i guess it will be solved eventually
