### ISSUE TITLE
Extremely slow scanning

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#412]
Sometime between 1.67.7x and 1.67.89 I noticed that scanning through 7z files that contain the actual music files can be so slow that the app will eventually seem to give up on it. Usually it took me about 45 seconds. Now I'm 20 minutes in and I'm still stuck scanning one single file.

**Comment by droidmjt** [comment]
send me the 7z file you are trying to scan, and version 1.67.89 doesn't exist.

**Comment by droidmjt** [comment]
yeah 7zip handling had a bug in previous version

**Comment by VIRGINKLM** [comment]
Yeah I meant .83 sorry for that. It ended up finishing up at around 1 hour and 35 minutes. It took about 20 minutes for a 7z file with Final Fantasy X psfs and that's on a Exynos Galaxy S7. I wouldn't want to know how long it would take on a midranger device or even lower spec. What caused such a dramatic change in scanning time? Before it wouldn't take longer than a minute and I didn't seem to come across any bugs. Curious to know.

**Comment by droidmjt** [comment]
bug in a new unarchiver library, does it work now with build 84?

**Comment by VIRGINKLM** [comment]
It does but it's still painfully slow. The biggest problem is that there is no progress for each file and it may appear like scanning is stuck. I doubt that anybody would wait 32 minutes for a 43MB 7z file without closing the app. It really looks like it's stuck, especially compared to previous scan times.

**Comment by droidmjt** [comment]
again, link to the file please

**Comment by droidmjt** [comment]
nevermind, got a file and reproduced the bug, fixing time

**Comment by VIRGINKLM** [comment]
Note that it's not a certain file that causes the issue. It's mostly large 7z files with lots of individual files on them. So the larger the file and the more individual files on them, the longer the app will take to scan.

**Comment by droidmjt** [comment]
the problem is how i handle the solid archives, fix will be available very soon, sorry for the inconvenience

**Comment by VIRGINKLM** [comment]
No problem. At least it didn't break completely scans which would make it harder to report what went wrong.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/he8wlb7fqcvrs9s/droidsounde167_86.apk?dl=1
try this

**Comment by VIRGINKLM** [comment]
Amazing work. This brought down the scan time to less than half minute. Case closed.
