### ISSUE TITLE
Broken playback of SNES .spc files on 7z archives.

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#413]
Title says it all. Extracted archives seem to work though. Other file types may be affected too but other than SNES .spc's I can't seem to find any that is broken.

**Comment by droidmjt** [comment]
crap, I'll check it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/3x8pfn0bqra8pax/droidsounde167_87.apk?dl=1
try this

**Comment by droidmjt** [comment]
leave a msg
