### ISSUE TITLE
Ignore stereo separation option on game rips that contain stereo panning already.

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#414]
This is gonna be a tough one. Gameboy and Gameboy Color games actually support stereo audio panning compared to NES that supports only mono. Games like Super Mario Land and Shantae are stereo out of the box, while games like Pokémon Yellow, Silver, Gold and Crystal have options for both stereo and mono options. I found that the option that separates audio conflicts with game rips that don't need it in the first place. The other thing that I found is that games that supposed to have stereo audio don't (Pokémon series mostly, possibly the game rip does not contain the panning data?). Is there something that can be done? (This is mostly a discussion rather than a bug report)

**Comment by droidmjt** [comment]
If the plugins what plays those formats don't support the feature in question, unfortunately there is nothing I can do here.

**Comment by VIRGINKLM** [comment]
Would a detection for panning happen on the plugin or on the app or it can be done one both cases? That the one thing I don't know.

**Comment by droidmjt** [comment]
inside a plugin, close this case, it would be better if you ask these questions from kode54 for example
