### ISSUE TITLE
SPC Inaccuracy

### ISSUE THREAD

**Issue by Xyz39808** [droidmjt/Droidsound#415]
This file sounds broken in app but works fine on desktop.
https://www.dropbox.com/s/osec20vdiu51und/Spooky_West.spc?dl=0
Any chance of updating our choices for playing .SPC to more than just GME? Perhaps SPCPlay?

**Comment by droidmjt** [comment]
SPCPlay, care to share  a link to the source code?

**Comment by droidmjt** [comment]
OK I did some googling, the spcplay stuff is x86-only, can't do anything about it, sorry :(
