### ISSUE TITLE
SPC playback within RSN archives broken

### ISSUE THREAD

**Issue by DoktorLucario** [droidmjt/Droidsound#416]
Whenever I play an SPC file within an RSN archive, it will either only play the first track, say "Too many failures. Stopping." or crash the whole app.
Device is a Galaxy S8+ running Android 8.0 if that info helps. I've attempted to download the old version (167.77) from the main page, but the link appears to be dead. (EDIT: link is working now. weird)

**Comment by droidmjt** [comment]
Yes the link is working because i fixed it :) I'll check the RSN issue

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/whgqaksqrhf5mji/droidsounde167_88.apk?dl=1
try this, the problem was related to RAR solid archives

**Comment by droidmjt** [comment]
get the latest from the front page and leave a msg if there are other problems

**Comment by JFD62780** [comment]
Okay, now I'd like to report that the 167.90 build isn't working on my Galaxy S4...

"Unfortunately, Droidsound-E has stopped."

**Comment by droidmjt** [comment]
@JFD62780 , crashlogs please

**Comment by JFD62780** [comment]
I even went so far as to test an uncompressed SPC, and a zip with SPC's.  They played perfectly, but I don't have any non-solid RAR's to test out; only the solid RSN's from SNESMusic.org...

I'm afraid the problem still exists on .90...

**Comment by droidmjt** [comment]
how about the crashlog?

**Comment by droidmjt** [comment]
ah nevermind, I'm able to reproduce the problem

**Comment by Sir-Sabin** [comment]
It's crashing when i try to rescan my super nintendo files that are in 7z files (i upgraded my sdcard from 64gb to 128gb because my sdcard path changed i have rescan everything)

**Comment by droidmjt** [comment]
the RSN problem is solved, the problem was in unicode handling in unrar library

**Comment by Sir-Sabin** [comment]
Does this also fix the scanning issuie with 7z files? And can you update vgmstream to?

**Comment by droidmjt** [comment]
It seems that the 7z problem is related to the solid mode archiving, for example if you have an archive what is over 700MB and it is solid (1 block), you will need 700MB of free memory to extract it. Check your archive sizes.

**Comment by Sir-Sabin** [comment]
I forgot to say there are spc files in 7z files when i try to rescan them it crashes

**Comment by droidmjt** [comment]
what are the sizes of those 7z files?

**Comment by Sir-Sabin** [comment]
The biggest i can find is 28mb in size and they are solid archives

**Comment by JFD62780** [comment]
...By 'newest build', you mean .90?  It crashed on me in terms of that problem...

**Comment by droidmjt** [comment]
I need to solve another problem related to archives,after that I will upload new binary

**Comment by JFD62780** [comment]
To Dok and MJT, thank you both for the update!

To Dok, sorry for questioning you; to MJT, take your time, the new build will be worth the wait! :D

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/00vxalzqg3j5025/droidsounde167_91.apk?dl=1
try this, I hope it works, solid archives are just pain in the neck to handle

**Comment by JFD62780** [comment]
Confirmed, working!  Waiting on other responses though.

**Comment by Sir-Sabin** [comment]
I put all the spc files in a non solid 7z file and it crashes at 5% of scanning it

**Comment by droidmjt** [comment]
surprise, I'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/0t6l3lxd5h504t8/droidsounde167_92.apk?dl=1
try this

**Comment by Sir-Sabin** [comment]
Works now, it was hanging on a sega genesis 7z file but i fixed it, thx for the help

**Comment by droidmjt** [comment]
I'll consider this fixed, leave a msg if something is not working

**Comment by vaguerant** [comment]
Most of my RAR/RSN archived SPCs play fine, but Donkey Kong Country 2: Diddy's Kong Quest (dkq.rsn) and Donkey Kong Country 3: Dixie Kong's Double Trouble (dkdt.rsn) crash Droidsound-E whenever I try to play them. I'd be happy to share crash logs if I knew how.

These same RSN archives are able to play in other media players, so they don't seem to be the issue.

**Comment by droidmjt** [comment]
I'll check this soon..I'm busy at the moment

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xgbvreno0pzblnz/droidsounde167_94.apk?dl=1 
try this, let me know how it works

**Comment by vaguerant** [comment]
Works perfectly, many thanks.
