### ISSUE TITLE
Could not replay Sangokushi 2 - Haou no Tairiku.nsf

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#417]
[Sangokushi 2 - Haou no Tairiku (EMU).zophar.zip](https://github.com/droidmjt/Droidsound/files/1986335/Sangokushi.2.-.Haou.no.Tairiku.EMU.zophar.zip)

This NSF file could be replayed with NotSoFatso on Windows with the following setting:
````
Ignore Illegal=1
````

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/whgqaksqrhf5mji/droidsounde167_88.apk?dl=1
ni hao, try this, you need to go to settings and force NSF play in NEZPlugin

**Comment by droidmjt** [comment]
build 88 had a playlist parser bug, try the build _89 please, i just fixed it

**Comment by wmjordan** [comment]
Thank you for the prompt reply!
BTW, is it possible to apply the fix for this issue to the NSFE version too?

**Comment by droidmjt** [comment]
unfortunately no because the plugin in question doesn't support NSFE format :(

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/r1ozlih5evqulou/droidsounde167_90.apk?dl=1
try this, instead of nezplug, force NSF and NSFE in NSFPlugin

**Comment by droidmjt** [comment]
I'll close this case, incase of other problems, leave a msg

**Comment by wmjordan** [comment]
Is it possible to apply this fix to the GMEPlugin?
Before encountering #418, I was using GMEPlugin to play all NSF(E) files, except _Sangokushi 2 - Haou no Tairiku_ which was not playable. The GMEPlugin seems to provide the best playback effects and detect silences at the end of NSF(E) tracks perfectly.

**Comment by droidmjt** [comment]
no, they are two different libraries, if you want illegal opcode fix to GME, contact kode54

**Comment by wmjordan** [comment]
Is it this repository: https://github.com/kode54/Game_Music_Emu?

**Comment by droidmjt** [comment]
yes it is

**Comment by wmjordan** [comment]
The NSF file turned out to be broken.
I got it fixed and it was playable without ignoring illegal code afterward.

[Sangokushi.2.-.Haou.no.Tairiku.EMU.zophar.zip](https://github.com/kode54/Game_Music_Emu/files/3032989/Sangokushi.2.-.Haou.no.Tairiku.EMU.zophar.zip)

**Comment by droidmjt** [comment]
great, thanks for the info
