### ISSUE TITLE
NSFPlugin was not detecting track silence correctly in NSFE

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#418]
I'd gotten some NSFE files, some tracks were not having an end time.
The GMEPlugin could detect the silence and stop playing at the end, but the NSFPlugin would loop the track until the default track length had been played.
Is it possible to add silence detection in the NSFPlugin for NSFE file type?

**Comment by droidmjt** [comment]
please post those NSFE songs here so I can test better

**Comment by wmjordan** [comment]
Please use this NSFE file for test. The 10th track was only about 3 seconds long, but NSFPlugin was looping it over and over. Please see whether silence detection can work there.
[Sangokushi 2 - Haou no Tairiku (EMU).zophar.zip](https://github.com/droidmjt/Droidsound/files/1998068/Sangokushi.2.-.Haou.no.Tairiku.EMU.zophar.zip)

**Comment by droidmjt** [comment]
all right, i'll check it

**Comment by droidmjt** [comment]
no need to fix anything here, use the .m3u from the zip above with the .nsfe file and everything works perfectly, silence detector works in GME only because it cannot produce any sound

**Comment by wmjordan** [comment]
Well then, the workaround is to create an extra m3u file accompanying the NSF or NSFE file.
I posted an issue onto the GME repository, but unfortunately the author did not seem to be willing to add the `IgnoreIllegal` support to his plugin.

**Comment by droidmjt** [comment]
yeah, use the m3u from the zip above and its good, i'll close this case, leave a msg

**Comment by wmjordan** [comment]
Finally I overridden NSF files with the NSF plugin, and let the GME plugin play the rest NSFE files. Since I only met with that single NSF file which requires the `IgnoreIllegal` hack. This way I achieved the best playback effect and solved the compatibility problem.
