### ISSUE TITLE
Droidsound-E doesn't respond to the Play/Resume command over Bluetooth in some circumstances

### ISSUE THREAD

**Issue by FraGag** [droidmjt/Droidsound#419]
When I connect my phone to my car over Bluetooth, I can control media players such as Droidsound-E with Play/Resume, Pause, Next track and Previous track commands. All of these commands work fine in Droidsound-E, except for the Play/Resume command, which only works if I used the Pause command over Bluetooth beforehand. It would be great if the Play/Resume command reacted the same way as if I tapped the Play button in the application itself, i.e. when the music is paused, it resumes playback, and if nothing is playing, it plays the last song played in the last used playlist.

FWIW, I've been able to reproduce this issue by connecting my phone to my computer over Bluetooth. My computer is running Arch Linux; I'm using [Plasma 5](https://www.archlinux.org/packages/extra/any/plasma-meta/) along with the [pulseaudio-bluetooth](https://www.archlinux.org/packages/extra/x86_64/pulseaudio-bluetooth/) package, which lets me control playback from the Bluetooth notification icon.

I'm using droidsounde167_90.apk.

**Comment by droidmjt** [comment]
let me get this clear, if you tap play/pause button from the computer end,  sometimes phone doesn't react to the command? If that is the case, I'm not even sure how to debug the problem

**Comment by FraGag** [comment]
> Let me get this clear, if you tap play/pause button from the computer end, sometimes phone doesn't react to the command?

That's right. The button only works if the player was paused from the computer while music was playing, otherwise nothing happens. The button in the app itself always works, of course.

For the record, I've noticed that VLC for Android responds correctly to the Play/Pause button. Even if I press Stop to completely stop playback (which appears to clear the playlist), when I click Play, the player resumes playback from the last used playlist. If even resumes the last track from the position where it was stopped, though I'm not asking that Droidsound-E do that much (i.e. I'm fine if the last track starts from the beginning when I click Play while the player is stopped).

> If that is the case, I'm not even sure how to debug the problem.

I can try to debug it myself. Some instructions on how to build the package (including the native libraries) would be appreciated, since I have no experience developing apps for Android. The current build system is based on Ant, but the Android SDK has switched to Gradle; do I need to use an older SDK? (25.2.5 seems to be the last version supporting Ant.)

However, I've noticed that README.md is constantly being updated, but not the sources. Does this mean that the sources for the built versions linked in README.md are not published? Why is that so?

**Comment by droidmjt** [comment]
I was able to reproduce it now, nevermind,first I thought it was just a random effect.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/d4byzdxwm8kweew/droidsounde167_93.apk?dl=1
try this

**Comment by FraGag** [comment]
Hmm, that's not quite right. Every time I click Play while Droidsound-E is not playing and after ensuring that Droidsound-E is the last media player I used, VLC starts instead (this behaviour is different from prior versions; it would just do nothing before). I even tried rebooting my phone, and VLC started even though I hadn't started VLC between the phone booting up and me pressing Play. The weird thing though is that Plasma shows "com.droidmjt.droidsounde" as the "Remote Name" when this happens (I don't know if that means anything; the name is still shown while the computer is not connected to the phone, so it might just be cached).

However, pressing Play while Droidsound-E is paused does work now. :+1:

**Comment by droidmjt** [comment]
Of course VLC starts, this is because Droidsound-E service has not been started after reboot. Now it is suppose to work so that, after pressing Stop and then Play it starts to play the last song just like without Bluetooth.

**Comment by FraGag** [comment]
OK, so I tried uninstalling VLC to see what happens. When no song is playing in Droidsound-E and I press Play (in the Bluetooth applet on my computer, not in Droidsound-E) while Droidsound-E is open, nothing happens. I was expecting Droidsound-E to start playing.

**Comment by droidmjt** [comment]
my bad, if you haven't played anything with DS-E over bluetooth , nothing happens because DS-E doesn't know what was the previous song

**Comment by FraGag** [comment]
OK, I consider the issue fixed then, so I'm closing the issue. Thanks for your time!
