### ISSUE TITLE
Feature request: Don't fade out unless track is longer than N seconds

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#421]
Is it possible to limit the fade out effect for long tracks only?
Say, short tracks, which are shorter than 10 seconds, shall not be faded out.

**Comment by droidmjt** [comment]
yes but it would only work for those cases when the correct songlength is known, I don't see this feature very useful

**Comment by wmjordan** [comment]
It is reasonable that only tracks with known song length will be checked.
There are still quite a lot of tracks tagged with specific length.

**Comment by droidmjt** [comment]
this is done, will be available in next binary

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nfuzn2clns9u0i6/droidsounde167_97.apk?dl=1
try this

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7oof6txxea8hd2f/droidsounde167_98.apk?dl=1

**Comment by wmjordan** [comment]
Thanks for updating. I'll test it and report to you later.

**Comment by droidmjt** [comment]
good, leave a message

**Comment by droidmjt** [comment]
probably, i'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bch01jrrqtgb1xn/droidsounde167_101.apk?dl=1
try this, should work now

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nhqsjxqey5g67v6/droidsounde167_102.apk?dl=1
use this instead

**Comment by wmjordan** [comment]
Thank you for working on this issue. I'll try it and report to you later.

**Comment by wmjordan** [comment]
I'd downloaded version 102 and used it for quite a few days. It was working as expected. Great!
