### ISSUE TITLE
Genh Flac files not playing

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#422]
The Genh files previously worked for Pokemon X/Y to implement looping, which is mainly an AAC file in the Genh container. I did a similar treatment for a Sly Cooper rip I did, where I have the soundtrack in FLAC, but put them in Genh containers for the looping. This works for VGMstream and foobar, although it appears these do not load in the latest version of droidsound-e at the time of writing. I've attached a test track that contains loop points.
[04_Police HQ (Danger).zip](https://github.com/droidmjt/Droidsound/files/2168697/04_Police.HQ.Danger.zip)
As a summary for Droidsound-e:
-Flac: Works
-Flac in Genh container (for looping): Doesn't load
-AAC in Genh container (for looping): Works

**Comment by Sir-Sabin** [comment]
I think is because the vgmstream plugin needs to be updated as some other file types don't work like .txtp

**Comment by droidmjt** [comment]
If there are other extensions what fail play, please post them here as soon as possible.

**Comment by froggestspirit** [comment]
I've not tested other formats, but i know when generating the pokemon aac
and the sly cooper flac, they both used the ffmpeg type in vgmtoolbox.

**Comment by Sir-Sabin** [comment]
There are some that are not appearing in droidsound like txtp and some switch games (Skyrim Fire Emblem Warriors, Hyrule Warriors and Mega Man Legacy Collection 2 (PS4) .txtp)

**Comment by froggestspirit** [comment]
I think this is unrelated to the .txtp files, as all genh files use the genh extension, they all appear, although the base format inside the container is what seems to be the issue, even if the same format not inside of a genh container work.

**Comment by Sir-Sabin** [comment]
Genh and txtp are ran by vgmstream, i'm saying it might need to be updated for genh flac to work

**Comment by droidmjt** [comment]
try this: https://www.dropbox.com/s/hzb5k3dmmvszylc/droidsounde167_95.apk?dl=1

**Comment by droidmjt** [comment]
leave a msg

**Comment by froggestspirit** [comment]
This seems to have fixed it. Thank you!

**Comment by Sir-Sabin** [comment]
Skyrim Fire Emblem Warriors, Hyrule Warriors and Mega Man Legacy Collection 2 (PS4) are still not showing up in droidsound

**Comment by droidmjt** [comment]
crap, I check it

**Comment by droidmjt** [comment]
could you give urls for those files which doesn't play?

**Comment by Sir-Sabin** [comment]
http://switch.joshw.info/f/Fire%20Emblem%20Warriors%20%5bFire%20Emblem%20Musou%5d%20(2017-09-28)(Omega%20Force,%20Team%20Ninja)(Koei%20Tecmo,%20Nintendo)%5bSwitch%5d.7z

http://switch.joshw.info/e/Elder%20Scrolls%20V%20-%20Skyrim,%20The%20(2017-11-17)(Bethesda%20Game%20Studios)(Bethesda%20Softworks).7z

http://psf4.joshw.info/m/Mega%20Man%20Legacy%20Collection%202%20%5bRockMan%20Classics%20Collection%202%5d%20(2017-08-08)(Bullets,%20Now%20Production)(Capcom)%5bPS4%5d.7z (the txtp files are in mm9)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nfuzn2clns9u0i6/droidsounde167_97.apk?dl=1
try this

**Comment by Sir-Sabin** [comment]
The txtp files in mega man 9 are still not showing up

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/pb2cj91t3mc2kj6/droidsounde167_99.apk?dl=1
try this
