### ISSUE TITLE
Unable to process archive error

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#424]
I'm getting an Unable to process archive error when open some 7z files (Dragon Quest XI - Echoes of an Elusive Age (PS4) and Final Fantasy X + X-2 HD Remaster (PC), They non-solid 7z files

**Comment by droidmjt** [comment]
I need more infos about those archives, for example their sizes would be a good start. Would it be possible for you to send me one of them?

**Comment by Sir-Sabin** [comment]
Here you go: http://psf4.joshw.info/d/Dragon%20Quest%20XI%20-%20Echoes%20of%20an%20Elusive%20Age%20[Dragon%20Quest%20XI%20-%20Sugi%20Sarishi%20Toki%20o%20Motomete]%20(2017-07-29)(Square%20Enix)[PS4].7z

**Comment by droidmjt** [comment]
the error is about too less memory available for unarchiving, I'll check it

**Comment by droidmjt** [comment]
according to 7zip the dragon quest 7z is solid+, repack it as non-solid

**Comment by Sir-Sabin** [comment]
I did and the error popup when i tryed run it in droidsound, I have 1.4gb of memory free out of 3gb,

**Comment by droidmjt** [comment]
double check that it's not solid by any chance, in the mean time i'll repack it also

**Comment by droidmjt** [comment]
The problem is with the file Movies/mt_cs_c300030_c01x_40534641.adx, that alone needs nearly 300MB of memory when extracting it, whether you have 1.4GB or 4.1GB free RAM, it doesn't matter, it's about how much you can allocate memory from heap and usually that amount is far less than your free RAM. I'll test with my phone and see how it goes.

**Comment by Sir-Sabin** [comment]
Some files in ffx remastered for pc has one file at 628mb it's one big fsb file with all game music in it

**Comment by droidmjt** [comment]
for me it worked, barely, but for ffx fsb, not a chance

**Comment by droidmjt** [comment]
I'll see if I can get this extraction done in parts

**Comment by droidmjt** [comment]
Crap, LZMA/LZMA2 cannot decompress a file partially, that's it. I can't think of any solution here.

**Comment by Sir-Sabin** [comment]
I'm going to close this, the only workaround is extracting them playing them from that

**Comment by droidmjt** [comment]
I'll try to implement less memory consuming solution for the next build

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7oof6txxea8hd2f/droidsounde167_98.apk?dl=1
try this, it should allow you to play all the songs what can be extracted from archives

**Comment by Sir-Sabin** [comment]
That worked, i can see the file when it scans for it
