### ISSUE TITLE
AAC files aren't showing up

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#429]
Device: Sony Xperia Z2 (D6503)
Android: 8.1.0
ROM: RR-O-v6.0.0-20180508-sirius-rev2-Official
DS-E Build:167_99

Since my SD card was running out of storage I've converted most of my tracks to aac to make up space but now I ran into the problem that I can't see the aac files in DS-Es File Explorer and I am pretty certain that DS-E can playback aac files.

![dse](https://user-images.githubusercontent.com/15172856/43357006-1e82cb28-927b-11e8-84bb-3dfaa58acc62.png)
![exp](https://user-images.githubusercontent.com/15172856/43357007-204ca94c-927b-11e8-8ed7-a3fb046533da.png)

**Comment by droidmjt** [comment]
would it be possible for you to send me one of those AAC files ?

**Comment by theGIZOID** [comment]
Sure, I've sent you one via E-Mail.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/jkn3t6nzts9fcsl/droidsounde167_100.apk?dl=1
try this, I did lot of changes there due to a visualizer, try also the visualizer and let me know how it works, it can be enabled from the Settings -> UI Settings

**Comment by theGIZOID** [comment]
About aac files: They are still a bit iffy. They show up in the Filesystem Browser but not in Database Folders.

About the visualiser: Sick, now I have 2 of them at the same time B) https://youtu.be/gaG4Ije_HdI
Jokes asside, the visualiser works only on the first song, as soon as the song changes the visualiser goes poof until I stop playback and then continue. Also, the text no longer wraps around and the text itself in the background is way smaller than it used to be and makes it kinda hard to read. And the visualiser also depends on how loud the phones volume is set and not independet from the volume

Also, I got an "too many errors" message when I atempted to play an aac file, can't tell whether that was the aac file or the visualiser. I had to restart not only DS-E but my entire system to fix this and I can't seem to reproduce this occurrence this error. Weird.

**Comment by droidmjt** [comment]
The AAC thingy is now fixed. 
>> the visualiser works only on the first song, as soon as the song changes the visualiser goes poof until I stop playback and then continue.

I had exactly the same problem earlier with CM12.1, but I managed to fix it. I cannot install the ROM you have but I can try with earlier RR ROM (7.1.2). 

The wrapping problem can be fixed. The "too many errors" message is weird in this case, if you are able to reproduce it, let me know.

**Comment by droidmjt** [comment]
you can adjust the textsize, when I did a fresh install to RR ROM 7.1.2, all the fonts were just normal sized.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bch01jrrqtgb1xn/droidsounde167_101.apk?dl=1
this should fix the wrapping and the AAC problem, the visualizer volume thing cannot be fixed easily, needs different kind of implementation, keep it disabled if you have problems with it :(

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nhqsjxqey5g67v6/droidsounde167_102.apk?dl=1

**Comment by theGIZOID** [comment]
I've downloaded and installed the new 167_102 build and I can confirm that aac files now indeed appear after a rescan. The wrapping text issue is fixed for me but the text itself is still tiny and somewhat hard to read on my 5,2 inch display. A customizable fontsize would be my idea.

Also, whenever I enable the equalizer my Viper4Android process gets disabled until I disable the equalizer in DS-E.

And I found another rather peculiar issue with aac files. It happened only with one file and it happened while I was typing this reply but for whatever reason it just skipped to the next song without finishing it. And it does that every time at 1:25 as demonstrated in the video: https://youtu.be/uPVzf8Or3Yk
And while I was writing this I found another file which it didn't even want to play at all. And no, the files themselves are fine, if I open them with a different player they work just fine.
I can send you the files in question via E-Mail, if requested.

**Comment by theGIZOID** [comment]
I've sent you a few non-functional files with a brief description of whats wrong at what point in the file via E-Mail. There are a lot of files affected by this issue and like I said they work fine with any other player I've used so the files themselves should not be to blame

**Comment by theGIZOID** [comment]
Yep, sorry, I didn't catch the first post about the Fontsize before, I went into those settings and now they are back to normal size again.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/99z8p5gkou2jrrv/droidsounde167_103.apk?dl=1
changed AAC playing to another plugin, hopefully works better now. About the visualizer volume thing, for some OS versions it is not locked to phone's volume, for example stock SGS8 (8.0) and SGS6 (7.0), but on some older Samsung phones (Android 4.2) including RR and Cyanogenmod ROMs it seems to be locked. Anyways, if it bothers, just don't use it, one day when I have time, I'll implement better visualizer.

**Comment by droidmjt** [comment]
If the AAC files work, close this case

**Comment by theGIZOID** [comment]
The visualiser is a nice touch but I already have one on my navbar (I don't need two of them) and it also causes some weird issues with Viper4Android so I have no use for it but I can confirm that the visualiser works, even though only sometimes.

I have tested several of the faulty aac files and I can confirm that they work properly for now.
I'll close the issue for now, I'll get in touch again if I find something not working.
Thanks again for the help.

**Comment by droidmjt** [comment]
ok i see the problem, i get wrong songlengths for some reason, i'll get this fixed

**Comment by theGIZOID** [comment]
Even if I don't know the exact songlengths themselves I can tell when its displaying a time too long or too short. On a too short timer the song ends prematurely, on a too long timer the song plays like normal (when the song finishes it just goes to the next as normal). Additionally I can look up the lengths with a different player to confirm this.
