### ISSUE TITLE
NSF playback is outdated and inaccurate due to use of Nsfplug

### ISSUE THREAD

**Issue by stgiga** [droidmjt/Droidsound#430]
I am here because certain multichip nsf songs play badly compared to hardware. NSFplay, rainwarrior's nsfplug fork, is able to handle these esoteric songs, but is only usable for vgm at present. I ask you to use nsfplay instead of nsfplug if possible, and to keep it updated for when rainwarrior adds opll to it. For nezplug core users, I ask that you use the fork of nezplug++ with the vgm playback modification instead of nezplug. Thank you for maintaining this app.

**Comment by droidmjt** [comment]
would it be possible for you to send me one song for each plugin so I can hear how they fail to play?

**Comment by stgiga** [comment]
I can link a song that uses nezplug++'s Vrc7 drums, and I have just heard from rainwarrior that he is more likely to add opll drums to nsfplay. Please add nezplug++ (vgm fork) first, and as for the song that has no drums on old nezplug, it is here: https://famitracker.org/fcp3/dl/original/Entry072.nsf

**Comment by stgiga** [comment]
I will tell you when rainwarrior adds opll

**Comment by droidmjt** [comment]
>> Please add nezplug++ (vgm fork) first

share the link please

**Comment by stgiga** [comment]
Also, if you have not already, please update all Bass and BASSMidi related code to the newest versions of each, as all older versions clip more at higher volumes.

**Comment by droidmjt** [comment]
there is no new BASSMIDI for Android available, last update is from 2017

**Comment by droidmjt** [comment]
BASS library got update in this month but not BASSMIDI

**Comment by stgiga** [comment]
Exactly

**Comment by stgiga** [comment]
May as well update

**Comment by droidmjt** [comment]
I have updated to latest BASS already.

**Comment by stgiga** [comment]
Nice

**Comment by droidmjt** [comment]
leave a msg when the nsfplay has been updated
