### ISSUE TITLE
[Enhancement] Add jsidplay2 code and VIC20 Ted Emulation (jsidplay2 features multiple sid chips and more options) 

### ISSUE THREAD

**Issue by stgiga** [droidmjt/Droidsound#431]
Dear Droidmjt, sorry for my earlier issue, but I feel that commodore music needs better representation. I feel like implementing a player supporting multiple sid chips like jsidplay2 is a good idea. (make sure not to use the existing Android code base, as that requires a streaming connection due to author laziness. The Linux Java code base should work fine.) I also noticed a lack of VIC20 Ted chip emulation. Please add those 2 things, as well as defaulting nsfplay's fds write protect to on.
Thanks.

**Comment by droidmjt** [comment]
I'll add the nsfplay fds thing, sidplay2fp is enough, sorry about that.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ckhk3qeopkl7753/droidsounde167_106.apk?dl=1
there, FDS thing done
