### ISSUE TITLE
Create Ringtone does not create ringtone completely

### ISSUE THREAD

**Issue by wolfensg** [droidmjt/Droidsound#432]
Function "Create ringtone" does not work completely fine.
Function creates temporary wav file in DroidSound internal folder but it is not copied anywhere where it could be normally accessed via ringtone selector nor it is being selected as default (due to the first issue).

However if wav file is being copied manualy to ringtones folder - all works fine.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/9lno7oxtlv92cea/droidsounde167_107.apk?dl=1
try this

**Comment by wolfensg** [comment]
Thanks!!! :)

**Comment by wolfensg** [comment]
Just tested - works like a charm! :)
