### ISSUE TITLE
Cosmetical/minor request: Widget 4x2 transparency

### ISSUE THREAD

**Issue by wolfensg** [droidmjt/Droidsound#434]
Would it be possible to set transparency level for 4x2 widget or have several widgets (1st - 100% transparent, 2nd - current one as example) with fixed transparency?

**Comment by droidmjt** [comment]
yeah I can add that

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/0l47d8h48tqrpqs/droidsounde167_108.apk?dl=1
you can edit the transparency and bg color from Settings -> UI Settings

**Comment by wolfensg** [comment]
Works fine :)
Requires removing/adding widget when setting changed (this info could be added as description of the setting)
