### ISSUE TITLE
Player: MP3 tags/album art handling

### ISSUE THREAD

**Issue by wolfensg** [droidmjt/Droidsound#436]
Is it possible to include some of the rest of the mp3 tags embedded in mp3 as standard player output while playing mp3? Currently displays only artist, title, genre.

What about the album art? Is it possible to include the image as well or not possible without involving much work with the UI?

BTW: Don't get me wrong for raising couple of issues recently :) Droidsound since you've taken over work is superb player and I thought only would it be possible to make it my one and only choice for playing everything.

**Comment by droidmjt** [comment]
Which MP3 tags are missing? send me a song with those missing tags. No albumart.

**Comment by wolfensg** [comment]
Tags are not missing but only couple of them are being displayed (leaving most of the space here empty) I thought about either putting some more tags in this place (or info like bitrate, album name from tag, composer, etc).

In my case the things that are being displayed while playing mp3 file is:
Title:
Artist:
(these are dispalyed in the section above the rest and below are the following:
Plugin: BASS
Copyright: 1999
Genre: something
Format: MP3
Channels: Stereo
Replay rate: 44100Hz
Size: xxxx bytes
Source:
path/filename

I only thought that having some more info would be cool (for modules there is instrument data as additional thing being displayed, for SID files info on the preffered sid chip, player data, etc)

It is NOT that something is not working. Just a thought - if it would be too much work involved to include any additional info - just close the issue. :) Thanks!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/0l47d8h48tqrpqs/droidsounde167_108.apk?dl=1
try this

**Comment by wolfensg** [comment]
Perfect :) Now nicely fits with the Vis :)
