### ISSUE TITLE
DroidSound crashed on playing this file

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#437]
The file name has Japanese characters--could this be the cause of the crash?

Please unzip the file first and play the rsn file for test.

[ルドラの秘宝.zip](https://github.com/droidmjt/Droidsound/files/2295919/default.zip)

**Comment by Sir-Sabin** [comment]
I'm also having problems with files with Japanese characters in them, they don't showing up in 7z files but show up with it's unpacked, I've uploaded the 7z files that is being a problem.

https://mega.nz/#!egVyECoC!VdBCkYYBfOOWq54IN4PRDi9YxrTKDHWWMgwqIOszJVE

**Comment by droidmjt** [comment]
did it work before?

**Comment by Sir-Sabin** [comment]
the 7z file worked before dunno how long it's been like that

**Comment by wmjordan** [comment]
It previously worked.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/dmv1d027v49cz7v/droidsounde167_109.apk?dl=1
try this

**Comment by wmjordan** [comment]
The new version worked.

**Comment by Sir-Sabin** [comment]
The 7z file still doesn't work with the updated file

**Comment by droidmjt** [comment]
@Sir-Sabin , crap, I forgot to check it, I check it now

**Comment by droidmjt** [comment]
@Sir-Sabin try this: https://www.dropbox.com/s/1tnuf6t8rmbzvja/droidsounde167_110.apk?dl=1

**Comment by Sir-Sabin** [comment]
It works now, thx
