### ISSUE TITLE
BASSMIDI soundfont volume non-functional

### ISSUE THREAD

**Issue by TheShinyCookie** [droidmjt/Droidsound#438]
After hearing clipping with one of the soundfonts I have, I wanted to see if this option would help it. However, it doesn't seem to do anything. Using it doesn't change the volume at all. The soundfont is Timbres Of Heaven V3.4.

**Comment by droidmjt** [comment]
this is fixed now, will upload new binary soon

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1tnuf6t8rmbzvja/droidsounde167_110.apk?dl=1
try this

**Comment by TheShinyCookie** [comment]
Awesome, it works! It does actually solve the clipping issue as well! :D

**Comment by droidmjt** [comment]
great, good to hear :)
