### ISSUE TITLE
BASSMIDI no longer plays .LDS music

### ISSUE THREAD

**Issue by TheShinyCookie** [droidmjt/Droidsound#439]
When trying to play Tyrian music using BASSMIDI, the whole app instantly crashes. The other MIDI players, as well as AdPlug, still play .LDS files though.

**Comment by droidmjt** [comment]
I cannot reproduce this problem. Double check that you have selected soundfont when you use BASSMIDI, other than that, you need to provide clear instructions how to reproduce this problem.

**Comment by TheShinyCookie** [comment]
I have infact selected a soundfont. It happens with any that I choose. Of course, AdPlug should have format override disabled. What's really strange is that in this version, it was actually working before. My phone crapped out and wouldn't play anything audio related, so in the process, I reinstalled Droidsound-E before restarting my phone. Now this specific format doesn't work with BASSMIDI.

**Comment by droidmjt** [comment]
Try this:
1. Go to settings and reset preferences
2. Restart the app
3. Disable Adplug format override
4. Select BASSMIDI + select soundfont
5. Try to play the file

If it still fails, at least send me logcat log but I doubt it helps.

**Comment by TheShinyCookie** [comment]
I don't exactly know what logcat is, sorry... but I found the crash logs folder.

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
	at com.droidmjt.droidsounde.plugins.BASSMIDIPlugin.load(BASSMIDIPlugin.java:494)
	at com.droidmjt.droidsounde.service.Player.startSong(Player.java:841)
	at com.droidmjt.droidsounde.service.Player.run(Player.java:1448)
	at java.lang.Thread.run(Thread.java:762)
============================
Droidsound-E version: 1.67
Droidsound-E build: 110
Time: Sat Aug 18 12:26:46 GMT+01:00 2018
CPU: armeabi-v7a
CPU: armeabi
Fingerprint: samsung/a3xeltexx/a3xelte:7.0/NRD90M/A310FXXU4CRB1:user/release-keys
CPUFeatures : fp asimd aes pmull sha1 sha2 crc32 wp half thumb fastmult vfp edsp neon vfpv3 tlsi vfpv4 idiva idivt 
Lang: English
Locale: en_GB
InternalSD free space: 4615274496
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
the error is about the file you are trying to play, it cannot find it, please do a Rescan to the Examples archive and try again

**Comment by droidmjt** [comment]
and make sure you have a folder inside /droidsound/ folder named 'tmp'

**Comment by TheShinyCookie** [comment]
Oh, the tmp folder was missing! Don't know why... I created it, and it works now. Thanks :)

**Comment by droidmjt** [comment]
I'll update the code so that it will create the folder if its missing.
