### ISSUE TITLE
Unable to play mt32 custom patch midis in mount due to lack of a no-gm option 

### ISSUE THREAD

**Issue by stgiga** [droidmjt/Droidsound#440]
I have some midis I want to play in munt which works for gm stuff. Sadly any mt32 song using custom patches will be left out, and use the set you chose instead, breaking compatibility. To fix this, add an option to Not use a gm set for munt. Also since gxscc has been ported to js, I was thinking you could add that if you wanted. Its jsscc on github. The app is also open source as well. I also want to ask you to allow toggle of analogue circuit emulation, plus the better and more accurate "boss" mt32 reverb chip emulation from Dev munt builds using the file from the mame romset provided by users. Also add the option Of reverb model and dac model selection, 256 partial support to avoid crashes or pops on gm midis, and 16 channel support from kode54, nicknamed super-munt. CM32 and lapc drum support would allow my midis to work as well. This all assumes you haven't added them. Next I wish to ask a favor of you; please allow ALL Plug-ins to use the highest output sample rate defined in their code. I want my stuff in high quality please. Thanks.

PS: Where possible, add an option to make multichannel and polyphonic plugins output all channels mixed using virtual surround. Thanks again.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/76n9z5lkxv1nsm3/droidsounde167_112.apk?dl=1
try this, I'm not sure if all is correct, custom sysex files can be loaded by first selecting Custom from GM SET then last item will show available sysex files, copy your sysex files to /droidsound/mt32/ folder

**Comment by stgiga** [comment]
Works flawlessly! However, I do wish oversampling was a thing for more plug-ins, but I know that's cpu intensive. Still, since this app does run on chromeos, and Chromeos can run on powerful hardware, it would be wise to think about it, especially as Android pc laptops Can be bought at riteaid (a drugstore). Therefore please think about oversampling everything else to their limits

**Comment by stgiga** [comment]
ALSO there needs to be an option to play munt midis with no custom or gm patch banks, as I have some Japanese midis that can only be played by removing all sysex from the folder. Plus I wanna play songs that use default patches like the works of anders enger Jensen at eox.no, in addition to an option from desktop munt which reverses stereo to GM standards. If possible, add oversampling to the plug-ins that don't have it, and to BASSMidi, use the bass library to split the BASSMidi stream into 4 channels as openmpt does on pc if asked to. Basically a headphone Quadraphonic option that can work on stereo phones due to using bx is a good idea, at least when not streaming to car or HDmi surround systems using a dock cable or Bluetooth. All this program needs is uniform audio quality. I notice a huge difference between 44.1 and 96.

**Comment by stgiga** [comment]
Please fork desktop pc munt with the 256 partial, super mode, and 96khz dac mode. It sounds great enough that I don't want pc users to suffer.

**Comment by stgiga** [comment]
And the sysex loading code, plus the wip Dev munt boss reverb rom chip code that still needs to be added to droidsound and munt. I want Uber-res mt32 audio for my dos games ;}

**Comment by stgiga** [comment]
Don't forget cm32+lapc+boss rom support, and mame mt32 rom chips too

**Comment by stgiga** [comment]
https://github.com/sergm/munt_devel has all the boss reverb code you need.

**Comment by stgiga** [comment]
Go with the mame filename for the rom.

**Comment by stgiga** [comment]
Ironically mame also has broken yamaha mu100 support, plus other weirder synth, including sc55. They all don't really work yet. Mame iirc has no midi support at all.

**Comment by droidmjt** [comment]
I just add the option to disable the sysex sets and thats it. Just for curiosity, what Android OS version you have in use?

**Comment by stgiga** [comment]
Thanks for adding the sysex disable option. I use android 8.1 oreo

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nrnaqtq0t9d780b/droidsounde167_113.apk?dl=1
try this, if it works, close this issue

**Comment by stgiga** [comment]
It works! Thank you
