### ISSUE TITLE
Droidsound-e build 113 is broken and update vgmstream

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#442]
I would like to tell you that the build 113 is broken and won't install and can you update vgmstream and add the version number in the song info it was added some time ago

**Comment by droidmjt** [comment]
what happens when you try to install it?

**Comment by droidmjt** [comment]
how do you try to install the app?

**Comment by Sir-Sabin** [comment]
Yep and i get that error to

**Comment by droidmjt** [comment]
I don't, tried with multiple devices + fresh install. I still would like to know how do you install the app.

**Comment by droidmjt** [comment]
I'll check more later today.

**Comment by Sir-Sabin** [comment]
I have 8.0 installed on my phone and it's giving me that error

**Comment by x-amp** [comment]
I use https://www.google.com/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dcom.speedsoftware.explorer%26hl%3Den_US%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Droot%2Bexplorer%26pcampaignid%3DAPPU_1_Ajp9W96dK8Pq_AaUoLPoAw&ved=2ahUKEwjepq_zuIDdAhVDNd8KHRTQDD0Q8oQBMAJ6BAgGEAc&usg=AOvVaw2nPLZjqIOQ1Ka32dvrRyFb to install. I just used my built-in file explorer and installed the update with no problem.  Build 112 and 113 are the only versions that have the error in Explorer

**Comment by Sir-Sabin** [comment]
i use that to, but works when using the built in file manager, could be something you did as Explorer hasn't been updated for a while

**Comment by Sir-Sabin** [comment]
It seems explorer updated yesterday and broke some stuff including apk installing

**Comment by droidmjt** [comment]
yeah, its the explorer, i tried to install another APK with it and got the same parsing error, close this issue

**Comment by droidmjt** [comment]
the vgmstream is already the latest

**Comment by Sir-Sabin** [comment]
Droidsound-e doesn't see these files

https://mega.nz/#!btdRWSBQ!mLhuB6Sl7WO2DS9aJD11WR1d7MV9DiHFI62o2_WSDG8

**Comment by x-amp** [comment]
Yeah, I was also gonna ask about those files.

**Comment by Sir-Sabin** [comment]
It works, no more issues for now :D
