### ISSUE TITLE
Modland search no longer functions

### ISSUE THREAD

**Issue by TheShinyCookie** [droidmjt/Droidsound#443]
As mentioned in my .LDS issue, I had reinstalled the app at some point trying to fix something. This is another one of the problems that came up. Trying to search anything in Modland doesn't do anything. In the notifications, it does say Searching for ,tsuper mario kart, but nothing happens. It just stays there. Searching the other locations seems to work fine though, like Local files and HVSC. Changing the Modland server doesn't help. Could it be a missing folder, like with the other issue I was having?

**Comment by droidmjt** [comment]
you need to index modland first, I need to add notification for this

**Comment by TheShinyCookie** [comment]
Ah, that fixed it. Cheers dude :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/6uwl46r9xx72rql/droidsounde167_115.apk?dl=1
try this, added notification about missing modland index and a new spectrum analyzer mode

**Comment by TheShinyCookie** [comment]
Deleted the index, and the notification does work. The street light visualizer mode works too. It would be nice to be able to change the update rate of the visualizer though, since it looks quite choppy.

**Comment by TheShinyCookie** [comment]
Also, the visualizer count option doesn't seem to do anything

**Comment by droidmjt** [comment]
you need to restart the app for visualizer count change

**Comment by droidmjt** [comment]
for some reason it works better with higher count
