### ISSUE TITLE
[Nuklear] Preset choosing doesn't makes effect

### ISSUE THREAD

**Issue by Wohlstand** [droidmjt/Droidsound#444]
Just now I have tried out the existing libADLMIDI stuff, but for curious I also have tried Nuklear synthesizer to compare sounding of some sounding, but I have found that it sticks on Doom bank when I have tried to choose Duke Nukem.

The assembly droidsounde167_117 where this bug I have found.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nk9zc3b8fqb59o0/droidsounde167_118.apk?dl=1
try this, should work now

**Comment by Wohlstand** [comment]
Will try at my evening, now I'm in a path to my job... But thanks for a fix!  :3
Will report you when I'll test a thing! :fox_face: :wink:

**Comment by Wohlstand** [comment]
Tested, now works! Thanks!
