### ISSUE TITLE
MIDI Plug-ins do not support 64ch Yamaha XG and 32ch SC88 series midi files correctly. 

### ISSUE THREAD

**Issue by stgiga** [droidmjt/Droidsound#446]
I want you to make it so that you can use 64 midi channels in munt super mode, other plug-ins if possible, and definitely bassmidi as dictated in Yamaha xg level 3, and so that the BASSMidi sample rate goes to 96000 like on newer desktop implementations of it. When you finish the previously requested interpolation filters, please add them to all the midi plug-ins if you haven't already. I want to use my HD soundfonts at maximum settings.
Thanks.

**Comment by droidmjt** [comment]
I have no idea how to add the 64 MIDI channel thing, sorry. The interpolation thing is in my backlog, it may or may not see the daylight.

**Comment by stgiga** [comment]
What about the 96khz for bassmidi? Is that possible on android even if it works on desktop?

**Comment by droidmjt** [comment]
96khz thing for BASSMIDI is done. For BASSMIDI you can already set the channel count in BASSMIDI settings. I have no idea how to enhance the MUNT library.

**Comment by stgiga** [comment]
I am on build 119 and BASSMidi is still 44.1 kHz.

**Comment by stgiga** [comment]
96khz works.
