### ISSUE TITLE
Hoot support?

### ISSUE THREAD

**Issue by J2913** [droidmjt/Droidsound#447]
Out of curiosity, I decided to download a zip of a PC-98 game, and it recognized the .mgs files in the zip, but crashed whenever I tried to play them. If there is hoot support, how do I set it up?

Here's one of the files: https://drive.google.com/file/d/1gsBckrUGdL0M1I40-YFdrem2mC8b_paL/view?usp=drivesdk

**Comment by droidmjt** [comment]
MGS is related to the MSX format in Droidsound-E, if it is MSX related file, it is missing a correct header and thats why it crashes, there is no hoot support in DS-E.

**Comment by J2913** [comment]
Alright, thanks for clearing that up!

**Comment by J2913** [comment]
Alright, thanks for clearing that up!
