### ISSUE TITLE
MT-32 playback issues

### ISSUE THREAD

**Issue by TheShinyCookie** [droidmjt/Droidsound#448]
This isn't a problem with Droidsound, but it's been frustrating me. I cannot figure out how to get the MT-32 working. I have the same issue in foobar2000. Sorry for bothering you about this, but I would appreciate knowing how to sort this out. I have no idea what to do.

**Comment by Bonboon228** [comment]
I am having similar problems.
I have the roms named correctly and placed in the correct folder, yet all my midis default to the EMIDI plugin.
Throw me a bone, please.

**Comment by TheShinyCookie** [comment]
Do they actually need to be specific names?

**Comment by stgiga** [comment]
Yes

**Comment by stgiga** [comment]
They have to have the date and version stripped off the end of the filename

**Comment by stgiga** [comment]
MT32 has to exist in addition to cm32l if cm32l sfx are used. No solo romset for cm32 only

**Comment by droidmjt** [comment]
@Bonboon228 these files you need to copy to /droidsound/mt32/ folder:

- CM32L_CONTROL.ROM (a439fbb390da38cada95a7cbb1d6ca199cd66ef8)
- CM32L_PCM.ROM (289cc298ad532b702461bfc738009d9ebe8025ea)
- MT32_CONTROL.ROM (7b8c2a5ddb42fd0732e2f22b3340dcf5360edf92)
- MT32_PCM.ROM (f6b1eebc4b2d200ec6d3d21d51325d5b48c60252)

SHA1's included of each files. They are case-sensitive. Then just change the MIDI player from the settings, it has to work.

**Comment by TheShinyCookie** [comment]
Awesome, it worked! I do find it dumb that you need the CM32L ROMs too, even if you just want MT-32...

**Comment by TheShinyCookie** [comment]
It doesn't say this anywhere on the page of the foobar2000 component either...
