### ISSUE TITLE
Pokemon XD Not Playing

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#449]
I tried the rip on the joshw site, although the streamed music seems to come in pairs. Each song is either ".isd" paired with a 1kb ".ish", or a ".001" paired with a 1kb ".dsp". Currently, none of these are playing in droidsound-e, although the ".isd" files appear to play fine when converted with cmd-line vgmstream. I was unable to get vgmstream to play the ".001" files. Is this something that could be fixed? If needed I can look into the files with a hex editor. I'm not sure why the game uses 2 different formats. I've included a few examples.
[Pokemon XD Tests.zip](https://github.com/droidmjt/Droidsound/files/2390605/Pokemon.XD.Tests.zip)

**Comment by droidmjt** [comment]
fixed, small mixup in the extension list, i'll upload a new binary soon

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/z2spvvo9oq7dy5f/droidsounde167_122.apk?dl=1

**Comment by froggestspirit** [comment]
i tried the new build, it fixed a few of the songs but i believe some of
the ISD files and none of the DSP files are playing. i can send more
examples later if it helps

**Comment by froggestspirit** [comment]
The files looked similar, so upon testing, renaming all .001 files to .isd and all .dsp files to .ish seems to fix it. I'll probably listen to the soundtrack more tomorrow to make sure
