### ISSUE TITLE
Add interpolation filters to at least vgm and bassmidi.

### ISSUE THREAD

**Issue by stgiga** [droidmjt/Droidsound#450]
Please do this so I can fully experience my HD soundfont and famicaloid nsf files, plus my opl4 and mt32 rips.

**Comment by droidmjt** [comment]
I haven't found any public library what I could use for this feature and I don't have time to implement my own.

**Comment by stgiga** [comment]
Also update nsfplay to 2.4 when it gets released, and fix adlmidi load failure and lag that never happened on old versions.
I use a Moto x4

**Comment by droidmjt** [comment]
tell me more about the adlmidi load failure and lag

**Comment by stgiga** [comment]
Sorry. But do fix the adlmidi load failure. Also, a public effect library you can use is the bass_fx library by the author of bassmidi.

**Comment by droidmjt** [comment]
how to reproduce the adlmidi load failure?

**Comment by stgiga** [comment]
Adlmidi worked on older versions where it was part of midisynth. I set chip count to 100, and 4 op to -1. It, and the other fm midi players have more lag, but adlmidi is the worst affected. It happens to all fm players, and vgmplay lags on multichip fm vgm files. Essentially fm code is shot.

**Comment by stgiga** [comment]
Basically max out all settings in the app for all fm music. There is something serious ly wrong with the new fm code.

**Comment by droidmjt** [comment]
do not set chip count to 100, secondly, please send me one of those vgm files so I debug the problem.

**Comment by stgiga** [comment]
If you need an effect library for interpolation, use BASS_FX to maximize compatibility with your existing code.

**Comment by droidmjt** [comment]
ok, got it, bassfx, now, please send me one of those problematic VGM files

**Comment by stgiga** [comment]
Chip count 100 worked on older versions of the app. Every other maxxed setting works. Here is the vgm https://drive.google.com/file/d/17xlk1ghRyt2bu3_k832iWkoF5vsKUg8n/view?usp=drivesdk

**Comment by stgiga** [comment]
Bassmix also has resample code

**Comment by stgiga** [comment]
They said this

 Wohlstand / libADLMIDI
Code  Issues 21  Pull requests 0  Projects 0  Wiki  Pulse
Jump to bottom Open
Chip count of 100 with any 4 op Chip count fails in 2018 version #177
@stgiga
stgiga opened this issue 
21 minutes ago 
 help wanted
In droidsound-e, the old library was able to handle a high chip count. The summer 2018 code fails at this high chip count and produces noise at best. It also lags so much that stuff fails to load. Please fix this.

@Wohlstand
Wohlstand commented 19 minutes ago • edited 17 minutes ago
That because of Nuked OPL3 emulator which is super-heavy one due it's goal to provide super-accurate simulation of the chip. Please switch the emulation core into DosBox and retry that. Another note: even you doesn't abusing count of Nuked chips, the heavy emulator will eat battery of mobile device faster. Therefore I don't suggest you to use Nuked on mobile devices, only on your own risk. Old library have used DosBox-only and hadn't Nuked OPL3 emulator. New library is using both DosBox and Nuked emulator with an ability to switch each other on the fly.

Wohlstand added the help wanted  label 15 minutes ago
Wohlstand added the question  label 15 minutes ago
Wohlstand removed the question  label 15 minutes ago
@stgiga
stgiga 
commented 10 minutes ago
Dosbox also fails

@Wohlstand
Wohlstand 
commented 6 minutes ago
To apply changes of emulator, it's need to stop the song and start it from scratch (in DroidSound-E). Did you that?

Anyway, looks like the author have forgot to pass "Play in PCM rate" flag which does reducing of cycles count and allows to play the song on slower device.

@Wohlstand
Wohlstand commented 3 minutes ago • edited 3 minutes ago
By default, DosBox emulator now working under ~49 Khz frequency to match real chip's rate and provide more accurate sound. However, if you are playing in 44100 Khz rate (not in... for example, 96 Khz), this means, chip will run with higher rate than the PCM rate. That flag which is exists in the library, forces DosBox chip to run in 44100 Hz rate which makes some distortions in cymbals, hi-hats, etc..

Comment on issue

Leave a comment
Close issue   Comment
Notifications for this thread
You’re receiving notifications because you authored the thread.

 Unsubscribe
 Desktop version Sign out

**Comment by droidmjt** [comment]
btw, why do you need that many chips? does it sound different if you just use 2-4 ?

**Comment by droidmjt** [comment]
so there is no ADLMIDI problem, how exactly you reproduce the vgm lag problem, what settings do you use?

**Comment by stgiga** [comment]
I needed polyphony

**Comment by droidmjt** [comment]
for DosBox core you can use more chips but for Nuked chips count should stay under 8

**Comment by droidmjt** [comment]
the bassfx filters are Tempo related, I don't think it the correct stuff for this purpose, good news is that I found suitable library for the interpolation filters, I'll close this case and reopen the original one once the feature has been implemented.

**Comment by stgiga** [comment]
Just make sure that bassmidi is one of the plugins that uses the filter
