### ISSUE TITLE
libADLMIDI needs update due bug in the version you have

### ISSUE THREAD

**Issue by Wohlstand** [droidmjt/Droidsound#451]
Some days ago I have composed a melody:
[Fox fantasy.mid.zip](https://github.com/droidmjt/Droidsound/files/2411614/Fox.fantasy.mid.zip)

Unfortunately, in Droidsound it stucks by unknown reason in a middle, but works perfectly on pure libADLMIDI at me everywhere. However, accidentally, I have found that my old install on my job computer had older libADLMIDI version, and my composition also got stucked while to WAV conversion. The bug has gone when I pulled my fresh version and re-installed it.

Then, I have found a fix that done by @jpcima which have fixed this damned stuck: https://github.com/Wohlstand/libADLMIDI/commit/13e4cb1528f36d3514fa6d7f26eb4028194c5b07

So, please pull my fresh libADLMIDI from the "master" branch to let that bug go away.

**Comment by droidmjt** [comment]
all right, I'll see if I can get that fixed

**Comment by Wohlstand** [comment]
Nothing to hard, just update libADLMIDI's files and recompile the project. :wink:

**Comment by Wohlstand** [comment]
Now I gonna to test it now...

**Comment by droidmjt** [comment]
cannot comment the song since it's not my genre :)

**Comment by droidmjt** [comment]
I guess it works.

**Comment by Wohlstand** [comment]
Anyway, I'm near to make a new release (that I'll push to GZDoom repo also) which you'll can pick up.
