### ISSUE TITLE
Possible file limit

### ISSUE THREAD

**Issue by tleej** [droidmjt/Droidsound#452]
Is there a limit to the number of files the DB browser can handle? My folder has over 10000 files and folders and the database doesnt go past the w's.

**Comment by droidmjt** [comment]
its sql limit, nothing I can do :(

it's not very good idea to have that many files under one folder :)

**Comment by Sir-Sabin** [comment]
You can try to compressing those files to decrease the number of files in one folder,  make sure they are non-solid 7z, zip or rar files so it doesn't crash droidsound-e

**Comment by droidmjt** [comment]
solid archives works but they are very slow, not recommended, secondly, packing won't help since they end up in SQL anyway, just sort the files to folders

**Comment by droidmjt** [comment]
At least in filesystem browser I was able to browse a folder with 14K files, but there is a small problem in that, I need to implement some sort of caching so that the filelisting stays in memory unless the folder changes. The only real problem is the SQL+query+cursor thingy.

**Comment by droidmjt** [comment]
I don't have time to solve this right now, I know a way how to overcome the SQL limitation but it requires lots of changes, I'll close this ticket and reopen it once I have fixed it. In Android Emulator the maximum capacity for SQL cursor (mCursorWindowCapacity) was 12896, what I need to do is a loop that does sql queries as long as the desired itemcount is done, for example 100000.
