### ISSUE TITLE
Request: Revert to BASS plugin for AAC playback

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#453]
Long story short: I did a dumb mistake by using an aac container for the aac codec. By using an m4a container for the aac codec instead I was able to fix the issue of songs ending prematurely and the runtime of the songs being sometimes too long/short.

The files should now work with the BASS plugin as they also work flawlessly with the FFmpeg plugin now. The reason I request this change is because of the gapless playback option.

**Comment by droidmjt** [comment]
send me couple of those files using m4a container please

**Comment by droidmjt** [comment]
BASS library is not capable of playing those files.

**Comment by droidmjt** [comment]
It works now, I will soon upload new binary.
