### ISSUE TITLE
Amiga Resampler in OpenMPT

### ISSUE THREAD

**Issue by TheShinyCookie** [droidmjt/Droidsound#454]
In an update for OpenMPT a while ago, there was a new interpolation option added exclusively for .mod files that emulates the Paula filter (listed as Amiga Resampler).

I don't know if it's in libopenMPT as well, but if it is, could you implement it into the options?

**Comment by stgiga** [comment]
Also add the interpolation filters please

**Comment by droidmjt** [comment]
@stgiga, the openmptplugin already supports 4 different kind of filters, the other plugins have to wait

**Comment by droidmjt** [comment]
the amiga thingy has been added,will upload new binary soon

**Comment by TheShinyCookie** [comment]
Sorry for asking, but where's the new binary?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/4pg6mbelmtl03x5/droidsounde167_126.apk?dl=1
try this

**Comment by TheShinyCookie** [comment]
Works, thanks!
