### ISSUE TITLE
Changelog and MT-32 instructions

### ISSUE THREAD

**Issue by TheShinyCookie** [droidmjt/Droidsound#455]
Whenever you release a new version and there's been no issue activity, I have no idea what's been changed. It would be nice to have a changelog.

Also, I did get Munt working after that help you gave, but not everyone would be willing to look around for the solution. It would be helpful to have instructions in the Munt settings menu.

**Comment by TheShinyCookie** [comment]
You could use the Releases feature and put the changelogs in there. And it also gives notifications to those who have them turned on for the repository (including me)

**Comment by droidmjt** [comment]
I'll add instructions in Munt settings at some point.
