### ISSUE TITLE
Add droidsound project for PC

### ISSUE THREAD

**Issue by AdityaMH** [droidmjt/Droidsound#457]
It's really hard enough to find game music player like droidsound for pc.

Can you make or add project droidsound for pc, @droidmjt ?

**Comment by droidmjt** [comment]
Unfortunately I cannot, I don't have time for things like that, sorry.

**Comment by theGIZOID** [comment]
Try Winamp or Foobar2000, you can download playback plugins for those and play pretty much any chiptune format. I myself use Winamp and the chipamp bundle from Overclocked and I'm totally satisfied with it. For mod tracker formats you could use something like modplug player.
