### ISSUE TITLE
Skipping to next song stops in Bluetooth.

### ISSUE THREAD

**Issue by 1983parrothead** [droidmjt/Droidsound#461]
I play a song through Bluetooth headset (mine is LG TONE Platinum+, a Best Buy exclusive I think), then skip it to next song, but then it stops until I press play button.

**Comment by droidmjt** [comment]
I tried with my BT devices and seems to work normally. I'm not sure how to fix this problem.

**Comment by droidmjt** [comment]
See if you can configure your device, are you able to play/pause/stop/next/prev anyhow with your device? All I can think of is some sort of compatibility problem.

**Comment by 1983parrothead** [comment]
Other Bluetooth devices I use such as a Toyota Camry stereo and a Pro-Scan tower speaker work well in skipping tracks. Perhaps my Samsung phone and LG TONE have a little poor relationships with each other because Samsung and LG are rival businesses from South Korea.

I was able to use both LG TONE for listening in one ear and Camry stereo buttons on steering wheel for changing songs and controlling volume.

As for working out with LG TONE and Galaxy S7 edge alone, I can usually set a long playlist and play through it automatically without manually changing tracks. Volume control on LG TONE has no problems.

Pretty soon, Google will release Android Pie on more phones than Oreo. Maybe that version might fix my problem. If not, I guess I would have to switch to better Bluetooth headsets.

Thank you for your response. Keep up the excellent work on droidsound-e! ^_^

**Comment by droidmjt** [comment]
Galaxy S7 Edge probably won't get Android Pie because the phone is soon three years old, if you are after BT headphones, try Bose QuietComfort 35 or Sony WH-1000XM3.

**Comment by droidmjt** [comment]
What comes to BlueTooth devices, check these links:
- https://www.soundguys.com/understanding-bluetooth-codecs-15352/
- https://www.guidingtech.com/sbc-vs-ldac-vs-aptx-bluetooth-codec-comparison/
