### ISSUE TITLE
Some MODs with certain samples play incorrectly

### ISSUE THREAD

**Issue by 9a3eedi** [droidmjt/Droidsound#463]
I have a few MODs that seem to be played incorrectly, specifically ones made by LHS, which is one of my favorite chiptune artists. Attached is the most obvious example. Seems like the decoder doesn't like the higher pitches of a particular sample or something. 
[LHS_MI.zip](https://github.com/droidmjt/Droidsound/files/2611262/LHS_MI.zip)

This is what it's supposed to sound like
https://www.youtube.com/watch?v=xlVyv7bzTHA

I have more examples, but they're not as obvious
[LHS_FQ.zip](https://github.com/droidmjt/Droidsound/files/2611269/LHS_FQ.zip) (at 0:51)
[LHS_TLN.zip](https://github.com/droidmjt/Droidsound/files/2611279/LHS_TLN.zip) (at 0:45)

The same MODs play back fine on foobar, so I don't think the MODs are at fault. Disabling interpolation doesn't fix the problem. Using the Amiga resampler doesn't fix the problem. 

A long time ago, droidsound used to play these MODs correctly. I think after a plugin has changed, these stopped being played properly. I have also changed my phone, not sure if it's related.

 I'm using Android 8.0.0 on a Oneplus 3T and Droidsound 167_130

**Comment by droidmjt** [comment]
on foobar, what plugin did you use to play these MODs?

**Comment by droidmjt** [comment]
nevermind, I checked the _MI song, it's a bug in the libopenmpt library

**Comment by droidmjt** [comment]
created an issue in libopenmpt bugtracker, I'll close this case now, once the library gets updated I'll reopen this

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/em1e3qt4sj77u5l/droidsounde167_133.apk?dl=1
try this, I hope it works now

**Comment by 9a3eedi** [comment]
This has resolved the issue. The MODs now play correctly.

Thank you very much!

**Comment by droidmjt** [comment]
all right
