### ISSUE TITLE
droidsound-e entirely bypasses sound processor

### ISSUE THREAD

**Issue by GL1TCH04** [droidmjt/Droidsound#464]
i've recently updated to droidsound 1.67-131 only to find out that it started completely bypassing viper4android whereas the version i was using previously (from 2017, no exact build number) had no such issues
i'd love to do more in depth testing on this but that seems impossible due to the fact that APKs of old versions seem to get wiped 

device: SM-G935F
android version: 7.0
viper4android version if needed: 2.6.0.5

**Comment by droidmjt** [comment]
Could you tell me what you mean by bypassing, bypassing what exactly?

**Comment by GL1TCH04** [comment]
oddly enough i attempted to update droidsound again and despite being under virtually the same circumstances as the last time i updated, sound processing with v4a now functions perfectly fine which means i'm closing this issue
