### ISSUE TITLE
Does not load the next song on single-file playlists (tested on nsf+m3u, nsfe)

### ISSUE THREAD

**Issue by FHomps** [droidmjt/Droidsound#467]
When playing a single-file format, such as NES files (nsf+m3u and nsfe), the songs are properly loaded and it is possible to switch from one song to the next manually. However, at the end of a song, instead of playing the next one, the first song of the file is played over and over.

Tested on android 8 and 9 on version 167_141.

**Comment by droidmjt** [comment]
and make sure you have enabled **"Search M3U files for metadata**" load from the plugin settings you are using

**Comment by FHomps** [comment]
My bad. I think this should be the default behaviour, as it is with all other players I have used.
Thank you.
