### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#468]
I wanted to suggest a few QOL things for the player:
-Sort by rating: This would make making playlists of higher rated songs easier
-Ability to add individual or all songs of a playlist to another playlist: if you wanted to take parts of one, or make a big playlist of many to put on shuffle
-export/import playlists: I've changed SD cards a few times, and due to the SD folder having a unique ID, this breaks existing playlists, even if all the songs are copied to the new SD. (On a side note, I tried pulling the playlist files, replacing the folder ID in a text editor, although this still did not work).

-On a side note, I think the ratings on the file browser will sometimes not update and appear as unrated. The rating seems to always be correct on the play screen however.

**Comment by FraGag** [comment]
>  -export/import playlists: I've changed SD cards a few times, and due to the SD folder having a unique ID, this breaks existing playlists, even if all the songs are copied to the new SD. (On a side note, I tried pulling the playlist files, replacing the folder ID in a text editor, although this still did not work).

From my experience, editing (or replacing) the .plist file in `droidsound/playlists/` for a playlist known to Droidsound-E doesn't cause the app to refresh the playlist in its database. You have to copy the .plist elsewhere, delete the playlist from Droidsound-E (which should delete the .plist file in `droidsound/playlists/`), edit the copy, copy the file back and restart Droidsound-E; then the app will notice the new playlist and import it.

**Comment by froggestspirit** [comment]
I'll have to try that if I need to do this again, still, it'd be nice to have an option to export/import

**Comment by qwertysampletext** [comment]
For exporting and importing playlists, can't you simply use Settings > Playlists >  Update playlist DB to/from files?

**Comment by droidmjt** [comment]
* sort by rating: maybe one day
* Ability to add individual or all songs of a playlist to another playlist: not gonna happen
* export plist: you can do it already from settings, but i'll improve it so that only changed playlists gets updated since

**Comment by droidmjt** [comment]
DSE indexes the full path of the songs, so if the SDCard ID changes, you need to reindex again.

**Comment by AdityaMH** [comment]
And add last played list on playlist or main tab.. and add setting maximum "last played" list.
