### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by aplumafreak500** [droidmjt/Droidsound#469]
For multi-channel formats (BXSTM, ffmpeg, AST, etc.), I'd like the ability to toggle on or off specific stereo streams instead of mixing to mono. That or a substream selector (not unlike NSF subtracks) would be fine. Thanks in advance!

**Comment by droidmjt** [comment]
fixed this also

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/l93eshr0i9lq2tq/droidsounde167_145.apk?dl=1
try this

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/awcs4ycvuildybb/droidsounde167_146.apk?dl=1

**Comment by droidmjt** [comment]
leave a msg if something is not correct
