### ISSUE TITLE
Don't erase settings when /sdcard/droidsound missing

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#470]
If I wipe /sdcard (by moving /data/media to /data/media-backup) such that /sdcard/droidsound is missing, droidsound-e will extract a fresh folder and wipe settings.

If I move /data/media-backup back to /data/media, my settings are still wiped.

Can you prevent this from happening? (I'm not sure if it's already fixed or not.)

**Comment by droidmjt** [comment]
fixed this already

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/l93eshr0i9lq2tq/droidsounde167_145.apk?dl=1
try this

**Comment by jimbo1qaz** [comment]
144 would extract /sdcard/droidsound (25-26 items), but when I close and reopen dse, settings are gone.

- https://www.dropbox.com/s/7zsku94neehkse3/2019_03_02_06_48_24_trim.mp4?dl=0

145 fails to extract examples/etc (only 6 items in droidsound folder).

**Comment by droidmjt** [comment]
maybe I misunderstood your request, what is /data/media?

**Comment by jimbo1qaz** [comment]
/data/media is the underlying filesystem behind /sdcard.

Exactly what i did to it is irrelevant, but at least twice in the last 2-3 years I've renamed it deleted /sdcard/droidsound and lost my /data/data settings as a result.

**Comment by droidmjt** [comment]
The app needs to verify somehow if it's a first time when user runs it, it checks shared preferences and songs.db for this. I think in your case what ever software you use to backup/restore the /data/media/ somehow cleans the shared preferences, including dse preferences. I will put back how it was previously (144).

**Comment by droidmjt** [comment]
I need to think about this more.

**Comment by jimbo1qaz** [comment]
i uploaded w video where merely renaming droidsound using a file manager is sufficient to trigger data clear. (I did this around 2 years ago because i wanted to extract new examples not available in my older Examples.zip.)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/awcs4ycvuildybb/droidsounde167_146.apk?dl=1
here, should be better now, if you remove droidsound folder and start the app, at least for me it didn't reset preferences, it just extracts all the necessary files
