### ISSUE TITLE
Issues with Creating Ringtone

### ISSUE THREAD

**Issue by Galindorf** [droidmjt/Droidsound#471]
version: 
1.67.144(c)

on:
Samsung Galaxy Note 9 SM-n96ou1
Android 8.1
6GB RAM

I was having this issue on my old phone as well(note 5), I have successfully created many ringtones on previous versions. When I choose "create ringtone" I am able to enter the title, set the length, and create the ringtone successfully with title and have it set as default, but the song is less than 1 second long, no matter how long I set the length for. I have tried with various file types and subtunes. 

I do not remember which version I was using last that let me create the successful ringtone, but I can tell you it is not working for me on this version. Thanks!

**Comment by droidmjt** [comment]
crap, I'll check it

**Comment by droidmjt** [comment]
found the bug and fixed it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/l93eshr0i9lq2tq/droidsounde167_145.apk?dl=1
try, should work

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/awcs4ycvuildybb/droidsounde167_146.apk?dl=1

**Comment by Galindorf** [comment]
It's working! Thank you!   I just got this phone and it definitely needed some improved ringtones. :)
Mario 3: Athletic, ftw! (And the hit-point sound for the notification)

Say, it might be nice to be able to choose what folder to save an exported sound to.  At the moment, it defaults to the ringtone folder. But, if I want to make a notification instead, I have to move the sound out of the ringtone folder and into the notifications folder. Also, I will sometimes export video game music to use in other applications and it would be nice to save them in their own folder.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/vd86zw6ca2bh27e/droidsounde167_147.apk?dl=1
added notification option in ringtone creator, if it works, close this issue
