### ISSUE TITLE
Droidsound-E got crashed in AndroidQ

### ISSUE THREAD

**Issue by 97lily** [droidmjt/Droidsound#472]
### sorry. first time to use this using to issue posting.
**Device:**  Pixel3
 Android Beta Q (official) 1st build
**-case-**
**1).**  selected  nsf file in Droidsoujd file selected 
-the tryed nsf  from Bandcamp community distributed songs.
**2).**  Droidsound-E Crashed as start to play
-and Crash dialog isn't displayed　(Nevertheless tuned Developer Options)

**-RecordedLog-**

E/InputDispatcher(1335): Window handle Window{29a09c9 u0 Splash Screen com.droidmjt.droidsounde} has no registered input channel
E/AndroidRuntime(32392): Process: com.droidmjt.droidsounde, PID: 32392
E/AndroidRuntime(32392): at com.droidmjt.droidsounde.PlayScreen.updateInfo(PlayScreen.java:1026)
E/AndroidRuntime(32392): at com.droidmjt.droidsounde.PlayScreen.update(PlayScreen.java:953)
E/AndroidRuntime(32392): at com.droidmjt.droidsounde.PlayerActivity.update(PlayerActivity.java:3275)
E/AndroidRuntime(32392): at com.droidmjt.droidsounde.PlayerActivity$ValueChangeHandler.handleMessage(PlayerActivity.java:3103)
E/InputDispatcher(1335): channel '3f3962e com.droidmjt.droidsounde/com.droidmjt.droidsounde.PlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by droidmjt** [comment]
I cannot fix this until I have working emulator for AndroidQ

**Comment by droidmjt** [comment]
I managed to test the latest versino with Android Studio Emulator using Android Q, at least the default NSF songs worked ok, please send me the song what failed.

**Comment by 97lily** [comment]
...sorry just now success to play nsf file before deleting "dsroot" folder.
(I mind the directly is looklike existed at Oreo used)

thanks working and sorry my checking mistakes...

**Comment by droidmjt** [comment]
no problem, good that it works
