### ISSUE TITLE
Audio quality

### ISSUE THREAD

**Issue by Andr20** [droidmjt/Droidsound#473]
the player works perfectly but the audio quality with mp3 or wma is not so good to compare with other audio players, is there some way to improve it?

**Comment by droidmjt** [comment]
Is the difference audible? If yes, I would like to know what other players you mean.

**Comment by Andr20** [comment]
Yes the difference is audible, the player i tried are Nplayer, Mx-player and Neutron music player

**Comment by droidmjt** [comment]
I couldn't hear any difference, I tried neutron player. I noticed neutron player has various settings enabled and probably uses different codec for decoding MP3 files.

**Comment by Andr20** [comment]
The difference it can be noticed more using the normal speakers and with wma files, for example the sound with Nplayer is more clean and full

**Comment by droidmjt** [comment]
Droidsound-E is using ffmpeg to play wma files, if you know a better library to play wma files, let me know, otherwise close this issue since I cannot fix it.

**Comment by Andr20** [comment]
Sorry but also Nplayer is using ffmpeg

**Comment by droidmjt** [comment]
even better, in that case I shouldn't do anything :) Since the libraries are the same the only difference here is that they might apply internally some filter or something for wma.

**Comment by Andr20** [comment]
Oook, it is possible to have the version updated the beginning of July 2015, i remember that this time was working better the sound and unfortunately I've lost this version

**Comment by droidmjt** [comment]
No, it's not possible, those builds are gone, secondly, it would still be the very same library for WMA format and NOTHING has changed since those days when it comes to WMA playing. Maybe you are using different device or different OS version or ROM or additional sound filters

**Comment by Galindorf** [comment]
I don't know if this is helpful, but I got a new phone recently, and it has 
a bunch of stuff enabled that alters sound quality. I was trying to listen 
to a YouTube video and the mixing was really off. My phone had switched on 
a new feature called Dolby Atmos, it made the video sound terrible over my 
Bluetooth speaker. You may have some kind of setting happening in your 
phone that you don't know about.

**Comment by Andr20** [comment]
Sorry if i answer late but i was incredibly busy, at the end i think i resolve the problem using the app Equalizer FX pro, it would be nice to implement the equalizer on droidsound-e

**Comment by droidmjt** [comment]
if you have samsung phone, try SoundAssistant, its great

**Comment by droidmjt** [comment]
equalizer will arrive one day in droidsound-e
