### ISSUE TITLE
[Enhancement] Update NSFPlay to 2.4 Beta 18

### ISSUE THREAD

**Issue by stgiga** [droidmjt/Droidsound#474]
NSFPlay has finally added the hardware-accurate VRC7 Patches and NSF2 support. Can you please update nsfplay? https://github.com/bbbradsmith/nsfplay/releases has the newest beta in case beta 18 is obsolete tomorrow.

**Comment by droidmjt** [comment]
all right, I'll check it

**Comment by stgiga** [comment]
Let me know when a new build comes

**Comment by droidmjt** [comment]
do you have any example songs using NSF2 format?

**Comment by stgiga** [comment]
Yes. Family Noraebang exists as "Family Noraebang unordered unoptimized.nsf"

**Comment by droidmjt** [comment]
could you email it to me or include the link here?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/6nicmn3gl0cp81q/droidsounde167_148.apk?dl=1
try this, if it works, close this issue

**Comment by droidmjt** [comment]
I'll close this, leave a message

**Comment by stgiga** [comment]
It does

**Comment by stgiga** [comment]
The non-beta 2.4 is out.
