### ISSUE TITLE
F-Droid Version

### ISSUE THREAD

**Issue by ubergeek77** [droidmjt/Droidsound#475]
First of all, thank you very much for your hard work and dedication on this app. It's great to see that this is still being worked on. I use this app daily, and it's by far the best way to listen to my long library of VGMs I like.

I haven't seen this suggested here, so I thought I should bring it up.

Have you considered submitting this app to F-Droid? With this being an open source app, I feel like F-Droid would be a great fit. Users of F-Droid are automatically notified when a new version of an app is available, so in the case of Droidsound-E, people will no longer have to remember to keep checking this repository for any new Dropbox links.

What do you think? There's tons of amazing FOSS apps on F-Droid, and I think Droidsound-E would be right at home there.

**Comment by droidmjt** [comment]
so you want me to host the binary there?

**Comment by ubergeek77** [comment]
I've never submitted an app, but I believe their build system requires you to merge the source to their own repository, and then their sever builds the .apk and publishes it to the store. It is a store for FOSS apps, after all.

They have a toolset that helps you do this very quickly. Here's some more info on the submission process:

https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by droidmjt** [comment]
right, thanks but I pass

**Comment by ubergeek77** [comment]
Sorry you feel that way. But I hope you'll reconsider in the future. It would really have a positive impact on this project.

Thanks for your time.

**Comment by awsms** [comment]
Damn, I was going to ask for it.
It would be great if you could make at least an [an F-Droid repo](https://www.f-droid.org/en/tutorials/create-repo/) since we have no idea when an update comes out without having to go back on the git everyday

**Comment by droidmjt** [comment]
next version has an update checker

**Comment by awsms** [comment]
> next version has an update checker

Glad to hear it !

**Comment by 9ary** [comment]
> I've never submitted an app, but I believe their build system requires you to merge the source to their own repository, and then their sever builds the .apk and publishes it to the store. It is a store for FOSS apps, after all.

That's not how it works. You submit a metadata file and then their bot will detect new versions. After the initial submission you usually don't have to do anything. The only problem is that it usually takes several days for updates to become available to end users because they have to manually approve and sign each build.
