### ISSUE TITLE
App permissions

### ISSUE THREAD

**Issue by tduyduc** [droidmjt/Droidsound#476]
Hi, could you please give me an explanation why this Droidsound-E release (version 167 at the time of writing) needs Microphone and Telephone permission?
![Screenshot_20190417-093907_Package installer](https://user-images.githubusercontent.com/15998902/56256898-c1219100-60f4-11e9-9a6a-3fe96c9f49c1.jpg)

**Comment by droidmjt** [comment]
RECORD_AUDIO for this: https://developer.android.com/reference/android/media/audiofx/Visualizer

READ_PHONE_STATE for this: https://developer.android.com/training/permissions/usage-notes
see topic **Pause media after losing audio focus**

**Comment by tduyduc** [comment]
Thank you so much for the clarification! :D
