### ISSUE TITLE
[Issue] Droidsound not seeing/adding .aiff files 

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#477]
Using 1.67 148. Added 3DO VGM in .zip format as DB Browser, also tried browsing the .zip files manually. Droidsound does not see or add .aiff files, despite it being seemingly supported in vgmstream. The readme for vgmstream does say that some filetypes clash with certain players, and .aiff renamed extension to .aiffl does allow files to be seen and played by Droidsound. 

Since Droidsound does not seem to utilize native .aiff support, can the .aif and .aiff filetypes be added to the vgmstream plugin as default? Not sure if other "conflict" file formats have a similar issue, will see if I can find any.

Let me know if you need me to provide a sample set for this.

**Comment by droidmjt** [comment]
aiff extension won't be a problem, could you give one sample so i can test if it works?

**Comment by Level99OCR** [comment]
http://3do.joshw.info/a/Advanced%20Dungeons%20&%20Dragons%20-%20DeathKeep%20(1995)(Lion)(SSI)%5b3DO%5d.7z

**Comment by droidmjt** [comment]
seems to work, I'll check the other issue now

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/pme8buawrzurd8g/droidsounde167_150.apk?dl=1
try this, both issues should be fixed

**Comment by droidmjt** [comment]
I'll close this case, leave a msg

**Comment by Level99OCR** [comment]
Apologies, I had unforeseen health issues crop up. Tested and this works great, thanks so much.
