### ISSUE TITLE
[Enhancement Request] Detect and Skip Silence

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#478]
No idea how difficult or time-consuming this would be, and I'm sure you've still got your own set of enhancements and priorities that you're working on. The ability to detect silence for a certain amount of time (Eg under -30db for X seconds) and then skip to either the next song or subsong as is already configured would be nice to have. For things like full chiprips of Wonderswan, Game Boy, etc where there are way more empty tracks than full, Droidsound could detect and skip forward.

Foobar has an implementation where it basically fast forwards through a track, however for Droidsound since some file formats do not support native seeking, a simple skip to next would probably be more viable. No worries if this is a no-go, just throwing the idea out there. Thanks as always for your continued development on the app.

**Comment by droidmjt** [comment]
I can do this, I just need to adjust the existing silence detector a bit

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/pme8buawrzurd8g/droidsounde167_150.apk?dl=1

**Comment by droidmjt** [comment]
leave a msg

**Comment by Level99OCR** [comment]
Is this enabled by default or is there a setting I'm just not seeing to enable it? Will be testing during the day regardless.

**Comment by droidmjt** [comment]
it enabled always, if something it fails in some files, could you post the files/links here

**Comment by Level99OCR** [comment]
Okay, so A.IV. Evolution: A Ressha de Ikou 4 seems to be failing right at the end of the file. Not a hardcrash but it'll stick about 5-6 seconds before the end and never go to the next song. Pressing forward manually does work to go to next song.

I disabled Audio Fadeout and that resolves the issue. So looks like it might be a conflict between the Audio Fade feature and the silence detection. 

http://psf.joshw.info/a/A.IV.%20Evolution%20-%20A%20Ressha%20de%20Ikou%204%20(1994-12-03)(Artdink)%5bPS1%5d.7z

**Comment by droidmjt** [comment]
right, the fadeout, crap, forgot to test with that in the first place, I'll try to get it fixed

**Comment by droidmjt** [comment]
which song of the game? and did you use the append fadeout length to song length option? what is your default fadeout length value?

**Comment by droidmjt** [comment]
>> but it'll stick about 5-6 seconds before the end and never go to the next song

ah, so you append the fadeout length to songlength, I never understood that feature anyways. I should remove the whole nonsense feature

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/p66q04k3qhhsjz3/droidsounde167_153.apk?dl=1
try this, let me know if something else broke

**Comment by Level99OCR** [comment]
grabbing now and testing today

**Comment by Level99OCR** [comment]
A few days without issue, closing this, thanks again.
