### ISSUE TITLE
Change track by long pressing volume button

### ISSUE THREAD

**Issue by Diamondragon** [droidmjt/Droidsound#479]
There appears to be a new API in android 8 and onwards that allows you to set an app up to use an ADB command to unlock changing tracks while the screen is off by long pressing the volume buttons.

https://www.xda-developers.com/android-oreo-volume-key-long-press/
https://www.xda-developers.com/skip-music-tracks-android-volume-keys-no-root/

I was wondering if this is something that Droidsound could support?

**Comment by droidmjt** [comment]
sounds like a boring feature :)

**Comment by Galindorf** [comment]
So! If you have a samsung like I do, there is an amazing app called 
bxActions that lets you reprogram the (ugh) Bixby button. However, if you 
implement full remapping, you can also reprogram the volume keys and Bixby, 
 with different instances for lockscreen or not, with single, double, hold, 
and tap-hold actions. I currently have Bixby on single click for play/pause 
on lockscreen, with double click for "next
" it works for whatever media I'm playing (off lockscreen I use it as a 
clickable back button) Maybe that can help you?

**Comment by Diamondragon** [comment]
Trust me, it's really exciting! Back in the day, phones could change the currently playing music without turning on the screen. Kinda like the old iPod Shuffle. Don't know why Google never added it to AOSP as a real, user facing feature. Way less hassle, IMO. 

Tried forcing the permission on Droidsound-E, but it looks like it really does need some change in the code:

D:\development\platform-tools>adb shell pm grant com.droidmjt.droidsounde android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER
Security exception: Package com.droidmjt.droidsounde has not requested permission android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER

java.lang.SecurityException: Package com.droidmjt.droidsounde has not requested permission android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:379)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1436)
        at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:91)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2133)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6001)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1735)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:222)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22550)
        at android.os.Binder.shellCommand(Binder.java:655)
        at android.os.Binder.onTransact(Binder.java:553)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2836)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4304)
        at android.os.Binder.execTransact(Binder.java:752)

If it isn't something you're interested in, that's cool too. I don't know how much work this would be, and besides: it's an undocumented API, who knows how long Google'll keep it along. But I've gotta say that I think it would be super neat.

**Comment by Diamondragon** [comment]
Hi Galindorf. Thank you for the idea, but I use a OnePlus 6. I've sometimes tried button reprogrammer type apps, but they never seem to work, or they have lots of weird restrictions. I was looking for a way to make my music apps work like they did when I had a customer ROM. Cilenco hade a new app, Skip Track by Volume Keys, to use this new functionality, but while it works with some music players (VLC, Google Play Music), it doesn't work with the ones I use most (Droidsound-E, PowerAmp.) Max has since updated PowerAmp to support this permission without the need for a separate app, so I wondered if that might be viable here.

**Comment by Diamondragon** [comment]
Hi Galindorf. Thank you for the idea, but I use a OnePlus 6. I've sometimes tried button reprogrammer type apps, but they never seem to work, or they have lots of weird restrictions. I was looking for a way to make my music apps work like they did when I had a custom ROM. Cilenco has a new app, Skip Track by Volume Keys, to use this new functionality with all installed music players, but while it works with some music players (VLC, Google Play Music), I find it doesn't work with the ones I use most (Droidsound-E, PowerAmp.) Max has since updated PowerAmp to support this permission without the need for a separate app, so I wondered if that might be viable here.

**Comment by droidmjt** [comment]
this feature would make the volume changing problematic while the screen is turned off

**Comment by Diamondragon** [comment]
It actually works a lot better than you might guess. It takes holding down for just over one second to change track, so a quick press, or succession of quick presses to raise more than one notch, won't trigger it. Even setting that aside, if you did implement this, the process of giving the permission to Droidsound over ADB (it can't be done through the OS' user interface) should ensure that anyone who does would know what they are doing. The feature was a staple of older devices, Blackberry and other feature phones, and on custom ROMs. Makes changing songs so quick and easy, when you don't need to pull your phone out of your pocket, turn on the screen, open Droidsound/some other music app. Especially useful in winter!

**Comment by droidmjt** [comment]
I googled about this feature and learned that it uses a hidden API and a modified android.jar is needed to make it work. Android official developer page doesn't show anything about this. As long as the API is not officially supported, its a no go, sorry.

**Comment by Diamondragon** [comment]
I see. Thank you for looking into it, though.

**Comment by Diamondragon** [comment]
I had one last question, actually. When I install the app, 'Skip Track by Volume Keys', and give it the permission it needs, it does work with most of my music apps (Google Play Music, VLC), including even other chiptune players (MoDo Computer Music Player, ZXTune), but it doesn't work to control Droidsound. Is there any way to allow Droidsound work with it?

**Comment by droidmjt** [comment]
It's not about allowing or not, I can add the permission to permissions list but thats it. I don't think it makes any difference.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ryfprtd4bmagvhk/droidsounde167_152.apk?dl=1
try

**Comment by Diamondragon** [comment]
It was worth a shot. Thank you for trying.

**Comment by droidmjt** [comment]
I tried the app you mentioned, surprisingly I was able to make it work by long pressing down it changed the tune, but I'm puzzled how it can even work like that.

**Comment by Galindorf** [comment]
Beats me! If you get the pro version and unlock the USB debugging thing 
with your PC, it can do even more. I was wondering if it would work on 
other phones!
