### ISSUE TITLE
Subtunes inaccessible through favorites

### ISSUE THREAD

**Issue by TheShinyCookie** [droidmjt/Droidsound#480]
When playing a file with multiple tunes in one through the favorites list (could be any playlist, haven't tested), trying to use the next button just goes to the next file in the list. It does work through search and the file browser.

**Comment by droidmjt** [comment]
go to settings -> playlists -> disable the one single entry mode

**Comment by TheShinyCookie** [comment]
Ah, thanks, it worked :)
