### ISSUE TITLE
[Bug] [Enhancement] Allow full 100k bassmidi polyphony on faster phones to allow KOR and Dsoundfont Ultimate to work.

### ISSUE THREAD

**Issue by stgiga** [droidmjt/Droidsound#481]
The two biggest sf2 files on the web, KOR GM Complete V4.51 and Dsoundfont Ultimate are great soundfont files. But at only 1000 note polyphony they just skip like a stone when you try to play any midi that isn't basic. Thus I ask that you allow users to Max it out to the limit bassmidi hardcodes at 100k that is used in omnimidi. Here is the most problematic sf2, Dsoundfont Ultimate: https://drive.google.com/file/d/11xdnOAwIaQNpPZ1eKwRBul47Bv1-MBSh/view?usp=drivesdk 

If this is caused by anything else, let me know and please fix it if possible.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/cikwuuer2emfg1z/droidsounde167_151.apk?dl=1
try this

**Comment by stgiga** [comment]
It doesn't fix the issue. But it does fix other midi files on other soundfonts. Must be cpu

**Comment by droidmjt** [comment]
could you send me one of those problematic midi files

**Comment by stgiga** [comment]
https://freemidi.org/download3-1827-simpsons-tv-themes is one that breaks with any sf2 with enough layers. It seems that complex midi files do not combine with complex soundfont files

**Comment by droidmjt** [comment]
tried the simpsons.mid with SGS8 using the dsoundfont + 100000 voices, no problems

**Comment by droidmjt** [comment]
actually, could you tell me, what do you mean by layers?

**Comment by droidmjt** [comment]
and how does it break?

**Comment by droidmjt** [comment]
by the way, if possible, find another app using BASSMIDI and see if the problem is there, if yes, report to Ian at un4seen.com forum.

**Comment by droidmjt** [comment]
from un4seen.com BASS documentation:
>>Platform-specific
>>The maximum setting is 1000 on Android, iOS, and Windows CE.

**Comment by stgiga** [comment]
Well then, guess it's gonna be limited until faster cpus are mainstream in Mobile

**Comment by droidmjt** [comment]
We'll see.

**Comment by droidmjt** [comment]
I did a small test with the simpsons song, maximum amount of voices it used was 420 and max memory consumption was 173 188 988 bytes.
