### ISSUE TITLE
Feature Request: Add setting to ignore Audiofocus requests

### ISSUE THREAD

**Issue by dicene** [droidmjt/Droidsound#484]
I listen to a lot of video game music while working, and often like to simultaneously listen to YouTube videos or audiobooks. I'm currently limited to listening to OST's using RocketPlayer with mp3's because it's basically the only player(besides the subpar MusixMatch) I could find that can ignore AudioFocus requests and continues playing when a second source of audio is used. Looks like it'd hopefully be an easy feature to implement since it'd be a combination of an additional setting in the Misc Setting menu and addition of a conditional or two in the AudioFocusWrapper. Either way, much appreciate the time you put into maintaining this fantastic app.

**Comment by droidmjt** [comment]
I'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/jscqkbomyg8h2xk/droidsounde167_162.apk?dl=1
try this, from Settings -> Misc Settings you can disable audiofocus

**Comment by dicene** [comment]
The new feature seems to be functioning as intended. DroidSound is ignoring audiofocus requests, and isn't sending them out. However, playing a track that is already loaded and paused(showing up in the Player screen) is causing a crash 100% of the time while audiofocus is disabled. I was able to reproduce this crash reliably with PSF files and MP3's both, and it did not matter if any other app was playing music at the same time or not.

Steps to reproduce crash:
- Disable audiofocus and restart DroidSound
- Play any song
- Press pause
- Unpause
- Music WILL begin playing, but crash occurs immediately after music start. Music continues playing until you confirm to Android that you want to restart DroidSound.

I'll be using the new feature throughout the day some, so if I see any other issue, I'll document it here.

**Comment by droidmjt** [comment]
should be fixed now, try this:
https://www.dropbox.com/s/ezz3eocvic0zvvr/droidsounde167_163.apk?dl=1

**Comment by dicene** [comment]
Looks fixed to me. I'll let you know if anything misbehaves as I use it today

**Comment by droidmjt** [comment]
good, leave a msg
