### ISSUE TITLE
Mp3 format for creating Ringtone

### ISSUE THREAD

**Issue by AdityaMH** [droidmjt/Droidsound#485]
Can you add mp3 format for create ringtone?
Because if using .wav format, 4 minute music length can take above 40mb.

**Comment by droidmjt** [comment]
I'll try to get that fixed

**Comment by DavidOliM** [comment]
It would be cool if it could also like, record 2 loops and a 10s fadeout

**Comment by droidmjt** [comment]
it would work just like it is now except the end result is mp3 format

**Comment by DavidOliM** [comment]
I see you changed it, though we still have to set the time manually instead of selecting how many loops

**Comment by droidmjt** [comment]
>> I see you changed it

what do you mean, what did I change?

**Comment by DavidOliM** [comment]
Last time i used this function (a few months ago) it didnt have a fade out.

**Comment by droidmjt** [comment]
fadeout has been there at least 2 years

**Comment by droidmjt** [comment]
I can set default time to 1min for example

**Comment by DavidOliM** [comment]
If possible, you could set the current music time as variable and use that as the time limit

**Comment by droidmjt** [comment]
I'll set it to 3min as the default time

**Comment by droidmjt** [comment]
tiny change to plans, there won't be MP3 format for ringtones instead there will be M4A

**Comment by AdityaMH** [comment]
My very "old" phone don't support .m4a at all, but that can add as format option to create ringtone.
But can you decreasing quality for decrease size file?
And sometine fadeout won't work either.

**Comment by DavidOliM** [comment]
I agree, it doesn't make sense using m4a/mp4 as a ringtone format unless you use this function to render a chiptune to a streamed format. A more suitable format for ringtones would be ogg, and i believe most android phones support it as a ringtone

**Comment by droidmjt** [comment]
@AdityaMH if the fadeout doesn't work, you need to provide steps how to reproduce it.

**Comment by AdityaMH** [comment]
I creating ringtone from psp game music with 4 minute and 10 second fadeout.
After completed created, that ringtone saved without fadeout when playing.
[bgm_eve_a_06.zip](https://github.com/droidmjt/Droidsound/files/3243797/bgm_eve_a_06.zip)

And maybe you understand this.
![Screenshot_2019-06-01-20-34-08-504_com estrongs android pop](https://user-images.githubusercontent.com/33791472/58749179-b35d7a80-84ac-11e9-8632-755f05d85164.png)

And one more thing, droidsound notification don't go to droidsound app when clicked.

**Comment by AdityaMH** [comment]
> I agree, it doesn't make sense using m4a/mp4 as a ringtone format unless you use this function to render a chiptune to a streamed format for later listening. A more suitable format for ringtones would be ogg, and i believe most android phones support it as a ringtone

My very "old" phone not Android phone, and only support .mp3, .aac, .wav, .amr (ignore about .amr).

**Comment by droidmjt** [comment]
The problem with MP3 is that it cannot store the sample rate.

**Comment by AdityaMH** [comment]
No problem with .wav format if can't implemented .mp3 format, but i still have problem with file size and fadeout,
 and now i found (bug) player in notification can't direct to app when touched/clicked.

P.S.: Don't be confused, i have 2 phone and my current phone is Android.

**Comment by droidmjt** [comment]
What is your Android phone brand and model? In old Android versions I used to experience the notification bug also but not anymore since Android 7 or so.

**Comment by AdityaMH** [comment]
Previous version still work, but after update to build 159, this bug always happen.
Btw, my phone Android is 7 (Nougat).

**Comment by AdityaMH** [comment]
Ignore about notification. since last update, app permission changed by themselves.
That's why player on notification didn't respond.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/4hk6fvjinkexdwq/droidsounde167_164.apk?dl=1
try this, I hope everything is fixed

**Comment by AdityaMH** [comment]
yes everything is fixed, I hope next update add ringtone format, I don't want previous format (.wav) to be deleted, and maybe someday add more format too.

**Comment by droidmjt** [comment]
We'll see.

**Comment by AdityaMH** [comment]
Wow, I don't know if you really add .mp3 format.

About ringtone title, please replace default title from "Droidsound-E" to actually music title.
maybe sometime previous music will be deleted, if forgot rename music twice even different music.
Or maybe can't give a kanji name.
![Screenshot_2019-07-07-20-53-06-853_com droidmjt droidsounde](https://user-images.githubusercontent.com/33791472/60769818-8ed56d80-a0fe-11e9-8b23-222e71a17eba.png)
