### ISSUE TITLE
Title of Subtunes Were Invisible if File Title Was Too Long

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#487]
[Might & Magic- Secret of the Inner Sanctum.zip](https://github.com/droidmjt/Droidsound/files/3260199/Might.Magic-.Secret.of.the.Inner.Sanctum.zip)

The above file has a long title.
The titles for subtunes were invisible.

Is it possible to word-wrap the title part?

**Comment by droidmjt** [comment]
no need to wrap, download the latest version (build 164)

**Comment by droidmjt** [comment]
I'll close this issue since the problem is fixed. You should see the scrolling title since build 164.

**Comment by wmjordan** [comment]
Thank you for addressing this issue.
Unfortunately I could not access dropbox in my country. I will attempt to download your release later. If you could upload your releases on GitHub, that will be much obliged.

**Comment by droidmjt** [comment]
Sorry, I won't be uploading any APK files here, you need to find a way how to get them from Dropbox.
