### ISSUE TITLE
HCA TXTP Doesn't loop even when loops are installed

### ISSUE THREAD

**Issue by mistersiraj11** [droidmjt/Droidsound#488]
This issue is fixed in the latest vgmstream but not with Droidsound-E. Can you implement that fix in here? I'll send you the files here.

This is the HCA and TXTP files together: https://mega.nz/#!ZWhRQKAQ!02z7973Yf0bnfmv0kle8n5iz6r6JAVMFzkD9OGpf2Gw

**Comment by droidmjt** [comment]
I'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/c8sn3iq3sr2svz0/droidsounde167_168.apk?dl=1
try this

**Comment by mistersiraj11** [comment]
It works. Thanks!
