### ISSUE TITLE
167 67 Crashing

### ISSUE THREAD

**Issue by tleej** [droidmjt/Droidsound#489]
Droidsound 167 67 Keepa crashing when I do a Filesystem broqsee rescan. I'm using an Samsung S9

**Comment by tleej** [comment]
Browser rescan. Sorry

**Comment by droidmjt** [comment]
Are you talking about build 67 or 167, build 67 is ancient? Secondly, filesystem browser doesn't have rescan option. Incase this is a mixup of DB browser rescan, you need to provide logcat log of the crash, you could also check crashlogs folder if there is anything. Without proper log file or steps how to reproduce the problem I cannot fix it.

**Comment by tleej** [comment]
Version 1.67.167. How do I get a log file?

**Comment by droidmjt** [comment]
check the crashlogs folder if there is anything, otherwise, google for instructions how to create android logcat log file, its not rocket science

**Comment by AdityaMH** [comment]
And for me, keep crashing when select "new playqueue" on playlist before play a music.

**Comment by droidmjt** [comment]
fixed the playqueue problem

**Comment by droidmjt** [comment]
@tleej, get adb.exe from Android SDK, connect your phone to your computer and run adb.exe logcat

**Comment by droidmjt** [comment]
@AdityaMH try this: https://www.dropbox.com/s/c8sn3iq3sr2svz0/droidsounde167_168.apk?dl=1

**Comment by droidmjt** [comment]
I'll reopen this once you provide the logcat log
