### ISSUE TITLE
List all tracks of nsf, gbs music files

### ISSUE THREAD

**Issue by rainsrx** [droidmjt/Droidsound#490]
Request for droidsound to list all tracks on NSF and gbs music files. For example, selecting zelda.gbs, droidsound would list track 1, track 2, etc. That way, we can select the track number we want instead of skipping x tracks to get the desired track. Foobar 2000 does this and I would like this feature on droidsound. Thanks for your work on droidsound, it is a well done music player.

**Comment by droidmjt** [comment]
and in which view you would like to see these tracks?

**Comment by droidmjt** [comment]
the only way to implement this is to handle those formats like archives, but in that case it probably gets confusing

**Comment by droidmjt** [comment]
to be precise, fb2k PC version has that version, not mobile, it's easy for windows applications

**Comment by rainsrx** [comment]
Something similar to how droidsound handles super Nintendo music files (rsn). It will show track 1, track 2 etc since gbs and nsf has no track names.

**Comment by droidmjt** [comment]
for RSN it was easy since RSN is an archive

**Comment by rainsrx** [comment]
It was worth a shot. Adding the tracks I like in favorites is always an option. Thanks for your time and feedback.

**Comment by droidmjt** [comment]
crap, I didn't mean I wouldn't add it, I'll add it but I also add an option to disable the feature since some ppl probably don't like the idea :)

**Comment by Galindorf** [comment]
I love the idea! Would make it WAY easier to make ringtones and 
notifications without having to forward through 42 tracks of sound 
effects.... AGAIN

**Comment by AdityaMH** [comment]
And i like that feature, some nsf file like "Downtown Nekketsu Koushin Kyoku - Soreyuke Daiundoukai" has 101 tracks. if i want to track # 95, i must click next until 95 times..

**Comment by droidmjt** [comment]
small setback for this feature, the subtune selector would only appear in player view during playback, the archive type of handling would overcomplicate things too much, sorry about that

**Comment by droidmjt** [comment]
the new subtune selector would be a fragment what shows all the subtunes and can be scrolled to selected subtune

**Comment by rainsrx** [comment]
Is the new subtune selector available with the new build?

**Comment by droidmjt** [comment]
this feature is not done yet

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/oryaqyqpfb1772a/droidsounde167_172.apk?dl=1
try this, the subtune selector can be opened by clicking the [01/01] in player view, there must be more than 1 subtune

**Comment by AdityaMH** [comment]
Fantastic..
I hope this selector implemented for playqueue too..

**Comment by droidmjt** [comment]
I'll close this case, in case of errors, leave a message

**Comment by rainsrx** [comment]
Thanks so much for this
