### ISSUE TITLE
VGM Stream plugin broken on 168 update

### ISSUE THREAD

**Issue by DooMGuy87** [droidmjt/Droidsound#491]
The app crashes trying to play VGM Stream files (.adx, .aiff, .xa) after the last update (168). Here is the crashlog if it helps.
[droidsounde_crash_20190614_072013.log](https://github.com/droidmjt/Droidsound/files/3290251/droidsounde_crash_20190614_072013.log)
Just downgraded the app to 164 and they play just fine.

**Comment by droidmjt** [comment]
right, I'll get it fixed ASAP

**Comment by droidmjt** [comment]
actually, go to settings and change your fade length to 25, now its using your old value

**Comment by DooMGuy87** [comment]
Thanks for the quick reply. Reinstalled 168, changed the fadeout value and the songs play again.
BTW thank you for the hard work you put on this, this app is amazing! :)
