### ISSUE TITLE
[Issue/Crashing] 167_168 version has ADX playback crashing

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#494]
Just got to adding back my Dreamcast collection. .DSF files work fine, but any attempt to play any .ADX file causes a Droidsound crash. Haven't tried a clean install as I went from 152 to 168 and all other formats work just fine. Let me know if you can't replicate the issue.

**Comment by droidmjt** [comment]
its the fade length thing, change your current fade length to integer value, for example 25.0 to 20

**Comment by droidmjt** [comment]
see issue #491

**Comment by Level99OCR** [comment]
Ah, okay, that seems to have done it. Thanks so much.
