### ISSUE TITLE
Could not Open File with Japanese Characters in File Name

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#495]
If we put a file into dsroot folder, it will be placed into the top most list in the browser.
However, if the file name contains Japanese character, that file will not be listed there or opened.

**Comment by droidmjt** [comment]
![japanese2](https://user-images.githubusercontent.com/5917820/60000921-e939ed00-966d-11e9-92e8-35115228f0a2.png)

**Comment by droidmjt** [comment]
works just fine, the problematic part is to transfer those files with asian characters in them. What I did is I renamed the bla.adl file after transfering, it also shows up in the filelist.

BTW, notice the background, its GLSL shader :)

**Comment by wmjordan** [comment]
I had trouble with this file (it was an RSN file, renamed to zip due to the file extension limitation of GitHub).
[ルドラの秘宝.rsn.zip](https://github.com/droidmjt/Droidsound/files/3319781/rsn.zip)

**Comment by wmjordan** [comment]
The above file wouldn't show up in the Browser list, after I put it into the _droidsound/dsroot_ folder.

**Comment by droidmjt** [comment]
![japanese3](https://user-images.githubusercontent.com/5917820/60015346-eea63000-968b-11e9-9e83-c7bf9b788981.png)

**Comment by droidmjt** [comment]
not exactly the same filename but it works, what I had to do is, first type the asian characters then switch to non-asian typing and add the extension (.rsn)

**Comment by droidmjt** [comment]
well, there is nothing I can do here, leave a msg

**Comment by wmjordan** [comment]
Well, I will try it on another cellphone and see whether it is due to unknown OS restriction.

**Comment by droidmjt** [comment]
BTW, those characters, I hope they don't mean anything, I just randomly typed something, first one should be chinese, second japanese. I don't think there are any restrictions, just add the extension with the dot like I guided.

**Comment by wmjordan** [comment]
On another cellphone, I copied the RSN file in trouble to a folder, and opened it with DroidSoundEx.
The app moved it to the _dsroot_ folder and updated the music database without any problem.
Yet on my previous phone, the file was just removed by DroidSoundEx (it did remove the file, but no file emerged in `dsroot` folder) after my attempt to open that file with the app.

**Comment by droidmjt** [comment]
What is DroidSoundEx? If you mean Droidsound-E, there is no code in the whole app what would move files around or delete files without user asking to do so first.

**Comment by wmjordan** [comment]
Oops, yes, DroidSound-E.

That was what I had experienced.
Every time when I clicked any rsn file in the file manager on my cellphone, the file manager would ask me with which app I would like to open that file, I selected DroidSound-E. After that, the rsn file was removed from its original position and moved to the _rsroot_ folder.

At first I was astonished to see that.
On both of my cellphone this issue occurred.
I thought that was by design.

**Comment by droidmjt** [comment]
I'll double check that. Anyway, so it works with your other phone, thats good. What comes to the original problem, I don't know what to do about it anymore.

**Comment by wmjordan** [comment]
Maybe the original problem has something to do with the aforementioned file removal issue.

**Comment by droidmjt** [comment]
Ah yes, if you click an archive with an external application the archive moves into dsroot, my bad. I'll remove the file moving part, let's see if it fixes anything.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1nz2zsz0fb0poal/droidsounde167_171.apk?dl=1
removed the zip file moving and launch from external app

**Comment by wmjordan** [comment]
I downloaded the new build.
Files no longer got removed. However, I still could not open files from the file manager.
I got this.
DroidSound had already been given file system privilege.

![shot](https://user-images.githubusercontent.com/12182730/60336710-b0827680-99d3-11e9-9684-1e80a50458a3.png)

**Comment by droidmjt** [comment]
Why you are using external file manager to play files?

**Comment by droidmjt** [comment]
also which file manager is it?

**Comment by wmjordan** [comment]
The file manager is a builtin one in my cellphone (_MIUI 10_).

Previously I found that if I opened a file with DroidSound from the file manager, it would be added to the Browser list in DroidSound.
Afterward, I will play that file from DroidSound.
