### ISSUE TITLE
Droidsound 169 crashes with every file

### ISSUE THREAD

**Issue by TheShinyCookie** [droidmjt/Droidsound#496]
After updating to this version, no files will play anymore, instead resulting in a crash.

STACKTRACE:
===========
java.lang.NumberFormatException: For input string: "5.0"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.droidmjt.droidsounde.service.Player.run(Player.java:1554)
	at java.lang.Thread.run(Thread.java:764)
============================
Droidsound-E build: 169
Time: Tue Jun 25 22:19:45 GMT+01:00 2019
CPU: armeabi-v7a
CPU: armeabi
Fingerprint: samsung/j6ltecis/j6lte:9/PPR1.180610.011/J600FXXU3BSD6:user/release-keys
CPUFeatures : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
Lang: English
Locale: en_GB
InternalSD free space: 17359740928
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
change the fadeout length to 5 instead of 5.0

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/fkzrcjl4955rrof/droidsounde167_170.apk?dl=1
I made a new build to avoid this problem

**Comment by droidmjt** [comment]
also please try the GLSL shader feature

**Comment by droidmjt** [comment]
before that, you probably need to go to Settings -> Misc Settings -> extract system/lib related files

**Comment by TheShinyCookie** [comment]
I don't know what GLSL shader feature you're talking about or what it has to do with playing music, but the app's working again now. Thanks :)

**Comment by TheShinyCookie** [comment]
I don't know what GLSL shader feature you're talking about or what it has to do with playing music, but the app's working again now. Thanks :)

**Comment by droidmjt** [comment]
go to Settings -> UI Settings -> GLSL Settings, then enable the GLSL shader, and try plasma and universe for example :)

**Comment by droidmjt** [comment]
remember to click the extract system/lib related files button from Settings -> Misc Settings

**Comment by Level99OCR** [comment]
Whoa, that is super-rad! Plasma runs great on my Moto G6 without any quality changes but I need to set it down to .3 for Universe to run at any kind of smooth speed. Small hiccup is that if you disable the bg while a song is playing after the bg has already started, it'll be stuck on whenever the player is stopped.

**Comment by droidmjt** [comment]
great, thanks for testing, I'll check the bug. The universe, for 1.0 quality you need to run it on emulator :)

**Comment by TheShinyCookie** [comment]
Looks pretty cool, plasma runs full speed at 1 but universe is also choppy for me. Same bug with disabling bg

**Comment by droidmjt** [comment]
I was able to reproduce the bug, will fix it. Yeah the universe is choppy for 100% users. Time will fix it.

**Comment by JFD62780** [comment]
Long time, no post.

Thing is I just upgraded my phone to a Galaxy S9, and Universe itself is smooth at 1.0 quality, but the Spectrum Analyzer is choppy.

0.5 runs both smoothly tho. ;)

**Comment by droidmjt** [comment]
[seascape.zip](https://github.com/droidmjt/Droidsound/files/3334254/seascape.zip)
unzip this one to your droidsound/shaders folder and say goodbye to your phone GPU :)

**Comment by 0ddb0d** [comment]
Cool! Just tried seascape on my Poco F1.

At 0.25 quality everything's fine, most browser ads are worse. At 0.5 the spectrum analyzer slows considerably but the shader only shows minor drops. At 1.0 the smell of magic smoke begins :-P

Presumably we can expect ray tracing in the next release.
