### ISSUE TITLE
Player changes files when playing multi-track files (GBS, NSF)

### ISSUE THREAD

**Issue by grandta13** [droidmjt/Droidsound#498]
When attempting to listen to files which have multiple tracks within them, such as Gameboy GBS files, if a particular track finishes playing without the user tapping the skip button, the player will try to proceed to the next file in the directory, rather than the next track within the current file.

Droidsound 1.67.171
Android 7.0
Samsung Galaxy S7 SM-G930V

This issue also occurred with the previous version of Droidsound that I had installed, though I didn't think to take note of the version. Though I do know I installed it over a month ago.

**Comment by droidmjt** [comment]
In settings there is an option to fix this.

**Comment by droidmjt** [comment]
settings -> misc settings -> cycle subtunes
