### ISSUE TITLE
CTR Nitro-Fueled .SND don't play correctly

### ISSUE THREAD

**Issue by hoodlum47** [droidmjt/Droidsound#499]
Hello!

It seems the .SND files from this game don't play correctly in this app. Just a bunch of audio jibberish is spat out when trying to play them.

I can attach a sample if needed.

**Comment by froggestspirit** [comment]
I believe this may go hand in hand with Mario Maker 2's cwav files. I'm wondering if updating to the latest vgmstream would fix both?

**Comment by droidmjt** [comment]
will fix this after #490 is completed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/oryaqyqpfb1772a/droidsounde167_172.apk?dl=1
try this

**Comment by froggestspirit** [comment]
The update fixed some of the CTRNF soundtrack, although a few still cause the "too many errors, stopping" message and don't play. I got that error for all Mario Maker 2 songs as well. I've included some samples, All the Dragon Mine songs worked, but the Polar Pass ones did not. The cwav files for Mario Maker also do not show in the song selector (like they are an excluded format?)
[Samples.zip](https://github.com/droidmjt/Droidsound/files/3357051/Samples.zip)
Thank you for taking time with this app!

**Comment by droidmjt** [comment]
if BWAV files don't show up in the file selector, then that means you have the wrong build, the BWAV was added to be visible in 172, besides, all the files in samples.zip works.

**Comment by hoodlum47** [comment]
The SND files from CTR now play correctly in build 172. Thank you!

**Comment by droidmjt** [comment]
good to hear

**Comment by droidmjt** [comment]
@froggestspirit BTW, that Samples.zip, how did you create it, in which OS? Droidsound-E cannot process it but when I repacked it in Windows with 7zip to ZIP again, then it worked.

**Comment by froggestspirit** [comment]
so rebooting my phone fixed CTR, but mario maker still has the same issue.
i got in the habit of unzipping the 7z soundtracks and re-zipping them as
zips

**Comment by droidmjt** [comment]
whats the issue with mario maker? bwav still don't show up?

**Comment by froggestspirit** [comment]
correct and choosing a txtp file causes the too many errors message

**Comment by droidmjt** [comment]
![itworks](https://user-images.githubusercontent.com/5917820/60680060-92fd5300-9e92-11e9-87f8-7b4e8430d61a.png)

**Comment by droidmjt** [comment]
did a fresh install to one of my old phones (build 172), I don't think I can help you further with this

**Comment by froggestspirit** [comment]
i got it to work, i rescanned the directory with version 172. sorry about
that

**Comment by droidmjt** [comment]
I know
