### ISSUE TITLE
Rescanning DB crashes Droidsound again

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#501]
when i rescan some 7z files (for Super Mario Maker 2) driodsound crashes, it happen on Starlink - Battle for Atlas (2018-10-16)(Ubisoft Toronto)(Ubisoft)[Switch].7z on http://switch.joshw.info/s/

**Comment by droidmjt** [comment]
send crashlog

**Comment by droidmjt** [comment]
actually, don't send the crashlog, the problem is the archive itself, repack it or unpack it, nothing can be done here, close this issue

**Comment by Sir-Sabin** [comment]
the archive is a repack and it's non-solid

**Comment by droidmjt** [comment]
the archive on the link you gave has solid archive, 7zip says its solid and i can manually check also if its solid

**Comment by droidmjt** [comment]
i created a repack of the archive and it worked, directly by using filesystem browser or by using DB browser and it worked fast.

**Comment by Sir-Sabin** [comment]
try this one i have made, https://mega.nz/#!e9kh2ApA!TfWmkFmrI-qLXjXOK5_HuF0etItQPyBvoSxG4WOPNwo and see if it crashes

**Comment by droidmjt** [comment]
reproduced and fixed the problem, fix will be available in build 172

**Comment by Sir-Sabin** [comment]
thanks for fixing it, closing now
