### ISSUE TITLE
Build HVSC Path Database is no longer working in Sidplay2fp Plugin

### ISSUE THREAD

**Issue by mbwum73** [droidmjt/Droidsound#502]
I can no longer use the option "Build HVSC Path Database"
When I choose the option in the Sidplay2fp plugin it says "downloading file" and this takes forever.
Because of that the HVSC stil is no longer visible when playing sids.
It used to work fine. Maybe the path of the stil file changed?

**Comment by droidmjt** [comment]
That's correct, the HTTP path changed, that's why it fails. The new path they use is this: http://www.prg.dtu.dk/HVSC/C64Music.old/DOCUMENTS/Songlengths.txt, they added the '.old'. I have a feeling this path will disappear in the future. I'll change it so that user has to download those 3 files and place them in correct folder. After all those files don't get updated more than 1-2 time per year.

**Comment by mbwum73** [comment]
Which 3 files are needed? Stil.txt, Songlenghts.txt? What's the third file?
And in which folder do I need to store them on my phone?

**Comment by droidmjt** [comment]
Songlengths.txt, STIL.txt,BUGlist.txt and you need to drop them to sdcard/droidsound/HVSC/DOCUMENTS/ but I'm not sure if it works, it could be that the download must finish successfully before it uses them :( 
This fix will be available in build 172, hopefully done today.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/oryaqyqpfb1772a/droidsounde167_172.apk?dl=1
try this, just drop the files to the folder I mentioned and click the build button

**Comment by mbwum73** [comment]
It Works. Thanks!

**Comment by 0ddb0d** [comment]
Songlengths.txt is deprecated, the server at http://www.prg.dtu.dk was frozen at update #70 because the old format is no longer supplied with HVSC updates. The announcement at https://hvsc.c64.org/download/C64Music/DOCUMENTS/Songlengths.faq explains the options available to developers.

**Comment by mbwum73** [comment]
Unfortunately the stil is no longer working since the last two beta's. I know songlenghts.txt is deprecated, but stil.txt is nice and I hope it can be shown again.

**Comment by droidmjt** [comment]
crap, I'll investigate the problem

**Comment by droidmjt** [comment]
ah ok, if you cannot wait until next binary update, download this file:
https://hvsc.c64.org/download/C64Music/DOCUMENTS/Songlengths.md5
and rename it to Songlengths.txt, then copy it to the path mentioned above and create the DB.

**Comment by droidmjt** [comment]
next version has automated downloader for these files

**Comment by mbwum73** [comment]
Great. Thanks. For now your workaround seems to work fine too.

**Comment by droidmjt** [comment]
I'll close this, once a new build is available, I'll comment here
