### ISSUE TITLE
Adding songs to playlist directly from browser listing causes incorrect metadata parsing

### ISSUE THREAD

**Issue by battaglia01** [droidmjt/Droidsound#504]
Fairly simple problem - suppose I am in the browser and I see some file I want to add to a playlist (like "Favorites"). I can bring up the menu and click "Add to 'Favorites'". If I do, the metadata is parsed incorrectly: the composer is listed as "Unknown" and the title of the file is just the filename (like "Castlevania.nsfe").

If I first play the song and then, from within the player, click the "+" icon, then it adds to the Favorites playlist correctly with the proper composer, name, etc.

This is mostly annoying when trying to add an entire game to Favorites - if you don't play each song individually and click "+", then the composer is listed as "Unknown" and the metadata isn't parsed.

You can see this even in just the "Examples" folder.

**Comment by battaglia01** [comment]
This is version  v1.67.715, btw.

**Comment by droidmjt** [comment]
This happens because you are trying to add items from filesystem browser to playlist, those items are non-processed, thats why the unknown field. Index them usin DB browser and your problem is solved.
