### ISSUE TITLE
Equalizer doesn't work with Droidsound-e

### ISSUE THREAD

**Issue by Andr20** [droidmjt/Droidsound#506]
I noticed with the new version, that the equalizer doesn't change the sound of the music played from droidsound-e, i tried all the equalizzer but they don't work, to be sure i tried with other players and with them it works, i use equalizer FX.

**Comment by droidmjt** [comment]
No idea, personally I use SoundAssistant and the equalizer it has works perfectly. Nothing I can do here.

**Comment by droidmjt** [comment]
Just for curiosity I installed Equalizer FX from PlayStore, worked just fine.

**Comment by Andr20** [comment]
i try to install droidsound-e again

**Comment by Andr20** [comment]
i tried, it doesnt work, till some version ago of droidsound it was working, i have the same problem on 3 other different smartphone and all the equalizer i tried i have the same problem, it happen only with droidsound-e

**Comment by droidmjt** [comment]
Tried now with custom ROM, didn't work. It works fine with all my phones using stock ROM.

**Comment by Andr20** [comment]
i am not using custom ROM

**Comment by droidmjt** [comment]
Droidsound-E doesn't know anything about external applications. The way how those external applications work, for example Equalizer FX is that they tap on audiosession 0 (global output mix) and use it send audio effects to other applications.
