### ISSUE TITLE
ModArchive.org database integration

### ISSUE THREAD

**Issue by awsms** [droidmjt/Droidsound#507]
Are you planning on the integration of modarchive ?
There are a ton of chiptunes only available there

I know the zxtune's dev ( https://bitbucket.org/zxtune/zxtune ) made it in his android application, it so it's possible (:

**Comment by droidmjt** [comment]
yeah, one day

**Comment by awsms** [comment]
> yeah, one day

any news on this?

**Comment by droidmjt** [comment]
no time for this at the moment
