### ISSUE TITLE
Droidsound-e Cannot Recognize CRI AWB or ACB

### ISSUE THREAD

**Issue by mistersiraj11** [droidmjt/Droidsound#509]
Hi, droidmjt. It's not an issue per se but more like want it to be implemented. The latest vgmstream can play AWB and ACB just fine. I was wondering if you can add that feature of possible. Thanks in advance!

**Comment by droidmjt** [comment]
yeah, I'll add it in next version

**Comment by mistersiraj11** [comment]
Cool! I'll wait for the new version.

**Comment by mistersiraj11** [comment]
I'll close this when link is posted.

**Comment by AdityaMH** [comment]
And replace "play endlessly order" icon to previous version.
Latest version  icon look same with "play one song order".
Make me confused..

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nx54tx003p12be3/droidsounde167_178.apk?dl=1
try if the formats work now, if not, provide links to files for test

**Comment by mistersiraj11** [comment]
They work. Thanks!
