### ISSUE TITLE
Problem with equinox snes

### ISSUE THREAD

**Issue by pantomm** [droidmjt/Droidsound#510]
Track like Deeso only play for 30 second instead 13 minutes.
I use v1.67.168

**Comment by droidmjt** [comment]
could you send me a link to the song so I can fix it?

**Comment by droidmjt** [comment]
nevermind, I foudn the file and reproduced the error, its silence detector what cuts the music, I'll fix it

**Comment by droidmjt** [comment]
nothing wrong with silence detector, the songlength is incorrect in the file, it is not supposed to be 12:58, nothing to fix here

**Comment by pantomm** [comment]
It works with app called Zxtune with silence detection set to none.
Maybe you can add silence detection option on droidsound.

**Comment by droidmjt** [comment]
I'll check it again, you shoud have mentioned the zxtune in the first place

**Comment by droidmjt** [comment]
when you play that file with zxtune, do you hear music after 33sec  ?

**Comment by droidmjt** [comment]
nevermind, there is no music, just silence, zxtune plays it until 12:58 because there is no silence detector

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/qmyzl6mu61o8rh7/droidsounde167_179.apk?dl=1
try this

**Comment by pantomm** [comment]
It's worked, thanks
