### ISSUE TITLE
Several DSE bugs

### ISSUE THREAD

**Issue by qwertysampletext** [droidmjt/Droidsound#513]
- changes made to "song-header" in the gui.css have no effect
- "!tags.m3u" (used by vgmstream) doesn't work
- filesystem browsers don't use the path specified when created (example: when creating an FSB, setting the path to "/sdcard/Download/" will use "/storage/emulated/0/Download" instead
- goto dir (from the context menu of playlist entries) doesn't work

**Comment by droidmjt** [comment]
- I will investigate the !tags.m3u effect, never heard about it before. 

- The filesystem browser effect is intentional.

- Tested the goto dir from playlist, I added a file from examples.zip/amiga to favourites and once I clicked the goto dir from the file's context menu, it went back to examples/amiga. Kindly tell me how to reproduce your problem.

- gui.css will be gone in very near future so won't fix anything there.

**Comment by qwertysampletext** [comment]
I just tried to use it normally. The file i used it on isn't in an archive, but i also tried using it on a file inside an archive and the results were the same. It just shows the browser tab and the path, but it doesn't show anything, as if there was no content on it (except that it doesn't even show the parent dir item). 

Also, why will gui.css be removed? Will it be replaced by another way to customize GUI colors, appearance, etc.?

**Comment by droidmjt** [comment]
The 'goto dir' feature, did it work before for you, has the behaviour changed?

Once the gui.css is gone there won't be replacement.

**Comment by qwertysampletext** [comment]
goto dir never worked for me. I've been using DSE since ver. 1.67.165, i think.

**Comment by droidmjt** [comment]
The goto dir is not suppose to do anything else except switch to browser tab and select the folder where  the file is located.

**Comment by qwertysampletext** [comment]
I know that's its purpose, but the browser tab just shows this: https://drive.google.com/file/d/13ZFJbcZpsoEdkUtOxjdFli7y8-tMKVvN/view?usp=drivesdk

**Comment by droidmjt** [comment]
I'll see if I can reproduce it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/51eazjqoxqu2uk8/droidsounde167_181.apk?dl=1
try if this works

**Comment by qwertysampletext** [comment]
It works.
