### ISSUE TITLE
some .txtp files don't play in droidsound-e

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#514]
some .txtp files don't play in droidsound-e, it just skips them

samples of txtp files: https://mega.nz/#!q1MAQKTb!81Zlhch-P3FylaVNiNhLgXF5f8rdTLl3GmPg7brkhQs

**Comment by AdityaMH** [comment]
It's not music file, .txtp format just plain text file..

**Comment by droidmjt** [comment]
do you have those txtp files extracted in the same folder where the music files are?

**Comment by droidmjt** [comment]
Either place those TXTP files in the same folder with the music files (unarchived) or put the music files inside the same archive with the TXTP files.

**Comment by droidmjt** [comment]
please post here one of those music files, it would help me in testing

**Comment by droidmjt** [comment]
it should work by clicking the TXTP file also, I can fix it but I need those music files

**Comment by droidmjt** [comment]
nevermind, I found the music files and fixed the problem, will upload new binary later today

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/vpbb7inuxd1f0mu/droidsounde167_182.apk?dl=1
should work now
