### ISSUE TITLE
Crashing on DB scan

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#515]
Hello, on the latest version of DSE (1.67.182), the app will start to scan music from my SD card, but into the 3rd zip file it crashes. This worked on my older phone, so it isnt the specific zip (deleting the 3rd zip made a different 3rd zip crash). is there a way i can find the crash log? rooted LG stylo 2 plus (64bit) with lineage os 15.1

**Comment by droidmjt** [comment]
See droidsound/crashlogs if there are any logs. If not, get adb.exe and run it like this: 'adb logcat'. It starts logging all the activities of your phone. Command 'abd logcat -c' cleans all the logs.

https://developer.android.com/studio/releases/platform-tools

Download the platforms tools to get the abd.exe.

**Comment by froggestspirit** [comment]
For some reason, windows really hates adb in my experiences, but I was able to pull this off of adb in linux: https://pastebin.com/g3D5714C
It crashed when scanning Kirby Air Ride (or when i removed kirby, the next one would be Super Mario Odyssey it crashed on). It looks like it crashes while enumerating, not sure if this helps?

**Comment by droidmjt** [comment]
I was able to reproduce the bug and its fixed now, a new binary will arrive soon.

**Comment by froggestspirit** [comment]
It seemed device specific to me, but im so glad you were able to find the
issue! thanks!!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/9kcwb7gcl8vk6m1/droidsounde167_183.apk?dl=1
try this

**Comment by froggestspirit** [comment]
this seems to have fixed it! thanks again!

**Comment by Level99OCR** [comment]
Grabbed 187 to see if it could fix my issue on my unrooted Android 8 LG V20. Battle Chess on 3DO in zip format keeps crashing the DB scanner. http://3do.joshw.info/b/Battle%20Chess%20(1993)(Krisalis)(Interplay)%5b3DO%5d.7z It also crashes on the same file even when it's extracted.

**Comment by droidmjt** [comment]
surprise, extension collision with another plugin, I'll fix it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/qt2g7bsrr4xtyed/droidsounde167_188.apk?dl=1
try this

**Comment by Level99OCR** [comment]
grabbed and testing the big scans now.

**Comment by Level99OCR** [comment]
So far so good, scanned 3DO, DS, arcade VGM, NES, SNES, GBA, FM Towns, PC Engine CD, N64, and Dreamcast without crashes. Will comment again if I find any outliers. Can be closed for now, thanks as always 😸

**Comment by droidmjt** [comment]
thats good
