### ISSUE TITLE
Add background image instead shader (enhacement)

### ISSUE THREAD

**Issue by AdityaMH** [droidmjt/Droidsound#516]
Can you add a image as a background? Instead of using shaders where many lay people don't know how to use it. And drain battery more faster too.

**Comment by droidmjt** [comment]
I can add a feature what takes an image from predefined folder and sets it as background image

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/21j6wrwwp8ad225/droidsounde167_184.apk?dl=1
try this

**Comment by droidmjt** [comment]
create folder named'backgrounds'  in droidsound folder and copy png files there. Only PNG files are supported for now.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/v8hcuikgknmy4av/droidsounde167_185.apk?dl=1
use that instead

**Comment by AdityaMH** [comment]
Ok, it's good. But this looks like a photo album rather than a background. Can you make a full screen background with white opacity in the player button and background added to all pages (Browser, Player, Search, Playlist). Like this..
![Playlist Page](https://i2.wp.com/www.apktops.ir/wp-content/uploads/2012/03/TTpod-2.jpg?zoom=2.625&w=680)

**Comment by droidmjt** [comment]
>> But this looks like a photo album rather than a background. 
You wanted background images to replace the shaders, you got it.
