### ISSUE TITLE
Request: add FlMML plugin

### ISSUE THREAD

**Issue by grj1234** [droidmjt/Droidsound#517]
I want to listen to FlMML songs with Droidsound-E.
Please consider making FlMML plugin.
The file extension of FlMML format is FML.
The Android version of FlMML is here:  https://github.com/trrk/FlMML-for-Android
The example of FML file is here: https://anonfile.com/X6r7C658n6

**Comment by droidmjt** [comment]
I don't think I'm going to add the support, the fileformat seems extremely rare.
