### ISSUE TITLE
NSF Plug internal mixing level is too high

### ISSUE THREAD

**Issue by LGA1150** [droidmjt/Droidsound#518]
Causing clippings internally.
GME works fine.

**Comment by droidmjt** [comment]
Too brief description, closing

**Comment by LGA1150** [comment]
Okay here are steps to reproduce the issue:
Download [this nsf](https://www.dropbox.com/s/4atvu2q377cw8eq/Supremacy.nsf?dl=1)
Play it with DSE, with default plugin (GME) it works fine.
But if I switch to NSFPlug (Settings - Plugins settings - NSF plugin - Format overrides - enable Override NSF) and play it, the music is _distorted_ at the beginning.

If I play this on my PC with @bbbradsmith's NSFPlay, which also uses NSFPlug, with Master volume in Device Mixer set too high, I get the same distorted sound. I figured out it's clipping internally.

So I think DSE's NSFPlug _Master volume_ is too high. But there are no options to adjust.

**Comment by droidmjt** [comment]
I'll check problem

**Comment by droidmjt** [comment]
Ok I listened the song with both plugins, in my opinion the sound is not distorted, both plugins sounds the same and both plugins have the crackling sound at the beginning. Nothing I can do here, changing internal volume levels have no effect.

**Comment by droidmjt** [comment]
best would be if the library authors check the supremacy.nsf

**Comment by LGA1150** [comment]
Version 185 works fine. Thanks.
