### ISSUE TITLE
Sound quality not good with most of audio formats

### ISSUE THREAD

**Issue by Martin365-0** [droidmjt/Droidsound#519]
I am new here, lately i noticed that most of audio format have the problem with the sound quality, is not so good comparing with other players, i noticed that for example there are Neon plugin, is it possible maybe to have the possibility to update some of the most plugin? like libmp3encoder.so and libffmpeg.so and not use the libffmpeg_neon.so, maybe the sound quality it becomes more clean after this update

**Comment by droidmjt** [comment]
how exactly I should update the plugins?

**Comment by Martin365-0** [comment]
changing the old plugin with the new one, if is not the plugins, i dont understand why on my S10 the sound is not good like in the other players, i prefer this player because is able to read many formats.
P.S. - i found that in the past there was some similar problem on the forum, there is some way to disable completely the sound options about volume and noise? maybe this option is ruining a bit the quality sound, maybe also if is on 0, this option is changing the quality

**Comment by Galindorf** [comment]
I had a similar problem, but nobody else was mentioning it so I thought 
maybe something was wrong with my speaker! It was worst on nes, SNES and 
gameboy tracks. The crackling was so bad on high notes I couldn't listen 
anymore!  I finally tried going into the settings menu of Droidsound-E and 
choosing "reset all settings." This seemed to remedy the situation but I'm 
not sure why. I don't recall messing with any sound settings but maybe I 
did at some point?  I've also updated to the very latest version. See if 
either of those two things helps you. :)

**Comment by droidmjt** [comment]
Did it happen with any NES/SNES/GB file ? I noticed that if I change the plugin volume to max and play from the speaker the sound starts crackling etc etc. Mostly I listen with headphones.

**Comment by Galindorf** [comment]
Yes but it was most noticeable on tracks with high pitch tones, like Final 
Fantasy Adventure (gba). It happened on the phone speaker, headphones, and 
my Megaboom, regardless of the volume. I did try messing with the plugin 
volume (to turn it down) to see if it helped... that's when I just reset 
everything. I wondered if something was wrong with my phone (it's a 
refurb)... but I'm not having the issue anymore as far as I can tell after 
a setting reset and upgrading
