### ISSUE TITLE
IMFs play back at wrong speed for Wolfenstein 3-D

### ISSUE THREAD

**Issue by BenMcLean** [droidmjt/Droidsound#521]
Wolfenstein 3-D plays back IMF notes at 700hz. Other games use other speeds. There needs to be a way to specify what speed to play the notes back at for IMF format.

**Comment by droidmjt** [comment]
The thing about the IMF files is that, if you wish to play at 700Hz, you need to use extension '.wlf' instead of '.imf.' Currently the '.wlf' extension is not supported but I will add it in next build.

**Comment by droidmjt** [comment]
Ignore my previous comment, the Adlib DB takes care of the rate. I'll investigate this more.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/b5f72txy0t7vnix/droidsounde167_186.apk?dl=1
try this

**Comment by BenMcLean** [comment]
Thanks!

Why do you use dropbox instead of making a release on Github?
