### ISSUE TITLE
TXTP's not working

### ISSUE THREAD

**Issue by sephirothkefka** [droidmjt/Droidsound#522]
I'm having some trouble with some TXTP's that happen to use the #C prefix in them to mute the rest of the channels (for example a TXTP that contains music.wav#C1,2 that only plays the first 2 channels of the quad channel file) yet looping TXTP's work perfectly fine. In VGMStream the current output is set to 8 channels. Do I have to adjust something for this or is it currently broken?

**Comment by droidmjt** [comment]
please provide necessary files so I can try to reproduce the problem

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/b5f72txy0t7vnix/droidsounde167_186.apk?dl=1
try this
