### ISSUE TITLE
167_188 issue with entering and exiting DB Browser folder

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#523]
When I go two folders deep into a DB Browser folder, then come back out to the main listing, most of the time it will be entirely blank outside of the Network folder. If I enter the Network folder then back out again, or restart the app, my folders appear again. Tested with 167_188.

**Comment by droidmjt** [comment]
cannot reproduce, provide detailed instructions how to reproduce this problem, folder names etc etc

**Comment by droidmjt** [comment]
since you are using DB browser, also let me know the path where you keep your archives

**Comment by Level99OCR** [comment]
LG V20 on Android 8.0. Files are on SD card under individual folders, either in a main Music folder on the sd card, or in subfolders under VGM. I just did a clean install (uninstall, renamed droidsound to droidsound-bak to keep my old install as a fallback). 

Installed 167_188. Add DB Browser, storage, [numerical sd card identifier], VGM, Nintendo 64, Select Folder. Named N64. Now I go into N64, click on a subfolder, then back out two levels. The only thing that shows up is Network and Examples.zip.
![Screenshot_2019-10-15-10-02-04](https://user-images.githubusercontent.com/6171738/66838615-f8052200-ef32-11e9-80d0-17aa2fff655b.png) this is right after adding or cold app start.

![Screenshot_2019-10-15-10-02-09](https://user-images.githubusercontent.com/6171738/66838647-06533e00-ef33-11e9-8415-fd48cbc8956d.png) this is after the bug is encountered.

**Comment by droidmjt** [comment]
Thanks for the instructions. I suspect the external SD card might be the problem, we'll see.

**Comment by droidmjt** [comment]
reproduced the problem, i'll fix it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/fdax207rsh0em6k/droidsounde167_189.apk?dl=1
try this

**Comment by droidmjt** [comment]
found another bug, don't use that build

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/zhecwkm1etaw7hx/droidsounde167_190.apk?dl=1
try this

**Comment by Level99OCR** [comment]
Just got to checking it and yes, this seems to have resolved the issue. Thanks again, I'll be sure to give the build a full vetting.
