### ISSUE TITLE
NSFPlug plays N163 sound too loud

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#524]
Use NSFPlug play any N163 sound is too loud.

**Comment by droidmjt** [comment]
would you be able to post couple of N163 songs here?

**Comment by droidmjt** [comment]
i'll start working on this once you give more details about the problem

**Comment by Yave-Yu** [comment]
Here is some N163 songs:
http://www.mediafire.com/file/9ha4ov5xddyy6ff/N163Songs.zip

**Comment by droidmjt** [comment]
Thanks for the files, unfortunately there is no point in adjusting the N163 volume, because that would affect the other N163 songs where the loudness is not a problem.
