### ISSUE TITLE
Using visualizer disables any audio effects app

### ISSUE THREAD

**Issue by qwertysampletext** [droidmjt/Droidsound#525]
When I enable the visualizer, any audio effects app is disabled until next reboot.

**Comment by droidmjt** [comment]
what audio effects app you are using?

**Comment by droidmjt** [comment]
for how long time you've been using these audio effects apps?

**Comment by qwertysampletext** [comment]
ViPER4Android FX, started using it at around version 1 67 70.

**Comment by droidmjt** [comment]
when did this problem appear for the first time?

**Comment by droidmjt** [comment]
I'm afraid I won't be able to fix this. I couldn't get it to work. I tried other equalizer applications and had no problems with them. I'm curious why Viper4Android FX requires root access.
