### ISSUE TITLE
Unable to read inside zip files.

### ISSUE THREAD

**Issue by miker84** [droidmjt/Droidsound#526]
I have a folder that contains different game music files in zip files and v1.67.190 seems to be unable to look inside for the files.  Has this ability been removed?  I updated from an old version, around 1.67.160(ish) where it worked.

**Comment by miker84** [comment]
1.67.188 can read and play from inside zip files.

**Comment by droidmjt** [comment]
please send me a zip file what is unable to read with build 190, I did some changes related to ZIP reading

**Comment by droidmjt** [comment]
I was able to reproduce the problem already, I'll fix it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nqr3t2haqthpo3b/droidsounde167_191.apk?dl=1
try this

**Comment by miker84** [comment]
It works.  Thanks for fixing this even at 1am (for me at least)

**Comment by droidmjt** [comment]
great, I'll close this issue
