### ISSUE TITLE
PMD: Incorrect Sample Bank loading, Incomplete Memo data

### ISSUE THREAD

**Issue by OPNA2608** [droidmjt/Droidsound#527]
The PMD module appears to load the wrong (always first?) PPS bank file inside a directory. Additionally, the Memo data is displayed weirdly.

(v1.67.191 here)

---

I don't know how low-level your parsing of the .M(2) file format is / how the library you use for parsing it works, but let me explain:

The PMD driver can load sample banks on .M file load. The end of the file has a table with pointers to various strings of extra data and file names of banks to load. To get to the start of the Extra Data pointer table, asap:

- Read short from 0x19, Subtract 3 from the result, Goto that file offset.
- Read short, Add 1 to result, Goto there, you're at the pointer table now.

Assuming it's a v4.7/v4.8 file. Other versions might function differently, I didn't dive into them yet. To identify a v4.8 file:

- version byte at start of file = 0x00
- read short at 0x19, subtract 1. byte at that adress = 0x48

The exact order of strings the table points to depends on the extra data format version, but the common order (v4.8) has the first 3 pointers (offset +1b) to:

- PPZ bank name
- PPS bank name
- PPC/P86 bank name

If you use a nice library for parsing/playing, this might already be parsed. In any case, it would be appreciated if you could fix the PPS loading to:

- Load the bank the file specifies by default.
- Maybe have an option to manually specify a PPS bank to load, in case the .M file fails to specify the proper bank. (as some games manually load a bank on startup and just leave it loaded for all following .M files to use)

If you need example files for testing:

- [Totsugeki! Mix](http://hoot.joshw.info/pc98/tmix98.zip): CLEAR.M loads CLEAR.PPS, but the file specifies PPS02.PPS (0x03CD)
- [Rusty](http://hoot.joshw.info/pc98/rusty98.zip): ALLMAP.M2 loads, again, CLEAR.PPS, but the file specifies none.* It actually needs DRUMS.PPS loaded, but the game handles the bank loading manually afaict.

*Format version is v4.3, I don't think I've found a consistent way of finding the bank metadata there yet.

---

On another note, the parsed Memo data gets displayed weirdly: All but the second line get dropped, and said line gets displayed under "Copyright". Maybe you could pretty that up?

![Screenshot_2019-11-16-22-55-37](https://user-images.githubusercontent.com/23431373/69007194-edc3b280-093a-11ea-9a17-293bcd2157a7.png)

![20191117_130914](https://user-images.githubusercontent.com/23431373/69007230-89552300-093b-11ea-8230-07c632f26f8e.jpg)

Thank you for the trouble, I hope my explaination was helpful. Documentation of the binary part of the format seems pretty bad, let me know if you have any questions and I'll share with you as much as I know  :slightly_smiling_face:

**Comment by droidmjt** [comment]
>> CLEAR.M loads CLEAR.PPS, but the file specifies PPS02.PPS (0x03CD)

since PPS02.PPS cannot be found, should it just play without it?

**Comment by OPNA2608** [comment]
Must've picked a bad example for this, but I'll say yes. FMPMD2000 would refuse to play it because PPS02.PPS is missing, but the official DOS toolkit for PMD just prints a warning and plays it regardless.

**Comment by droidmjt** [comment]
would it be possible for you to send me the th03_09.m file?

**Comment by OPNA2608** [comment]
Here's the whole pack it's from. It doesn't work with the playing-from-zip functionality of DroidSound-E because it's one directory too deep, apologies.

https://dl.dropboxusercontent.com/s/3cctw52mj84iuky/TH3_-_PoDD_English.zip

**Comment by droidmjt** [comment]
thanks,I'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bwoyz5flowhc3d9/droidsounde167_192.apk?dl=1
try this, at least the memo data should be ok, not sure about the rest

**Comment by droidmjt** [comment]
about the zip file you sent and why it doesn't work, its because it doesn't use relative paths

**Comment by OPNA2608** [comment]
Memo data seems spread over several fields (in brackets after Title, in Copyright, concatenated to one string in Comment). Can you change that to just abunch of lines in the Comment field? There's no obligation for the composer to stick to any rules when it comes to Memo lines, so trying to parse out a Copyright field doesn't make sense. They should also all just be separated by newlines.

For reference, a source file might look something like this:
```
#Title    My Cool Cover
#Composer Someone else
#Arranger Me :)
#Memo     This is my cool little tune.            ^v^)
#Memo     I hope you like it! I worked hard on it ^o^)
#Memo     Let me know what you thought about it!

; ADPCM sample bank
#PPCFile SAMPLES.PPC
; Also using PPS bank! :o
#PPSFile SAMPLES.PPS
```
Ideally, it would be nice to have it parsed out the same way again :slightly_smiling_face: 

Also, we recently figured out that those metadata fields can contain ANSI escapes for text colouring etc. DS-E seems to ignore those, not sure if that's something you want to enable or not.

![](https://cdn.discordapp.com/attachments/535253084104949760/647516277228961814/20191122_201810.jpg)

---

I think there is a problem with loading PPS and PPC files still, specifically with older versions of the format?

I tested Totsugeki! Mix after fixing the `#PPSFile` reference (v4.7) and a custom file (v4.8) and they load and play file.

I tried the Hoot archive's Trouble Outsiders pack (broken) and it didn't load the bank (good). Tried my fixed version and it did load it. :+1: 
At first it didn't, but I figured out that having the "Override PPC with P86" setting disabled also disables autoloading any properly referenced P86 files. Maybe you could adjust that to not interfere with files that manually want to load a P86 bank?

When I tested a v4.5 module where I fixed the missing `#PPCFile` reference (to a P86 one), it didn't load the bank. Instead, it used the previously loaded P86 bank from Trouble Outsiders (correct behaviour I think), _but applied the samples as if they were PPS ones (definitely wrong)._ Can you take another look at this?

[I've attached a zip to reproduce this.](https://github.com/droidmjt/Droidsound/files/3915999/DSE_bugRepro_P86asPPS.zip) Start from a fresh DS-E launch (with P86 override enabled), play `OS_08.M2` (samples should load), then `SMOON_fixed.M` (misuses the previous samples as RSS extensions (what PPS are for)).

Also, after playing various PMD modules I got DS-E to suddenly crash a second after starting to play another PMD module, but I haven't been able to reproduce it at all yet.

---

Maybe you're interpreting the <v4.8 data wrong? For v4.8 files the extra data table starts with pointers (add +1 to all) to
- PVI/PZI filename
- PPS filename
- PPC filename
- Title
- …

Before v4.8, the table started like this
- PPS filename
- PPC filename
- Title
- …

You can identify v4.5 to v4.8 (and I think v4.3) as described in the initial message, the extra data version byte would then be e.g. `0x45` for a v4.5 file. For other versions it might work differently, those are the only versions I've seen and tried to understand yet. Apologies.

**Comment by droidmjt** [comment]
>> I've attached a zip to reproduce this. Start from a fresh DS-E launch (with P86 override enabled), play OS_08.M2 (samples should load), then SMOON_fixed.M (misuses the previous samples as RSS extensions (what PPS are for)).

This has been fixed now. I'm curious about the SMOON_fixed.M file, could you send me the original set where the non-fixed file belongs to? 

About the version 4.5, the instruction above how to find the table where all the metadata is (including the pcm filenames) fails. Would it work if you just go to the end of the file and start going backwards as long as you encounter null, then you have offsets to all the metadata fields?

**Comment by OPNA2608** [comment]
> I'm curious about the SMOON_fixed.M file, could you send me the original set where the non-fixed file belongs to?

It's from the second PMD Ryokusui Disk, they're hard to come by. [Here you go.](https://cdn.discordapp.com/attachments/535250375981137930/646611500861095946/RST.7z)

> About the version 4.5, the instruction above how to find the table where all the metadata is (including the pcm filenames) fails.

Ah, I'm sorry! It seems I forgot to patch the pointer to the extra data table in a hurry, `0x1024` should be `0xEE` instead of `0xE4`! It's possible that messed something up with the bank loading too. :slightly_frowning_face: 

If that's the problem you had with the instructions, please try again after patching the file. If it's another file that gave you problems with parsing though, let me know which one it is. I'm mostly focusing on v4.8 right now as it's the one i can still find the compiler and documentation for, but maybe there are different formats and structures in older versions I don't know about yet!

> Would it work if you just go to the end of the file and start going backwards as long as you encounter null, then you have offsets to all the metadata fields?

I don't think this will work reliably. I have seen rips that contain abit of junk data appended to the modules which does not interfere with proper parsing, but would break your walking-backwards approach. Some of them aren't too unpopular either.

![grafik](https://user-images.githubusercontent.com/23431373/70122483-01785400-1671-11ea-8537-d2d1fb4a00e2.png)

**Comment by droidmjt** [comment]
The 0xe4 -> 0xee fixed the problem, ignore my idea about the offsets.

https://www.dropbox.com/s/1awjcarawojii9i/droidsounde167_193.apk?dl=1
try this build, hopefully ok now.

**Comment by OPNA2608** [comment]
We're getting there, looks alot better! :smile: 

The Memo data is still displayed incompletely, it seems to show only the first 4 lines. There can be up to 128 lines [according to the manual](https://pigu-a.github.io/pmddocs/pmdmml.htm#2-9), [Love Escalator](http://hoot.joshw.info/pc98/love_e_98.zip)'s `BGM_22.M86` for example has 7.

I also noticed that .M26 and .M86 extensions are treated as not playable (don't show up in the player), could you add them as PMD ones? They're used very infrequently, but aren't completely unheard of (Hoot archive's rips of Love Escalator and one of the Touhou games). Another file extension that gets used sometimes seems to be .MMM (S*x 2, Sorcer Kingdom), although I haven't actually checked if you already support it.

Lastly, DS-E likes to crash if there are any problems with playing back a PMD-associated module. Ideally they should all be well-formed, but sometimes packs still have some compressed modules that won't play and halt the player entirely, especially annoying when they happen in the middle of a pack.
I don't know if it's feasible and it's really not in the scope of the original bug report, but maybe you could wrap an error handler around the whole thing to gracefully stop playback instead?

Either way, cheers. :slightly_smiling_face:

**Comment by droidmjt** [comment]
>> Lastly, DS-E likes to crash if there are any problems with playing back a PMD-associated module

How to reproduce this?

**Comment by OPNA2608** [comment]
> How to reproduce this?

The Rusty pack from earlier for example is faulty, all the `ENDING<n>.M(2)` songs are still LZ77-compressed and thus invalid. Also, all tracks from YU-NO (different driver, same extension) and the `_GS` marked tracks from GaoGao! 4th Canaan (maybe MMD data? iunno) should all be invalid. FMPMD2000 on Windows can catch those and gracefully stops playback.
(Actually, I think the PMDWin library has checks to determine if the requested file/data is valid PMD data? It's too complex for me to understand though.)
As an example, playing ENDING2.M2 from Rusty will skip to EYECATCH.M, but playing ENDING2.M (would presumably skip to ENDING2.M2 and) crashes the player.

On the topic of crashes,

> Also, after playing various PMD modules I got DS-E to suddenly crash a second after starting to play another PMD module, but I haven't been able to reproduce it at all yet.

I _was_ able to reproduce this 2 more times just now by clicking and skipping through the start of the RST4 directory from earlier, but with no consistent way of inducing it, sorry. Maybe this alone helps you with reproducing it already?

> EDIT: fixed the other stuff

Can you also consider the PPC/P86 option improvement and manual bank file selection if it's not too much to ask? Those would be very welcomed additions to ease with playing rips/songs with only a P86 bank / unfixed rips that expect a preloaded environment.

**Comment by droidmjt** [comment]
>> Can you also consider the PPC/P86 option improvement ....

what kind of improvement?

**Comment by droidmjt** [comment]
currently it works so that, first it tries to load what ever it finds from the end of the file, if it fails, it uses a built-in hootdb to search for possible pps/ppc/p86 files

**Comment by OPNA2608** [comment]
> what kind of improvement?

> I tried the Hoot archive's Trouble Outsiders pack (broken) and it didn't load the bank (good). Tried my fixed version and it did load it. +1
At first it didn't, but I figured out that having the "Override PPC with P86" setting disabled also disables autoloading any properly referenced P86 files. Maybe you could adjust that to not interfere with files that manually want to load a P86 bank?

> currently it works so that, first it tries to load what ever it finds from the end of the file, if it fails, it uses a built-in hootdb to search for possible pps/ppc/p86 files

Is that already in the v193 apk? When I try loading `SMOON_fixed.M` there with the Override PPC with P86 option disabled, it won't load the .P86 bank it (correctly) links to. Same with my fixed Trouble Outsiders back.

**Comment by droidmjt** [comment]
There was a bug in 193, check the binary below, all should be fixed now.
https://www.dropbox.com/s/d8m9clqfn8w71qr/droidsounde167_194.apk?dl=1

**Comment by droidmjt** [comment]
are there any problems? if not, close this issue

**Comment by OPNA2608** [comment]
I don't think there are any left right now, thanks alot!
