### ISSUE TITLE
Unable to play .dsp files

### ISSUE THREAD

**Issue by Trogdorbad** [droidmjt/Droidsound#528]
DSE seems to still be unable to read the .dsp files from Pokemon XD, though I'm not gonna act like I know the first thing about coding so I don't know how easy a fix that is. I do know someone made a build of Audacity that can import/export .dsp files so it's definitely a thing, though if it's not an easy fix I'll figure something out, make brstms or something

**Comment by droidmjt** [comment]
VGMStream is not able to play these files, I assume you are talking about the .dsp files with what comes with files using .001 extension.

**Comment by droidmjt** [comment]
and as long as VGMStream cannot play these, there is nothing I can do.

**Comment by Trogdorbad** [comment]
My B, I forgot about that part

**Comment by droidmjt** [comment]
If you rename those files extensions like this:

.dsp -> .ish
.001 -> .isd

Then they work.

**Comment by Trogdorbad** [comment]
Oh, thanks for telling me this, you're a lifesaver
