### ISSUE TITLE
Crash on db scan

### ISSUE THREAD

**Issue by Solo187** [droidmjt/Droidsound#530]
I'm getting a crash whilst scanning Amiga games. So far it's crashing on Diabolik - Fatal Deceit (1993)(Gian Luca Gaiba)(Simulmondo) & if i remove that it will crash on Time Runners - The Killer Shadow (1994)(Gian Luca Gaiba)(Simumondo,Fabbri). These are folders containing mods. I have the Amiga parent folder containing game folders which hold the music in various amiga formats.

Edit: Possibly found offending files. My Amiga music is stored in the amiga naming format e.g filetype first. So mod.filename. I think the offending files are mod.st1. Each of the folders it fails on contain files name mod.st1 mod.st2 mod.st3 mod.st4

Edit: Ok so it's definitely the reversed filetype layout. So, Mod.Volley.d will crash the scan. Anything with a letter or number at the end

**Comment by droidmjt** [comment]
thanks for checking this more, mod.volley.d has valid extension at both ends, I'll see if I can get this fixed.

**Comment by droidmjt** [comment]
would it be possible for you to rename those files from Mod.Volley.d -> Volley.d.Mod ?

**Comment by Solo187** [comment]
Yes. Infact i already renamed them all as a work around. There we're quite a few offending files so i had to just rename, rescan, rename. It's how they come from the amiga exotica site. & How the actual amiga stores it's files. Just thought I'd let you know these things we're crashing your app

**Comment by droidmjt** [comment]
There is also another thing, for example, Mod.Volley.d, if you take the extension '.d' away, the mod will be played using UADE while there is a better alternative, openmpt. I'm not sure what would be the optimal solution here. Amiga filenames are usually in format 'ext.filename' and many plugins use extension to identify the format, the rootcause here was the ZXPlugin using extension '.d' and ZXPlugin has priority over UADE. 

If you can live with the renamed files, that would be nice. Otherwise it may take awhile to overcome this problem.

**Comment by Solo187** [comment]
Yes thats totally fine. Ive renamed them now & its all working fine. Just incase you do get around to fixing it though, i've uploaded the set i scanned so you can have a proper look at the file names crashing it. There are others besides the .d extension. Just try scanning in the folders i've sent you & wait for the crashes. I think what it is is, Whoever ripped the music in the first place on the real amiga probably just ripped it all as is with the file names kept intact. Which would obviously cause no problems on a real amiga.

https://drive.google.com/open?id=1INZOds2vklhfGbca1gnn_hIzO_n-WsLB

**Comment by droidmjt** [comment]
thanks for the set, I'll check it once I start working on this issue, I'll close this issue for now and reopen when the fix is available
