### ISSUE TITLE
GUI freeze if I enable visualizer, then rotate screen and switch tracks

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#531]
- Enable GUI visualizer. This bug will not happen otherwise.
- In portrait mode, start music playback so visualizer appears.
- Alternate between:
    - Rotate screen to landscape and portrait and back.
    - Switch to the next song in landscape or portrait.

Pretty soon the app will freeze, though the music will keep playing. Android will pop up an ANR dialog.

(Also, I noticed that all visualizer settings require an app restart, but only some are marked as needing a restart.)

droidsounde167_194.apk, Android 8.1, Moto G5 Plus.

**Comment by droidmjt** [comment]
all right, I'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7lk28a1xrdvvwy8/droidsounde167_195.apk?dl=1
try this

**Comment by jimbo1qaz** [comment]
Seems fixed. Thanks!

**Comment by droidmjt** [comment]
good good
