### ISSUE TITLE
VBA-M plugin for GSF?

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#532]
mGBA plays square wave sounds a bit crack especially on Mega Man Battle Network series, so I want VBA-M, could you add it for an option of play GSF?
https://foobar2000.xrea.jp/up/files/up1284.7z

**Comment by droidmjt** [comment]
Mega Man Battle Network series, which one? please give exact filename

**Comment by droidmjt** [comment]
Could you tell how to reproduce the problem? Does it happen with any MMBN series song?

**Comment by Yave-Yu** [comment]
1: 08 Fire Field, 13 Red or Blue, 16 Operation!
2: 01 Title Screen
4: 04 Elec Town, 08 Foreign Country
I personally think these are more obvious on square wave between mGBA and VBA-M, the former plays more wild, the latter plays more mild.

**Comment by droidmjt** [comment]
I listened those songs, I thougth there is some cracking sound in those songs as you stated in your first message but I couldn't hear any.

**Comment by droidmjt** [comment]
I wouldn't like to add another library for the sake of few songs, secondly, the source code seems to have an external dependency  (viogsf.bin, PE executable, windows-only stuff)

**Comment by Yave-Yu** [comment]
OK, mGBA is not bad either.

**Comment by Yave-Yu** [comment]
I wonder which version of mGBA (library) you used?

**Comment by droidmjt** [comment]
I have updated mGBA now to the latest, will be available in next binary
