### ISSUE TITLE
A minor issue about NSF's start songno

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#533]
NSFPlug supports any start songno to play, like this NSF:
http://www.mediafire.com/file/juwmwhbrdq2waha/Mega_Man_3_TBoG.nsf
When you open it, play songno 2 directly instead of 1.
NSFPlug in Droidsound-E supports this too, but Droidsound-E still displays 01.
So can you fix it? or just disable NSFPlug's any start songno feature like GME.

**Comment by droidmjt** [comment]
if the library is able to identify the start song number, I can fix it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bvuubzhkarywvti/droidsounde167_196.apk?dl=1
try this

**Comment by Yave-Yu** [comment]
It fixed! Thank you!
