### ISSUE TITLE
Droidsound crashes in background

### ISSUE THREAD

**Issue by miker84** [droidmjt/Droidsound#534]
I've tried different file types and all encountered the same thing.  Upon putting the app in the background, the app crashes after 1 minute.  When the music stops, opening the app from either the icon or from the recents menu both results in the app launching fresh (as if it was never running).  Currently running 1.67.196 on Samsung Galaxy Note 8

**Comment by droidmjt** [comment]
could you tell me which filetypes you tried? crashlog would be welcome also

**Comment by droidmjt** [comment]
try without external apps, let it play from speaker for 1minute and see what happens

**Comment by miker84** [comment]
I played with psf2, psf3, dsp, smc, bcstm.  What is an external app?  Not sure how to get the crash log.  Would that be to have it attached to Android Studio?

**Comment by droidmjt** [comment]
External app like Equalizer etc etc. After crashing, does it produce a log file in sdcard/droidsound/crashlogs?

**Comment by droidmjt** [comment]
what android version you have? stock or custom ROM?

**Comment by droidmjt** [comment]
if its sharp 1minute every time, it sounds like an external application or some OS battery related optimization is killing the background player service

**Comment by miker84** [comment]
I'm running Android 9 Stock.  And yeah, there is a log.  Also, I'm not using any external app.  I can start a song, not exit to home screen and press the sleep button, and it will still stop after a minute.  Let me get the log off and attach.
[droidsounde_crash_20200105_054237.log](https://github.com/droidmjt/Droidsound/files/4023446/droidsounde_crash_20200105_054237.log)

Did that work?  Tried to upload from mobile.

**Comment by droidmjt** [comment]
yeah I got the log, thanks. What is sleep button?

**Comment by miker84** [comment]
Checked the sleeping apps settings, seems it was set to sleep automatically.  Disabled it.  Cleared up the issue.  But why would it be flagged and set to sleep by the system automatically?  I didn't have to set it to not monitor it before.

**Comment by miker84** [comment]
The screen off button is what I meant.

**Comment by droidmjt** [comment]
>>But why would it be flagged and set to sleep by the system automatically?

difficult to say, maybe OS update it made it like that. Anyway, good thing it works now,please close this issue.

**Comment by miker84** [comment]
Okay, thanks for your guidance.
