### ISSUE TITLE
SMB network folder

### ISSUE THREAD

**Issue by keenanweaver** [droidmjt/Droidsound#535]
Having a bit of an issue connecting Droidsound to a Samba share. I'm using the server OS Unraid v6.8.0 to create the share. Following your instructions in #201 & #207, the connection just hangs trying to establish. Nothing in the error log, just a "...working..." status. I've created a user ("phone", password the same) and set the appropriate permissions. When setting the network link, I point the path to "smb://phone:phone@192.168.1.37/Media/Audio/Music/".

In my troubleshooting, I've attempted the following, but none resolved the issue:

- Set share to fully public
- Used guest syntax in SMB URI
- Explicitly defined port 445 in SMB URI
- Tried root share only in SMB URI
- Used server hostname instead of IP

The share itself works as expected. I used the Android app Solid Explorer to verify I can make connection with the created user, it's just I can't establish that connection in Droidsound. The only thing I can think of is I'm disabling SMBv1 support in Unraid for security reasons. Any advice or ideas would be greatly appreciated. I'm using Droidsound-E v1.67.196 on Android 9. Thank you for reading and for the wonderful work you've done on Droidsound!

**Comment by droidmjt** [comment]
I tried with Windows SMB sharing and worked perfectly. I guess its SMBv1. Your configuration is correct.

**Comment by droidmjt** [comment]
so when you added the network item in droidsound-e, in the network link window you had these:
* /sdcard/droidsound/dsroot/Network
* smb://phone:phone@192.168.1.37/Media/Audio/Music/
* randomname

correct?

**Comment by keenanweaver** [comment]
Correct.

**Comment by droidmjt** [comment]
found the problem, the SMB client im using doesn't support SMBv2/v3. I'll see if I can get that updated.

**Comment by droidmjt** [comment]
it worked because I had SMBv1 enabled and I just checked with powershell if SMBv2 is enabled :(

**Comment by droidmjt** [comment]
close this issue, I'll reopen it when I have a library what supprots SMBv2/v3.

**Comment by keenanweaver** [comment]
Okay, great. Thank you!
