### ISSUE TITLE
PMD: EVE Burst Error PPZ8 Pack Issues

### ISSUE THREAD

**Issue by melipog** [droidmjt/Droidsound#536]
Since updating to the December builds I've noticed that the EVE Burst Error PPZ8 hoot pack (Download: http://hoot.joshw.info/pc98/eveppz8_98.zip) behaves very strangely on them.
I've noticed crashes while selecting tracks and a weird issue where upon selecting a track, the track after it will be played instead. For example, if I pick EVE_01.M, there's a chance EVE_02.M will be played instead.
I suspect the issue is related to changes made to fix issue #527 since builds made before that were fine.

**Comment by droidmjt** [comment]
i'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xtxc3l9o8cm5w9d/droidsounde167_197.apk?dl=1
try this

**Comment by melipog** [comment]
Thanks, I can select tracks properly now and there are fewer crashes.
However, I still get crashes when I try to change between tracks sometimes, and this happens in other PMD sets too, not just EVE's.
In fact, if I keep switching between tracks I'm bound to get a crash within a minute or two.

**Comment by droidmjt** [comment]
how quickly you switch between tracks? could you also send crashlog from /droidsound/crashlogs

**Comment by melipog** [comment]
Once every two seconds.
Here's a crashlog:
[droidsounde_crash_20200111_025042.log](https://github.com/droidmjt/Droidsound/files/4048787/droidsounde_crash_20200111_025042.log)
I wish I could send more but a lot of these crashes don't create crashlogs for some reason.

**Comment by droidmjt** [comment]
I tried to switch tracks as fast as possible, no crashes, what kind of device you have, android version and phone model ?

**Comment by droidmjt** [comment]
learn how to capture logs with adb from android sdk and send me a proper log please

**Comment by melipog** [comment]
Is this OK?
[droidsoundlog.txt](https://github.com/droidmjt/Droidsound/files/4056992/droidsoundlog.txt)
I have a Xiaomi Mi Mix 2 with LineageOS 16 (Android 9)

**Comment by droidmjt** [comment]
thats good, unfortunately its impossible to say why it crashes.
>> LineageOS Version: '16.0-20200111-NIGHTLY-chiron'

have you tried the same with stock ROM?

**Comment by melipog** [comment]
I'll try to reflash the stock rom at some point and see if it makes a difference.
