### ISSUE TITLE
AT9 files cause instant crashes on playback in version 1.67.197

### ISSUE THREAD

**Issue by melipog** [droidmjt/Droidsound#537]
Hello again.
Like the title says at9 (ATRAC 9) tracks make the app crash instantly if you attempt to play them.
Unfortunately, I can't send any crashlogs because the app hasn't generated any for these crashes so far.
The good news is that these crashes only happen on the latest build (197) and none of the previous ones, so hopefully that'll make it easier to track the issue down.
You can find at9 music here: [vita.joshw.info](vita.joshw.info) 
Thanks for reading and keep up the good work!

**Comment by droidmjt** [comment]
this must be vgmstream related, I'll check it
