### ISSUE TITLE
Vgmstream wont play .hlwav files on latest version

### ISSUE THREAD

**Issue by TheRektafire** [droidmjt/Droidsound#539]
Sorry for the duplicate issue, I was typing on my phone and hit the enter button on accident when i meant to press . >:( Anyway in the latest version of droidsound vgmstream wont play .hlwav files despite that format apparently being supported, I tested with the HL2 ost rip from zophar domain

**Comment by droidmjt** [comment]
I'll fix it

**Comment by droidmjt** [comment]
Could you give me a direct link to those hlwav files

**Comment by droidmjt** [comment]
I tried to play hlwav files from zophar, they didn't play

**Comment by droidmjt** [comment]
leave a msg

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/uyfjhklzq5zjxrj/droidsounde167_199.apk?dl=1
you need to rename files using .hlwav extension to .lwav extension
