### ISSUE TITLE
MLRPG keeps silent

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#540]
Play Mario and Luigi: Superstar Saga's minigsf, nothing output, version 1.6.7.198.

**Comment by droidmjt** [comment]
I just tried with the same build, Mario & Luigi - Superstar Saga [Mario & Luigi RPG] (2003-11-17)(AlphaDream)(Nintendo)[GBA], worked fine

**Comment by Yave-Yu** [comment]
Where are you find it? I found it in zophar's domain, and extract to sdcard, but when I try to play it, it keeps silent. Other minigsf are works fine.

**Comment by droidmjt** [comment]
gsh.joshw.info

**Comment by droidmjt** [comment]
I think the problem is gsflib file using incorrect filename

**Comment by Yave-Yu** [comment]
Problem solved, thank you for sharing this another gsf site.
