### ISSUE TITLE
S98 plugin produces distorted sound

### ISSUE THREAD

**Issue by melipog** [droidmjt/Droidsound#541]
As the title says the s98 plugin makes distorted sound when playing back certain songs.
Here's an example, recorded from Droidsound: https://files.catbox.moe/hhzjt0.ogg
(This is yuno043.s98 from the [YU-NO S98 set](http://s98.joshw.info/k/Konoyo%20no%20Hate%20de%20Koi%20wo%20Utau%20Shoujo%20-%20Yu-No%20(PC-98)(1996)(elf).7z))
And this is how it should sound like (took this from the official soundtrack from the game): https://files.catbox.moe/drxgb8.ogg

I think I have a clue as to why this is happening:
![image](https://user-images.githubusercontent.com/52966576/73533441-855b7c00-4427-11ea-92fc-4fd45a55ef5b.png)
The replay rate here is listed as "48000Hz", but the PC-98 sound chip(s) produce sound at a rate of 55466Hz/55467Hz (or 55466.6666666, to be exact) so it should probably be 55466Hz or 55467Hz instead.
To confirm this is the case, I used Hoot, a retro music player that allows you to change the internal sampling rate.
I played back this song at a sampling rate of 48000Hz and the sound is pretty much identical to Droidsound's: https://files.catbox.moe/v2fnhd.ogg
I also played it back at the correct rate, 55466Hz: https://files.catbox.moe/1gdnvr.ogg
As expected it sounds identical to the official soundtrack.

Hope this is enough to fix the issue.

**Comment by droidmjt** [comment]
I check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7xfaruaiqq021a1/droidsounde167_200.apk?dl=1
try this

**Comment by melipog** [comment]
Thanks, that fixed it.
