### ISSUE TITLE
nsf and gsf plugin requests

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#542]
NSFPlug:
Add "Use non-linear interpolation mixer" on 2A03 and MMC5, default is checked, like **nsfplay24** and **foo_input_nsf** (foobar2000 component).
Add "Write protect $8000-$DFFF" on FDS, default is checked. If it checked, multi-expansion with FDS song will play correctly, like this [w7n's cover](http://www.mediafire.com/file/zgwuzjsmmgopn55/Entry127.nsf/file), but some original FDS game like [Silviana](http://www.mediafire.com/file/390b8dk611pifw7/Silviana_%2528FDS%2529.nsf/file) will play abnormally, so this option is a bit necessary.
mGBA:
Update it to latest (Current is 0.8 stable).
XQ Audio option, default is unchecked.

Thanks!

**Comment by droidmjt** [comment]
could you tell me a song in where I can hear the XQ Audio feature?

**Comment by Yave-Yu** [comment]
In some mainly using sample game like Pokemon, Final Fantasy, Kirby, Megaman Zero... might be could hear difference.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/q8hgzuv7ikhipn3/droidsounde167_201.apk?dl=1
try this

**Comment by Yave-Yu** [comment]
Great job! But still have a minor issue.
FDS write protect is unchecked, but first play FDS nsf still keeps checked status, unless switch song by one time.

**Comment by droidmjt** [comment]
I'll fix it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/j8ohvjjdttmsn09/droidsounde167_202.apk?dl=1
I used the same default values what the nsfplay sets

**Comment by sentogiga** [comment]
There are random beeps in all nsf and gsf files that weren't there before

**Comment by sentogiga** [comment]
I turned on XQ and nsfplay settings but it bugged the songs

**Comment by droidmjt** [comment]
XQ is an experimental feature so you can expect problems. About the NSF songs, could you send me one song where these beeps happens ?

**Comment by droidmjt** [comment]
it must be one of those settings since I never set them before build 201

**Comment by Yave-Yu** [comment]
XQ Audio is still in development in mGBA side.

**Comment by Yave-Yu** [comment]
NSFPlug's setting now fixed, thank you!

**Comment by droidmjt** [comment]
good good
