### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#543]
NSFPlug:
Issue: Uncheck **Stereo sound**, replay nsf, it still displays **Channels: Stereo**.
Request: Region seletion, NTSC PAL Dendy.
mGBA:
Request: Resample option (to 44100Hz), I think PSG sound(Square 1, Square 2, Wave, Noise) could reach it like GB, NES.
S98:
Issue: Seems it won't loop forever even I use **Play song endlessly**, tested on _Ys 2_.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/h2uwh38vipyp3e8/droidsounde167_203.apk?dl=1
try this

**Comment by droidmjt** [comment]
the mGBA request is not there, the rest are

**Comment by Yave-Yu** [comment]
Nice.

**Comment by droidmjt** [comment]
the s98 loops so that when end it reached, it rewinds back to loop position

**Comment by droidmjt** [comment]
I'll add the 44100Hz feature in next build.

**Comment by Yave-Yu** [comment]
OK, waiting for next release :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/dblpywv2ykdh4s9/droidsounde167_204.apk?dl=1
