### ISSUE TITLE
One funny bug and one feel

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#545]
The funny bug:
GME plays any format song are all displays **Channel: Mono**, music is still in stereo though.
The feel:
After I heard so many nsf, I feel the NSFPlug is still in older version, because APU2 is a litter weaker than **NSFPlay 2.4's**. The brick smash SFX in _Super Mario Bros. 3_ is more like **VirtuaNSF**(A very older NSFPlayer)'s effect, so I think the NSFPlug in Droidsound-E might be older, if it's real, can you update it to latest?

**Comment by droidmjt** [comment]
Nsfplugin is using the latest nsfplay code. I can check the GME channel problem.

**Comment by droidmjt** [comment]
I close this issue, I'll leave a msg when a new build is around.

**Comment by Yave-Yu** [comment]
New build is still working? So I will give a new request: update mGBA library to 0.8.1, thanks.

**Comment by Yave-Yu** [comment]
This funny bug is fixed, nice.
