### ISSUE TITLE
Request: Support for HLS-streaming Radio Stations

### ISSUE THREAD

**Issue by grj1234** [droidmjt/Droidsound#546]
Some radio stations use HLS (HTTP Live Streaming) for streaming, but Droidsound-E can't play HLS streams. Please consider adding the support for HLS streams.

As an example of HLS-streaming radio station, I post the URL of the Japanese radio station called "NHK Radio 1":
https://nhkradioakr1-i.akamaihd.net/hls/live/511633/1-r1/1-r1-01.m3u8

**Comment by droidmjt** [comment]
I'll consider this feature, I'll close this issue now and reopen once the feature is implemented.

**Comment by droidmjt** [comment]
this feature will be available in next binary

**Comment by grj1234** [comment]
OK, waiting for next binary. :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1m06ctp3m46qcit/droidsounde167_205.apk?dl=1
try this

**Comment by grj1234** [comment]
It works. Thank you!

**Comment by droidmjt** [comment]
great, i'll close this
