### ISSUE TITLE
More vgmplay options?

### ISSUE THREAD

**Issue by BlackYoshi485** [droidmjt/Droidsound#547]
Hi, I'd like to request if it would be possible to add more emulation options for the vgmplay plugin, such as QSound emulation core (currently set to quattroplay, which has some weird panning and mixing issues) to be set to MAME.

**Comment by droidmjt** [comment]
I'll see if it's possible to add an option to switch between those two.

**Comment by BlackYoshi485** [comment]
Thanks a bunch :smile:

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1m06ctp3m46qcit/droidsounde167_205.apk?dl=1
try this

**Comment by droidmjt** [comment]
i'll close this one, I think the feature works
