### ISSUE TITLE
Three requests

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#548]
1. Update mGBA Library to 0.8.1
    _I think they improved PSG performance_
2. Update GME Library
    _Is this uses [that](https://github.com/kode54/Game_Music_Emu) ?_
3. Add resample to 44100Hz of S98 Plugin
    _Well, this is not very important than other two, but if it implemented, it would be more cool_

**Comment by droidmjt** [comment]
I'll check 1. and 2. later, 3. is not gonna happen, I'll work on this later,  I'll close this case and open when I start working on this.

**Comment by Yave-Yu** [comment]
Yes, update 1 and 2 is cool too, I'll waiting for new release :)

**Comment by droidmjt** [comment]
build 211 has 0.8.1 mGBA, I'm already using GME by the way
