### ISSUE TITLE
App shouldn't request permission to Record audio

### ISSUE THREAD

**Issue by VideogameScrapbook** [droidmjt/Droidsound#549]
I downloaded Droidsound-E from your readme:
https://www.dropbox.com/s/kdi49pesohl0x81/droidsounde167_205.apk?dl=1

One of the permissions it requests is to Record audio. Why would it need that permission?

Other questionable permissions that would be nice to explain:
* Modify system settings
* Read phone status and identity
* Modify or delete the contents of your SD card (would it be possible to not have "delete" portion?)

**Comment by droidmjt** [comment]
* Record audio is for this: https://developer.android.com/reference/android/media/audiofx/Visualizer
* READ_PHONE_STATE for this: https://developer.android.com/training/permissions/usage-notes
see topic Pause media after losing audio focus

* Modify or delete the contents of your SD card, this permission is needed to access internal and external SD card memory. It doesn't delete anything on its own.

* Modify system settings, needed for these: https://developer.android.com/reference/android/provider/Settings.System

**Comment by Galindorf** [comment]
Thanks for these clarifications! I was curious about some of these as well.

**Comment by VideogameScrapbook** [comment]
> * Record audio is for this: https://developer.android.com/reference/android/media/audiofx/Visualizer
> * READ_PHONE_STATE for this: https://developer.android.com/training/permissions/usage-notes
>   see topic Pause media after losing audio focus
> * Modify or delete the contents of your SD card, this permission is needed to access internal and external SD card memory. It doesn't delete anything on its own.
> * Modify system settings, needed for these: https://developer.android.com/reference/android/provider/Settings.System

Could you please copy this information to your readme since I think the unexplained permission settings would scare off others from using your amazing app?
