### ISSUE TITLE
Add basic support for m-TAGS

### ISSUE THREAD

**Issue by VideogameScrapbook** [droidmjt/Droidsound#550]
First off, I should say I'm very impressed with Droidsound-E, I wish I discovered it a long time ago!

m-TAGS is the best way to offer song title/artist name/etc. for VGM and was developed as a component for foobar2000. The developer of m-TAGS created it in a way that would be easy to implement and he does a good job describing everything:
http://www.m-tags.org/

For the first version of this support, you could just add the ability to read "@" : "example.lopus" with "RATING" : "X" from a ".tags" file, updating your program's database of any song ratings. Then if that works, you could explore allowing reading "TITLE" : "Example Title" from a ".tags" file, storing the song titles in the same way you store ratings. After that, there are a lot of possibilities for tagging songs in a way that could be shared among the community.

For an example of extensive use of m-TAGS, copy column A of the m-TABS tab of my public Super Smash Bros. series music Google spreadsheet:
https://docs.google.com/spreadsheets/d/1rxouo4OxyF6TcnUwgavqyNrx6E5yiknQkVCvwWq_QJs/edit#gid=1991770518

**Comment by droidmjt** [comment]
Thanks for the info, I'll get back to this when I have more time.

**Comment by droidmjt** [comment]
leave a msg

**Comment by VideogameScrapbook** [comment]
> leave a msg

What do you mean by this?
