### ISSUE TITLE
DroidSound-E and Viper4Android FX

### ISSUE THREAD

**Issue by NgrNxk** [droidmjt/Droidsound#551]
Hi,

I'm using VIPER4Android 2.5.0.4 (at least the "Driver version" says that). And while it wasn't always working especially well with DroidSound-E, it simply stopped after 205(?) or somewhere about. Well, not really. Sometimes it works with the normal MP3 player, but only up to pressing "next". Then I have to stop the playback and restart it again. And playing from a stream does not initiate VIPER4Android processing at all any more. 
I just installed 198 again, and it's working just fine for streams; the issue with normal playback is as described for 198 and 205.

Is there any possibility to look into that? Otherwise my shitty head phones produce really horrible audio :). VLC works with "AudioTrack" or "OpenSL ES" just fine.

Thanks,
Adam

**Comment by droidmjt** [comment]
I know what causes the trouble, I'll add a switch what you can use to get it working like before.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/myp9obz2nzrrm1y/droidsounde167_206.apk?dl=1
try this, unfortunately I cannot guarantee that it works, I cannot test with Viper4Android.

**Comment by droidmjt** [comment]
I rooted one of my devices and installed Viper4Android, I don't think the problem is Droidsound-E, I'm using AudioTrack, I even tried to force it to session_id 0 and still it didn't work. If you know an open source application what works with viper4android and uses audiotrack, let me know.

**Comment by droidmjt** [comment]
I also tested this with VLC, it didn't work immediately, had to switch between AudioTrack and OpenSL but eventually I got it working. I suspect the Viper4Android might have an issue in detecting audio players presence properly.

**Comment by droidmjt** [comment]
VLC seems to be opensource so I checked how the AudioTrack is being used there, they use Session-ID 0. I don't think there is anything I can do with this, unfortunately.

**Comment by droidmjt** [comment]
I probably figured this out, if you set sessionId to zero the AudioTrack picks randomly a SessionID, that would explain why Viper4Android doesn't always find the audio players using AudioTrack. The author of Viper4Android should agree what SessionID to use. Unless there is a way to tell Viper4Android what SessionID to expect from an audio player.

**Comment by droidmjt** [comment]
I got it working, I'll prepare a new binary.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/heosuowt5eq5rxl/droidsounde167_208.apk?dl=1
Here is a new binary, actually, I think it would have worked with previous build also, but just for sure I added an option to switch to another session ID.

The main reason why it fails is the Visualizer, you cannot have them both at the same time. Try it so that you start Droidsound-E, go to settings and disable Visualizer, then start playing something. 

If Visualizer is enabled while music is playing, it will make Viper4Android angry, the only way to recover Viper4Android is to restart device.

**Comment by NgrNxk** [comment]
Thank you very much for the work you put into it! It works better than before, now that you gave the hint with the visualizer.
