### ISSUE TITLE
Minimum API version support change

### ISSUE THREAD

**Issue by droidmjt** [droidmjt/Droidsound#552]
I'm about to increase the minimum API level to 21 (Android 5.0). If possible, let me know on what API level most of your devices are.

**Comment by Yave-Yu** [comment]
Android Pie, API 28.

**Comment by rainsrx** [comment]
Android Pie

**Comment by drew887** [comment]
Android 10, API 29

**Comment by qwertysampletext** [comment]
API level 29

**Comment by pantomm** [comment]
android 6.0.1

**Comment by Galindorf** [comment]
Android 10.0 (as of Tuesday! ) API 29, as far as I can tell?

**Comment by 97lily** [comment]
I’m using in Android 11 (beta1) on Pixel3.

**Comment by VIRGINKLM** [comment]
API 27

**Comment by Diamondragon** [comment]
Android 10, API level 29

**Comment by TheLastZombie** [comment]
API level 29 (Android 10 / Q).

**Comment by droidmjt** [comment]
Great, thank you all for the answers.
