### ISSUE TITLE
AdPlug freezes the player in play song endlessly mode

### ISSUE THREAD

**Issue by LGA1150** [droidmjt/Droidsound#553]
Steps to reproduce the bug:
1. On player page, set player to "Play song endlessly"
2. Play an AdLib song such as The Alibi in Examples - Other
3. At 3:05 the player will freeze. Have to restart the app to play another song

**Comment by droidmjt** [comment]
I have fixed this already, fix will be available in next build

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/myp9obz2nzrrm1y/droidsounde167_206.apk?dl=1
try this, should be fixed

**Comment by LGA1150** [comment]
It worked, thanks!
