### ISSUE TITLE
VGMStream seems broken

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#554]
Version: 206
Any ADPCM music are keeps silent, like brstm(e.g. NSMBWii), xa(e.g. Mega Man X4).
.
Also one typo in NSFPlug setting, the first $4007 should be $4003.
![Screenshot_2020-03-05-11-03-31-675_com droidmjt droidsounde~01](https://user-images.githubusercontent.com/54294476/75943853-29c25980-5ed1-11ea-82f9-a2c96a08a837.png)

**Comment by droidmjt** [comment]
thanks for testing, I switched from GCC to Clang recently, I'll investigate this

**Comment by droidmjt** [comment]
its broken on ARM, not on x86 :( I'll fix it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/fx4eed45y93p2qn/droidsounde167_207.apk?dl=1
try this

**Comment by Yave-Yu** [comment]
It fixed, nice, thank you.
