### ISSUE TITLE
+/- buttons on "Noise sharpening"

### ISSUE THREAD

**Issue by qwertysampletext** [droidmjt/Droidsound#555]
Buttons to add/subtract .01 to/from "Noise sharpening" (found in the "Effects Setting" menu) would be useful, as I always have it set to either 0 or .01, and setting it to the latter takes multiple attempts with the slider.

**Comment by droidmjt** [comment]
I'll add it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/03hs6m1375blv41/droidsounde167_209.apk?dl=1
try this

**Comment by Yave-Yu** [comment]
Two minus??
![Screenshot_2020-03-07-17-57-54-308_com droidmjt droidsounde~01](https://user-images.githubusercontent.com/54294476/76141242-44e1c480-609d-11ea-86ba-faa02eccad0e.png)

**Comment by droidmjt** [comment]
yeah, copypaste FTW, i'll fix it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/42lk2xonijnlgkc/droidsounde167_210.apk?dl=1
