### ISSUE TITLE
GSF: MMBN1 music skips a little at beginning

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#556]
Version: 211
Only happens on Mega Man Battle Network 1, when play a music, it skips a little part at beginning, what's this problem?

**Comment by droidmjt** [comment]
It is intentional, there are some GSF songs what crackles at the beginning when using XQ option. I'll revisit this code

**Comment by Yave-Yu** [comment]
Ah, but I won't use XQ option, it still skips.

**Comment by droidmjt** [comment]
fixed, new link at readme

**Comment by Yave-Yu** [comment]
Nice.
