### ISSUE TITLE
scaling/stretching of UI

### ISSUE THREAD

**Issue by NgrNxk** [droidmjt/Droidsound#557]
Hi,

I am using DerpFest 9 as my Android distribution on my Xiaomi Mi 9T. And most of the apps are working fine, but some, especially DroidSound-E, are not stretching all the way to the bottom of the screen.

Also, the search is missing the scroll bars (second screenshot). Can I help to solve this somehow?

Regards
Adam

![Screenshot_20200309-135248](https://user-images.githubusercontent.com/2931938/76218422-86e14680-6214-11ea-8201-4d0fb7c0cda8.jpg)
![Screenshot_20200309-134226](https://user-images.githubusercontent.com/2931938/76218453-8ea0eb00-6214-11ea-95a8-ba673fc771a1.jpg)

**Comment by Yave-Yu** [comment]
If you are using MIUI, try:
Settings - Full screen display - Fullscreen mode, turn Droidsound-E on.
If you are AOSP... Full screen might be in somewhere...

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xmrsro1ie439yd6/droidsounde167_213.apk?dl=1
try this

**Comment by NgrNxk** [comment]
Perfect! Thank you very much!
