### ISSUE TITLE
Converting Bug

### ISSUE THREAD

**Issue by AdityaMH** [droidmjt/Droidsound#559]
I want converting this music into MP3.
[LGS_SOUND_0000298.zip](https://github.com/droidmjt/Droidsound/files/4351859/LGS_SOUND_0000298.zip)

But this music going too fast.

And this nothing happen if converting into WAV file.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8e0gp5lml4tkmrh/droidsounde167_215.apk?dl=1
try this

**Comment by AdityaMH** [comment]
Now fixed. Thanks.
