### ISSUE TITLE
Mp3 ringtone convert quality select doesnt work, stuck at 128kbps

### ISSUE THREAD

**Issue by TheRektafire** [droidmjt/Droidsound#560]
The mp3 export quality selection under ringtone settings doesnt work, it is always 128kbps no matter what you actually put there. I tested using a couple of midis that I wanted to convert to mp3 from here http://jamespaddockmusic.com/midi-files/

**Comment by droidmjt** [comment]
all right, i'll fix it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xeahl28r6pj6no5/droidsounde167_216.apk?dl=1
try this

**Comment by TheRektafire** [comment]
Thanks, now it's working :) but now there's another glitch, some songs aren't converting at the correct length, I'm trying to convert "global_130" from here https://www.zophar.net/music/playstation2-psf2/24-the-game but it's only outputting as 1:29 instead of 1:52 which is the actual song length

**Comment by TheRektafire** [comment]
And I found another one, I think I found the reason why the mp3 export is longer, for some reason parts of the song repeat themselves when exporting as mp3 but NOT as wav, I figured this out by listening to both versions, I noticed a couple of very obvious parts where some sections last noticeably longer than they should, for some reason it doesn't sound glitchy or the wrong speed or anything like that though, its weird

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/it71cpprnzs6kml/droidsounde167_217.apk?dl=1
try this
