### ISSUE TITLE
vgmstream update

### ISSUE THREAD

**Issue by Incineroar** [droidmjt/Droidsound#561]
Persona 5 Royal just had its soundtrack dumped online the other day, and the vgmstream plugin was updated because Atlus decided to add ADX encryption keys to the soundtrack this time around.

When you publish your next build, would you be able to incorporate the updates to vgmstream so it has the required keys to decrypt and play this soundtrack?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/xeahl28r6pj6no5/droidsounde167_216.apk?dl=1
try this

**Comment by Incineroar** [comment]
Looks to be working. Thanks!
