### ISSUE TITLE
USB headset playback control button not working properly

### ISSUE THREAD

**Issue by qwertysampletext** [droidmjt/Droidsound#562]
I have had this issue since Oreo, double clicking the pause/play button on USB headsets will pause or resume, but double clicking it will not skip track and double clicking while paused will not play prev. track. Would be useful to have this working, since it is the only convenient way to change tracks with screen off.

**Comment by droidmjt** [comment]
Try clicking three times, at least for BlueTooth it works. When a song is playing, 3-click goes to previous song and double click goes to next one. I don't have USB headset, so I cannot fix it.
