### ISSUE TITLE
NSFPlug: Dendy region issue

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#563]
Use Dendy region will cause all nsf playing very fast...

**Comment by droidmjt** [comment]
I just tested few example songs with Dendy option (Prefer and Force) and they played just like with nsfplay. All other settings are defaults.

**Comment by Yave-Yu** [comment]
Now with one temporary solution: enable force 60.09/50Hz, it plays normal in Dendy region.
I tested NSFPlay 2.4, it plays normal in Dendy region without enable force 60.09/50Hz.

**Comment by droidmjt** [comment]
Reinstalled the app to make sure all the preferences are defaults, tried with Force Dendy and Prefer Dendy, kick master played just like with NSFPlay. Force Dendy plays slower, Prefer Dendy plays with same speed as with Auto mode.
