### ISSUE TITLE
Crash when playing Nettou Garou Densetsu 2 - Aratanaru Tatakai (GBS)

### ISSUE THREAD

**Issue by brianpow** [droidmjt/Droidsound#564]
Crash when playing Nettou Garou Densetsu 2 - Aratanaru Tatakai (GBS)
Tested on version 1.67.213, 1.67.217
Also failed to play by gbsplay v0.0.93
Play fine on MiniGBS v1.4.2

**Comment by droidmjt** [comment]
It seems to be a library related issue, you should report it here:
https://github.com/kode54/game_music_emu OR
https://bitbucket.org/kode54/game-music-emu/commits/

**Comment by droidmjt** [comment]
Doesn't crash here, just stays silent.

**Comment by droidmjt** [comment]
also close this one, lets wait for library update

**Comment by droidmjt** [comment]
Correction, this one crashes with GME but works with NEZ Plugin when you override the format.
