### ISSUE TITLE
No sound when playing Top Gear Pocket 2 [Top Gear Rally 2] (GBS)

### ISSUE THREAD

**Issue by brianpow** [droidmjt/Droidsound#565]
No sound when playing Top Gear Pocket 2 [Top Gear Rally 2] (GBS)
Tested on version 1.67.217
Also failed to play by gbsplay v0.0.93
Play fine on MiniGBS v1.4.2

**Comment by droidmjt** [comment]
It seems to be a library related issue, you should report it here:
https://github.com/kode54/game_music_emu OR 
https://bitbucket.org/kode54/game-music-emu/commits/

**Comment by droidmjt** [comment]
close these issues, I cannot fix these

**Comment by droidmjt** [comment]
actually, there is a fix, go to Settings -> Plugin Settings -> NEZ Plugin -> Format Overrides and check GBS
