### ISSUE TITLE
Add all to 'Favorites' crash

### ISSUE THREAD

**Issue by brianpow** [droidmjt/Droidsound#566]
Steps to reproduce:
Under browser, tap and hold any music file, tap "Add all to 'Favorites' in the popup menu, then Droidsound-E crash.

Tested on 1.67.217

**Comment by droidmjt** [comment]
I went to Examples -> Amiga -> and added all to favourites, no crash.

**Comment by brianpow** [comment]
Did some futher test. It happens if the archive contains non-music file (e.g text file, png file etc).

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/62jfxvkvhlw4h1p/droidsounde167_218.apk?dl=1
try this

**Comment by brianpow** [comment]
Thanks. It works like a charm. One more feature request, it would be great if it also works on folder and archive file so we don't need to dive in before adding to favourites

**Comment by droidmjt** [comment]
I'll fix it one day
