### ISSUE TITLE
Add interpolation filters on mGBA audio.

### ISSUE THREAD

**Issue by VIRGINKLM** [droidmjt/Droidsound#568]
Once back I asked for something similar for NDS audio which was eventually added and I really appreciate it.
What is missing from the XQ Audio option to take GBA audio to the next level on that plugin is simply somekind of interpolation that will eliminate all those nearest neighbor aliasing artifacts of the used samples.
A simple linear interpolation would do the job.

**Comment by droidmjt** [comment]
You should suggest this filtering to mGBA library developers. I wouldn't like to add any extra filters.

**Comment by VIRGINKLM** [comment]
Guessed so, thanx alot!
