### ISSUE TITLE
[Question] Is It Possible to Show Loop Information when Playing Music?

### ISSUE THREAD

**Issue by mistersiraj11** [droidmjt/Droidsound#570]
Hi, droidmjt. It's not an issue per se but I'm curious if Droidsound-E can show loop information (a la loop start and loop end points) when playing any music with loop info? Thanks in advance!

**Comment by droidmjt** [comment]
whats the benefit of knowing that info?

**Comment by mistersiraj11** [comment]
> whats the benefit of knowing that info?

I'm just curious. If you can't do it, that's fine too.

**Comment by drew887** [comment]
I mean personally it sounds cool knowing how short/long of a loop actually makes up some music. Its definitely something I pay attention to if I'm viewing files in a tracker :thinking:
