### ISSUE TITLE
Update LibOpenMPT plugin with Composer 670 Support

### ISSUE THREAD

**Issue by JFD62780** [droidmjt/Droidsound#571]
First post in years, but I have a suggestion.

The LibOpenMPT engine now supports tracked music with both FM synth channels and PCM channels.  As used in the Sound Blaster version of the Zone 66 soundtrack.  Which was composed in Composer 670 (AKA CDFM Tracker) inhouse by developers, Renaissance.

[Here](http://www.shikadi.net/files/games/renaissance/cdfm.zip) is the tracker itself, along with virtually all the tracks made by the composer.  [Here](http://sbfmdrv.blogspot.com/2015/12/renaissance-cdfm-music.html) is the blog page explaining the Composer 670 program itself.  And [here](https://forum.openmpt.org/index.php?topic=6062.0) is a topic page at the OpenMPT forums explaining more.

As for compatibility?  The latest LibOpenMPT releases, simply treat them like those hybrid S3M's with FM+PCM.

Meanwhiles, the current Droidsound release doesn't even see them, whether they have C67 or S3M extensions.  Can this be remedied?

**Comment by droidmjt** [comment]
The support should be there already, try with extensino .670

**Comment by droidmjt** [comment]
ehh, ignore the .670 extension. I need to investigate this.

**Comment by droidmjt** [comment]
Could you give URL to some 670 songs?

**Comment by JFD62780** [comment]
...The sad thing is that archive I linked to has all the known songs from that tracker in the Music folder.  I don't know what else to tell you...

**Comment by droidmjt** [comment]
crap, I didn't read the message carefully, I'll check them

**Comment by JFD62780** [comment]
It's cool.  Just as long as you got the message, which I've written carefully. ;)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/4v9bnkcmcnv8smk/droidsounde167_219.apk?dl=1
try this

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8amwaw1a6w4u5m7/droidsounde167_219.apk?dl=1
try this

**Comment by JFD62780** [comment]
Nope.  Droidsound still doesn't see the files, even after a rescan.  Not sure what it's gonna take, frankly...

**Comment by droidmjt** [comment]
I thought so. I forgot to mention that, by using .s3m extension won't work since they are not ScreamTracker 3 files.
