### ISSUE TITLE
Some txtp files don't work

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#572]
Pokemon Sword + Shield [Pocket Monsters Sword + Shield] (2019-11-15)(Game Freak)(The Pokemon Company, Nintendo)[Switch] and Super Mario Odyssey (v1.3.0) (2017-10-27)(Nintendo EPD)(Nintendo)[Switch] txtp files don't work, don't know why they don't work and only give a error when trying to play them.

**Comment by droidmjt** [comment]
its because those txtp files have \ instead of /

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/if06w4joc7dlnly/droidsounde167_221.apk?dl=1
try this

**Comment by Sir-Sabin** [comment]
That fixed it , thx
