### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by juanreina921** [droidmjt/Droidsound#573]
Hi Droidjmt, thank you for giving us thewinamp like app for chiptunes. If it's   not too much, could you update Brad Smith's NSF play to laytest? Found 

[Here](ci.appveyor.com/project/bbbradsmith/nsfplay/branch/master/artifacts) 

Once again thank you, and thanks for keeping the interface accessible, as I am blind and using screen reader.

**Comment by droidmjt** [comment]
what makes you think its not the latest already?

**Comment by droidmjt** [comment]
Nevermind, I'll update the nsfplay library once they make a release.

**Comment by juanreina921** [comment]
Yeah, some nsfs don't work,, and thank you.

**Comment by droidmjt** [comment]
could you post here those NSF songs which don't work?

**Comment by juanreina921** [comment]
Quite a bit, its from 2013 so alot of fds chiptunes, don't sound good,
especially those that use vocaloid.

**Comment by juanreina921** [comment]
There are after the start of the song, the vrc7  chanall stops playing.
This is all fixed in the mar15, 2020 update. If you nead more, please ask!
