### ISSUE TITLE
Laytest droidsound won't install

### ISSUE THREAD

**Issue by juanreina921** [droidmjt/Droidsound#574]
Hello Droidjmt, I tried the laytest version of droidsound, but to my surprise, it said app not installed. I did everything as usual, clear storage and cash. The ver prire to laytest works. Am I missing something? Or is this an error in the apk. Wit regards, Juan.

**Comment by droidmjt** [comment]
I'll rename the files for clarity. Does the build _222 work now?

**Comment by juanreina921** [comment]
Yes it works now, I had to run the 32 one. Thank you so much.

**Comment by droidmjt** [comment]
great, i'll close this issue

**Comment by JFD62780** [comment]
Welp!  I tried the 64-bit build myself, for shiggles...

It was actually stubborn enough to NOT let a weak-ish wifi signal stop it from streaming Internet Radio!

Great job! 8D

**Comment by AdityaMH** [comment]
what happen/affected if i install 32bit? (my phone is 64bit).

**Comment by droidmjt** [comment]
nothing will happen, but you should get better performance with 64bit build

**Comment by AdityaMH** [comment]
better perfomance? it's just music player.
