### ISSUE TITLE
Droidsound 64bit version has crashed in Android 11 beta

### ISSUE THREAD

**Issue by 97lily** [droidmjt/Droidsound#576]
Hello, and thanks to hope the good player (so I enjoy to chiptune on app :3 )

I just tried to install the latest version and it crashes when to launch 
and I'm tried to remove app data & cache and  reinstalling the apk files, but still crashed  

-details 
Error type : when launched to clash
Device : Google Pixel 3
OS: Android 11 beta 1 (not developer preview version, it's latest version)

-log
Strange story, I'm trying to get the log, but it doesn't show up even if I choose vervose, error and any level (maybe my mistake)
If you get it, put it in this issue

**Comment by 97lily** [comment]
Successful log acquisition
-log
06-30 10:46:10.711 E/AndroidRuntime(17278): Process: com.droidmjt.droidsounde, PID: 17278
06-30 10:46:10.711 E/AndroidRuntime(17278): 	at com.droidmjt.droidsounde.plugins.DroidSoundPlugin.<clinit>(DroidSoundPlugin.java:30)
06-30 10:46:10.711 E/AndroidRuntime(17278): 	at com.droidmjt.droidsounde.plugins.DroidSoundPlugin.setContext(DroidSoundPlugin.java:100)
06-30 10:46:10.711 E/AndroidRuntime(17278): 	at com.droidmjt.droidsounde.PlayerActivity.onCreate(PlayerActivity.java:1898)
06-30 10:46:11.222 E/InputDispatcher(1600): channel '870bd29 Splash Screen com.droidmjt.droidsounde (server)' ~ Channel is unrecoverably broken and will be disposed!
06-30 10:46:11.797 E/InputDispatcher(1600): channel 'acc4e40 Application Error: com.droidmjt.droidsounde (server)' ~ Channel is unrecoverably broken and will be disposed!
06-30 10:46:49.768 E/mjt.droidsound(17362): Not starting debugger since process cannot load the jdwp agent.

**Comment by droidmjt** [comment]
Tested with the ROMs available from Google, worked fine with API 30 x86_x64. I don't have any devices having Android 11 arm64-v8a. The log doesn't tell anything useful. Unfortunately I cannot investigate this more. If you can, roll back to Android 10.

**Comment by 97lily** [comment]
The cause is unknown, but since I deleted the dstoot folder and reinstalled it, it started as if nothing had happened.  I solved it, but I am sorry that it is useless due to lack of information
