### ISSUE TITLE
NSFPlug: Give an ability to adjust each volume.

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#577]
Like original NSFPlay's **Device Mixer**.
![DeviceMixer](https://user-images.githubusercontent.com/54294476/86201973-96a1e380-bb93-11ea-9968-d2f993b12b17.png)

**Comment by droidmjt** [comment]
Done with this feature. I'll upload new binaries once I have solved another problem.

**Comment by Yave-Yu** [comment]
Thanks!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7ix17hj2tnh0o47/droidsounde167_225_32bit.apk?dl=1
https://www.dropbox.com/s/j4l1st4hf36slj2/droidsounde167_225_64bit.apk?dl=1
check the feature please

**Comment by droidmjt** [comment]
now you can also see the used devices in metadata

**Comment by Yave-Yu** [comment]
All volume settings works, and **Devices** display is nice idea.

**Comment by droidmjt** [comment]
great

**Comment by rhjdvsgsgks** [comment]
It would be better if this feature could be added to midi plugin
