### ISSUE TITLE
Missing the "Add additional length to a song" function

### ISSUE THREAD

**Issue by Batatacius** [droidmjt/Droidsound#578]
Please bring it back as it is useful to me.

**Comment by droidmjt** [comment]
How it is useful?

**Comment by Batatacius** [comment]
For some reason, at least in my case, many songs have approximately one second cut off at the end, unless endless loop mode is selected. This problem is very noticeable when playing jingles and short songs. For example, jingles and sound effects shorter than 1 second are not even played normally. So to solve this problem I always had 1 second added.

**Comment by droidmjt** [comment]
In which plugins this happens?

**Comment by Batatacius** [comment]
GME, NSFPlug, MGBA, VIO2SF, kss plugin and vgmplay have this problem, but these are the plugins I use, I think several other plugins have this problem as well.

**Comment by droidmjt** [comment]
Could you post some of those short songs here so I can test them?

**Comment by Batatacius** [comment]
Here it is:

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7ix17hj2tnh0o47/droidsounde167_225_32bit.apk?dl=1
https://www.dropbox.com/s/j4l1st4hf36slj2/droidsounde167_225_64bit.apk?dl=1
try if the files work now, I didn't add the feature back but did some other changes

**Comment by Batatacius** [comment]
First of all, my phone is 32 bit, so that is the version I tested. It's better than before, but it's still not perfect. Vgmplay keeps cutting out the end of the songs, as well as kssplugin (in the kss file I sent you, try listening to track 02 with kssplugin or gme with endless mode on and then with it off to notice the difference).

**Comment by Batatacius** [comment]
About vgmplay, here are some other vgm and vgz files, again I ask you to listen with and without endless mode so you can notice the difference.
https://drive.google.com/file/d/1SoXQs32s213G0I7H-pQht3zuhqlEKHKL/view?usp=drivesdk

**Comment by droidmjt** [comment]
I'll test them.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/yqu43f8fmbg2x74/droidsounde167_226_32bit.apk?dl=1
https://www.dropbox.com/s/xetdg6eqyxdpo4q/droidsounde167_226_64bit.apk?dl=1
see if this build works better

**Comment by Batatacius** [comment]
Yes! It's working perfectly, thank you. And keep up the good work.

**Comment by droidmjt** [comment]
great, I'll close this issue
