### ISSUE TITLE
Android 10 Internal SD Folder not appearing

### ISSUE THREAD

**Issue by Zackie32b** [droidmjt/Droidsound#579]
![Screenshot_20200711-233353](https://user-images.githubusercontent.com/68175024/87238360-9e515b80-c3cf-11ea-9904-75148b50ea14.png)
For some reason on Android 10, the internal directory doesn't show up anymore...

**Comment by droidmjt** [comment]
What is the internal sdcard path in that device?

**Comment by Zackie32b** [comment]
Here

**Comment by droidmjt** [comment]
Your comment has just a word 'Here'. Did you try to attach a screenshot?

**Comment by Zackie32b** [comment]
Yeah, didn't it send?

**Comment by droidmjt** [comment]
nope

**Comment by droidmjt** [comment]
If you just go to Add -> Local Filesystem Browser -> click OK, what happens?

**Comment by Zackie32b** [comment]
I hope it sends now

Em dom., 12 de jul. de 2020 às 01:08, droidmjt <notifications@github.com>
escreveu:

**Comment by droidmjt** [comment]
nope

**Comment by Zackie32b** [comment]
thanks anyway, i was able to fix it!
