### ISSUE TITLE
Link to last legacy version?

### ISSUE THREAD

**Issue by 60fpshacksrock** [droidmjt/Droidsound#580]
I was wondering if you could post a link to
to the last version that works on at least android 4.1.

I ask because downloaded a recent version and couldn't get it to work even on 4.4 KitKat.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/n2wcd8t2ikwe8az/droidsounde_legacy.apk?dl=1
there you go

**Comment by droidmjt** [comment]
the link is also in readme.md, I'll close this issue

**Comment by 60fpshacksrock** [comment]
Thanks a lot. 

Apologies for opening this as an issue when it really isn't.
