### ISSUE TITLE
Feature request: Adjust playback speed for NSF(E) files

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#581]
Could this be done with the GME plugin?
A plugin-wide setting will be OK for me.

**Comment by droidmjt** [comment]
could you tell a bit more, what playback speed, does the NSFPlugin has it already?

**Comment by wmjordan** [comment]
I don't know whether NSFPlugin has it.
[NotSo Fatso](http://slickproductions.org/notsofatso.php), the original NSFE player on the Windows platform has that option. It allows the user to adjust the "frame rate", which by default is 60 FPS (NTSC). The user can change it to any value, for instance, to 50 FPS (the frame rate of PAL), so the music will play a little bit slower.

**Comment by wmjordan** [comment]
It seems that GME has something to do with playback speed adjustment:
https://github.com/kode54/Game_Music_Emu/blob/master/gme/Nsf_Impl.h

**Comment by droidmjt** [comment]
I don't think its possible to add the feature. Is there a problem with NSFPlugin?

**Comment by wmjordan** [comment]
It is not a problem with NSFPlugin.
I just miss that option in NotSo Fatso which allows NSFE music tracks to be played a little bit slower.

**Comment by droidmjt** [comment]
so with NSFPlugin you cannot play NSFE music tracks a little bit slower?

**Comment by wmjordan** [comment]
I think so.
I could not find a setting to do that.
BTW, I think the GME Plugin provides better sound quality than the NSF Plugin, for the former has better stereo separation and sound dynamics. Could you utilize [this function in GME](https://github.com/kode54/Game_Music_Emu/blob/b757c4a4145943ae3837bf2026da5d0d173bd2c3/gme/Music_Emu.h#L94) to adjust the tempo?

**Comment by droidmjt** [comment]
see Settings -> NSF plugin > Region -> General -> Region, you should be able to force PAL and NTSC

**Comment by droidmjt** [comment]
ok I'll add the tempo setting

**Comment by wmjordan** [comment]
Thank you for considering this.
Since GME supports various file types, is it possible to separately adjust the tempo for each file types? i.e. NSFE can have a tempo, SPC have another one, etc.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/g79s8fnvq0d82pu/droidsounde167_228_32bit.apk?dl=1
https://www.dropbox.com/s/kqagdiapw60zcp9/droidsounde167_228_64bit.apk?dl=1
tempo added, its just one setting for all the formats

**Comment by wmjordan** [comment]
I'd just downloaded and tested the new version, and found that most NSFE songs could not be played to the end (if their lengths were specified). It might because that the song length had not been correctly adjusted after the song length after the tempo was changed.

The track length returned by the `song_info` should be divided by the tempo if it is not 1.0, according to [the comment of `set_tempo`](https://github.com/kode54/Game_Music_Emu/blob/b757c4a4145943ae3837bf2026da5d0d173bd2c3/gme/Music_Emu.h#L94).

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tw7eerv4r0qichc/droidsounde167_229_32bit.apk?dl=1
https://www.dropbox.com/s/ba180zskg0lyt31/droidsounde167_229_64bit.apk?dl=1

**Comment by wmjordan** [comment]
Thank you very much.
It is really great!
