### ISSUE TITLE
1 minor bug and 1 request

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#582]
1 minor bug:
Not functional bug, just look odd. For any multi-song file like nsf gbs kss, if you are using endless mode, you will see below:
First time to play, bottom-right timer displays 00:00, it's normal; but when you switch a sub-song, it will change to 00:01, and timebar will reach full when bottom-left timer goes to 00:01, it's so odd in endless mode.
1 request:
NSFPlug update to latest dev build, it fixes triangle pop (It's very clear on Mega Man 4 Bright Man song at 00:01 and [Mega Man 3 TBoG](http://www.mediafire.com/file/juwmwhbrdq2waha/Mega_Man_3_TBoG.nsf/file) 3th song at 00:19), also please add new options which in APU1 APU2 VRC7, thanks.
APU1: Initialize sweep unmute ($4001, $4005 = $08)
APU2: Reverse bits of DPCM
VRC7: Replace VRC7 with YM2413 (OPLL)

**Comment by droidmjt** [comment]
1 bug: I noticed this also and should be fixed in build _227
1 request: This was asked before, I'll update the nsfplay once the official release is out

**Comment by Yave-Yu** [comment]
OK, I haven't update to 227, I will see.

**Comment by Yave-Yu** [comment]
227 really fixed that odd looking bug.
And I'm looking forward latest NSFPlug into Droidsound-E, it's best NSF player, nothing else.
