### ISSUE TITLE
The character "é" is not displayed by Droidsound

### ISSUE THREAD

**Issue by Diamondragon** [droidmjt/Droidsound#583]
I'm not sure if this is something that could be addressed, but certain characters, like that displayed in the title, do not seem to display correctly in Droidsound.

![Screenshot_20200730-150845](https://user-images.githubusercontent.com/8113474/88959073-cec24200-d277-11ea-912b-63e60f5b7c0b.jpg)
![Screenshot_20200730-150905](https://user-images.githubusercontent.com/8113474/88959082-d255c900-d277-11ea-930c-93be5a4d08eb.jpg)

**Comment by droidmjt** [comment]
I'll try to fix this

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/g79s8fnvq0d82pu/droidsounde167_228_32bit.apk?dl=1
https://www.dropbox.com/s/kqagdiapw60zcp9/droidsounde167_228_64bit.apk?dl=1
try one of those if it works

**Comment by Diamondragon** [comment]
Thank you for the update. It has been fixed on the Player screen, but not on the Browser screen.

![Screenshot_20200801-132826](https://user-images.githubusercontent.com/8113474/89106192-2a1e3c80-d3fe-11ea-8e7b-c3185edeb395.jpg)

![Screenshot_20200801-132809](https://user-images.githubusercontent.com/8113474/89106197-2db1c380-d3fe-11ea-9f79-f081d573af1b.jpg)

**Comment by droidmjt** [comment]
did you rescan?

**Comment by Diamondragon** [comment]
Good catch. I hadn't done that. It does work now. Thank you very much!
