### ISSUE TITLE
update request. update to laytest version of vgmplay, or dev library libvgm?

### ISSUE THREAD

**Issue by juanreina921** [droidmjt/Droidsound#584]
Hello Droidjmt, Would it be possible to update to latest vgmplay, or to the recent started library called libvgm? The newest vgmplay has support for vgms using the Gameboy DMG, soundchip, as well as new chips and emulator cores.
You can find libvgm at
[]()https://github.com/ValleyBell/libvgm
And for vgmplay
[]()https://github.com/vgmrips/vgmplay
Thanks for making this the best player ever. Thanks so much!

**Comment by droidmjt** [comment]
I can update it. Could you provide an URL for the vgm file what the present version of Droidsound-E doesn't play, so I can test the updated code?

**Comment by juanreina921** [comment]
I just looked and to what I know, it looks fine, but for a couple of things. When playing rips like dragon ball buyu retsuden, in one of the songs the soundchip brakes on one note, even if loop is on. Or in the rip for kyokiu tiger, tg 16, the chip brakes completely at the end if loop is on. I tested with the nes vgm of this rip, and if loop is on or off, it still respects the vgm file, and the file plays as it should.
If you want to test some vgms out to, go to 
Vgmrips.net
And maybe someone could find some more bugs too.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tw7eerv4r0qichc/droidsounde167_229_32bit.apk?dl=1
https://www.dropbox.com/s/ba180zskg0lyt31/droidsounde167_229_64bit.apk?dl=1

**Comment by juanreina921** [comment]
Hello Droidjmt, There is still a bug, where playing dragon ball byuu retsuden, one of the chips still brake, notably the SN76496 Emucore, the YM2612 Emucore, and the YM2413 Emucore. This only happens if loop is on. I will test kiokyoku tiger, and see if the bug persists, and let you know. Ok?  Please take a look at my previous comment, for dragon ball, byuu retsuden link. thank you, and keep it up!

**Comment by droidmjt** [comment]
Could you at least tell me which file? I don't want to listen all of them through.

**Comment by juanreina921** [comment]
@Droidjmt, really sorry about that, it's track 15 and 16. ,

**Comment by droidmjt** [comment]
Great, I'll check them.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/4wixrkx143zjr98/droidsounde167_230_32bit.apk?dl=1
https://www.dropbox.com/s/xq1q5z1k2jrdvls/droidsounde167_230_64bit.apk?dl=1
I hope it works now

**Comment by juanreina921** [comment]
Thanks man, that's a fix.

**Comment by droidmjt** [comment]
great
