### ISSUE TITLE
Can't playing .midi files

### ISSUE THREAD

**Issue by AdityaMH** [droidmjt/Droidsound#585]
Usually droidsound-e able to play MIDI files with .mid extension. but can't play files with .midi extension when other song player can run smoothly.
Btw, i'm using 64bit version and using BASSMIDI plugin.

Here for example file:
[愛を伝えたいだとか 完熟レモン.zip](https://github.com/droidmjt/Droidsound/files/5020294/ver.midi.zip)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tw7eerv4r0qichc/droidsounde167_229_32bit.apk?dl=1
https://www.dropbox.com/s/ba180zskg0lyt31/droidsounde167_229_64bit.apk?dl=1
try this

**Comment by AdityaMH** [comment]
Fixed. Thanks
