### ISSUE TITLE
Non-Vgmstream fadeout

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#587]
it appears that version 1.67.230 32bit does not fade out songs that are not vgmstream (tested ncsf, 2sf, usf,spc). these have the extra length added properly for the fadeout, but play that extra length as silence instead of fading out.

**Comment by droidmjt** [comment]
Yeah, I need to remove the extra length feature.

**Comment by froggestspirit** [comment]
not sure if its separate, but can the append fadeout to end of song option still be available?

**Comment by droidmjt** [comment]
No it cannot, the append fadeout length will be gone in next build.
