### ISSUE TITLE
OGG Opus Loop Information Reading Issue

### ISSUE THREAD

**Issue by mistersiraj11** [droidmjt/Droidsound#588]
Hi, droidmjt! You need to use headphones to hear what I mean. The moment my songs reach their loop-end point, instead of looping seamlessly, they loop with a click or an audio glitch. Do you think you can find where the problem is? Thanks in advance! The files that I use to play are at the bottom.

The glitch sometimes happens when I set the loop to "Play song endlessly."

EDIT: It happens in the first loop, then it loops perfectly after the first.

Oh, if the issue is solved, I'll close it myself.
[LOPUS Files.zip](https://github.com/droidmjt/Droidsound/files/5084989/LOPUS.Files.zip)

**Comment by droidmjt** [comment]
I'll check it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/sk7swtxjj0lwwu6/droidsounde167_231_32bit.apk?dl=1
https://www.dropbox.com/s/ss6g5a3i85n23ld/droidsounde167_231_64bit.apk?dl=1
try if it works now

**Comment by mistersiraj11** [comment]
Testing it...

**Comment by droidmjt** [comment]
When this started happening, since which build?

**Comment by droidmjt** [comment]
Also, what kind of device you use?

**Comment by mistersiraj11** [comment]
Since the builds at Q3 of 2019.
As for devices: my first one used to be Samsung Galaxy A7 (2017). My current device is Razer Phone 1.

**Comment by droidmjt** [comment]
Q3 2019?? why didn't you report it before?

**Comment by mistersiraj11** [comment]
I honestly thought the problem would be addressed. That's why I didn't report it. I don't use the codec much but I'm starting to like it when I got the hang of it.

I appreciate the hard work you do. Trust me.

**Comment by droidmjt** [comment]
Well, unfortunately I cannot reproduce the problem.

**Comment by mistersiraj11** [comment]
See what you can do. If the problem still persists, you've done your best and I'll close this issue unless if you want to keep it for future reference.

**Comment by droidmjt** [comment]
>>The glitch sometimes happens when I set the loop to "Play song endlessly."

So does it also happen without "Play song endlessly"? 

What are your settings for VGMStreamPlugin?

**Comment by mistersiraj11** [comment]
> > > The glitch sometimes happens when I set the loop to "Play song endlessly."
> 
> So does it also happen without "Play song endlessly"?
> 
> What are your settings for VGMStreamPlugin?

Without "Play song endlessly", There's a click/audio gap in the first loop and after that, it plays like normal. No gaps, no glitch. Plays normally after that.

My settings for vgmstream are mostly the same, with the exception of loop count which I set to 4 to test some songs.

**Comment by droidmjt** [comment]
when the click/audio gap is audible, in which file and what is the loop count?

**Comment by droidmjt** [comment]
for example if I play RM4_BGM_NV_DRILLM using loop count 2, I cannot hear anything strange

**Comment by mistersiraj11** [comment]
The gaps are noticeable in ALIENZ_LP and RX5_BGMVOLT_K.

**Comment by droidmjt** [comment]
there is no ALIENZ_LP in the zip you provided

**Comment by droidmjt** [comment]
so in RX5_BGM_VOLT_K, tell me the loop count and the correct time when it happens

**Comment by mistersiraj11** [comment]
What about NAPALMM?

**Comment by mistersiraj11** [comment]
> so in RX5_BGM_VOLT_K, tell me the loop count and the correct time when it happens

After loop count 1

**Comment by droidmjt** [comment]
what did you set as loop count in vgmstream options?

**Comment by mistersiraj11** [comment]
As of now? Still 4

**Comment by droidmjt** [comment]
ok, could you just tell me how long you need to listen the song in minutes/seconds before the glitch happens?

**Comment by mistersiraj11** [comment]
![Screenshot_20200818-002715](https://user-images.githubusercontent.com/50802310/90446193-a47eda00-e0e9-11ea-9082-4055592d4f00.png)


At around 1:38 you'll hear a slight audio gap. Headphones are required.

**Comment by droidmjt** [comment]
I was able to reproduce the bug, it's about phone performance, it doesn't happen with fast devices.

**Comment by mistersiraj11** [comment]
Sure

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/mnu3qbenytzuo8r/droidsounde167_232_32bit.apk?dl=1
https://www.dropbox.com/s/8jchcoc280e2lnk/droidsounde167_232_64bit.apk?dl=1
try again

**Comment by mistersiraj11** [comment]
Currently testing it...

**Comment by droidmjt** [comment]
Make sure your phone is running on maximum performance and try again. The RX5_BGM_VOLT_K song caused  glitch with one of my old phones, once I increased the buffer, it started working fine. Another thing is not to use phone for anything else while listening these songs, the looping method itself requires some CPU since the looping is done by rendering samples until correct position has been reached.

**Comment by mistersiraj11** [comment]
Sure. If this solved my problem, I'll close this issue.

**Comment by droidmjt** [comment]
I meant that once I increased the buffer for VGMStreamPlugin, it started working.

**Comment by mistersiraj11** [comment]
Ok. Nevermind. You did your best. Thanks.

**Comment by droidmjt** [comment]
[RX5_BGM_VOLT_K1.zip](https://github.com/droidmjt/Droidsound/files/5092174/RX5_BGM_VOLT_K1.zip)

unzip that and listen, can you hear the glitch ?

**Comment by mistersiraj11** [comment]
> [RX5_BGM_VOLT_K1.zip](https://github.com/droidmjt/Droidsound/files/5092174/RX5_BGM_VOLT_K1.zip)
> 
> unzip that and listen, can you hear the glitch ?

I'll look into it tomorrow. I'm busy right now with college work. I'll give you a confirmation when I'm done.

**Comment by mistersiraj11** [comment]
Hi, Droid. Sorry for re-opening this issue. I've been examining the loop points for the LOPUS files. It turns out (I think) Droidsound-E is messing with the loop points. I took some screenshots to help you fix the issue if possible. I'll also send said LOPUS file and its decoded OGG version to help you with the problem.


[XCOA_CYCLS.zip](https://github.com/droidmjt/Droidsound/files/5566776/XCOA_CYCLS.zip)

![decoded OGG loop end](https://user-images.githubusercontent.com/50802310/99668091-55e13300-2a7e-11eb-8a42-b119e48b4bd3.png)
![decoded OGG loop start](https://user-images.githubusercontent.com/50802310/99668097-57aaf680-2a7e-11eb-8df2-8f3c8efe901b.png)
![original LOPUS loop end](https://user-images.githubusercontent.com/50802310/99668100-58dc2380-2a7e-11eb-9811-4ce1af54aa8c.png)
![original LOPUS loop start](https://user-images.githubusercontent.com/50802310/99668102-5974ba00-2a7e-11eb-9f77-530a396e715f.png)

**Comment by droidmjt** [comment]
droidsound-e plays the pcm data how vgmstream renders it, it doesn't apply any changes to it and I couldn't hear any problems while listening the lopus file you sent

**Comment by mistersiraj11** [comment]
Strange. I'm not sure why I have this issue specifically with LOPUS. Any other seems just fine. Odd.

**Comment by mistersiraj11** [comment]
Actually, did you check the OGG file? They're decoded from the LOPUS file that I sent.

**Comment by droidmjt** [comment]
At least tell when the bug happens in the LOPUS file.

**Comment by mistersiraj11** [comment]
As seen from the converted OGG file above, (which was converted from LOPUS) it is near the loop end. As in decoded OGG loop end. I suggest using an audio editor for checking the OGG file and input the original LOPUS loop info to see what I mean. It messes with the original LOPUS file loops.

I hope everything is clear for you.

**Comment by droidmjt** [comment]
Noty clear, I cannot hear any problems with these files. The only thing I noticed is that if the loop count is set to 1 then at the end it messes up a bit but in that case one should also check the ignore-loops option.

**Comment by mistersiraj11** [comment]
Odd. I take it that you checked the decoded OGG file (which originally was LOPUS) then?

**Comment by droidmjt** [comment]
how did you create the OGG file?

**Comment by mistersiraj11** [comment]
From Droidsound-E using the create ringtone function to convert the LOPUS file.

**Comment by droidmjt** [comment]
what were the OGG quality setting and vgmstream settings?

**Comment by mistersiraj11** [comment]
Quality 8 (or 256 kbps), and mostly the default settings. Loop count is on 1. The length of the OGG file was 3 mins (counting 3 sec fade out) and that's it AFAIK.

**Comment by droidmjt** [comment]
also, when exactly the problem is audible in the OGG file in minutes/seconds?

**Comment by droidmjt** [comment]
have you tried the 'ignore loops' option in vgmstream settings?

**Comment by mistersiraj11** [comment]
> also, when exactly the problem is audible in the OGG file in minutes/seconds?



> also, when exactly the problem is audible in the OGG file in minutes/seconds?

Around 52 secs

**Comment by mistersiraj11** [comment]
> have you tried the 'ignore loops' option in vgmstream settings?

No, I haven't.

**Comment by droidmjt** [comment]
please check the ignore loops option and try again

**Comment by mistersiraj11** [comment]
> 
> 
> what were the OGG quality setting and vgmstream settings?

Oh! I forgot to mention I was using "loop endlessly". Not sure if that counts. Looking into the ignore loops right now...

**Comment by mistersiraj11** [comment]
I used "ignore loop" but I don't see what I'm doing with the file...

**Comment by droidmjt** [comment]
I have listened the OGG file several times now, near 52s there is absolutely nothing wrong. It's impossible to fix something what cannot be reproduced.

**Comment by mistersiraj11** [comment]
I'll send you a better screenshot later. By any chance, did you listen to the OGG file with headphones? Listen to it after the 52 sec mark.

**Comment by droidmjt** [comment]
I tried to create a ringtone of the lopus file, now at the 52-53s mark the bug is audible, but this happens only when creating a ringtone, everything else is fine including the OGG file you sent. I'll get this fixed.

**Comment by mistersiraj11** [comment]
> I tried to create a ringtone of the lopus file, now at the 52-53s mark the bug is audible, but this happens only when creating a ringtone, everything else is fine including the OGG file you sent. I'll get this fixed.

Great!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/07vq4g65xtvhjxk/droidsounde167_244_32bit.apk?dl=1
https://www.dropbox.com/s/xvsxuoiw8hc8nsl/droidsounde167_244_64bit.apk?dl=1
I hope these work better

**Comment by mistersiraj11** [comment]
Hi. I tried both and I have come to a conclusion from my end: something is wrong with my phone. You did your best. I'll try to solve this from my end. Thanks for everything!

**Comment by droidmjt** [comment]
I was able to reproduce the bug only when creating a ringtone and that is fixed in those builds, that's the best I can do.

**Comment by mistersiraj11** [comment]
You did your very best. I can't thank you enough for this application :)
