### ISSUE TITLE
Latest 232 64bit crashes

### ISSUE THREAD

**Issue by NekoEd** [droidmjt/Droidsound#589]
The latest version of Droidsound-E (232 64bit) crashes on my device (LG G7 ThinQ, Unrooted Android 9) when attempting to play any songs from Modland. No debug information available.

**Comment by droidmjt** [comment]
You could reinstall the application or remove the modland index and reindex it. There hasn't been any changes related to Modland for ages.

**Comment by NekoEd** [comment]
Okay, clearing data/cache fixed it. Sorry for the trouble.
