### ISSUE TITLE
Streaming Formats Crash on 167.234 (64-bit tested)

### ISSUE THREAD

**Issue by JFD62780** [droidmjt/Droidsound#591]
Upon my use of the latest build as a portable Internet Radio, I experienced immediate crash-to-homescreens, where the stream links used to work on previous builds. (.230 specifically)

**Comment by 97lily** [comment]
Excuse me,
I'm not a developer, but I think it would be helpful if the link destination was posted (for example, if there are special characters in the link or the end of the link changes like m3u or hls)  , And the behavior of link loading may change.)

**Comment by JFD62780** [comment]
I meant saved, working stream links in a personal database, be they MP3, AAC, etc.

**Comment by droidmjt** [comment]
Please tell how to reproduce the problem. I just clicked those usual network m3u files what comes with the app and they seem to work.

**Comment by droidmjt** [comment]
If the problem can be reproduced just by trying to play those network links and it fails, then I don't think I can help, nothing has changed in network streaming.

**Comment by droidmjt** [comment]
Best would be if you could provide crashlog.

**Comment by JFD62780** [comment]
On a second testing session involving actual MP3 and FLAC files, I found the problem extends to the files themselves.

Also, how would one provide a crash report?

(Tested on a Galaxy S9 on Android Q)

**Comment by droidmjt** [comment]
When it crashes, does it create a new file in /sdcard/droidsound/crashlogs folder? If not, google for instructions how to create  adb logs with android devices.

**Comment by JFD62780** [comment]
Actually, it's Internal Storage/droidsound/crashlogs .

Here's its contents:

Droidsound-E crashlog
---------------------
Droidsound-E build: 234
Time: Thu Sep 03 16:22:53 EDT 2020
Current ABI: arm64-v8a
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Fingerprint: samsung/starqltesq/starqltesq:10/QP1A.190711.020/G960USQS7ETH2:user/release-keys
CPUFeatures	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp

Language: English
Locale: en_US
InternalSD free space: 27403853824
InternalSD path: /storage/emulated/0
---------------------
Stacktrace:

java.lang.NumberFormatException: For input string: "5.0"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.droidmjt.droidsounde.service.Player.run(Player.java:1548)
	at java.lang.Thread.run(Thread.java:919)


Dontcha love multi-entry clipboards? XD

Eternal thanks for the tip, BTW...

**Comment by droidmjt** [comment]
Go to Settings -> Audio Fade -> Default fadeout length and set the value again.

**Comment by JFD62780** [comment]
Holymoly, it works like a charm! o.o

THANK YOU! XD

**Comment by droidmjt** [comment]
excellent, I'll close this issue :)
