### ISSUE TITLE
Legacy build keep crashing on Android 4.1

### ISSUE THREAD

**Issue by AdityaMH** [droidmjt/Droidsound#592]
I want play droidsound-e on my old phone with legacy build. but keep crashing in first place without any reason.

**Comment by droidmjt** [comment]
sorry to hear that, but there is no way to fix it

**Comment by droidmjt** [comment]
There is always reason for a crash, check /sdcard/droidsound/crashlogs folder for new entries or if the folder is empty, create log using android adb, google for instructions
