### ISSUE TITLE
DroidSound terminates unexpectedly when playing tracks without length

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#593]
I found DroidSound terminated unexpectedly when playing some tracks without length.

The default track length was used, length  = 2:00.
File format was NSFE.
Plugin used to play the format was GME.
After playing the default length DroidSound was terminated (maybe crashed).

The sample file (track 1):
[Yie Ar Kong-fu.zip](https://github.com/droidmjt/Droidsound/files/5179245/Yie.Ar.Kong-fu.zip)

**Comment by droidmjt** [comment]
check new crashlogs from sdcard/droidsound/crashlogs folder, it the folder is empty, use adb to create a log when it terminates

**Comment by droidmjt** [comment]
nevermind, problem solved, I'll upload new binaries soon

**Comment by wmjordan** [comment]
OK. Thanks for looking into this problem.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/pq6p51xjtzg3phi/droidsounde167_235_32bit.apk?dl=1
https://www.dropbox.com/s/e02n7606fas9rmw/droidsounde167_235_64bit.apk?dl=1
