### ISSUE TITLE
Silence detection was not working

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#594]
Some tracks in this NSFE file are missing length and hence default length will be used.
However, silence detection are detecting the end of the tracks.

Plugin: GME

[Battle City.zip](https://github.com/droidmjt/Droidsound/files/5180564/Battle.City.zip)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2jfpz4k5sdwcb6r/droidsounde167_236_32bit.apk?dl=1
https://www.dropbox.com/s/6vm2z0vtol9si5q/droidsounde167_236_64bit.apk?dl=1

**Comment by wmjordan** [comment]
Thank you. Problem was solved very well.

**Comment by droidmjt** [comment]
good to hear
