### ISSUE TITLE
Seeking for BASSZXTUNE supported formats

### ISSUE THREAD

**Issue by edger78** [droidmjt/Droidsound#595]
Hi droidmjt,
It seems seeking broken for BASSZXTUNE compatible formats. Could you please fix it?

**Comment by droidmjt** [comment]
Hi, which formats, tell some examples please?

**Comment by droidmjt** [comment]
Actually, it's not broken, it's disabled.

**Comment by edger78** [comment]
AY (Compliled data in native format)
AS0/ASC (ASC Sound Master 0.xx/1.xx-2.xx modules)
FTC (Fast Tracker modules)
GTR (Global Tracker 1.xx modules)
PSC (Pro Sound Creator 1.xx modules)
PSG (Stream format)
PSM (Pro Sound Maker modules)
PT1 (ProTracker v1 modules)
PT2 (ProTracker v2 modules)
PT3 (ProTracker v3 modules)
SQT (SQ-Tracker compiled modules)
ST1 (SoundTracker uncompiled modules)
ST3 (Sound Tracker 3.0 compiled modules)
STC (SoundTracker compiled modules)
STP (SoundTrackerPro modules)
TXT (VortexTracker modules)
TS (TurboSound modules (Container and PT3.7-based)
VTX (Vortex Project by V_Soft modules)
YM (StSound Project by Leonard/Oxygen modules)
$M

**Comment by edger78** [comment]
> 
> 
> Hi, which formats, tell some examples please?

AY (Compliled data in native format)
AS0/ASC (ASC Sound Master 0.xx/1.xx-2.xx modules)
FTC (Fast Tracker modules)
GTR (Global Tracker 1.xx modules)
PSC (Pro Sound Creator 1.xx modules)
PSG (Stream format)
PSM (Pro Sound Maker modules)
PT1 (ProTracker v1 modules)
PT2 (ProTracker v2 modules)
PT3 (ProTracker v3 modules)
SQT (SQ-Tracker compiled modules)
ST1 (SoundTracker uncompiled modules)
ST3 (Sound Tracker 3.0 compiled modules)
STC (SoundTracker compiled modules)
STP (SoundTrackerPro modules)
TXT (VortexTracker modules)
TS (TurboSound modules (Container and PT3.7-based)
VTX (Vortex Project by V_Soft modules)
YM (StSound Project by Leonard/Oxygen modules)
$M

**Comment by edger78** [comment]
Hi, any chance seeking will be enabled for mentioned formats?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/026w8sv4ur7jiwb/droidsounde167_237_32bit.apk?dl=1
https://www.dropbox.com/s/dzyfmxd1eh2edox/droidsounde167_237_64bit.apk?dl=1
try these

**Comment by edger78** [comment]
Thank you!!
Working like a charm!
