### ISSUE TITLE
cursor not visible in "Browser"

### ISSUE THREAD

**Issue by NgrNxk** [droidmjt/Droidsound#596]
Hi!

Since I discovered that you split the package in 32 and 64 bit versions, I can finally install my favourite music player on my FireTV Stick! Thank you!

But, there is a problem: I cannot see which element in the browser is highlighted. That makes selecting the right element a little difficult. All in all it's working fine, but this one is a nuisance.

Thanks
Adam

**Comment by NgrNxk** [comment]
Just discovered: the same goes for "Search" and "Playlist".

**Comment by droidmjt** [comment]
It's because the app was never designed to work with TVs. Currently I have no time to add this kind of features.

**Comment by NgrNxk** [comment]
The buttons are highlighted just fine. And I can browse and "click", play streams and files and everything. It's just that I don't see the currently selected element in the "Browser".

**Comment by droidmjt** [comment]
yes but currently I don't have time to fix anything, sorry

**Comment by droidmjt** [comment]
I tried with Android TV emulator and I cannot reproduce the problem but I was able to see other problems instead. I don't think this will be fixed any time soon, like I said, this was never intended to work with Android TV, sorry about that.
