### ISSUE TITLE
Latest version crashing when rescanning database

### ISSUE THREAD

**Issue by Sebby75** [droidmjt/Droidsound#597]
Updated recently from 167_230_64bit to 167_236_64bit and attempting to rescan database (full) results in crashes.

Tested on Huawei P20 Pro and Samsung Tab S2 with identical result.
After Droidsound installation everything works.. until I copy latest HVSC 7.3 in zipped form (C64Music.zip 327744811 bytes) into dsroot and rescan.
Droidsound crashes at 98%, to the point where it won't start again unless completely reinstalled (including wipe of it's directory).

I have reverted to 167_230_64bit and everything is working again... (I don't have any versions in between to test).

Regards
Seb

**Comment by Sir-Sabin** [comment]
i'm having the same problem, it seems to the .txt files in 7z files.

**Comment by Sebby75** [comment]
oh yeah.. does indeed look like it's .txt files inside archives.. after deleting them everything works again as normal.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/026w8sv4ur7jiwb/droidsounde167_237_32bit.apk?dl=1
https://www.dropbox.com/s/dzyfmxd1eh2edox/droidsounde167_237_64bit.apk?dl=1
try this

**Comment by Sebby75** [comment]
Doesn't crash anymore... thanks..

I have another question though... when "Rescan DB onstart" is selected, after throwing in couple of .zip and .7z archives into dsroot.. on startup screen in completely blank while droidsound is rescanning these newly added archives... it doesn't show any progress and doesn't indicate that anything is actually happening... is this how it's supposed to work??? I think I have always had rescanning on startup switched off and scanned manually after changes (which always shows progress %).

![Screenshot_20201004_192309_com droidmjt droidsounde](https://user-images.githubusercontent.com/72308577/95023976-1e5a2b00-0678-11eb-8bd4-b5c47610bb1d.jpg)

**Comment by droidmjt** [comment]
that's not how it suppose to work, I have no idea when that started to happen, I'll investigate it

**Comment by droidmjt** [comment]
how about placing those archives to /sdcard/Music and create DB browser for it?

**Comment by droidmjt** [comment]
dsroot is a bit wrong place to keep archives

**Comment by Sir-Sabin** [comment]
it seems to work for me, i'm not getting that problem on my Samsung Galaxy S20 5G+

**Comment by droidmjt** [comment]
Yeah, that's the problem, you cannot keep your archives in dsroot folder or in its subfolders, you need to move them elsewhere. It's because dsroot folder is intended for another kind of purpose and there is no mechanism what would keep track what files have been added/removed there and scan accordingly.

**Comment by Sebby75** [comment]
That's very interesting... I have always kept my music files/archives in dsroot without issues... 

I have been keeping files in that folder for the last 10 years (since 2010 with original droidsound by Swimsuitboys and then same with droidsound-e since around 2014). Never had a slightest issue.. ever.. 
By my logic... if Examples.zip is there, any other zip file with music goes in the same folder.

**Comment by JFD62780** [comment]
I found another crash case with a bunch of zips from Explizit's library of tracker files.  I recommend [the All-in-One archive](https://www.explizit.org/e-all/e-all.zip) With all the releases, extracting the zips to an accessible folder and try to successfully add those to a Database Folder. (Spoilers: an archive or two may have trigger files that cause the crash to this very release.)

**Comment by droidmjt** [comment]
@JFD62780 remove the .ASC files, then it works

**Comment by droidmjt** [comment]
now that I checked a bit more, the blank screen + rescanning silently, it has been like that always, I was a bit confused earlier, I'll see if I can find a way to display the progress dialog before it starts scanning

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/18v1chvslg72q5s/droidsounde167_238_32bit.apk?dl=1
https://www.dropbox.com/s/ncab0z0d9ke550o/droidsounde167_238_64bit.apk?dl=1
this time it should display stuff

**Comment by Sebby75** [comment]
Scanning on startup is showing progress now and I don't have that blank screen any longer.. Thanks.

Just one more question.. 
I have only just noticed this yesterday ( likely because I have never used "Rescan DB on start" before ).
When I turn orientation of the (phone/tablet) from horizontal to vertical it seems to try to rescan database every time..

https://www.youtube.com/watch?v=FPjCZK8gypA

**Comment by droidmjt** [comment]
crap, I'll fix it

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/mlrajxqa59364ut/droidsounde167_239_32bit.apk?dl=1
https://www.dropbox.com/s/xfy5yz9lux6igsw/droidsounde167_239_64bit.apk?dl=1
try this

**Comment by Sebby75** [comment]
Thanks a lot !! Working perfect now.
