### ISSUE TITLE
Licence clarification?

### ISSUE THREAD

**Issue by Dunnysoft** [droidmjt/Droidsound#598]
Hi,

Just wondering if you can please clarify what sort of licence you have on your code?  I would love to be able to play tracker music in my games but I don't want to utilise your code without the right permission to do so :) I'm part of the LibGDX Discord and I know of at least one other developer who is also keen on the idea

**Comment by droidmjt** [comment]
If you want to play tracker music in your software, this is what you need: https://lib.openmpt.org/libopenmpt/
