### ISSUE TITLE
Can't read music on sd card

### ISSUE THREAD

**Issue by ionn28** [droidmjt/Droidsound#599]
I'm using Android 10 device with sd card formatted to exfat.
If I put any music to sd card and try to open it with droidsound-e - pop-up appears saying "too many errors". Same music plays fine if it's located on internal storage.
I've tried latest 64-bit version as well as legacy one - both have the same issue.

**Comment by ionn28** [comment]
I also noticed that I can't create new folders on sd card via droidsound-e as if it lacks some sort of permission.

**Comment by droidmjt** [comment]
the problem seems to be the exFAT, with FAT32 it works just fine, I need to investigate this

**Comment by droidmjt** [comment]
I'm able to read/play from exFAT sdcard, but cannot write for some reason.

**Comment by ionn28** [comment]
I've just tested it. I'm able to play mp3 music, but playing 2sf/ncsf gives me too many failures error.

**Comment by droidmjt** [comment]
![2sf](https://user-images.githubusercontent.com/5917820/95493233-dbb08f80-09a4-11eb-963a-5fe40f4dbd3a.jpg)
![nscf](https://user-images.githubusercontent.com/5917820/95493241-de12e980-09a4-11eb-985c-ef9d5946efa9.jpg)

**Comment by droidmjt** [comment]
close this issue

**Comment by ionn28** [comment]
https://imgur.com/a/W1VPHhs
This is what happening in my case

**Comment by droidmjt** [comment]
![nscf2](https://user-images.githubusercontent.com/5917820/95501226-a4e07680-09b0-11eb-8b5f-3d694c237747.jpg)

**Comment by ionn28** [comment]
So I downloaded 239 version of droidsound-e from issue #597 and for whatever reason now I can play ncsf/2sf music on ad card just fine... So I guess it's fixed?

**Comment by droidmjt** [comment]
I didn't change anything
