### ISSUE TITLE
[Feature] Update BassMIDI libraries to the newest version, which includes support for more modulators

### ISSUE THREAD

**Issue by sentogiga** [droidmjt/Droidsound#600]
Recently BassMIDI updated to include support for more of the sf2 format's modulator features. Can these updates be implemented?

**Comment by droidmjt** [comment]
I have updated the binaries already in build 239, have you tried it?

**Comment by sentogiga** [comment]
When I try to play a MIDI the app crashes

**Comment by sentogiga** [comment]
I'm using the 64bit version on a Galaxy S8.

**Comment by droidmjt** [comment]
could you send the midi file here what crashes the app?

**Comment by sentogiga** [comment]
I've tried many MIDIs and all of them crash

**Comment by sentogiga** [comment]
It also doesn't matter what soundfont I use.

**Comment by droidmjt** [comment]
any MIDI file make BASSMIDI crash? I'll check it

**Comment by sentogiga** [comment]
Also, at some point I would like support for LZH archives, which are similar to LHA but are used often in Japan, and many Japanese MIDIs are contained in them. https://archive.org/details/sound_canvas_midi_collection
This collection is full of Japanese MIDIs, and many of them are inside LZH files that droidsound can't open. 7zip and the associated libraries are able to open LZH files and have been able to do so for a long time.

**Comment by droidmjt** [comment]
![Uploading dse_bassmisi.png…]()

**Comment by droidmjt** [comment]
there, latest build, doom midi file + GeneralUser GS v1.471.sf2, seems to work just fine

**Comment by sentogiga** [comment]
Thanks!

**Comment by sentogiga** [comment]
239 still crashes. I don't know why.

**Comment by sentogiga** [comment]
Regular non-MIDI audio files also crash too

**Comment by sentogiga** [comment]
As do NSFs and vgms

**Comment by sentogiga** [comment]
The 32bit version also crashes in exactly the same way in all of the same situations

**Comment by sentogiga** [comment]
A full reinstall fixed the issue, via using the internal updater after nuking the folder.
