### ISSUE TITLE
[Feature] Add LZH archive support.

### ISSUE THREAD

**Issue by sentogiga** [droidmjt/Droidsound#601]
Many Japanese MIDIs (as well as other formats) are contained in LZH files, which are able to be extracted via the 7z libraries and this has been the case for a long while. LZH archives are sometimes also found in the Amiga scene. 

This link below has a collection of MIDIs contained in LZH files, which droidsound-e can't presently play because it can't see inside LZH archives. While certain MIDIs in the collection aren't in LZH files, there are many MIDIs in the  linked collection that are exclusively found inside LZH files. 

https://archive.org/details/sound_canvas_midi_collection

If you could implement LZH opening into Droidsound-E's unarchiving I would be super happy!

**Comment by droidmjt** [comment]
change the extension from LZH to LHA then close this issue

**Comment by sentogiga** [comment]
Oh. That's nice to hear. However, it doesn't appear to work consistently. Given that I have a 7z app on my phone I can just extract them... However, further testing indicates that your solution does work well, so I will close the issue.

Thanks for the advice!
