### ISSUE TITLE
cant read external storage

### ISSUE THREAD

**Issue by fireclouu** [droidmjt/Droidsound#602]
Im using android 11 and seems the app lacks permission to read from external storage, even SAF not showing to be able to read those storage

**Comment by droidmjt** [comment]
all right, I'll check it

**Comment by droidmjt** [comment]
check the app permissions that you have granted all the permissions it needs

**Comment by droidmjt** [comment]
if you are able to reproduce the bug, could you get send logcat log?

**Comment by fireclouu** [comment]
all available permissions are granted, idk if it was a bug but i really cant see my sdcard at /storage, i just does not appear there or in anywhere else, i use some 3rd party file manager and to be able to read it, it needs to call storage access framework first to make it usable

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/eb7xwu5il9rbl3z/droidsounde167_240_32bit.apk?dl=1
https://www.dropbox.com/s/jli0hnl0q4z8hgx/droidsounde167_240_64bit.apk?dl=1
let me know how it works

**Comment by fireclouu** [comment]
yup now it works normally as it should. thanks!

**Comment by Speedvicio** [comment]
I'm using v167_244_64bit.apk on Android 11 Security patch level October 2020.
Unable to mount external storage, all permission to the app has garanted.

**Comment by droidmjt** [comment]
whats the path to the external storage?

**Comment by Speedvicio** [comment]
> 
> 
> whats the path to the external storage in your device?

/storage/9016-4EF8/

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ohlbrkumymea5db/droidsounde167_245_64bit.apk?dl=1
https://www.dropbox.com/s/k1lwoo477zitf10/droidsounde167_245_32bit.apk?dl=1
see if it works now, it seem DB browser creation wasn't working with Android 11

**Comment by Speedvicio** [comment]
Thx for your interest, the new version can mount external storage.
Adding a new folder for a scan cause the app freeze, but after pair of crash seem that the new folder is added and recognized correctly.

**Comment by droidmjt** [comment]
When you say a folder, what do you mean? Which option did you select from the New menu? If the app crashed, check sdcard/droidsound/crashlogs folder if it created new files, if not, please send logcat log file, google for instructions how to create it.
