### ISSUE TITLE
NEZPlug issue: tap song no. makes force close.

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#604]
Use NEZPlug to override format and play a file, then tap [01/**] song no. , Droidsound-E will force close.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/eb7xwu5il9rbl3z/droidsounde167_240_32bit.apk?dl=1
https://www.dropbox.com/s/jli0hnl0q4z8hgx/droidsounde167_240_64bit.apk?dl=1

**Comment by Yave-Yu** [comment]
Fixed! Thanks!
