### ISSUE TITLE
Latest builds (32-bit) fail to play any audio on Android 5.1 devices

### ISSUE THREAD

**Issue by spaztron64** [droidmjt/Droidsound#607]
On my Lenovo A1000 and Asus X00BD, playing any supported audio format results in either a freeze of the application or the appearance of "Too many failures, stopping". Had to downgrade to the legacy 217 build.

To my knowledge, both should be supported since the API increase this year was for 5.0

**Comment by droidmjt** [comment]
I tested the latest build with Android emulator using 5.0 (API 21) and it worked. See if full reinstall helps (if possible, delete also the droidsound folder).

**Comment by droidmjt** [comment]
If reinstall doesn't help, then you need to use adb.exe to get some logs. 
https://developer.android.com/studio/releases/platform-tools
