### ISSUE TITLE
Song loop issues

### ISSUE THREAD

**Issue by lunathir** [droidmjt/Droidsound#608]
Heyo, I seem to have an issue where the songs I've played using emulated cores (at least) end a second or so early, creating a rather jarring loop issue. I'm on a Galaxy S20 Ultra running Android 10 if that helps with any info. 
I believe that maybe when the song is mostly played through it MIGHT be resetting the core entirely?

**Comment by droidmjt** [comment]
could you tell me which plugin and send me an example song please

**Comment by lunathir** [comment]
The ones I've tried and it was happening with were the Organya, VGMPlay, Game Music Emu, and Sidplay2fp, and it seems to happen with every song.
[https://drive.google.com/folderview?id=1bNOPpJGat6V_Njrh7CD7IFdXa008NE6_](url)

**Comment by droidmjt** [comment]
I tested with sidplay2fp, used endless looping mode, I'm not able to reproduce your problem. The plugin just renders endless amount of audio data and that's it.

**Comment by lunathir** [comment]
Ah, alright. I just tapped the loop button again and that fixed it, sorry. User error.
