### ISSUE TITLE
Crash when attempting to make ringtone out of wav file

### ISSUE THREAD

**Issue by TheRektafire** [droidmjt/Droidsound#611]
[droidsounde_crash_20210110_182538.log](https://github.com/droidmjt/Droidsound/files/5793591/droidsounde_crash_20210110_182538.log)
I downloaded this song https://soundcloud.com/remstage/remstage-thrall and am trying to convert it to mp3 with the ringtone feature so I can use it in a quake map, the issue is that when I try to make the ringtone droidsound just crashes and creates another wav copy of the song and a corrupted mp3 in the ringtones folder

**Comment by TheRektafire** [comment]
Update: I was able to convert the song to ogg successfully, but not mp3 so this seems specifically to be an issue with mp3 conversion possibly?

**Comment by droidmjt** [comment]
The log file says you are using build 216, update to build 244 and try again. At least I was able to create mp3 of wav file.
