### ISSUE TITLE
Crashing when running in Android 11

### ISSUE THREAD

**Issue by 1983parrothead** [droidmjt/Droidsound#612]
Everytime I run it while leaving to other apps, it crashes. I think it stays on when I'm still on its screen. Some other apps like foobar2000 Mobile also crashed the same way, but not ZXTune.

**Comment by droidmjt** [comment]
Thanks for reporting this, unfortunately I don't have Android 11 devices so I cannot work on this issue, I'll fix this once I get Android 11 device.

**Comment by droidmjt** [comment]
I'll test this with Android Emulator, if the problem can be reproduced there, I'll try to fix it.

**Comment by 1983parrothead** [comment]
Okay. Understood. Thank you very much!

**Comment by droidmjt** [comment]
Tested with Android 11 using emulator, started playing a song, minimized and started Chrome, worked fine.

**Comment by 1983parrothead** [comment]
Hmmm, it's still crashing on mine. I cleaned cache, force stopped app, restarted phone, but nothing worked. Perhaps it's my Samsung Galaxy S20+. Security settings? Droidsound-e worked well from factory setting, until I updated Android firmware.

**Comment by 1983parrothead** [comment]
![Screenshot_20210113-213244_Settings](https://user-images.githubusercontent.com/41495763/104537132-5d890800-55e7-11eb-8b3f-28672539ac5a.png)

Problem solved! It has to be switched off in "Optimize battery usage" list.

**Comment by droidmjt** [comment]
Excellent, thanks for sharing this info.
