### ISSUE TITLE
Add sub-tune only to PlayList

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#613]
I checked the loop sub-tune option and added a sub-tune to the play list.
I was expecting that only that sub-tune played.
However, DroidSound not only played that added one, but also subsequent sub-tunes.

Is it possible to add the sub-tune to the play list but ignore the loop sub-tune option so that only the added sub-tune gets played?

**Comment by droidmjt** [comment]
go to Settings -> Playlists and check if Single entry mode is checked. I tested with some C64 Games songs, added subtunes to playlist and with that option checked, it only played the selected subtune

**Comment by wmjordan** [comment]
I did checked that option. But when playing an entry from a NSFE file, it did not stop after the added sub-tune.

**Comment by droidmjt** [comment]
make sure you have disabled Settings -> Misc settings -> Cycle subtunes

**Comment by wmjordan** [comment]
Is it possible to play all subtunes when I click an NSFE file in the Browser, but play only added subtune in the PlayList?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/y9njfsa1tnrfjgc/droidsounde167_246_32bit.apk?dl=1
https://www.dropbox.com/s/im7j8g2ium8lkde/droidsounde167_246_64bit.apk?dl=1
try if it works

**Comment by wmjordan** [comment]
It works great!
I just enjoyed the Japanese state in Double Dragon III in the Play List. As expected, it jumped to another song in the list after that.

Thank you very much.
