### ISSUE TITLE
BASS plugin Gapless Playback broken

### ISSUE THREAD

**Issue by hc6-rescuesquad** [droidmjt/Droidsound#615]
I've experienced this issue for a few months already but I never bothered to write a report. Sorry.

**Expected Event:**
Will play songs without "silence" or gaps before changing tracks.

**What actually happens:**
Noticeable silence before track changes, (and in random occurrences} sometimes plays a track without outputting audio.
This happens to the newer versions of Droidsound.
I tried Legacy, it worked.
I tried a clean install of the 32bit (My device supports only 32bit) variant but Gapless Playback still won't work. (Removing Droidsound-E's working directory won't affect the issue)

The sample I used to test Gapless Playback can be found here.
https://wiki.hydrogenaud.io/index.php?title=Gapless_playback

**Summary**
Legacy Gapless Playback works
Newer versions are broken for me.

**Device Specifications:**
Xiaomi Redmi 6A
Android 9 Pie
2GB Ram, 16GB ROM
No software/hardware modifications.

Thank you for your outstanding service. Droidsound-E has been my Go-to audio player for a few years already.

**Comment by droidmjt** [comment]
I'll check it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/tqr4h1aaq63g9ha/droidsounde167_247_32bit.apk?dl=1
https://www.dropbox.com/s/bjomsbgsbqo5ch6/droidsounde167_247_64bit.apk?dl=1

I hope it works.

**Comment by hc6-rescuesquad** [comment]
Can confirm it works! Thank you so much for fixing it and I hope you take care there!
Video Report: https://streamable.com/21h2pc
