### ISSUE TITLE
Support playing miniusf inside 7z archive.

### ISSUE THREAD

**Issue by jnaviask** [droidmjt/Droidsound#616]
I downloaded a bunch of 7z archives of miniusf files (N64), and Droidsound would not play them directly from the archive. However they played fine after extracting them. I was wondering if supporting miniusf playback without extraction would be possible. Thanks!

**Comment by droidmjt** [comment]
I just tested an archive (.7z) with USF songs. Works directly with filesystem browser and using DB browser.

**Comment by jnaviask** [comment]
It works with USF but not MINIUSF!

**Comment by droidmjt** [comment]
please send here the 7z archive you are trying to play

**Comment by droidmjt** [comment]
![usf](https://user-images.githubusercontent.com/5917820/109340745-13e03e00-7872-11eb-985e-3e93a4dc8380.png)

**Comment by droidmjt** [comment]
I'll close this since there is nothing to fix.
