### ISSUE TITLE
.wlv playback

### ISSUE THREAD

**Issue by Trogdorbad** [droidmjt/Droidsound#617]
Hey, just a small one, but it seems the app doesn't recognize the .wlv files Toejam & Earl III on the Dreamcast uses. Is it possible it isn't using the latest version of vgmstream? I googled the format to make sure it wasn't some unique plugin foobar needed but it seems vgms was updated to support the format relatively recently. Much appreciated!

**Comment by Sir-Sabin** [comment]
vgmstream needs to be updated in droidsound for them to play

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/90eh1ruz9vxr2kt/droidsounde167_248_32bit.apk?dl=1
https://www.dropbox.com/s/mg465q31ss1m5nf/droidsounde167_248_64bit.apk?dl=1
it should work now

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/hn0uid9jw1wgqxo/droidsounde167_248_32bit.apk?dl=1
https://www.dropbox.com/s/ifjkpyzobj5x1rw/droidsounde167_248_64bit.apk?dl=1
it should work now

**Comment by Trogdorbad** [comment]
100% does now, huge thanks 👍👍
