### ISSUE TITLE
Bug, Bugs and more Bugs

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#618]
Bug 1: sid files don't play just slient
Bug 2: gsf files play wrong ex. (Metroid - Zero Mission (2004-02-09)(Nintendo RD1)(Nintendo)[GBA])
Bug 3 .txtp files made with wwiser don't play, please update vgmstream latest version is r1050-3622-g12becc0e

that's all for now

**Comment by droidmjt** [comment]
Are there other gsf files which don't play correctly? Please post here few more.

**Comment by Sir-Sabin** [comment]
it makes a clipping noise when tracks begin and 35 Space Pirate Mother Ship.minigsf sounds off in droidsound-e, but good in foobar

**Comment by droidmjt** [comment]
if Metroid -Zero Mission is the only game where you can hear these bugs, I won't roll back to previous version.

**Comment by sentogiga** [comment]
The issue also happens in the 4-Swords tracks in The Legend of Zelda - ALTTP & 4-Swords when using XQ.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/90eh1ruz9vxr2kt/droidsounde167_248_32bit.apk?dl=1
https://www.dropbox.com/s/mg465q31ss1m5nf/droidsounde167_248_64bit.apk?dl=1

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/hn0uid9jw1wgqxo/droidsounde167_248_32bit.apk?dl=1
https://www.dropbox.com/s/ifjkpyzobj5x1rw/droidsounde167_248_64bit.apk?dl=1
I rolled back the GSF player

**Comment by Sir-Sabin** [comment]
sid files (C64) still don't play just slient and .txtp files made with wwiser in .7z still don't play.

**Comment by droidmjt** [comment]
for sid files, make sure you have the rom files in place, droidsound/c64roms, secondly, send me one example of the .txtp file made with wwiser so I can test

**Comment by Sir-Sabin** [comment]
one that uses .txtp file made with wwiser so I can test is Sonic & All-Stars Racing Transformed (2013-01-31)(Sumo Digital)(Sega)[PC].7z

**Comment by droidmjt** [comment]
![Uploading c64.png…]()

**Comment by droidmjt** [comment]
![c64](https://user-images.githubusercontent.com/5917820/111061548-92f98700-84ac-11eb-81f3-bb0f398c6861.png)

**Comment by Sir-Sabin** [comment]
where do you find these rom files? google is failing me

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/rqfhf20nr332q31/droidsounde167_250_32bit.apk?dl=1
https://www.dropbox.com/s/4kcudd9eqd0m5kj/droidsounde167_250_64bit.apk?dl=1

**Comment by droidmjt** [comment]
go to settings -> misc settings -> extract system files to get the roms back

**Comment by Sir-Sabin** [comment]
anything is working, thx for your time fixing these problems

**Comment by kode54** [comment]
I would love to know what changes were needed for the front end to start working with mGBA 0.9, so I may fix foo_input_gsf too.

**Comment by droidmjt** [comment]
I didn't use 0.9, I rolled back to previous version.

**Comment by kode54** [comment]
@Sir-Sabin I'm reverting the fix I rolled out, and forwarding to libmgba 0.9.1. The bug is the rip's fault. It's equally broken on real hardware. Eat shit, users.

**Comment by droidmjt** [comment]
I'll update to latest mgba then.

**Comment by kode54** [comment]
I'm sorry I was angry. It pisses me off that this VBA-M rips issue happens.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/o6wtm9yvhmc0wzo/droidsounde167_255_32bit.apk?dl=1
https://www.dropbox.com/s/4cifo6xifcmt8se/droidsounde167_255_64bit.apk?dl=1
updated mgba to 0.9.1
