### ISSUE TITLE
Update mGBA library to latest 0.9 and a vgmstream problem

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#619]
Update mGBA library to latest 0.9, thanks!
The VGMStream problem is: Non-endless mode, no fade out, then switch to next song.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/m2eeufpvtidhjly/droidsounde167_251_64bit.apk?dl=1
https://www.dropbox.com/s/fr4rmb0v2926707/droidsounde167_251_32bit.apk?dl=1
try this, vgmstream should be fixed now, won't upgrade mgba because some songs fail to play with it

**Comment by Yave-Yu** [comment]
Well, now mGBA released 0.9.1, can you test it again? If no issue, update mGBA library please, thanks.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/o6wtm9yvhmc0wzo/droidsounde167_255_32bit.apk?dl=1
https://www.dropbox.com/s/4cifo6xifcmt8se/droidsounde167_255_64bit.apk?dl=1
updated mgba to 0.9.1

**Comment by Yave-Yu** [comment]
Thank you!
