### ISSUE TITLE
Plugin request. Update nezplug to nezplug++ and ad option to change sample rate?

### ISSUE THREAD

**Issue by juanreina921** [droidmjt/Droidsound#621]
from what I know the laytest version of nezplug is nezplug++ by off gao, and was updated the first of 2019. Src. http://offgao.net/program/nezplug++_s.zip
It would also be cool if you could ad an option to change sample rate from the plugin. Thanks so much, and keep working on droidsound droidjmt! On a side note, have you ever thought of changing the app to droidamp haha.

**Comment by droidmjt** [comment]
this is done, I'll upload new binary together with bassmidi update

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bpc11qcp5so2kyy/droidsounde167_252_32bit.apk?dl=1
https://www.dropbox.com/s/dzymyc1zoxxyou8/droidsounde167_252_64bit.apk?dl=1
try this
