### ISSUE TITLE
Bassmidi having problems with a song

### ISSUE THREAD

**Issue by Juancarlo577** [droidmjt/Droidsound#622]
Song in question is this https://www.vgmusic.com/new-files/Zeldamedley.mid its having problems with the tempo timings almost midway but emu de midi works just fine though

**Comment by droidmjt** [comment]
this requires bassmidi library update

**Comment by Juancarlo577** [comment]
Is it possible to get it updated if not then its fine its just one song anyway

**Comment by droidmjt** [comment]
I cannot update bassmidi library myself. Next week I know more about this.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/bpc11qcp5so2kyy/droidsounde167_252_32bit.apk?dl=1
https://www.dropbox.com/s/dzymyc1zoxxyou8/droidsounde167_252_64bit.apk?dl=1
should work now
