### ISSUE TITLE
Reading folders or switching views with many small files on android 11 extremely slow

### ISSUE THREAD

**Issue by Sci3ntia** [droidmjt/Droidsound#624]
I know this is a duplicate of #609, but I have more information about the cause of this slowdown, due to android 11's scoped storage, reading folders with more than 100 small files (txtp, 2sf, etc) is extremely slow, I would encourage you to try with 100+ small files in an android 11 emulator (or real device preferably) and see how folder loading fares. for me I have seen decreases in loading speed when opening folders and switching from the song to folder view up to 20x slower. I have no clue if this can be worked around or if android 11 will just be very slow.

**Comment by droidmjt** [comment]
It seems to be Android 11 curse, nothing I can do about it.

**Comment by droidmjt** [comment]
Tested now with real hardware using Android 11 (April patch), over 100 files in sdcard/Music/, loads as fast as usual.  No idea why the emulator was slow.
