### ISSUE TITLE
Ogg and Opus .BGM Files Crash Issue

### ISSUE THREAD

**Issue by mistersiraj11** [droidmjt/Droidsound#625]
Hi, droid. Apologies for bothering you. Every time I click to play on one of these .bgm
 files, Droidsound-E crashes. What's the problem here?

Departure from Duke Nukem 3D is the only bgm file with OPUS header.
[BGM.zip](https://github.com/droidmjt/Droidsound/files/6430080/BGM.zip)

**Comment by mistersiraj11** [comment]
That I know but can you make these bgm files playable by any chance?

**Comment by droidmjt** [comment]
will be fixed in next build, there is another plugin using same extension

**Comment by mistersiraj11** [comment]
Sure. I'll close this issue once fixed.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/u3hb5mz9mlnj8bf/droidsounde167_253_32bit.apk?dl=1
https://www.dropbox.com/s/xmi5k3x5wn7cugg/droidsounde167_253_64bit.apk?dl=1
try if it works

**Comment by mistersiraj11** [comment]
They all work. Thanks! :)
