### ISSUE TITLE
OGG Vorbis Loop End Point

### ISSUE THREAD

**Issue by mistersiraj11** [droidmjt/Droidsound#627]
Hi, @droidmjt. This isn't an issue per se, but vgmstream just got updated with the fix where the OGG Vorbis loop end point problem got fixed. Mind if you can update Droidsound using the new vgmstream update? Thanks in advance!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/5azo8rc0kuy33mk/droidsounde167_254_32bit.apk?dl=1
https://www.dropbox.com/s/ihizamwacn9yya9/droidsounde167_254_64bit.apk?dl=1
try if it works

**Comment by mistersiraj11** [comment]
Sure. Will close this if it works.

**Comment by mistersiraj11** [comment]
UPDATE: It works! Thanks for your hard work!
