### ISSUE TITLE
Feature request: favorites in filesystem

### ISSUE THREAD

**Issue by jnaviask** [droidmjt/Droidsound#628]
Hi, I have a feature I'd like to request.

I have a lot of soundtracks all as zips, and I'd like to be able to favorite an entire zip file or folder rather than song-by-song using the playlist feature. I assume it would be straightforward to add an "isFavorite" column to the file db, and then display a "favorites" folder at the root level. Currently the only way to do this is manually, by creating a separate folder and copying the albums I like into it.

Let me know if this is possible! I could even help out with some of the development work if needed.

**Comment by droidmjt** [comment]
How this should work, should it add a zip file to Favourites and play all the files from it OR should it add all the contents from a zip file to Favourites?

**Comment by droidmjt** [comment]
sorry, this is not possible, I tried to implement this so that if an playlist entry is a zip it would queue all the files from it, its just too complex to implement
