### ISSUE TITLE
Feature request - Option to have minimum minutes to loop instead of loop count

### ISSUE THREAD

**Issue by nathanmp** [droidmjt/Droidsound#629]
There are pretty large discrepancies between the length of loops in some game soundtracks. For instance, some older soundtracks have loops less than 30 seconds. Some newer ones have loops more than 120. So 5 loops of a song with (e.g.) intro and outro combined of 1 minute, could last anywhere from 3:30 to 11:00.

It'd be great if there was a way to set a minimum number of minutes to play the song. If I wanted to listen for 5 minutes, at each loop point it could check to see how long the current song has been playing: if it's not over the 5-minute threshold, loop again. Else, keep going to the outro.

This probably isn't terribly difficult. The easiest way to do it would probably be adding a checkbox to the plugins that allow looping. If it's checked, then treat the number in the loop box as a number of minutes instead of loops. Then in the player you could add an if block to the state that handles loops in supported formats.

This would be a great feature for me! I like listening to around 10 minutes of a looping song while working - too much gets stale, and too little is frequently jarring. If I had done anything with Android more recently than 4.0's release I'd try to add this myself.

**Comment by droidmjt** [comment]
I can try to add this to vgmstream plugin only

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8vtcwkdymelo601/droidsounde167_256_32bit.apk?dl=1
https://www.dropbox.com/s/chdeqdb9m7xdw54/droidsounde167_256_64bit.apk?dl=1

**Comment by nathanmp** [comment]
Sorry for the delayed response - didn't get the notification until now. It works perfectly! Thank you so much! That's really helpful.

**Comment by nathanmp** [comment]
I'm just curious, is the most recent source available? It seems like the code in this repo hasn't been updated recently, although the app obviously has. And thanks again for the quick feature addition! I really appreciate it!
