### ISSUE TITLE
Wrong speed for some CRI AWB audio 

### ISSUE THREAD

**Issue by brianpow** [droidmjt/Droidsound#630]
Example: Track 3 in this (Other tracks are fine)
http://rxdres.capcom.com.tw/175/CriWare/Android/Assets/StreamingAssets/BGMe1.awb
Tested on Droidsound-E v167_255_64bits on Android 11

It works fine on foobar with latest vgmstream plugin

**Comment by droidmjt** [comment]
i'll fix this

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8vtcwkdymelo601/droidsounde167_256_32bit.apk?dl=1
https://www.dropbox.com/s/chdeqdb9m7xdw54/droidsounde167_256_64bit.apk?dl=1

**Comment by brianpow** [comment]
Thanks. It works perfectly
