### ISSUE TITLE
Append Fadeout

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#631]
Can there be an option to append the fadeout to the length of a song? This way, if a song is set to loop twice, it will do two complete play throughs before the fade starts (fading starting when the 3rd loop starts). Or if this could be achieved by setting a negative fade length?

**Comment by droidmjt** [comment]
If you set it to loop twice it won't go to 3rd loop instead it goes to the end. Sorry, this is a no go.

**Comment by froggestspirit** [comment]
Wouldn't it be possible to just add the fadeout time to the length of the song, and it just plays until that time?
